### ISSUE TITLE
Improve helm-operator main.go

### ISSUE THREAD

**Issue by tamarakaufler** [weaveworks/flux#1001]
**Problem**

The main.go file for helm-operator currently contains too much implementation detail, that needs abstracting away.  Refactoring will improve readability, clarity and will increase testability.

**A/C**

Refactored helm-operator entry point. Added tests.

**Comment by jml** [comment]
[Refactoring – not on the backlog](https://ronjeffries.com/xprog/articles/refactoring-not-on-the-backlog/)
