### ISSUE TITLE
fluxd dies with "read-only file system" error

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/flux#1002]
_From @crw on March 6, 2018 23:41_

Part of my job is to watch every FullStory and send every trialist an email. One scenario I occasionally see is a user getting through setup to the point that the agents are "Installing," but the session ends without the agents having completed setup. This is frequently combined with the user bailing on the installation screen.

I do not know if our agents are in fact not installing, or if FullStory is not capturing data, or what. But, I am going to start collecting examples of this "problem" in this ticket. 

_Copied from original issue: weaveworks/service-ui#2064_

**Comment by jpellizzari** [comment]
_From @crw on March 6, 2018 23:41_

https://app.fullstory.com/ui/6PB27/session/5660845757431808:5660845757431808!5741031244955648/user/5660845757431808

**Comment by jpellizzari** [comment]
_From @crw on March 6, 2018 23:42_

https://app.fullstory.com/ui/6PB27/session/5652910805352448:5652910805352448!5629499534213120

**Comment by jpellizzari** [comment]
_From @crw on March 7, 2018 21:50_

https://app.fullstory.com/ui/6PB27/session/5710753378074624:5710753378074624!5629499534213120

**Comment by jpellizzari** [comment]
_From @crw on March 8, 2018 19:21_

https://app.fullstory.com/ui/6PB27/session/5669802911727616:5669802911727616!5629499534213120/user/5669802911727616

**Comment by jpellizzari** [comment]
_From @crw on March 10, 2018 0:2_

https://app.fullstory.com/ui/6PB27/session/5642771025100800:5642771025100800!5629499534213120

**Comment by jpellizzari** [comment]
_From @crw on March 13, 2018 22:54_

Live debugging this issue with a user: https://app.intercom.io/a/apps/nvwp88sj/conversations/15156029658?redirectTo=feed

**Comment by jpellizzari** [comment]
Logs from the user's `fluxd`:

```
ts=2018-03-13T22:53:46.94353978Z caller=main.go:133 started=true
ts=2018-03-13T22:53:46.957318348Z caller=main.go:192 err="mkdir /etc/fluxd/ssh/..weave-keygen410528597: read-only file system"
```

**Comment by awh** [comment]
When flux starts for the first time, it tries to generate a key into the tmpfs mounted at `/etc/fluxd/ssh`  by the `git-key` secret volume mount. This should be mounted read/write as we do not specify `readOnly: true` on the mount, but it would seem that this isn't always the case - could be a peculiarity of a particular kind of kubernetes installation?

**Comment by awh** [comment]
If it turns out that secret volume mounts aren't writeable on some platforms, we can add an additional volume mount of type `emptyDir` with `emptyDir.Medium: Memory` to the manifest and write the key into that. (NB overriding the medium in this fashion will yield a tmpfs mount, which is vital to avoid writing the key to the host disk).

**Comment by rade** [comment]
wouldn't that result in the key being lost when fluxd is moved to another node?

**Comment by squaremo** [comment]
> wouldn't that result in the key being lost when fluxd is moved to another node?

No, it gets written to a secret first. But that is only mounted on the next pod restart. Writing it to the tmpfs is so that it will be usable in the meantime.

**Comment by squaremo** [comment]
https://github.com/kubernetes/kubernetes/pull/58720 makes secret and configmap volumes read-only, from Kubernetes 1.10 onward (with an escape hatch that will go away in 1.11). So, there you go. We'll need to require an `emptyDir` volume as Adam describes.

**Comment by rade** [comment]
Odd that somebody would hit that on GKE already then since 1.9.3 is the highest version there.

**Comment by squaremo** [comment]
@awh Any ideas for how to make sure in the daemon code that the key is generated in a tmpfs? I was thinking, as a start, of having a mandatory flag `--ssh-keygen-dir`, to make it a breaking change (that we can paper over in the lunch generator).

**Comment by squaremo** [comment]
Oh barf, #892 fixed the key location to `/etc/fluxd/ssh/identity` so that we didn't have to sprinkle SSH environment variables through the git operations. Bit it does so by maintaining the symlink there -- which won't be possible if the containing directory is mounted read-only.

**Comment by squaremo** [comment]
I can think of a couple of remedies:

 - go back to prefixing git operations with env variables
 - use more than one `IdentityFile` in the ssh_config, so there's still a stable location

**Comment by crw** [comment]
I am continuing to add examples of this in the wild to the closed ticket, just to the severity of the issue is being recorded. We had someone wait 3 hours before giving up yesterday.

**Comment by errordeveloper** [comment]
I've noticed this with a GKE cluster today. I am not sure if this affects all GKE users, but I wouldn't be surprised if that's the case. I've used few non-default options: `--image-type=UBUNTU --cluster-version=1.8.9-gke.1`.

**Comment by squaremo** [comment]
@errordeveloper Did secret volume mounts get quietly switched to read-only in GKE?

**Comment by squaremo** [comment]
> Did secret volume mounts get quietly switched to read-only in GKE?

https://cloud.google.com/kubernetes-engine/release-notes#march-13-2018 <- yes, exactly that.

**Comment by errordeveloper** [comment]
I'm happy to update launch generator unless someone has already started on that...

**Comment by squaremo** [comment]
> I'm happy to update launch generator unless someone has already started on that...

I'm doing it right now.
