### ISSUE TITLE
Do helm-operator semver releases separately from flux releases

### ISSUE THREAD

**Issue by sambooo** [weaveworks/flux#1004]
When the helm operator is ready for a 1.0 release, we can skip versions so that `flux:x.y.z` is released together with `helm-operator:x.y.z`.

For now though, we want to be able to release 0.x versions independently from flux itself. In order to trigger releases from CI we'll need to devise a tagging scheme for the helm operator (`helm-x.y.z` ought to suffice) and make sure that pushing such a tag doesn't cause a flux release.

This process should also be documented clearly in `internal_docs/releasing.md`, and a followup issue about removing this versioning split should be opened once _this_ issue is resolved so we don't lose track of it.

**Comment by sambooo** [comment]
We should also have a separate changelog as mentioned by @tamarakaufler [here](https://github.com/weaveworks/flux/pull/1003#discussion_r174471908). Doesn't make much sense to tangle the two together but we still need to log changes!

**Comment by squaremo** [comment]
We now have a separate changelog too.
