### ISSUE TITLE
Make it possible to specify which Chart releases should be purged on delete

### ISSUE THREAD

**Issue by tamarakaufler** [weaveworks/flux#1009]
**Feature**

Currently, when a Custom Resource (FluxHelmResource kind) gets deleted, the corresponding Chart release gets deleted. It stays in tiller ConfigMaps with status "DELETED".  This has the practical effect that the same Release name cannot be reused.

Helm users should be able to choose per Chart release which ones are deleted with purge, ie removed from tiller release history meaning the release names, as a result, can be subsequently reused. 

**A/C**

It is possible to specify, per Custom Resource, which Chart release is purged and which only deleted.

**Comment by squaremo** [comment]
Obviated by #1106
