### ISSUE TITLE
Delete all yaml-modifying code

### ISSUE THREAD

**Issue by sambooo** [weaveworks/flux#1019]
We have the requirement that modifying yaml belonging to the user must preserve their comments, since the output may still be read by humans. There is no existing library for Go which supports this behaviour, and as a result we manipulate yaml with a collection of regular expressions in [`cluster/kubernetes/update.go`](https://github.com/weaveworks/flux/blob/f220230cb0b6c420babbb347a32899b27e7bb893/cluster/kubernetes/update.go#L129) and [`cluster/kubernetes/policies.go`](https://github.com/weaveworks/flux/blob/f220230cb0b6c420babbb347a32899b27e7bb893/cluster/kubernetes/policies.go#L80).

This code is difficult to maintain, changes to it are difficult to review, and it's difficult to be sure it does the right thing for all possible inputs.

We should delete it all and offload the yaml-modification to `kubeyaml`, as is being done in #976.

**Comment by squaremo** [comment]
As of #976 being merged, we don't modify YAMLs from the go code any more.

**Comment by sambooo** [comment]
Awesome!

**Comment by squaremo** [comment]
For the record: https://github.com/weaveworks/flux/issues/1120

**Comment by sambooo** [comment]
No `help wanted` labels in sight

**Comment by squaremo** [comment]
> No help wanted labels in sight

Magic labeling machine waved!
