### ISSUE TITLE
Secrets?

### ISSUE THREAD

**Issue by mikecann** [weaveworks/flux#1024]
Hi, 

So we are just starting to experiment with Flux and were wondering about secrets. 

If we keep all our configuration in git, what about secrets? We obviously shouldnt keep passwords or secret keys in git so how should one get these configuration secrets into a deployment?

Perhaps a service like shush (https://github.com/realestate-com-au/shush) to pre-encrypt the secrets, commit those into git then decrypt them at runtime?

Cheers

**Comment by squaremo** [comment]
> Looks like you guys have already thought of this

Or bitnami did :) In general, yes you want to use some kind of out-of-band mechanism for introducing secrets. In the future flux may do something special about secrets, but likely only so as to work in sympathy with some other system, like vault, or sealed secrets.

**Comment by mikecann** [comment]
Awesome thanks. Sealed secrets looks like it should do the job just fine for us for now.
