### ISSUE TITLE
Recommended to put flux /deploy in git?

### ISSUE THREAD

**Issue by mikecann** [weaveworks/flux#1028]
I was wondering if its a good idea to keep the flux config files (i.e. the ones in the /deploy dir) in git along side your other micro-service definitions?

Would that mean that flux would auto-update itself?

**Comment by squaremo** [comment]
Hi -- yes we do this ourselves, including using the automation to update it. You may wish to be a bit careful with the automation, and use a tag filter to only get releases, since we push CI builds to the same repo (tagged as master-*).

**Comment by mikecann** [comment]
Awesome thanks!
