### ISSUE TITLE
tag filters should apply to manual updates

### ISSUE THREAD

**Issue by rade** [weaveworks/flux#1054]
At the moment, tag filters are only taken into account for automatic updates, not manual updates. This is somewhat surprising behaviour and can easily lead to users accidentally releasing the wrong images when, say, running `--update-all` and expecting the tag filters to be taken into account.

The only time the filter should be ignored is when manually releasing a specific version of an image with `--update-image=...`.

**Comment by squaremo** [comment]
We have a (hitherto unused) `force` flag in the API types now, so we could implement `--force` per #132, #941, etc. This would free us to tighten the restriction on what you can do in the _absence_ of that flag.
