### ISSUE TITLE
Helm releasesync does git pull after having computed changes, but before applying them

### ISSUE THREAD

**Issue by ncabatoff** [weaveworks/flux#1092]
I noticed while working on #1089 that the 'git pull' is done *after* having examined the repo and compared it to the cluster to determine what changes to make.  So we figure out what to do, then git pull, then apply changes based on a potentially stale plan.  Looks like a bug to me.   See releasesync.ReleaseChangeSync.sync() for the pull in question.

**Comment by squaremo** [comment]
This is no longer the case after #1240 (use the same git code as fluxd); the git mirroring is done _only_ in `*Repo.Start(...)`, and not ad-hoc.
