### ISSUE TITLE
Import ssh key from self hosted git

### ISSUE THREAD

**Issue by konfiot** [weaveworks/flux#1155]
Hello,
I try tu use a internal gitlab as configuration repo, but I always get the "git repo not ready error"
I traced that back to the ssh key of the gitlab server not being known by the flux pod, thus trigering 
```
No ECDSA host key is known for gitlab.binets.fr and you have requested strict checking.
Host key verification failed.
``` 
when trying to clone
A fix would be to change the dockerfile (https://github.com/weaveworks/flux/blob/master/docker/Dockerfile.flux#L28) but then I would need a private image for fluxd as well that I would have to keep up to date with the upstream
wouldn't there be a better alternative ?

**Comment by stefanprodan** [comment]
Hi @konfiot 

We have several PRs in the works to deal with this problem: #1112 #1154 #1142

**Comment by konfiot** [comment]
Oh, sorry, haven't searched enough, found a workaround in one of them, thanks  !
