### ISSUE TITLE
getting unlocked automated services: git repo not ready"

### ISSUE THREAD

**Issue by MicroKernelXulj** [weaveworks/flux#1157]
ts=2018-06-21T06:37:20.975765984Z caller=images.go:23 component=sync-loop error="getting unlocked automated services: git repo not ready"
ts=2018-06-21T06:37:25.702149173Z caller=loop.go:89 component=sync-loop err="git repo not ready"
ts=2018-06-21T06:37:55.702477599Z caller=loop.go:89 component=sync-loop err="git repo not ready"
ts=2018-06-21T06:38:25.702843592Z caller=loop.go:89 component=sync-loop err="git repo not ready"
ts=2018-06-21T06:38:55.703180119Z caller=loop.go:89 component=sync-loop err="git repo not ready"
ts=2018-06-21T06:39:25.703658933Z caller=loop.go:89 component=sync-loop err="git repo not ready"
ts=2018-06-21T06:39:55.703856181Z caller=loop.go:89 component=sync-loop err="git repo not ready"
ts=2018-06-21T06:40:25.704187139Z caller=loop.go:89 component=sync-loop err="git repo not ready"
ts=2018-06-21T06:40:55.704480871Z caller=loop.go:89 component=sync-loop err="git repo not ready"
ts=2018-06-21T06:41:25.704803743Z caller=loop.go:89 component=sync-loop err="git repo not ready"
ts=2018-06-21T06:41:55.705068382Z caller=loop.go:89 component=sync-loop err="git repo not ready"
ts=2018-06-21T06:42:20.9760949Z caller=images.go:17 component=sync-loop msg="polling images"

**Comment by MicroKernelXulj** [comment]
I have a git repo,and I have added The key ! I can git clone it in pod!But The flux  still doesn't work！

ts=2018-06-22T04:35:24.602585718Z caller=git.go:86 component=git error="Failed to clone git repo [git@gitlab.aaatech.com:aaa/online-base-yaml, charts, master]: ssh: handshake failed: knownhosts: key is unknown"
ts=2018-06-22T04:35:34.630099758Z caller=git.go:86 component=git error="Failed to clone git repo [git@gitlab.aaatech.com:aaa/online-base-yaml, charts, master]: ssh: handshake failed: knownhosts: key is unknown"
ts=2018-06-22T04:35:44.694995161Z caller=git.go:86 component=git error="Failed to clone git repo [git@gitlab.aaatech.com:aaa/online-base-yaml, charts, master]: ssh: handshake failed: knownhosts: key is unknown"
ts=2018-06-22T04:35:54.723815669Z caller=git.go:86 component=git error="Failed to clone git repo [git@gitlab.aaatech.com:aaa/online-base-yaml, charts, master]: ssh: handshake failed: knownhosts: key is unknown"
ts=2018-06-22T04:36:04.752648219Z caller=git.go:86 component=git error="Failed to clone git repo [git@gitlab.aaatech.com:aaa/online-base-yaml, charts, master]: ssh: handshake failed: knownhosts: key is unknown"
ts=2018-06-22T04:36:14.810547229Z caller=git.go:86 component=git error="Failed to clone git repo [git@gitlab.aaatech.com:aaa/online-base-yaml, charts, master]: ssh: handshake failed: knownhosts: key is unknown"
ts=2018-06-22T04:36:24.836749241Z caller=git.go:86 component=git error="Failed to clone git repo [git@gitlab.aaatech.com:aaa/online-base-yaml, charts, master]: ssh: handshake failed: knownhosts: key is unknown"
ts=2018-06-22T04:36:34.864547139Z caller=git.go:86 component=git error="Failed to clone git repo [git@gitlab.aaatech.com:aaa/online-base-yaml, charts, master]: ssh: handshake failed: knownhosts: key is unknown"
ts=2018-06-22T04:36:44.894741164Z caller=git.go:86 component=git error="Failed to clone git repo [git@gitlab.aaatech.com:aaa/online-base-yaml, charts, master]: ssh: handshake failed: knownhosts: key is unknown"
ts=2018-06-22T04:36:54.930954624Z caller=git.go:86 component=git error="Failed to clone git repo [git@gitlab.aaatech.com:aaa/online-base-yaml, charts, master]: ssh: handshake failed: knownhosts: key is unknown"
ts=2018-06-22T04:37:04.965382584Z caller=git.go:86 component=git error="Failed to clone git repo [git@gitlab.aaatech.com:aaa/online-base-yaml, charts, master]: ssh: handshake failed: knownhosts: key is unknown"
ts=2018-06-22T04:37:15.004083158Z caller=git.go:86 component=git error="Failed to clone git repo [git@gitlab.aaatech.com:aaa/online-base-yaml, charts, master]: ssh: handshake failed: knownhosts: key is unknown"

**Comment by stephenmoloney** [comment]
Are you using helm operator?

Id recommend running the following to get more information:

```
kubectl -n flux exec -ti flux-pod-name -- ssh -v gitlab.<yourdomain>
```
and also
```
kubectl -n flux exec -ti flux-pod-name -- cat /root/.ssh/known_hosts
```

Does all the information from above commands match expectations?

**Comment by MicroKernelXulj** [comment]
[root@i-rgp1jdbe helm]# kubectl get pods -n flux
NAME                                  READY     STATUS    RESTARTS   AGE
flux-7975cc8748-wlgj8                 1/1       Running   0          19m
flux-helm-operator-5b4d9f4d5d-kqp8g   1/1       Running   0          19m
flux-memcached-5fcbc78447-qmdnr       1/1       Running   0          19m



[root@i-rgp1jdbe helm]# kubectl exec -it flux-7975cc8748-wlgj8 -n flux -- ssh -v git@gitlab.aaa.com 
OpenSSH_7.5p1-hpn14v4, LibreSSL 2.5.5
debug1: Reading configuration data /root/.ssh/config
debug1: /root/.ssh/config line 1: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Connecting to gitlab.aaa.com [192.168.55.41] port 22.
debug1: Connection established.
debug1: permanently_set_uid: 0/0
debug1: key_load_public: No such file or directory
debug1: identity file /etc/fluxd/ssh/identity type -1
debug1: key_load_public: No such file or directory
debug1: identity file /etc/fluxd/ssh/identity-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /var/fluxd/keygen/identity type -1
debug1: key_load_public: No such file or directory
debug1: identity file /var/fluxd/keygen/identity-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.5p1-hpn14v4
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.4
debug1: match: OpenSSH_7.4 pat OpenSSH* compat 0x04000000
debug1: Remote is NON-HPN aware
debug1: Authenticating to gitlab.aaa.com:22 as 'git'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:2uCYi1AG+U7yag0y9CumZWD4gkVAEx7r9V2LfQhDguM
debug1: Host 'gitlab.aaa.com' is known and matches the ECDSA host key.
debug1: Found key in /root/.ssh/known_hosts:6
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<rsa-sha2-256,rsa-sha2-512>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: publickey
debug1: Trying private key: /etc/fluxd/ssh/identity
debug1: Authentication succeeded (publickey).
Authenticated to gitlab.aaa.com ([192.168.55.41]:22).
debug1: HPN to Non-HPN Connection
debug1: Final hpn_buffer_size = 2097152
debug1: HPN Disabled: 0, HPN Buffer Size: 2097152
debug1: channel 0: new [client-session]
debug1: Enabled Dynamic Window Scaling
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: pledge: network
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug1: Remote: Forced command.
debug1: Remote: Port forwarding disabled.
debug1: Remote: X11 forwarding disabled.
debug1: Remote: Agent forwarding disabled.
debug1: Remote: PTY allocation disabled.
PTY allocation request failed on channel 0
Welcome to GitLab, Administrator!
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
debug1: client_input_channel_req: channel 0 rtype eow@openssh.com reply 0
debug1: channel 0: free: client-session, nchannels 1
Connection to gitlab.aaa.com closed.
Transferred: sent 2684, received 2660 bytes, in 0.2 seconds
Bytes per second: sent 14315.4, received 14187.4
debug1: Exit status 0



[root@i-rgp1jdbe helm]# kubectl exec -it flux-helm-operator-5b4d9f4d5d-kqp8g -n flux -- ssh -v git@gitlab.aaa.com 
OpenSSH_7.5p1-hpn14v4, LibreSSL 2.5.5
debug1: Reading configuration data /root/.ssh/config
debug1: /root/.ssh/config line 1: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Connecting to gitlab.aaa.com [192.168.55.41] port 22.
debug1: Connection established.
debug1: permanently_set_uid: 0/0
debug1: key_load_public: No such file or directory
debug1: identity file /etc/fluxd/ssh/identity type -1
debug1: key_load_public: No such file or directory
debug1: identity file /etc/fluxd/ssh/identity-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /var/fluxd/keygen/identity type -1
debug1: key_load_public: No such file or directory
debug1: identity file /var/fluxd/keygen/identity-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.5p1-hpn14v4
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.4
debug1: match: OpenSSH_7.4 pat OpenSSH* compat 0x04000000
debug1: Remote is NON-HPN aware
debug1: Authenticating to gitlab.aaa.com:22 as 'git'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:2uCYi1AG+U7yag0y9CumZWD4gkVAEx7r9V2LfQhDguM
debug1: Host 'gitlab.aaa.com' is known and matches the ECDSA host key.
debug1: Found key in /root/.ssh/known_hosts:8
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<rsa-sha2-256,rsa-sha2-512>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: publickey
debug1: Trying private key: /etc/fluxd/ssh/identity
debug1: Authentication succeeded (publickey).
Authenticated to gitlab.aaa.com ([192.168.55.41]:22).
debug1: HPN to Non-HPN Connection
debug1: Final hpn_buffer_size = 2097152
debug1: HPN Disabled: 0, HPN Buffer Size: 2097152
debug1: channel 0: new [client-session]
debug1: Enabled Dynamic Window Scaling
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: pledge: network
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug1: Remote: Forced command.
debug1: Remote: Port forwarding disabled.
debug1: Remote: X11 forwarding disabled.
debug1: Remote: Agent forwarding disabled.
debug1: Remote: PTY allocation disabled.
PTY allocation request failed on channel 0
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
debug1: client_input_channel_req: channel 0 rtype eow@openssh.com reply 0
Welcome to GitLab, Administrator!
debug1: channel 0: free: client-session, nchannels 1
Connection to gitlab.aaa.com closed.
Transferred: sent 2684, received 2660 bytes, in 0.2 seconds
Bytes per second: sent 14124.8, received 13998.4
debug1: Exit status 0


[root@i-rgp1jdbe helm]# kubectl exec -it flux-helm-operator-5b4d9f4d5d-kqp8g -n flux -- cat /root/.ssh/known_hosts
github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
bitbucket.org ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==
gitlab.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsj2bNKTBSpIYDEGk9KxsGh3mySTRgMtXL583qmBpzeQ+jqCMRgBqB98u3z++J1sKlXHWfM9dyhSevkMwSbhoR8XIq/U0tCNyokEi/ueaBMCvbcTHhO7FcwzY92WK4Yt0aGROY5qX2UKSeOvuP4D6TPqKF1onrSzH9bx9XUf2lEdWT/ia1NEKjunUqu1xOB/StKDHMoX4/OKyIzuS0q/T1zOATthvasJFoPrAjkohTyaDUz2LN5JoH839hViyEG82yB+MjcFV5MU3N1l1QL3cVUCh93xSaua1N85qivl+siMkPGbO5xR/En4iEY6K2XPASUEMaieWVNTRCtJ4S8H+9
gitlab.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFSMqzJeV9rUzU4kWitGjeR4PWSa29SPqJ1fVkhtj3Hw9xjLVXVYrU9QlYWrOLXBpQ6KWjbjTDTdDkoohFzgbEY=
gitlab.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAfuCHKVTjquxvt6CM6tdG4SLp1Btn/nOeHHE5UOzRdf
gitlab.aaa.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC7s2lrd4uK47ES5I9IewsCMdc2XQeqnxaVmFnAusKt1
gitlab.aaa.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDODqs3N0/b9jVYO1SGmLZ1CprlGMg3F+SH6VFNf9QqHaCoLncWLD4jc/A/2F05eQ0j3pPTWYPXmkAnRzYp9XkKyIcWDZ8XbCkX49zC1ktazFD4KXfVkOkS/ps3tufnRa97eFTj48gp/o++cK2nZTmT6vX0F2F8gXrbhn3b5X3nQSeE1MKP5Xm4SkIVUpXsPr8NUB6yN7pDUoKOvUi9TZo5TMRbyq4wlSzg7z8HUc1sEBxsdV5GY8JB1yuHJvhaS6SPZpkt8HO2XJ0XNukM4erkOjeONSUXtlDQXYv2T2h53uWO2hfVF6zqzNOboFugOn2KAduztQ7HZehd5KvBPcM1
gitlab.aaa.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBPCxngIU2hQrG6aQd/wMWFojT7VzL7Cw8T4Ppffww+7MO6Oa857+AxmQ6skga6HkMJsAUdxQ1Lzz2neBlDROlmk=
192.168.55.41 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBPCxngIU2hQrG6aQd/wMWFojT7VzL7Cw8T4Ppffww+7MO6Oa857+AxmQ6skga6HkMJsAUdxQ1Lzz2neBlDROlmk=

[root@i-rgp1jdbe helm]# kubectl logs flux-helm-operator-5b4d9f4d5d-kqp8g  -n flux 
ERROR: logging before flag.Parse: W0625 06:20:16.164295       5 client_config.go:529] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
ts=2018-06-25T06:20:16.179774244Z caller=helm.go:49 component=helm info="Helm client set up"
ts=2018-06-25T06:20:16.179917673Z caller=main.go:168 component=helm-operator error="Failed to set up git authorization : &os.PathError{Op:\"stat\", Path:\"/etc/fluxd/ssh/identity\", Err:0x2}"
ts=2018-06-25T06:20:36.180801348Z caller=main.go:185 component=helm-operator info="Starting to clone repo ..."
ts=2018-06-25T06:20:36.267917384Z caller=git.go:86 component=git error="Failed to clone git repo [git@gitlab.aaa.com:ztwl/online-base-yaml, charts, master]: ssh: handshake failed: knownhosts: key is unknown"
ts=2018-06-25T06:20:46.323328061Z caller=git.go:86 component=git error="Failed to clone git repo [git@gitlab.aaa.com:ztwl/online-base-yaml, charts, master]: ssh: handshake failed: knownhosts: key is unknown"

**Comment by MicroKernelXulj** [comment]
I used the flux-helm-operator.I need to add .kube/config to it!
Thank you, my friend！

**Comment by squaremo** [comment]
It looks like you managed to solve this with Stephen's suggestion. Please re-open if there's still a problem.
