### ISSUE TITLE
Flux history mid-weight API requests

### ISSUE THREAD

**Issue by fbarl** [weaveworks/flux#1165]
It would be nice if querying Flux history with `{ simple: true }` also returned the list of affected services/workloads, or alternatively if there was an extra option to ask just for that additional info.

The use case in mind is filtering deployment annotations by namespace/service in Weave Cloud UI without having to make separate calls to the API - https://github.com/weaveworks/service-ui/issues/1358.

Unfortunately, using `{ simple: false }` there would be too expensive.

**Comment by squaremo** [comment]
@fbarl Looks like this pertains to weave cloud, rather than flux -- would you move it to weaveworks/service please. Thanks :sparkle:

**Comment by squaremo** [comment]
> would you move it to

Belay that, I'll do it now, since I closed this one.
