### ISSUE TITLE
Git clone fails in the helm-operator for private git repos

### ISSUE THREAD

**Issue by stephenmoloney** [weaveworks/flux#1167]
*Issue Description:*

- Whilst git clone is working within the flux operator, the helm flux operator is encountering an error `knownhosts: key mismatch` when it attempts to clone the repo. 

- Error message:

```
ts=2018-06-23T14:38:24.97059565Z caller=git.go:86 component=git error="Failed to clone git repo [ssh://git@git.codinghere.com:10022/kubernetes/kubenow_phoenix.git, charts, master]: ssh: handshake failed: knownhosts: key mismatch
```
- The error is emanating somewhere on line 86 of this file - `integrations/helm/git/git.go`

I can confirm that the following steps work inside the container for known_host key matching:

```
ssh -v -p 10022 git.codinghere.com
```

*Suggestion*:

- Run a test against a git url in the form `ssh://git@domain:[port]/[user]/repo.git`

Unfortunately, I'm not familiar with go so I don't know how to tackle this.

Kubernetes version: `v1.10.4`
Flux version: `https://github.com/weaveworks/flux/pull/1166`

**Comment by squaremo** [comment]
Is it possible that the helm-operator doesn't cope with private repos at all? I'm not sure it uses `known_hosts`, which would seem to need one of these:

https://github.com/src-d/go-git/blob/bb7c1a75dda604f8d7ee343227a64669a20aaab9/plumbing/transport/ssh/auth_method.go#L236

**Comment by squaremo** [comment]
Additionally: does the entry in known_hosts include the port? I wonder if that matters for `go-git` (the go library that is used in the helm operator) but not for `git` on the command line.

**Comment by stephenmoloney** [comment]
- `does the entry in known_hosts include the port?` yes.
```
kubectl -n flux exec -ti flux-helm-operator-646cc7d97b-x566w -- cat /root/.ssh/known_hosts
[git.codinghere.com]:10022 ssh-rsa <long_key>
```
- ` helm-operator doesn't cope with private repos at all?` - not sure, I'm unfamiliar with go code so it's taxing to read at the moment. I suppose the way I see it is, if the `flux` container can sync with the git repo at the same address, then I suppose the `flux-helm-operator` should be able to too theorectically.

**Comment by squaremo** [comment]
> I suppose the way I see it is, if the flux container can sync with the git repo at the same address, then I suppose the flux-helm-operator should be able to too theorectically.

The helm operator uses `go-git`, a library that replicates the git plumbing and some porcelain; whereas the flux daemon uses the `git` binary. So, regrettably, they can behave a bit differently (and secondarily, it's easier to troubleshoot the flux daemon).

> * does the entry in known_hosts include the port? yes.

OK scratch that theory then :-} I'll try running my own git server and go from there.

**Comment by squaremo** [comment]
@stephenmoloney If you don't mind trying a known_hosts that _doesn't_ use the port number, that would help eliminate (or confirm) another possibility, in the meantime.

**Comment by stephenmoloney** [comment]
Yea, I did think of trying that but it would be quite tricky because port 22 is occupied and I can't free it up.

**Comment by stephenmoloney** [comment]
```The helm operator uses go-git, a library that replicates the git plumbing and some porcelain; whereas the flux daemon uses the git binary. So, regrettably, they can behave a bit differently (and secondarily, it's easier to troubleshoot the flux daemon).```

What would it take to use the git daemon for the helm operator also?

**Comment by squaremo** [comment]
I set up a git server in my cluster using https://github.com/squaremo/git-serv, on a non-standard port, and the helm operator and fluxd could both clone the repo.

I'm not sure it's to do with the port, since when you removed the port from the known_hosts entry, it complained about the port being missing.

On the other hand, SSH was able to connect while git is not. So there's something odd going on there.

**Comment by squaremo** [comment]
A handful of troubleshooting things to try:

 - try using the most recent build of helm-operator, if you're not (https://quay.io/repository/weaveworks/helm-operator?tab=tags)
 - can you `git clone` from a shell in the helm-operator container?
 - if you `ssh-keyscan -p 10022 git.codinghere.com > ~/.ssh/known_hosts` in the container, does that change anything?

**Comment by stephenmoloney** [comment]
> try using the most recent build of helm-operator, if you're not (https://quay.io/repository/weaveworks/helm-operator?tab=tags)
 - Tried it on `quay.io/weaveworks/helm-operator:master-335c768`, same outcome.

> can you git clone from a shell in the helm-operator container?
Using master of flux, no - using the pull request branch #1166, yes.

> if you ssh-keyscan -p 10022 git.codinghere.com > ~/.ssh/known_hosts in the container, does that change anything?
- No it does not. I did a manual `ssh-keyscan -p 10022 git.codinghere.com > /root/.ssh/known_hosts` inside the container. Verified that it added the keys. Then verified that it would clone using the shell. But I continued to see the same error as outlined in the top of the issue.

The fact that the `git daemon` has been able to clone but not `git-go`, points to an issue with `git-go` for me.

**Comment by stephenmoloney** [comment]
I changed the VPS server I am running gitlab on to use port 22 for gitlab and unfortunately, I'm seeing the same issue. So the problem is not due to a port problem possibly. Although, something is still not right with git-go.

Cloning using the git daemon works:

```bash
kubectl -n flux exec -ti flux-helm-operator-69fdd596c9-4lwsn -- git clone ssh://git@git.codinghere.com/kubernetes/kubenow_phoenix.git
Cloning into 'kubenow_phoenix'...
remote: Enumerating objects: 410, done.
remote: Counting objects: 100% (410/410), done.
remote: Compressing objects: 100% (216/216), done.
remote: Total 410 (delta 199), reused 359 (delta 165)
Receiving objects: 100% (410/410), 123.35 KiB | 5.87 MiB/s, done.
Resolving deltas: 100% (199/199), done.
```

Cloning inside the helm operator is not working:

```bash
ts=2018-07-04T22:49:51.790805617Z caller=git.go:86 component=git error="Failed to clone git repo [ssh://git@git.codinghere.com/kubernetes/kubenow_phoenix.git, charts, master]: ssh: handshake failed: knownhosts: key mismatch"
```

Using latest master branch of helm-operator and flux (4/July/2018)

Summary:

Same problem exists on port 22 for a gitlab server.

**Comment by squaremo** [comment]
> I wonder if anyone else has the same issue with a private gitlab server?

Mind asking in the weave-community channel #flux? There's a fair to middling chance someone else there is using self-hosted gitlab. (I have tried it for myself only with a bare-bones SSH host, running inside the cluster.)

I'm going to take this as a big +1 for porting the helm-operator to the git implementation used in fluxd. It's less elegant, execing `git`, but it does seem to be a bunch less trouble :-/

**Comment by stephenmoloney** [comment]
@squaremo

I had another go at this today and on first glance, I have found a solution - replacing the <domain> with the <ip_address> in the knownhosts.

For some reason using the ip address instead of the domain name `git.codinghere.com` resolved the problem. 

I'm still checking now that everything is working and I'll report back if there are any issues but from a quick look just now, the helmoperator seems to be syncing ok now.

**Comment by stephenmoloney** [comment]
I think we can close this issue now, phew :sweat:

**Comment by squaremo** [comment]
That is mighty strange. Glad you got it working!
