### ISSUE TITLE
no errors or feedback when repo does not match running services

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/flux#117]

**Comment by squaremo** [comment]
The better output PR #421 checks the repo first, and shows if services defined there are not running in the platform. This will only show up as a side-effect of doing a release, though.

**Comment by squaremo** [comment]
There aren't that many opportunities to check this -- we only clone the repo when it's time to do a release (and when doing `flux status` -- I guess we could check some things there, but it only matters if the user calls it ...)

**Comment by sambooo** [comment]
Flux's job as of 1.* is to make sure the _cluster_ matches the repo, and not the other way around. No longer an issue.
