### ISSUE TITLE
Simplify getting the SSH key from the logs

### ISSUE THREAD

**Issue by dholbach** [weaveworks/flux#1179]
As part of #1130 @squaremo and I talked about how to most easily get the SSH keys from the log.

We currently

 1. advertise `fluxctl identity` (which requires having downloaded the binary and put it into `$PATH`) in `site/using.md`.
 1. extract it from Flux's logs:
 ```sh
[daniel@reef flux ]$ git grep "grep identity.pub"
chart/flux/README.md:kubectl -n flux logs deployment/flux | grep identity.pub | cut -d '"' -f2
chart/flux/templates/NOTES.txt:  kubectl -n {{ .Release.Namespace }} logs $FLUX_POD | grep identity.pub | cut -d '"' -f2
site/helm/installing.md:kubectl -n flux logs $FLUX_POD | grep identity.pub | cut -d '"' -f2
site/standalone/installing.md:kubectl logs deployment/flux | grep identity.pub | cut -d '"' -f2
[daniel@reef flux ]$ 
 ```

The latter can be convenient, but maybe we should agree on one way to go about it.

@squaremo brought up the idea of using something like `kubectl run --image weaveworks/flux -- identity`.

**Comment by dholbach** [comment]
Now that #1212 is landed, shall we cut over our docs to tell people to download `fluxctl` and use `identity` instead?

**Comment by dholbach** [comment]
If yes, we should probably land this before the next release? :)

**Comment by squaremo** [comment]
> Now that #1212 is landed, shall we cut over our docs to tell people to download fluxctl and use identity instead?

Can you elaborate on this suggestion? I thought the objection to "just use fluxctl" is that it means you have to go on an excursion to explain where to download fluxctl and so on.

**Comment by dholbach** [comment]
Where to download was only one step. This was what we had documented before:
```sh
fluxpod=$(kubectl get pod -l name=flux -o name | awk -F / '{ print $2; }')
kubectl port-forward "$fluxpod" 10080:3030 &
export FLUX_URL="http://localhost:10080/api/flux"
fluxctl list-controllers --all-namespaces
```
