### ISSUE TITLE
How to use flux to pass parameters to helm？

### ISSUE THREAD

**Issue by JoeyX-u** [weaveworks/flux#1202]
How to use flux to pass parameters to helm？
Such as using the helm hook.

**Comment by squaremo** [comment]
Hi; can you give more detail about what you're trying to do?

**Comment by JoeyX-u** [comment]
When I submit yaml to the repository, The flux will execute helm install to deploy the application, but I want to use helm preinstall to deploy.

**Comment by squaremo** [comment]
As I understand it from https://github.com/helm/helm/blob/master/docs/charts_hooks.md, pre-install hooks will be run as usual by Tiller, when the helm operator does the equivalent of `helm install`.

Did you try it out and find that it didn't work?

**Comment by squaremo** [comment]
Closing to take off the radar. Please feel free to re-open if it turns out my understanding was wrong all along ..
