### ISSUE TITLE
Extract useful info from site/helm/helm-integration*.md

### ISSUE THREAD

**Issue by dholbach** [weaveworks/flux#1205]
The content of `site/helm/helm-integration*.md` reads like a feature design document. Maybe we should extract all the relevant information for users into other parts of our docs and archive the rest.

**Comment by squaremo** [comment]
Yep I agree, that material needs a bit of repurposing.

**Comment by dholbach** [comment]
Largely fixed via #1357, remaining bits tracked in #1359 and #1360.
