### ISSUE TITLE
Gitlab CI runs every 5min on config repo

### ISSUE THREAD

**Issue by konfiot** [weaveworks/flux#1207]
Hello,
First of all, thanks a lots for flux, awesome software !
I've added CI to the configuration repo in order to check that the yaml in them are correct.
But now a Gitlab CI job is triggered every 5 min, every time flux refrexhes the repo, which is quite annoying (even when flux does no commit at all)
Do you have any idea of what may cause that ?
Thanks =)

**Comment by squaremo** [comment]
Hi! Thanks for the nice words.

Here's an explanation of why CI pipelines might get triggered: https://github.com/weaveworks/flux/pull/1158/files#diff-fcba6c0e142e67cd9cb9939369ac7154R186
(yes, it's still in a PR!)

In short: flux pushes a tag to the upstream repo, to keep track of where its up to with syncing. The name of the tag is something you can set, so you could try excluding that from your CI config. I _think_ this is the relevant section of gitlab docs: https://docs.gitlab.com/ee/ci/yaml/#only-and-except-simplified

**Comment by konfiot** [comment]
Oh, yes, thanks  !

**Comment by stephenmoloney** [comment]
I might add something to the docs for gitlabci when i get it done myself.

**Comment by konfiot** [comment]
I can give you mine if you want, but that's pretty straightforward

**Comment by stephenmoloney** [comment]
This is what I have at the moment for `.gitlab-ci.yml`
```
  except:
    variables:
      - $CI_COMMIT_TAG =~ /flux-*/
```
