### ISSUE TITLE
fluxctl on Windows?

### ISSUE THREAD

**Issue by geofflamrock** [weaveworks/flux#1214]
Hi,

Is it possible to run fluxctl on Windows? I didn't see a build for Windows listed in the releases.

Thanks.

**Comment by squaremo** [comment]
To be honest, so much of flux assumes Linux or at least Unix, that I didn't consider building Windows binaries. But of course, much of it is running in containers, so perhaps `fluxctl` would be OK.

**Comment by squaremo** [comment]
Looks like it builds. I am reluctant to attach a binary here (and github probably wouldn't let me). But if we can establish that it works, I can include it in the release build.

**Comment by geofflamrock** [comment]
I'd be happy to test the binary out if you can get it to me somehow?

**Comment by squaremo** [comment]
> I'd be happy to test the binary out if you can get it to me somehow?

Email me at my published address and I'll send you a ZIP-of-a-binary.

**Comment by squaremo** [comment]
^ review label = reminder to myself to add a windows `fluxctl` build to the Makefile and CI uploads

**Comment by geofflamrock** [comment]
Hi @squaremo, just wondering where this has gotten up to? I'd be happy to give a retest on the new 1.5.0 version if that would help. Thanks :)

**Comment by squaremo** [comment]
Releases now include a windows binary of `fluxctl` -- and I just [released v1.6.0](https://github.com/weaveworks/flux/releases/tag/1.6.0), so you can download it from there, and future release pages :smiley_cat:

By the way, if there is a preferred Windows package manager, akin to `brew` or `snap`, we may be able to make it available that way too.

**Comment by geofflamrock** [comment]
Thanks heaps @squaremo !

For Windows there is Chocalatey (https://chocolatey.org/), I'm not really sure what is involved in getting packages registered, I can have a look tho.

Thanks again :)
