### ISSUE TITLE
Link to a config / repo setup example docs

### ISSUE THREAD

**Issue by dholbach** [weaveworks/flux#1220]
In the past weeks I've seen a couple of questions which were about the config / repo setup and the requirements of flux. It'd be great if we could document this or at least link off to 1-2 different examples we maintain.

Good fits would be:
- https://github.com/weaveworks/flux/blob/master/site/requirements.md
- https://github.com/weaveworks/flux/blob/master/site/faq.md#do-i-have-to-have-my-application-code-and-config-in-the-same-git-repo

**Comment by dholbach** [comment]
The following repos come to mind - which of these are the best maintained and most likely to be of use?

 - https://github.com/weaveworks/flux-example
 - https://github.com/weaveworks/flux-helm-test
 - https://github.com/stefanprodan/k8s-podinfo
 - https://github.com/stefanprodan/weave-flux-helm-demo
 - https://github.com/microservices-demo/microservices-demo(?)
 - which others?

@squaremo @stefanprodan - which repos do you usually point people to?

**Comment by squaremo** [comment]
> In the past weeks I've seen a couple of questions which were about the config / repo setup and the requirements of flux

What were the questions?

**Comment by dholbach** [comment]
The last two I saw were

 - "app and config are part of the same code base.. [...] do we care if app and config are separate repos?"
 - https://weave-community.slack.com/archives/C4U5ATZ9S/p1531227261000051

**Comment by dholbach** [comment]
With #1527, I think this one can be closed. We clarified a few bits regarding requirements and repo setup in our FAQ as well.
