### ISSUE TITLE
helm-op: VSTS git repositories are not cloning

### ISSUE THREAD

**Issue by grimesjm** [weaveworks/flux#1224]
Running Flux in GKE with the helm operator. From the flux logs it's cloning my private repo down just fine having set the known hosts.  The helm operator container is failing to clone with the following error: " empty git-upload-pack given".  I execed into that container and was able to clone just fine.  

After digging around for a while I think the issue that it works with flux but not in the helm operator has to do with the fact there are two different implementations for working with git.  The helm operator is using go-git underneath and it looks like and there's a long outstanding issue on multi-ack support and VSTS which is what I'm using.  https://github.com/src-d/go-git/issues/335

I also just mirrored it to a private github repository dropped in the deploy key and the helm operator picked it up just fine

**Comment by marccarre** [comment]
Many thanks for opening this issue @grimesjm.
For the record & posterity, this was originally raised on [Slack](https://weave-community.slack.com/archives/C4U5ATZ9S/p1531352975000016).

**Comment by squaremo** [comment]
@grimesjm #1240 swapped out the git implementation in the helm operator for the code used by fluxd -- if you're in a position to, would you mind trying the image `quay.io/weaveworks/helm-operator:master-dfcfd33` (the build from the merge of that PR into master) to see if you have better results. Thanks!

**Comment by grimesjm** [comment]
I will give that a try.  It will be a few days

**Comment by hiddeco** [comment]
Confirmed the Helm operator does no longer have issues with VSTS (now Azure DevOps).

```
ts=2019-02-17T21:33:28.819046807Z caller=chartsync.go:272 component=chartsync info="started mirroring repo" repo=git@ssh.dev.azure.com:v3/<snip>/hidde/hidde
```
