### ISSUE TITLE
Interactive `fluxctl release` command

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#1227]
At present you can

    fluxctl release --dry-run ...

to show you what would have been released at that moment, or

    fluxctl release ...

to just release what will be released at that moment. But you can't either release exactly what the first thing tells you (and do it all in one go), or pick and choose what to do (and do it all in one go).

With #1218 it's possible to release an exact specification of images; so it's possible to get the plan and turn that into a spec (if it looks good), and either succeed or fail in one go.

**Comment by sambooo** [comment]
an extension of this is adding or removing arbitrary bits of yaml interactively rather than just specific images on containers I think
