### ISSUE TITLE
Unable to sync helm

### ISSUE THREAD

**Issue by konfiot** [weaveworks/flux#1232]
Hello,
I've got a little problem, when trying to setup the helm integration, the helm operator outputs the following error : 
```
ts=2018-07-15T14:47:52.536540553Z caller=git.go:86 component=git error="Failed to clone git repo [ssh://git@<gitlab>/br/kubernetes-helm-state, charts, master]: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain"
```
I can manually clone the repo when attaching the pod though

Thanks in advance for any help

**Comment by squaremo** [comment]
The help operator's use of go-git seems to struggle with authentication, more so than fluxd (which just exec's `git` itself). One thing that seems to have helped, though I don't know why, is replacing hostnames in `known_hosts` with IP addresses (https://github.com/weaveworks/flux/issues/1167).

**Comment by konfiot** [comment]
Nope =/
Also my server was offering ecdsa first as his key, forced it to rsa, but still the same error...

**Comment by konfiot** [comment]
Why is helm not using git as fluxd ?

**Comment by squaremo** [comment]
> Why is helm not using git as fluxd ?

It was developed separately, at a time when the git implementation in fluxd wasn't very generic (it is more so now), and using a native go git library was appealing. I'm in the process of replacing it with the package used in fluxd.

**Comment by stephenmoloney** [comment]
@squaremo Actually, replacing with ip addresses was not the solution in the end - I think.

Can you `cat /root/.ssh/known_hosts` and paste the output here @konfiot ?

**Comment by squaremo** [comment]
Another thing that may help diagnose the problem is the output of

    ssh -vv git@<gitlab>

run from a shell in the pod.

**Comment by konfiot** [comment]
Yep, the spacing is correct, (generated with keyscan), one line by key. I even tried with only one key

**Comment by konfiot** [comment]
```ssh -vv``` works, here's the output : 
```
/home/flux # ssh -v git@gitlab
OpenSSH_7.5p1-hpn14v4, LibreSSL 2.5.5
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 1: Applying options for *
debug1: Connecting to gitlab [<ip>] port 22.
debug1: Connection established.
debug1: permanently_set_uid: 0/0
debug1: key_load_public: No such file or directory
debug1: identity file /etc/fluxd/ssh/identity type -1
debug1: key_load_public: No such file or directory
debug1: identity file /etc/fluxd/ssh/identity-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /var/fluxd/keygen/identity type -1
debug1: key_load_public: No such file or directory
debug1: identity file /var/fluxd/keygen/identity-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.5p1-hpn14v4
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.7p1 Debian-2
debug1: match: OpenSSH_7.7p1 Debian-2 pat OpenSSH* compat 0x04000000
debug1: Remote is NON-HPN aware
debug1: Authenticating to gitlab:22 as 'git'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: rsa-sha2-512
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ssh-rsa SHA256:qIRr5JU8tefawsvZ4Bngwf8k8hvAXtxWHkkDAvaAVTw
debug1: Host 'gitlab' is known and matches the RSA host key.
debug1: Found key in /root/.ssh/known_hosts:1
Failed to add the RSA host key for IP address '<IP>' to the list of known hosts (/root/.ssh/known_hosts).
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Trying private key: /etc/fluxd/ssh/identity
Authenticated with partial success.
debug1: Authentications that can continue: keyboard-interactive
debug1: Next authentication method: keyboard-interactive
debug1: Authentication succeeded (keyboard-interactive).
Authenticated to gitlab ([<IP>]:22).
debug1: HPN to Non-HPN Connection
debug1: Final hpn_buffer_size = 2097152
debug1: HPN Disabled: 0, HPN Buffer Size: 2097152
debug1: channel 0: new [client-session]
debug1: Enabled Dynamic Window Scaling
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: pledge: network
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug1: Remote: /var/opt/gitlab/.ssh/authorized_keys:105: key options: command user-rc
PTY allocation request failed on channel 0
Welcome to GitLab, @konfiot!
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
debug1: client_input_channel_req: channel 0 rtype eow@openssh.com reply 0
debug1: channel 0: free: client-session, nchannels 1
Connection to gitlab closed.
Transferred: sent 2820, received 2644 bytes, in 0.3 seconds
Bytes per second: sent 10072.0, received 9443.4
debug1: Exit status 0
```

**Comment by squaremo** [comment]
> debug1: Authentications that can continue: publickey
> debug1: Next authentication method: publickey
> debug1: Trying private key: /etc/fluxd/ssh/identity
> Authenticated with partial success.
> debug1: Authentications that can continue: keyboard-interactive
> debug1: Next authentication method: keyboard-interactive
> debug1: Authentication succeeded (keyboard-interactive).
> Authenticated to gitlab ([<IP>]:22).

This bit looks like it asked for a password at the console -- is that the case? (If not, I wonder if go-git needs more tweaking to get it to do the right thing at this step)

**Comment by konfiot** [comment]
Nope, it didn't ask for any password..., I'll check the server config

**Comment by konfiot** [comment]
Okay, that was it : We have a yubikey auth on our servers, that's why there is this keyboard-interactive auth after the key auth, but in case of the git user, it is trivial because there is no yubikey activated and the auth with yubikey is desactivated for this user, ssh seems to see that automatically, but go-git doesn't

**Comment by squaremo** [comment]
The `ssh` and `git` binaries seem to do a bit more finessing than go-git does (or our code in the helm operator does). Yet another reason to replace go-git :-/
