### ISSUE TITLE
helm operator continuously upgrades chart with dependencies

### ISSUE THREAD

**Issue by ncabatoff** [weaveworks/flux#1235]
After logging "Resyncing manually upgraded Chart", helm-operator upgrades the chart, then a few minutes does it again, and again, forever.

I hacked the code to log the currRel.GetChart().String() and desRel.GetChart().String() from shouldUpgrade(), and diffed them.  It looks like the only difference was in the "dependencies" field, and that they had the same set of values but in different order. 

One way to fix this might be to use go-cmp on the chart objects instead of simple string comparison, with cmpopts.SortSlices to accommodate the variable order of the dependencies.  This would also allow logging a more informative message as to what will change post-upgrade, via the Diff() method.

**Comment by stefanprodan** [comment]
Closing since it's fixed in #1235
