### ISSUE TITLE
find yamls in more than one dir

### ISSUE THREAD

**Issue by grantbachman** [weaveworks/flux#1267]
I know there exists an option for ignoring specific manifests through an annotation in the manifest, but it would be nice to be able to configure flux to ignore entire directories. The use case I see for this is two-fold:
  * We'd like to be able to store both our production and non-production manifests in a single repository. We have a large number of [sealed-secrets](https://github.com/bitnami-labs/sealed-secrets), where they are partitioned out by environment. We don't wish to deploy credentials for a staging environment onto the production cluster and vice versa.
  * Flux seems to get choked up over helm chart template files that are suffixed as `.yaml`. Ideally, we'd like to store all of our custom helm charts and config in the same repo, but don't wish to use the FluxHelmOperator just yet. Flux is still walking our helm chart directory tree and erring out when it finds a template file.

How are people getting around this limitation currently, and do you see this as being hard to implement?

**Comment by squaremo** [comment]
> We'd like to be able to store both our production and non-production manifests in a single repository. We have a large number of sealed-secrets, where they are partitioned out by environment. We don't wish to deploy credentials for a staging environment onto the production cluster and vice versa.

Is the implied requirement that you also have a bunch of config that is exactly the same in both environments, and you don't want to duplicate it? E.g., you have something like

```
/
/common
/prod
/non-prod
```

and you'd like to point flux at `/` but exclude `/prod` or `/non-prod`.

You can already restrict flux to looking at a subdirectory of the git repo; would it be suit you better or worse if that were extended so you could provide more than one subdirectory, i.e., the paths that you _do_ want to include?

> Flux seems to get choked up over helm chart template files that are suffixed as .yaml

It's supposed to avoid directories that look like charts (specifically, any directory that has both a Chart.yaml and a values.yaml file in it); if you can put together a example of this not working, please file a separate issue and include the example -- thanks.

**Comment by grantbachman** [comment]
Thanks for getting back to me @squaremo! Yes, most of our config is exactly the same, but with some differences (mainly secrets) across the different environments.

> would it be suit you better or worse if that were extended so you could provide more than one subdirectory, i.e., the paths that you do want to include?

Thinking about it more, it would be way better to be able to specify multiple _include_ directories, as you suggested. I imagine the dominant use case would be to have mostly the same config in each environment with slight differences. It'd also have the benefit of not having to reconfigure flux in the existing environments if you were to create a new environment that you want ignored.

**Comment by squaremo** [comment]
> It'd also have the benefit of not having to reconfigure flux in the existing environments if you were to create a new environment that you want ignored.

Oh yeah, nice point.

> How are people getting around this limitation currently,

In the case of our own use of flux, for weave cloud, we almost always have only _near_ duplication in manifests, so there's fairly few files which can be factored out anyway. We'd have to use something like `kustomize` to really factor out the common bits.

> [...] and do you see this as being hard to implement?

I think there's a few superficial places that assume a single subdirectory (or none), but most of the machinery in flux is already build to look in multiple paths. I've labeled this with a coarse estimate of `size/medium` because I think the superficial stuff might take a bit of chasing down.
