### ISSUE TITLE
Use helm recreate-pods option

### ISSUE THREAD

**Issue by ncabatoff** [weaveworks/flux#1275]
For the in-house CD system that Flux is replacing at my workplace, I've been using the helm option --recreate-pods when doing upgrades.  I'm aware that with Flux I could use automation to perform upgrades whenever the docker registry gets newer images.  I don't want to do that: our CI system produces both charts and docker images from the same project repo, and I want all upgrades to go through Helm, so that the charts and the images coming from the same build are always used together.

I'd be happy to provide a PR if you're open to adding this feature.

**Comment by stefanprodan** [comment]
If you want to trigger a rolling update on each deploy, you could increment the chart version in your CI system and if you use the chart version as a label on your pods this will recreate all pods without the need to pass ` --recreate-pods`.

**Comment by stefanprodan** [comment]
You can use this [Helm plugin](https://github.com/mbenabda/helm-local-chart-version) in your CI to bump the chart version:

```bash
helm plugin install https://github.com/mbenabda/helm-local-chart-version

helm local-chart-version bump --version-segment patch -c ./path-to-chart-dir
```

**Comment by squaremo** [comment]
I'm not clear on what problem `helm upgrade --recreate-pods` solves -- if you update the image using in the chart (or values for the chart), won't that result in a rolling upgrade?

**Comment by ncabatoff** [comment]
You're right, I was imagining a bogus use case that doesn't make sense in this context.
