### ISSUE TITLE
Provide pod status when listing services

### ISSUE THREAD

**Issue by rndstr** [weaveworks/flux#1303]
The current service status when listing services is either `ready`, `updating`, or `X out of N updated`. It would be helpful to have a detailed pod status that tells a broader picture what is currently going on.

**Comment by rade** [comment]
> a broader picture what is currently going on.

Like what?

**Comment by squaremo** [comment]
I think the mode of calling this API will matter too -- e.g., if you want to know the status of your release,

 - you'll probably need to be able to ask for the status of a particular set of services;
 - you also need to know whether your release is actually in the process of being rolled out yet (versus fully rolled out), so you might have to give it a baseline;
 - you will want to know if there was a problem applying the change for any particular controller, since that means you won't see any rollout progress.

**Comment by rndstr** [comment]
Talked this over with @lelenanam and a structure to provide more info about a workload's pod rollout progress could be
```
{
  "default:deployment/work-load": {
    …
    Status: "updating", // deprecated
    PodStatus: {
      Status: "updating",
      Desired: 10,
      Updated: 4,
      Ready: 3,
      Outdated: 7,
      Pods: {
        "work-load-123456-123": {
          …
        },
        …
      }
    }
  },
  …
}
```

**Comment by lelenanam** [comment]
We can use deployment conditions, for example:
```
Type=Progressing
Status=False
Reason=ProgressDeadlineExceeded
```

**Comment by squaremo** [comment]
> * you also need to know whether your release is actually in the process of being rolled out yet (versus fully rolled out), so you might have to give it a baseline;

Is this correct: if you know that your new version of a manifest has been applied, then all the pod status numbers will be in relation to that new revision, so if it says they are all ready, it must have completed rollout.

**Comment by lelenanam** [comment]
I think so, yes.

**Comment by squaremo** [comment]
OK so the related issues are:

> you'll probably need to be able to ask for the status of a particular set of services;

Covered in #1352.

> you will want to know if there was a problem applying the change for any particular controller, since that means you won't see any rollout progress.

Still a concern; covered in #1010.

**Comment by lelenanam** [comment]
Pod rollout progress structure example:
```
type ControllerPodStatus struct {
	// Status of controller pod
	Status string
	// Desired number of pods as defined in spec.
	Desired int32
	// Updated number of pods that are on the desired pod spec.
	Updated int32
	// Ready number of pods that are on the desired pod spec and ready.
	Ready int32
	// Outdated number of pods that are on a different pod spec.
	Outdated int32
	// Conditions represents the latest available observations of a controller's current state.
	Conditions []PodCondition
}

// PodCondition describes pod condition
type PodCondition struct {
	Name string
	// A human readable message indicating details about why the pod is in this condition.
	Message string
	// A brief CamelCase message indicating details about why the pod is in this state.
	Reason     string
	Conditions []Condition
}

// Condition describes the state of a Controller at a certain point.
type Condition struct {
	// Type of condition.
	Type string
	// Status of the condition, one of True, False, Unknown.
	Status string
	// The reason for the condition's last transition.
	Reason string
	// A human readable message indicating details about the transition.
	Message string
}
```
And we can return only conditions with Type `PodScheduled`/`PodInitialized`/`PodReady` and with Status `False`.

**Comment by lelenanam** [comment]
>Is this correct: if you know that your new version of a manifest has been applied, then all the pod status numbers will be in relation to that new revision, so if it says they are all ready, it must have completed rollout.

Correction: It is correct if all are ready and outdated is zero, otherwise, it means that they are ready but not updated yet.
