### ISSUE TITLE
Explain how the annotations work, thoroughly

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#1309]
- lock and lock_msg etc.
 - automated
 - ignore (there's already good material there)
 - tag filters

**Comment by sahitpj** [comment]
I think I would like to work on this issue, if it hasn't been assigned to anyone yet.

**Comment by squaremo** [comment]
> I think I would like to work on this issue, if it hasn't been assigned to anyone yet.

That'd be great! I'm more than happy to discuss and review things.

**Comment by dholbach** [comment]
https://github.com/weaveworks/flux/blob/master/site/helm-integration.md#optional-fields lists two examples for the `automated` annotation (thanks to @stefanprodan).

They might be useful to pull out and explain more generally somewhere else.

**Comment by dholbach** [comment]
https://github.com/weaveworks/flux/issues/1337#issuecomment-421152125 (a duplicate issue) has another example.

**Comment by tux-00** [comment]
Any news on this issue ? A good documentation would ease adoption of flux.

**Comment by paulmil1** [comment]
where the hell is documentation?  are you serious????

**Comment by 2opremio** [comment]
@paulmil1 the tone of your comment is unprofessional, uncalled for and against CNCF's code of conduct. Thus, I am locking this conversation. 

However, if you want to improve the documentation, feel free to create a PR for it, it will always be welcome as long as it confirms the code of conduct.

**Comment by dholbach** [comment]
You might be looking for https://docs.fluxcd.io/en/latest/tutorials/driving-flux.html (we moved the docs a little).
