### ISSUE TITLE
Include docker.config mount in chart

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#1310]
From https://github.com/weaveworks/flux/issues/539#issuecomment-414046279:

> would it be possible to add the docker.config parameter to the helm chart? Than you only need to generate the config-mapping or secret

I think this means: if you supply this argument, then mount the docker-config from the resource named.

**Comment by Alien2150** [comment]
Hey, you nailed it :)

**Comment by squaremo** [comment]
> if you like i could provide a PR @squaremo

That would be very welcome!

**Comment by Alien2150** [comment]
https://github.com/weaveworks/flux/pull/1314
