### ISSUE TITLE
Document using sidecar/job pod to get ECR credentials into a secret

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#1324]
See https://github.com/weaveworks/flux/issues/539#issuecomment-417372214

**Comment by bzon** [comment]
@squaremo  See also https://github.com/bzon/ecr-k8s-secret-creator

**Comment by geoah** [comment]
Would be nice if there was an optional value in the helm chart that would allow mounting the config from @bzon's sidecar and using it as a docker config without having to manually edit or manage the kubernetes resource.

**Comment by hiddeco** [comment]
Since #1619 we have native support for ECR credentials.
