### ISSUE TITLE
fluxctl port forward is broken on GKE

### ISSUE THREAD

**Issue by stefanprodan** [weaveworks/flux#1331]
Once this PR gets merged https://github.com/justinbarrick/go-k8s-portforward/pull/2/files the portforward package has to be updated in Flux.

**Comment by hiddeco** [comment]
Our clusters are running on GKE and we are able to connect to the Flux daemon without any changes to underlying libraries.

The `fluxctl` binary we use is build from https://github.com/weaveworks/flux/tree/1.5.0 with a patch applied to `Gopkg.toml` (`version = "v1.0.1"`).

**Comment by hiddeco** [comment]
Did some more digging and I think the `fluxctl` bundled with the `1.6.0` release is faulty and packaged with the `1.0.0` release from `go-k8s-portforward`.

```console
$ curl -o /tmp/fluxctl -LO https://github.com/weaveworks/flux/releases/download/1.6.0/fluxctl_linux_amd64
$ sudo install -m755 /tmp/fluxctl /usr/local/bin/
$ fluxctl --k8s-fwd-ns flux list-controllers --all-namespaces
Error: No Auth Provider found for name "gcp"
Run 'fluxctl list-controllers --help' for usage.
```

```console
$ git checkout tags/1.6.0
$ dep ensure && make
$ fluxctl --k8s-fwd-ns flux list-controllers --all-namespaces
CONTROLLER                                                        CONTAINER                      IMAGE                                                                                    RELEASE             POLICY
<snip>
```
