### ISSUE TITLE
Add indent function to improve the use of the additionalArgs option in the Flux Helm chart

### ISSUE THREAD

**Issue by kozejonaz** [weaveworks/flux#1347]
Right now the [additionaArgs](https://github.com/weaveworks/flux/blob/master/chart/flux/values.yaml#L118) is [missing indentation](https://github.com/weaveworks/flux/blob/master/chart/flux/templates/deployment.yaml#L83) to properly support more than one additional arguments.

If you change
```
          {{- if .Values.additionalArgs }}
          {{ toYaml .Values.additionalArgs }}
          {{- end }}
```
to something like
```
# {{- if .Values.additionalArgs }}
# {{ toYaml .Values.additionalArgs | indent 10 }}
# {{- end }}
```
it will properly indent all additional arguments specified in `values.yaml`.

**Comment by bhavin192** [comment]
I would like to work on this
