### ISSUE TITLE
Consider new Helm example

### ISSUE THREAD

**Issue by dholbach** [weaveworks/flux#1360]
In #1357 the question came up if we want to continue to use [flux-helm-test](https://github.com/weaveworks/flux-helm-test) as an example. It's referred to from our [Helm tutorial](https://github.com/weaveworks/flux/blob/master/site/helm-get-started.md).

Who has a small example test-case which we could use here?

**Comment by squaremo** [comment]
This is the neon bug! (see labels)
A small example that covers the basics (and is not quite as messy as flux-helm-test) would be wonderful.

**Comment by AugustasV** [comment]
Sorry, I still don't understand so what should I do? Ok I setup flux-helm-test, what now?

**Comment by squaremo** [comment]
> Sorry, I still don't understand so what should I do? Ok I setup flux-helm-test, what now

If you've got flux and the helm operator running, using a fork of flux-helm-test, you could try committing changes in your fork to see what happens.
