### ISSUE TITLE
Question: How can flux with helm support auto detect latest docker image

### ISSUE THREAD

**Issue by tlvu** [weaveworks/flux#1378]
Hi, I am following the [using.md](https://github.com/weaveworks/flux/blob/master/site/using.md) tutorial using the [flux-helm-test](https://github.com/weaveworks/flux-helm-test) repo.

I tried `fluxctl release --controller=test:fluxhelmrelease/mongodb --k8s-fwd-ns=flux --update-all-images` and it was not able to detect the latest docker image (the standalone flux was able to).  It results in this broken commit https://github.com/tlvu/flux-helm-test/commit/00916a3185a935a2476a99ab04b9055dc0bbb0a3 (notice the bad update `image: bitnami/mongodb:_`).

How can flux with helm support auto detect latest docker image?

**Comment by squaremo** [comment]
It's only fluxd that's doing any latest image detection; i.e., it would work the same with or without the helm operator. What you might be seeing is that the mongodb image has a tag `_` which points at the most recent image. If I look on dockerhub, I do not see that tag though. This bears a bit of looking into.

**Comment by squaremo** [comment]
> If I look on dockerhub, I do not see that tag though.

Ops! I was looking at the official mongo image. The _bitnami_ image does have a tag `_`: https://hub.docker.com/r/bitnami/mongodb/tags/

I'd put a semver filter on that resource, so it is restricted to the images with a proper version.

**Comment by tlvu** [comment]
Oh so the tag `_` actually exist !  Wow misleading tag !

Closing this issue as I just retested with my own image and `--update-all-images` is working:

```
$ fluxctl list-images --controller=default:fluxhelmrelease/bc-release-service                                                                     
CONTROLLER                                  CONTAINER    IMAGE                                                            CREATED
default:fluxhelmrelease/bc-release-service  chart-image  bcdocker-staging-rnd-artifacts.intelerad.com/bc-release-service  
                                                         |   1.0.1-lvu-testing                                            26 Sep 18 21:40 UTC
                                                         |   latest                                                       25 Sep 18 18:35 UTC
                                                         '-> 1.0.0                                                        24 Sep 18 13:47 UTC

$ fluxctl release --controller=default:fluxhelmrelease/bc-release-service --update-all-images -vv                                                 
Submitting release ...
CONTROLLER                                  STATUS   UPDATES
default:fluxhelmrelease/bc-release-service  success  chart-image: bcdocker-staging-rnd-artifacts.intelerad.com/bc-release-service:1.0.0 -> 1.0.1-lvu-testing
Commit pushed:  9b77caa
Commit applied: 9b77caa
```
