### ISSUE TITLE
defaults for rbac.create

### ISSUE THREAD

**Issue by stephenmoloney** [weaveworks/flux#1388]
***Issue:***

By default `rbac.create` does not seem to be specified in the `values.yaml` file and hence is effectively missing unless the `helm install --set rbac.create=true` command includes it. 
Perhaps, it should be set by default.

***Proposed solution:***

Add 

```
rbac:
  create: true
```

to the `values.yaml` file

**Comment by stefanprodan** [comment]
This is in values.yaml https://github.com/weaveworks/flux/blob/master/chart/flux/values.yaml#L53

**Comment by stephenmoloney** [comment]
ok, thanks, i must have missed it !
