### ISSUE TITLE
(flux with helm) fluxctl release --user is not respected

### ISSUE THREAD

**Issue by tlvu** [weaveworks/flux#1398]
```
$ fluxctl release --controller=default:fluxhelmrelease/bc-release-service --update-all-images --user "lvu@intelerad.com" --message "BC-3916: update latest image" -vv
Submitting release ...
CONTROLLER                                  STATUS   UPDATES
default:fluxhelmrelease/bc-release-service  success  chart-image: bcdocker-staging-rnd-artifacts.intelerad.com/bc-release-service:1.0.0 -> 1.0.1-lvu-testing
Commit pushed:  e93cf00
Commit applied: e93cf00
```

fluxd logs:
```
ts=2018-09-27T16:23:03.208744265Z caller=daemon.go:582 component=daemon event="Released: bcdocker-staging-rnd-artifacts.intelerad.com/bc-release-service:1.0.1-lvu-testing to default:fluxhelmrelease/bc-release-service, by lvu@intelerad.com, with message \"BC-3916: update latest image\"" logupstream=false
```

But the actual commit to the Flux repo is using the user previously given by `--set git.user=` and `--set git.email=` when we helm install the flux chart into k8s.

I would have expected the commit to use the `--user` value supplied to `fluxctl`.

**Comment by squaremo** [comment]
Have you given fluxd the flag `--git-set-author` as well? It's a bit counter-intuitive, but you need that as well.

**Comment by tlvu** [comment]
> Have you given fluxd the flag `--git-set-author` as well? It's a bit counter-intuitive, but you need that as well.

Nope, we didn't do that.  That would correspond do the chart value `git.setAuthor` I assume.

Will test and report back.

**Comment by tlvu** [comment]
Yup using helm install flux with `--set git.setAuthor=true` does honor the `--user` option with `fluxctl`.

However, it even use my git user configured in my `~/.gitconfig` even if I did not supply the `--user` with `fluxctl` while I have given `--set git.user=` and `--set git.email=` when installing flux helm chart.

I guess I can live with this behavior but can you just confirm this is by design and not a sneaky bug?

**Comment by squaremo** [comment]
> can you just confirm this is by design and not a sneaky bug?

It's by design -- `fluxctl` gets those values from git config, deliberately. It was intended as a convenience; if it's not what you expected or wanted, maybe we could add a flag or environment variable to disable that behaviour.

**Comment by tlvu** [comment]
As I use this, I think I like the current convenience behavior. Closing.
