### ISSUE TITLE
Automated Upgrades Only Reacting To Binary Changes

### ISSUE THREAD

**Issue by leoblanc** [weaveworks/flux#1408]
Hello, we have a question/issue please. We are using Flux via Helm and using ECR to store our Docker images.

We are testing the automated upgrades feature by using the following configuration on each "release" file:

```
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:master-*
```

We use a similar approach for other releases/environments like "qa" etc. [Upgrades basically works as it's described on the documentation.](https://github.com/weaveworks/flux/blob/master/site/how-it-works.md#monitoring-for-new-images). Every time that a new Docker image is pushed using the same preffix mentioned on the annotation (master-*, qa-* etc), the container image is also upgraded by Flux. So far, so good.

However, there is a special case where we noted that this process doesn't occur. Not sure if this is intentional or a bug. This is the case: 

1. Suppose that your Docker image contains the application code saying "Hello World". Docker image is built and pushed to Docker Registry, tagged as master-v1 (using the build number as suffix)

2. Then, you change your application code to say "Hello World 2". A new Docker image is built and pushed to Docker Registry, tagged as master-v2. Flux automatically upgrades the container image to use v2 instead of v1, since this is a more recent image. So far, so good.

3. Then, you change the application code to rollback your previous change, so it says "Hello World" again (exactly as in the point #1). A new build process occurs and the image is pushed to Docker Registry (ECR in our case). This is the third build, so the tag used is master-v3. However, since v1 and v3 are exactly the same code and exactly the same binary image, ECR just adds the new tag to the old image, so you have basically 2 images:

a. First image tagged as v1 and v3
b. Second image tagged as v2

This time, Flux doesn't upgrade the image of the container. So, the container is still running v2 ("Hello World 2") even when a more recent build process occurred. I guess that this behavior occurs because, v2 is still newer than v3 (from a binary point of view). However, could be great if Flux can detect what is the image with the latest tag (v3 in this case). This behavior is very useful to deploy an automated rollback. There are any workarounds to support this use case?

Thank you very much in advance.

**Comment by rndstr** [comment]
If you use semantic versioning it would determine the newest by comparing the versions (and not image creation time which it does when using globs or no filter):
https://github.com/weaveworks/flux/blob/master/site/using.md#semver

> Using a semver filter will also affect how flux sorts images, so that the higher versions will be considered newer.

```
    flux.weave.works/tag.chart-image: semver:*
```

That means you would need to actually introduce semver tags like `v1` or `1.0.0`.

**Comment by leoblanc** [comment]
@rndstr Thank you very much for your feedback! I think that semver can be a good option. Also, your comment give me another idea: [maybe I can also use the regexp option](https://github.com/weaveworks/flux/blob/master/site/using.md#regexp), since we include the name of the git branch (matching a k8s namespace) as preffix. Thank you very much!
