### ISSUE TITLE
Flux applies changes to the cluster very slowly

### ISSUE THREAD

**Issue by brantb** [weaveworks/flux#1422]
Recently we've begun to see a significant increase in the amount of time flux takes to sync the git repository to the cluster:

```
ts=2018-10-03T19:09:42.295546122Z caller=sync.go:121 component=cluster method=Sync cmd=apply args= count=119
ts=2018-10-03T19:14:31.162556177Z caller=sync.go:164 component=cluster method=Sync cmd="kubectl apply -f -" took=4m48.866802454s err=null output="namespace \"cluster-admin\" configured\n <snip>
```

Based on the flux logs, it looks like individual `kubectl apply` calls are taking 6-11 seconds to return:

```
ts=2018-10-02T21:18:17.751129168Z  caller=sync.go:164 component=cluster method=Sync cmd="kubectl apply -f  -" took=4.865805366s err=null output="clusterissuer  \\"redacted\\" configured"
ts=2018-10-02T21:18:24.480141851Z  caller=sync.go:164 component=cluster method=Sync cmd="kubectl apply -f  -" took=6.728899883s err=null output="sealedsecret  \\"redacted\\" configured"
ts=2018-10-02T21:18:28.58635465Z  caller=sync.go:164 component=cluster method=Sync cmd="kubectl apply -f  -" took=4.106128199s err=null output="fluxhelmrelease  \\"redacted\\" configured"
ts=2018-10-02T21:18:33.328764968Z  caller=sync.go:164 component=cluster method=Sync cmd="kubectl apply -f  -" took=4.742312018s err=null output="horizontalpodautoscaler  \\"redacted\\" unchanged"
```

In contrast, syncing the entire git repo from my local machine takes under 5 seconds.

I launched a copy of `k8s.gcr.io/hyperkube:v1.9.0` in the cluster, ran `kubectl apply -Rf` on a clone of our git repository, and it completed quickly there as well. I also tried moving the flux pod to a different node on the cluster to rule out a transient network issue, but there was no effect. It seems only flux is affected.

Let me know if there's any other information I can provide to help troubleshoot this, because I'm stumped.

k8s version: 1.11.2
flux: 1.7.1

([initial discussion](https://weave-community.slack.com/archives/C4U5ATZ9S/p1538583413000100))

**Comment by justinbarrick** [comment]
Do individual applies take 4-6 seconds if you try that locally?

```
time kubectl apply -f file.yaml
```

As I understand it, flux is deploying files or directories one at a time and this might be inefficient.

**Comment by brantb** [comment]
@justinbarrick Run locally, individual applies also finish very quickly, and don't exhibit the same problem.

@squaremo Interesting, thanks for the background info! We had one YAML manifest containing a formatting error, which must have been why flux was doing the sync in two stages.

I tested `kubectl apply` within the flux pod as you suggested and reproduced the slow behavior, but I decided to bump up the log verbosity and found something interesting:

```
# kubectl exec -it flux-54fb649979-whv55 -- time kubectl apply -v=6 -f /tmp/flux-working134349209/path-to/namespace.yaml
I1004 14:27:24.022489   19805 loader.go:357] Config loaded from file /root/.kube/config
I1004 14:27:24.023028   19805 merged_client_builder.go:123] Using in-cluster configuration
I1004 14:27:25.085618   19805 round_trippers.go:436] GET https://10.0.0.1:443/swagger-2.0.0.pb-v1 200 OK in 1062 milliseconds
I1004 14:27:25.200885   19805 merged_client_builder.go:123] Using in-cluster configuration
I1004 14:27:25.201544   19805 merged_client_builder.go:123] Using in-cluster configuration
I1004 14:27:25.202082   19805 decoder.go:224] decoding stream as YAML
I1004 14:27:25.202500   19805 merged_client_builder.go:123] Using in-cluster configuration
I1004 14:27:25.223500   19805 round_trippers.go:436] GET https://10.0.0.1:443/api 200 OK in 20 milliseconds
I1004 14:27:25.238057   19805 round_trippers.go:436] GET https://10.0.0.1:443/apis 200 OK in 13 milliseconds
I1004 14:27:25.241120   19805 cached_discovery.go:133] failed to write cache to /root/.kube/cache/discovery/10.0.0.1_443/servergroups.json due to mkdir /root/.kube/cache: read-only file system
I1004 14:27:25.252141   19805 round_trippers.go:436] GET https://10.0.0.1:443/apis/apiregistration.k8s.io/v1 200 OK in 10 milliseconds
I1004 14:27:25.252851   19805 cached_discovery.go:86] failed to write cache to /root/.kube/cache/discovery/10.0.0.1_443/apiregistration.k8s.io/v1/serverresources.json due to mkdir /root/.kube/cache: read-only file system
I1004 14:27:25.276198   19805 round_trippers.go:436] GET https://10.0.0.1:443/apis/apiregistration.k8s.io/v1beta1 200 OK in 23 milliseconds
I1004 14:27:25.280988   19805 cached_discovery.go:86] failed to write cache to /root/.kube/cache/discovery/10.0.0.1_443/apiregistration.k8s.io/v1beta1/serverresources.json due to mkdir /root/.kube/cache: read-only file system
I1004 14:27:31.085824   19805 round_trippers.go:436] GET https://10.0.0.1:443/apis/extensions/v1beta1 200 OK in 5804 milliseconds
I1004 14:27:31.086479   19805 cached_discovery.go:86] failed to write cache to /root/.kube/cache/discovery/10.0.0.1_443/extensions/v1beta1/serverresources.json due to mkdir /root/.kube/cache: read-only file system
<snip many lines like the previous two>
namespace "cluster-admin" configured
real	0m 43.37s
user	0m 0.24s
sys	0m 0.07s
```

Each of the API calls takes either 8-15ms or, randomly, _2-5 seconds_. 💥 The reason I was unable to reproduce this elsewhere was because flux is making around 100 requests to the API server per `apply` operation, vs. 2-3 when `.kube/cache/discovery` is already populated. This made it much less obvious that our API server is having a bad day.

**Comment by squaremo** [comment]
Nice sleuthing! I wonder why that bit of filesystem is read-only. Do you mount your own kubeconfig file from a configmap?

**Comment by squaremo** [comment]
Ahhh that'll be it then -- configmaps and secrets are mounted read-only, which makes the cache directory read-only. I suspect the easiest solution will be to mount the kubeconfig elsewhere and use the environment variable `KUBECONFIG` to point to it.

**Comment by squaremo** [comment]
@stefanprodan Something to try in the Helm chart I reckon ^
