### ISSUE TITLE
Hook for telling helm-operator about git changes

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#1430]
For the flux daemon we have (in the RPC, and possibly in the HTTP API) a hook to tell it when there's new commits in git. The helm operator would also benefit from a hook, since it also monitors a git repository.

NB though, this most likely requires some architectural changes, or at least other components to be employed, since there still needs to be something to listen to a public IP and convey the webhook to the operator.

**Comment by aaparmeggiani** [comment]
What about using something like https://hub.docker.com/r/almir/webhook to listen to webhooks?

**Comment by squaremo** [comment]
There's plenty of possibilities to play the part of the hook receiver -- what's missing is the endpoint in the helm operator to tell it to fetch the git repo. (Not difficult, just not a requirement covered by off-the-shelf kit)

**Comment by aaparmeggiani** [comment]
Yep, but having fluxctl inside the webhook container, it wouldn't be the case of just firing a 'fluxctl sync' ?  Avoiding extra code in the operator??.

**Comment by squaremo** [comment]
`fluxctl sync` will tell fluxd to fetch from git and apply everything. That's different from the helm-operator fetching from (chart) git and re-releasing charts; hence this issue.
