### ISSUE TITLE
Document what gets synchronized to the git repo by flux

### ISSUE THREAD

**Issue by timthelion** [weaveworks/flux#1443]
Reading the documentation it is not at all clear to me what gets automatically synchronized to the git repo by flux. The sentence here https://github.com/weaveworks/flux/blob/master/site/faq.md#why-does-flux-need-a-deploy-key "Flux needs a deploy key to be allowed to push to the version control system in order to read and update the manifests", seems to suggest to me that only the manifests which are in the git repo will be updated, and other manifests will not. I presume that means that if I upload secrets to the cluster using kubectl then they won't end up automatically synced to my git repo by flux, but that's not actually stated and this lack of clairity makes me quite nervous.

**Comment by hiddeco** [comment]
To calm your nerves: Flux will not create new manifests for resources in your git repository, it will only update resources already in git to reflect cluster state.

**Comment by squaremo** [comment]
> it will only update resources already in git to reflect cluster state.

Not even that; it will only update manifests in git, when you tell it to, then apply them to the cluster.

**Comment by timthelion** [comment]
How does that work? I've created a placeholder PR which I'll update until we come to the heart of the matter https://github.com/weaveworks/flux/pull/1444

**Comment by hiddeco** [comment]
@timthelion see my updated answer, I was a bit too quick with the shiny green button.

**Comment by squaremo** [comment]
Thanks for opening a PR, @timthelion -- it's certainly worth clearing up what gets synced with what. I've commented in the PR, on the direction of synchronisation. Let us know here or there if we can shine more light on the matter ..
