### ISSUE TITLE
Add prometheus annotation for Helm chart

### ISSUE THREAD

**Issue by marcusolsson** [weaveworks/flux#1461]
We're using the Helm chart to deploy Flux, and want to let Prometheus scrape the metrics endpoint. Right now I'm annotating the pod with `kubectl annotate ...` but ideally there should be an option to add it to the deployment. 

I'd like to either add `prometheus.io/scrape: "true"` to the chart manifest by default, or enable it through `values.yml`. I'd happily submit a PR if you think it's worthwhile.

**Comment by stefanprodan** [comment]
Adding the prometheus annotation to Flux deployment file sounds good to me, I don't think it needs to be in `values.yml`.
