### ISSUE TITLE
Setting helmOperator.tls.caContent doesn't work

### ISSUE THREAD

**Issue by arthurk** [weaveworks/flux#1475]
Following this guide: https://gist.github.com/thojkooi/fee37a4b0e872c17783bcc44eee3e974 I tried to install Flux with the helmOperator tls verify option:

```
helm install --name flux \
--set helmOperator.create=true \
--set git.url=ssh://git@github.com/username/flux-helm-test \
--set helmOperator.git.chartsPath=charts \
--set helmOperator.tls.enable=true \
--set helmOperator.tls.verify=true \
--set helmOperator.tls.secretName=helm-client-certs \
--set helmOperator.tls.caContent="$(cat ca.pem)" \
--set-file helmOperator.tls.caContent=ca.pem \
--namespace flux \
weaveworks/flux
```

The problem is the `helmOperator.tls.caContent` variable. Running the above example will result in only the first line being set to `-----BEGIN CERTIFICATE-----` as the configmap value. The helmOperator fails with `Error creating helm client: failed to append certificates from file: /etc/fluxd/helm-ca/ca.crt`.

Using `--set-file` fails with the following error when installing the chart `Error: YAML parse error on flux/templates/helm-tls.yaml: error converting YAML to JSON: yaml: line 7: did not find expected key`

**Comment by hiddeco** [comment]
@arthurk I just pushed a fix to the `master` branch to address this issue, if you check out this repository and run `helm install` in `chart/flux/` it should work.

```
$ git clone git@github.com:weaveworks/flux.git
$ cd flux/chart/flux
$ helm install --name flux \
    --set helmOperator.create=true \
    --set git.url=ssh://git@github.com/username/flux-helm-test \
    --set helmOperator.git.chartsPath=charts \
    --set helmOperator.tls.enable=true \
    --set helmOperator.tls.verify=true \
    --set helmOperator.tls.secretName=helm-client-certs \
    --set helmOperator.tls.caContent="$(cat ca.pem)" \
    --set-file helmOperator.tls.caContent=ca.pem \
    --namespace flux .
```
