### ISSUE TITLE
Improve commit message for containers release

### ISSUE THREAD

**Issue by rndstr** [weaveworks/flux#1478]
Currently

```
Release containers

default:deployment/foo
- quay.io/bar/foo:master-d9500ad8

default:deployment/moo
- quay.io/bar/moo:master-d9500ad8
```

A better version
```
Release containers to default:deployment/foo, default:deployment/moo

default:deployment/foo
- quay.io/bar/foo:master-d9500ad8

default:deployment/moo
- quay.io/bar/moo:master-d9500ad8
```

which brings it more in tune with other commit messages that mention the workloads in the main message.

**Comment by rade** [comment]
@lelenanam didn't you already do some work on this?

**Comment by rndstr** [comment]
I did talk with @lelenanam about this which she intended to do as part of the events/notification work
