### ISSUE TITLE
A filename start/end with spaces should not trimmed ？

### ISSUE THREAD

**Issue by mumutu66** [weaveworks/flux#1481]
This is a rare cases, but once meet is really difficult to find out the reason.

when the manifest file in git with name start or end with spaces. 

in git/operations.go 

```
func splitList(s string) []string {
	outStr := strings.TrimSpace(s)
	if outStr == "" {
		return []string{}
	}
	return strings.Split(outStr, "\n")
}

```
then the filename is changed , will always got a `lstat` error

there is two case

* one know the filename with spaces --- then means flux not support it
* one don't know the filename with spaces --- in case use gitlab , filename with spaces cannot be seen on the  ui (gitlab ui also trim the filename),  while the error print the path is what the people thought (no spaces).. and is hard to find out the error.. 

so I suggest  instead of using Trim  maybe can append ` ' ` `'` on the filename can do the tick.... or just document that one should care about the filename (maybe there already exists one , but I didn't find it, in that case be free  to close this ticket )

though this maybe out of the project scope (I think no normal person would like use a name start or end with spaces..)..

**Comment by squaremo** [comment]
Thank you for reporting this -- it must have been tricky finding the cause of the problem.

I figured out some more context: the place `splitList` is used with filenames is in `changed()` (in the same file), which is then used in `Checkout.ChangedFiles()`. I wonder if it would be better if callers of `splitList` trimmed the string themselves (or even if it weren't done at all).
