### ISSUE TITLE
All logging goes to Stderr

### ISSUE THREAD

**Issue by olib963** [weaveworks/flux#1491]
It seems that all logs from flux go to Stderr, which makes it difficult in stack driver to determine what logs are actually errors. I think [this line](https://github.com/weaveworks/flux/blob/6c8cd0d0f0c50e0a28d789edcf68717c84aa3831/cmd/fluxd/main.go#L144) is the cause. Happy to look into opening a PR for this, but wanted a bit of guidance on preferred solution/implementation. Thanks.

**Comment by stefanprodan** [comment]
All Kubernetes services/operators are logging to stderr. You need to write a Fluentd filter for Flux and determine if a log contains an error or not based on the `err=''` field.

**Comment by hiddeco** [comment]
I am unsure if a Fluentd filter is a solution for GKE but you should be able to do the same filtering with [Advanced Filters](https://cloud.google.com/logging/docs/view/advanced-filters).

**Comment by olib963** [comment]
Thank you both for the feedback, I was not aware this was a convention. I will try implementing the Fluentd solution.

**Comment by squaremo** [comment]
@olib963 Do you mind closing this issue, if you are happy with the advice here? You can still comment here, e.g.,  to report results for posterity.

**Comment by hpurmann** [comment]
Has someone written and published a fluentd filter/parser? @stefanprodan ?

**Comment by pratap-dotnet** [comment]
Anybody still looking at the parser/filter? If yes, could you please share the filter. Stackdriver is completely filled with error logs even while there is no error

**Comment by pratap-dotnet** [comment]
> Thank you both for the feedback, I was not aware this was a convention. I will try implementing the Fluentd solution.

@olib963 do you have the solution
