### ISSUE TITLE
Incorrect Flux and Helm Operator version defaults in source code of release 1.8.0 

### ISSUE THREAD

**Issue by adamsteinbok** [weaveworks/flux#1495]
It seems that the changes made in [#1470](https://github.com/weaveworks/flux/pull/1470) were not included in the 1.8.0 release. This means that the charts included in that release are, by default, actually deploying `flux:1.7.1` and `flux-helm-operator:0.2.1` rather than the expected `flux:1.8.0` and `flux-helm-operator:0.3.0`.

Additionally, the manifests in `deploy` and `deploy-helm` do not appear to have been updated since release 1.7.0 and are deploying `flux:1.7.0` and `flux-helm-operator:0.2.1` respectively.

Seems like the chart in the repo at https://weaveworks.github.io/flux is correct.

**Comment by stefanprodan** [comment]
Our release process goes like this: we do a Flux or helm-op GitHub release that will publish a docker image for that git tag, if the build was successful we update the Helm chart and do another git tag with the chart version and finally we publish the chart.

**Comment by stefanprodan** [comment]
The chart and Helm repo https://weaveworks.github.io/flux are updated after we release Flux and/or helm-op. Closing this.
