### ISSUE TITLE
Get started with Flux using Helm instructions not lead to working example

### ISSUE THREAD

**Issue by kopachevsky** [weaveworks/flux#1528]
Followed those steps https://github.com/weaveworks/flux/blob/master/site/helm-get-started.md

No pods/deployments in test namespace, see log file attached with

`kubectl -n flux logs deployment/flux -f `

output
[flux.log](https://github.com/weaveworks/flux/files/2592209/flux.log)

**Comment by stefanprodan** [comment]
@kopachevsky the Flux Helm Operator that you've installed is no longer compatible with the CRD used in the flux-helm-test repo. Sorry for this, I've updated the docs in #1527

**Comment by kopachevsky** [comment]
@stefanprodan nice to see such quick fix, can you clarify what documentation file should I use for quickstart? same helm-get-started.md?

**Comment by stefanprodan** [comment]
You can use this https://github.com/weaveworks/flux/blob/60dc37429a5f61762851ad4e286a7a18c6cdd8dc/site/helm-get-started.md

**Comment by stefanprodan** [comment]
Closing this as the [docs](https://github.com/weaveworks/flux/blob/master/site/helm-get-started.md) have been updated in master.
