### ISSUE TITLE
Upgrade docs 0.4 to 0.5 break CRD

### ISSUE THREAD

**Issue by sfrique** [weaveworks/flux#1534]
Hello,

The docs [1] on upgrade from 0.4 to 0.5 deletes the current CRD and makes flux (while not terminated) remove some charts, and the updated helm doesn't work as there are no CRD because `crd-hook` is only ran at install [2]

As of now, I don't have time to debug/test a nice upgrade path.
What seems to work, is to remove the annotation, then helm will create both, but also remove it when flux is deleted.

Do flux plan to create CRs at helm install? I think hook is only needed if creating CRs at helm are necessary.
Also, do flux want to helm to delete or keep CRD at flux chart deletion? This also helps to define what will be default behavior.

Anyway, when I get sometime I will see a good way of making the `helm upgrade` works, most likely we need to template the annotation and only use it for new installs.

By the way, I love flux, we are using on all our clusters, but not yet for all charts.

1 - https://github.com/weaveworks/flux/blob/helm-0.5.0/site/helm-upgrading-to-beta.md
2 - https://github.com/helm/helm/pull/3982

**Comment by stefanprodan** [comment]
This has been fixed in #1536
