### ISSUE TITLE
GitTimeout is not been used on helm-op anymore (chartsync)

### ISSUE THREAD

**Issue by sfrique** [weaveworks/flux#1551]
There was some refactor on upgrading to 0.5 to use git uri per CRD and that change is not using  mirrors at chartsync and not passing the timeout to git.

Here is the line:
https://github.com/weaveworks/flux/blob/master/integrations/helm/chartsync/chartsync.go#L267

**Comment by hiddeco** [comment]
@squaremo 

I am wondering if this should be a per `HelmRelease` configuration or a global flag like it used to be, by the looks of it the `--git-poll-interval` flag has also stopped working (or is actually replaced by the `---charts-sync-interval` flag).

**Comment by sfrique** [comment]
I think all git options now should be per `HelmRelease` each repository can have it's own key/timeout and so on.
For the `charts-sync-interval` I rather have it global.
