### ISSUE TITLE
Helm chart : serviceAccount.name ignored

### ISSUE THREAD

**Issue by batpok** [weaveworks/flux#1588]
Helm chart is incorrect: 
If serviceAccount.create is false, serviceAccount.name is ignored.
`default` serviceAccount is used in both flux anf helm-operator deployments.

see both 
* https://github.com/weaveworks/flux/blob/master/chart/flux/templates/deployment.yaml
* https://github.com/weaveworks/flux/blob/master/chart/flux/templates/helm-operator-deployment.yaml

**Comment by stefanprodan** [comment]
This is the intended behavior, nothing wrong with it from my perspective. Can you please explain what are you trying to accomplish?

**Comment by batpok** [comment]
Thank you Stefan, we did not want to associate flux service account with an "admin" cluster role
