### ISSUE TITLE
DNS resolution of memcached service fails

### ISSUE THREAD

**Issue by dilshad18** [weaveworks/flux#1591]
Following error is happening in flux installation inside minikube instance:

`component=memcached err="error updating memcache servers: lookup 172-17-0-3.flux-memcached.flux.svc.cluster.local. on 10.96.0.10:53: no such host"`

This is a rather fresh installation and only few files have been applied. We update a single file and it tries to update that and it fails,

**Comment by squaremo** [comment]
It looks like it either can't reach the DNS server, or doesn't get a result back. The hostname there is a bit odd -- should it include the hyphenated IP address like that? I would expect just `flux-memcached.flux.svc.cluster.local`.

**Comment by johnraz** [comment]
I can reach the memcache container from the fluxd container by hitting the hostname passed to fluxd:

`ps aux` gives (truncated by me):

```
fluxd --ssh-keygen-dir=/var/fluxd/keygen --k8s-secret-name=flux-git-deploy --memcached-hostname=flux-memcached ...
```
Telnet session from the fluxd container gives (again truncated by me):

```
/home/flux # telnet flux-memcached 11211
stats
STAT pid 1
STAT uptime 63144
STAT time 1544719316
...
```

**Comment by squaremo** [comment]
> So I would say the memcache server list is properly provisioned with the valid hostname and some "ghost" hostnames are trying to get in and are rejected because they can't resolve...

Yes, that sounds like a good diagnosis. Filling in some details, after looking in the Kubernetes docs re service discovery:

The way it's set up in the example deployment (and chart, and Weave Cloud config, ...) is that memcached has a headless service. According to https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#services (also see https://github.com/kubernetes/dns/blob/master/docs/specification.md), in DNS there will be:

 - An A record for memcached.namespace.svc.cluster.local with the IP of each ready pod;
 - An A record for <hostname>.memcached.namespace.svc.cluster.local for each pod, where <hostname> is a generated name;
 - A SRV record which has the auto-generated hostname, and the port, for each pod in the service

With the arguments given in the example deployment of fluxd, it'll query for the SRV records, then the memcache client code (linked above) will query the IP of each host mentioned. So where it's failing is in that second bit -- it can't resolve some or all of the hosts it got from the SRV records.

But the question remains: how did those unresolveable endpoints get there in the first place? That I don't know :-(

**Comment by squaremo** [comment]
BTW it is entirely fine to give the memcached service a clusterIP (i.e., don't set it to `None`), and _not_ supply the `memcached-service` argument -- this will make it just resolve the service address, rather than go through SRV records etc.
