### ISSUE TITLE
Despite adding the annotation to automate the release, POLICY field is empty.

### ISSUE THREAD

**Issue by rampreethethiraj** [weaveworks/flux#1598]
I have added the annotation to automate the release. But when I run the list-controllers command , under the policy field, I don't see anything./
```
flux-ctl list-controllers 
```
under the policy , it shows empty. Is there anything else to be done for flux ctl to understand that it is an automated release other than adding the annotation.

**Comment by hiddeco** [comment]
Adding the annotation should be enough to automatically release the latest version of the image in your manifest.

Can you please share a (stripped) copy of the manifest containing the annotation so we can verify you added them at the right place / used the correct annotation?

**Comment by rampreethethiraj** [comment]
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: <sample-name>
  namespace: <sample-namespace>
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:<sample-tag>-*
spec:
  releaseName: <sample-release-name>
  chart:
    git: <sample-git-url>
    path: charts/<sample-release-name>
    ref: master
  values:
     <sample-values>
---

**Comment by hiddeco** [comment]
Does your `.spec.values` contain `.spec.values.image.repository` and `.spec.values.image.tag` values?

If this is not the case please add them, without them Flux is unable to determine _what_ it should update as it does not look at the default values from the chart.

**Comment by rampreethethiraj** [comment]
Yes, it does contain that.

**Comment by hiddeco** [comment]
Do you mind dropping by on our Slack channel `#flux`? It is easier for me to help you there as I need to know a couple of things to draw conclusions on the issue you are experiencing. [You can request an automated invite here](https://slack.weave.works/).

My username on Slack is `@hidde`, feel free to ping.

**Comment by squaremo** [comment]
Additional info (from Slack): the manifest posted above is in a file in the git repo, and is _synced_ by fluxd

**Comment by hiddeco** [comment]
Closing this as it was [due to a typo in the `values` of the `HelmRelease`](https://weave-community.slack.com/archives/C4U5ATZ9S/p1555409055249400?thread_ts=1555408535.249000&cid=C4U5ATZ9S).
