### ISSUE TITLE
only push tag if changes

### ISSUE THREAD

**Issue by davidkarlsen** [weaveworks/flux#1604]
We send events to slack on changes in our repos - and flux causes an event on every loop run every 5mins - either there are changes or not.

See slack thread: https://weave-community.slack.com/archives/C4U5ATZ9S/p1544906747429300
where I talked to @justinbarrick which found https://github.com/weaveworks/flux/blob/5cdd31490cffd16fd065dee671f2be83c10b4089/git/operations.go#L226 where it seems a push is done either there was a change or not.

Could this be altered to only push if there are in fact changes?

It also causes this problem:
```
git fetch --tags
remote: Counting objects: 1, done.
remote: Total 1 (delta 0), reused 0 (delta 0)
Unpacking objects: 100% (1/1), done.
From ssh://fsstash.evry.com:7999/tac_jfr/flux
 ! [rejected]        flux-sync  -> flux-sync  (would clobber existing tag)
```

**Comment by squaremo** [comment]
Closing as duplicate, and also because #1605.
