### ISSUE TITLE
Using standalone flux to deploy secrets

### ISSUE THREAD

**Issue by marcincuber** [weaveworks/flux#1607]
Context:
I am using flux to deploy system wide resources which include cluster roles, cluster role bindings, namespaces and services such as external dns, metrics server. All the yamls are in the protected repository which doesn't contain any secrets, tokens etc. So it is safe for people to have Read-Only access.

Now I am trying to add NewRelic integration which requires unique `token`. Currently, I have bash script which fetches the token (encrypted with KMS) from AWS Parameter Store, generates yamls including secrets and then deploys it using kubectl. I would like to move away from that approach and use flux to deploy both the secret and NewRelic.

Questions:
Please assume that I don't want to add unencrypted tokens or values to the repository. 

1. What is the advised way of creating and deploying secrets which are later used by applications?
2. Is it possible for flux to fetch encrypted values from Parameter Store?
3. Should flux be used to create secrets? If so, question 1.

**Comment by squaremo** [comment]
Thanks for bringing this use case up!

1. A way that seems to work for people is to use [SealedSecrets](https://github.com/bitnami-labs/sealed-secrets), and commit the encrypted secret to git. Fluxd will create or updated the encrypted secret, then the sealed secret controller will decrypt to a regular Secret that other resources can refer to.

2., and 3. fluxd doesn't have any integration with the AWS Parameter Store; and, it's not really in the business of secrets management.

Having said that latter, I'm not stridently opposed to integrations where they will straighten the path for people on particular platforms -- more apprehensive about embarking on new features where there are already adequate solutions. Make sense?

**Comment by marcincuber** [comment]
> Thanks for bringing this use case up!
> 
> 1. A way that seems to work for people is to use [SealedSecrets](https://github.com/bitnami-labs/sealed-secrets), and commit the encrypted secret to git. Fluxd will create or updated the encrypted secret, then the sealed secret controller will decrypt to a regular Secret that other resources can refer to.
> 
> 2., and 3. fluxd doesn't have any integration with the AWS Parameter Store; and, it's not really in the business of secrets management.
> 
> Having said that latter, I'm not stridently opposed to integrations where they will straighten the path for people on particular platforms -- more apprehensive about embarking on new features where there are already adequate solutions. Make sense?

Thanks for quick answer. SealedSecrets looks like something I could use. Do you have any simple examples of how to use SealedSecrets with Flux?

Apart from SealedSecrets, are there any other options that I could consider?

I am not too keen on integration either. I would rather keep Flux simple and specific to what it is meant to do.

**Comment by stefanprodan** [comment]
@marcincuber here is an example of using Sealed Secrets and Flux https://github.com/stefanprodan/gitops-helm#managing-kubernetes-secrets

**Comment by marcincuber** [comment]
Closing as my questions have been answered and [SealedSecrets](https://github.com/bitnami-labs/sealed-secrets) is the valid solution for me.

👍

**Comment by squaremo** [comment]
@marcincuber Thank you for posting that. I have not seen an example of the layered fluxes as you have in there, before. Really interesting, and thorough!
