### ISSUE TITLE
`fluxctl` commands fail when using composite KUBECONFIG environment varible

### ISSUE THREAD

**Issue by switchboardOp** [weaveworks/flux#1613]
Running `fluxctl identity` on WSL Ubuntu 16.04 with my `KUBECONFIG` environment variable set to concatenate several configs returned this error. 

```text
[☸ kubernetes-admin@cluster.local:default] flux|master⚡ ⇒ fluxctl identity
Error: stat /home/lm/.kube/config:/home/lm/.kube/kube-config-mnd-k8s:/home/lm/.kube/kube-config-mnp-k8s:/home/lm/.kube/spray-config: no such file or directory
Run 'fluxctl identity --help' for usage.
```

**Comment by switchboardOp** [comment]
This also causes the same error when running `fluxctl sync`.
Is there a work around for this or is `flux` unusable if you have to access more than one cluster?

**Comment by switchboardOp** [comment]
one can run the command with a temporary env var like this:
`KUBECONFIG=/home/lm/.kube/config fluxctl sync`
But i would still expect the cli to respect the current kube context.

**Comment by 2opremio** [comment]
The Kubernetes port-forwarding library used by flux [doesn't respect path lists in KUBECONFIG](https://github.com/justinbarrick/go-k8s-portforward/blob/v1.0.1/portforward.go#L74-L89). I will look into upstreaming a fix for it.

**Comment by switchboardOp** [comment]
Thanks for the quick PR @2opremio!
