### ISSUE TITLE
Question: Helm sealed secrets

### ISSUE THREAD

**Issue by donifer** [weaveworks/flux#1616]
Noob question:

I created a sealed secret for mysql username and another one for its password. However, I'm not sure how to feed it to mysql's helm chart. I actually think its not possible but want someone to tell me if I'm correct.

Looks like using `values:` on my `HelmRelease` will override the values.yaml. I can set `mysqlUser` and `mysqlPassword` but I have no idea how to get them from the actual secret. Would appreciate any advice.

**Comment by stefanprodan** [comment]
It is possible, you can supply values from secrets using the `HelmRelease.spec.valueFileSecrets` array, here are the docs https://github.com/weaveworks/flux/blob/master/site/helm-integration.md#specvaluefilesecrets

You should create a single secret file with both username and password and supply that in the `valueFileSecrets`.

**Comment by donifer** [comment]
What a beauty. Thank you so much!

**Comment by stefanprodan** [comment]
I've never seen this, helm-op or Flux are not deleting any kind of Kubernetes objects. Looks a like a bug in the Sealed Secrets controller, you should submit an issue to their repo.

**Comment by aaparmeggiani** [comment]
Hi Stefan,

in the end it was my mistake as  my 'rabbitmq'  Secret name  was clashing
with the one created by the HelmRelease :^/

I deleted the question to avoid confusion, but thanks a lot for you quick
response!

Cheers,
Andre

**Comment by katherine-boost** [comment]
I came here via google, and for others who do the same - 

`valueFileSecrets` has now been replaced by `valuesFrom` `secretKeyRef`
https://docs.fluxcd.io/projects/helm-operator/en/stable/helmrelease-guide/values/#secrets
