### ISSUE TITLE
Flux not honouring /etc/hosts file

### ISSUE THREAD

**Issue by rampreethethiraj** [weaveworks/flux#1627]
We have a private repo where we store all the images. When flux is trying to read images from this private repo, what is happening is  that it is resolving the dns to a public ip and is trying to connect there despite specifying hostAliases in the yaml and I have crossverified that under /etc/hosts there is an entry for the docker repo. Could someone please help me out as to understand what is happening here .

**Comment by squaremo** [comment]
This is most likely connected to https://github.com/golang/go/issues/22846: Go's native hostname resolution checks DNS before `/etc/hosts` (in the absence of `/etc/nsswitch.conf`). We use alpine as the base image, and there is no `/etc/nsswitch.conf` shipped with alpine.

Remedy: we can include a minimal `/etc/nsswitch.conf` in the image, as suggested in the issue mentioned.
