### ISSUE TITLE
Unable to fetch private registry

### ISSUE THREAD

**Issue by shahbour** [weaveworks/flux#1635]
Flux is not able to list tags from our private registry even though the pod and deployment do have       `imagePullSecrets` set. I think there is something wrong with my secret but it is working with the deployment 

```
ts=2019-01-07T12:40:37.87551769Z caller=images.go:128 component=cluster resource=default:deployment/cdrimport err="decoded credential for https://registry.xxxxxxxx.com has wrong number of fields (expected 2, got 1)"
```

**Comment by stefanprodan** [comment]
Have you used kubectl 1.13 to generate the secret? if so see #1596

**Comment by shahbour** [comment]
yes I did

**Comment by stefanprodan** [comment]
No workaround for now, please use kubectl 1.12

**Comment by shahbour** [comment]
ok I confirm everything workes perfect on version 1.12
