### ISSUE TITLE
Github public repository fails to clone

### ISSUE THREAD

**Issue by Tusharsb** [weaveworks/flux#1651]
Whether I try [Get Started with Standalone Flux](https://github.com/weaveworks/flux/blob/master/site/get-started.md) or [Get Started with Flux using Helm](https://github.com/weaveworks/flux/blob/master/site/helm-get-started.md) I end up with this error in my `logs deployment/flux`
```
ts=2019-01-13T10:45:43.057854652Z caller=loop.go:87 component=sync-loop err="git repo not ready: git clone --mirror: fatal: Could not read from remote repository."
```
To troubleshoot deeper when I try to SSH into the flux pod using `exec` command I get the following error
```
$ kubectl -n flux exec -it flux-64598f5975-gbxvd /bin/bash
OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown
command terminated with exit code 126
```
I wanted to get some more verbose response to why flux is not able to read from the public github repository ?

I am trying to deploy the flex-get-started example by using 
```
helm upgrade -i flux \                                    
--set helmOperator.create=true \
--set helmOperator.createCRD=false \
--set git.url=git@github.com:tusharsb/flux-get-started \
--namespace flux \
weaveworks/flux
```

And my kubernetes version is as follows
```
$  ~ kubectl version                                           
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

What I might be doing wrong ?

**Comment by stefanprodan** [comment]
I'm guessing you didn't setup the SSH public key with write access as a GitHub deploy key. Flux image is based on alpine and doesn't have bash installed. Exec will work with `kubectl -n flux exec -it flux-9f586b47d-6ppxr sh`

**Comment by Tusharsb** [comment]
> Exec will work with `kubectl -n flux exec -it flux-9f586b47d-6ppxr sh`

After successfully logging into the pod, I find that pod does not has access to internet at the first place. troubleshooting it further. Will post updates for future googlers here. I am using minikube

**Comment by 2opremio** [comment]
Closing. @Tusharsb did you solve the problem?
