### ISSUE TITLE
Exclude domains from image metadata scanning

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#1654]
While implementing #1619 I realised it would be quite easy to add a filter to the domains that get scanned for image metadata. This would be useful for

 - stopping fluxd scanning the system images
 - switching scanning off altogether

and no doubt a few requirements specific to individual cases.

**Comment by alanjcastonguay** [comment]
I would like to see this. I have some images pulled from public registries on gcr.io or quay.io that I'm never going to enable automation on. I don't need the image metadata from those registry repositories, so the continual scanning creates unnecessary network traffic. Ideally this would be possible to specify with an annotation on a given controller (like the inverse of `automated=true`), or a list of domain/repository patterns configured on the Flux deployment.

**Comment by rade** [comment]
> disable scanning for anything that's _not_ needed for automation.

That's an eminently sensible idea. No extra config/flag needed. _However_, wouldn't this break listing of available versions for manual deployment, e.g. in the likes of Weave Cloud?

**Comment by dananichev** [comment]
Related to my issue #1677. I want to avoid unnecessary traffic and scanning. As i suggested in #1677 maybe Flux should scan only those images for which automate enabled?
