### ISSUE TITLE
Allow specifying registry certificate authority

### ISSUE THREAD

**Issue by michaelfig** [weaveworks/flux#1682]
My internal Docker registry uses https only, and its certificate is signed by an internal CA.  When I run fluxd installed with the helm chart, I get:

```
ts=2019-01-22T20:26:18.820968558Z caller=warming.go:155 component=warmer canonical_name=registry.example.com/
                              image-name auth="{map[registry.example.com:<registry creds for user@registry.example.com, 
                               from user:secret/cluster-registry>]}" err="Get https://registry.example.com/v2/: x509: certificate signed 
                               by unknown authority"
```

and the images are never detected.

This configuration works for Docker because I have installed the appropriate CA in the host OSes credential store.

I expect the same error to happen with self-signed certificates.

I am preparing a PR for this issue, to use an approach similar to the flux helm operator's `--tiller-tls-ca-cert-path` option, and will post it when I have something workable.

Thanks,
Michael.

**Comment by squaremo** [comment]
#1526 will be of interest.

**Comment by michaelfig** [comment]
Thanks @squaremo.

 I adapted https://github.com/weaveworks/flux/commit/096bd478dbe2808d3b3a5699b73f94568b06a9f7

always to use basic authentication (not just for HTTPS), and I'm pleased to report that it works in my environment.

I've created a pull request, #1685, to summarize the changes I used: not for merging as you already have #1526.

**Comment by kennethredler** [comment]
@squaremo / @michaelfig What if I want to use a private CA and not consider it insecure. How do I get flux to (only) trust my own private CA(s)?

The [above-mentioned idea](https://github.com/weaveworks/flux/issues/1682#issue-402059381) of:

> an approach similar to the flux helm operator's --tiller-tls-ca-cert-path option

seems appealing.
