### ISSUE TITLE
When I am going to install fluxctl, the command "makepkg -si" doesn't working

### ISSUE THREAD

**Issue by FullStack-blockchain** [weaveworks/flux#1698]
When I am going to install fluxctl, the command "makepkg -si" doesn't working

                  makepkg: command not found

Please help me!!!

**Comment by hiddeco** [comment]
`makepkg` is not available on your system, giving me the impression you are following [the guide for Arch Linux](https://github.com/weaveworks/flux/blob/master/site/fluxctl.md#arch-linux) while you are not on Arch.

You should instead install one of the `fluxctl_*` binary releases listed [here](https://github.com/weaveworks/flux/releases).

Given you have `coreutils` and `curl` available on your system and are running some Linux flavor, this should be as easy as:

```
curl -L https://github.com/weaveworks/flux/releases/download/1.9.0/fluxctl_linux_amd64 -o fluxctl
sudo install fluxctl /usr/local/bin
rm fluxctl
```

**Comment by FullStack-blockchain** [comment]
Thanks, it works for me.
