### ISSUE TITLE
Deploy flux into cluster, the status is pendding.

### ISSUE THREAD

**Issue by FullStack-blockchain** [weaveworks/flux#1699]
Every 2.0s: kubectl get pods --all-namespaces         kubernetes-slave: Wed Jan 30 15:51:55 2019

NAMESPACE     NAME                                       READY   STATUS    RESTARTS   AGE
default       flux-7548594d9c-smtxp                      0/1     Pending   0          85m
default       memcached-57f9c8d4c-qq26l            0/1     Pending   0          85m
kube-system   coredns-86c58d9df4-b7pmm        0/1     Pending   0          99m
kube-system   coredns-86c58d9df4-dsw5z          0/1     Pending   0          99m
kube-system   etcd-kubernetes-slave                      1/1     Running   0          98m
kube-system   kube-apiserver-kubernetes-slave            1/1     Running   0          98m
kube-system   kube-controller-manager-kubernetes-slave   1/1     Running   0          99m
kube-system   kube-proxy-9nnsb                           1/1     Running   0          99m
kube-system   kube-scheduler-kubernetes-slave            1/1     Running   0          99m

**Comment by 2opremio** [comment]
@FullStack-blockchain I would advise you to get a stable cluster and, if you have flux-specific problems after that, ask on the #flux channel in the Weave Community Slack team ( get an invite https://slack.weave.works/)

If you need support with Kubernetes in general, Weaveworks can help you, see https://www.weave.works/services/
