### ISSUE TITLE
When running multiple Flux instances in the same namespace fluxctl fails

### ISSUE THREAD

**Issue by stefanprodan** [weaveworks/flux#1700]
fluxctl port forwarder component gets confused when running multiple Flux instances in the same namespace.

```
Error: Ambiguous pod: found more than one pod for selector: labels "app=flux"
``` 

We should add the following workaround to docs:

```
kubectl -n flux logs deployment/flux-1 | grep identity.pub | cut -d '"' -f2
```

**Comment by hiddeco** [comment]
This works when you only want to get the public key but `fluxctl` will still not be able to communicate with the daemon.

Wouldn't it be better to make the label selector(s) configurable?

**Comment by stefanprodan** [comment]
Having an optional flag where you can specify the label would be ideal.

**Comment by squaremo** [comment]
Needs a bit of co-ordination with Justin's port-forwarding lib, but I think this is a fairly easy win.
