### ISSUE TITLE
Avoid requiring explicit --url somehow

### ISSUE THREAD

**Issue by peterbourgon** [weaveworks/flux#171]
> **jml** just did a deploy w/ flux earlier today. I don't know if it's helpful feedback, but I found the command `fluxctl --url=http://localhost:8001/api/v1/proxy/namespaces/fluxy/services/fluxy release --update-image=quay.io/weaveworks/ui-server:master-139c12d --all` much harder to remember than the equivalent `wcloud deploy quay.io/weaveworks/ui-server:master-139c12d` command. Had to consult the docs.

Perhaps we can figure out a way to e.g. autodetect kubectl proxy and suggest an appropriate --url by default?

**Comment by squaremo** [comment]
We no longer need the kube API proxy to operate -- you can use weave cloud or dev; or if testing locally, your own frontend or NodePort or whatever. I think this is much less of an issue, since most of the time it'll be the default.

**Comment by squaremo** [comment]
> I think this is much less of an issue, since most of the time it'll be the default.

Yep. For weave cloud users, the default is correct. For people setting it up standalone, the daemon API is what they want, and the URL will be particular to their cluster.
