### ISSUE TITLE
add image.repository Value for memcached

### ISSUE THREAD

**Issue by jimangel** [weaveworks/flux#1717]
Allow image.repository for memcached much like already done for "quay.io/weaveworks/flux:1.10.0".

This could be included with a PR that addresses: https://github.com/weaveworks/flux/issues/1716 for memcached.

**Comment by stefanprodan** [comment]
Memcached has a repository option: https://github.com/weaveworks/flux/blob/master/chart/flux/templates/memcached.yaml#L26

**Comment by jimangel** [comment]
Ah, perfect! This option would be great to include in: https://github.com/weaveworks/flux/tree/master/chart/flux#configuration
