### ISSUE TITLE
Can flux run in an air-gapped / offline environment?

### ISSUE THREAD

**Issue by jimangel** [weaveworks/flux#1719]
Looking at the logs it appears flux regularly checks out to the internet:
```
checkpoint.go:17 component=checkpoint err="Get https://checkpoint-api.weave.works/v1/check/weave-flux?arch=amd64&flag_cluster-version=kubernetes-v1.10.11&flag_git-configured=true&flag_kernel-version=4.4.0-141-generic&os=linux&signature=<string>&version=1.10.0: dial tcp 172.217.6.19:443: connect: connection refused"
```

I understand that flux _may_ still run without a successful check, but is there a way to disable the check all together?

If you were able to specify an "air-gapped / offline" flag, you could skip the AWS check too:

```
aws.go:69 component=aws warn="no AWS region configured, or detected as cluster region" err="RequestError: send request failed\ncaused by: Get http://169.254.169.254/latest/meta-data/placement/availability-zone: dial tcp 169.254.169.254:80: connect: connection refused"
ts=2019-02-08T16:13:13.598884141Z caller=main.go:288 warning="AWS authorization not used; pre-flight check failed"
```

If this isn't in scope for flux's roadmap, I can close this issue as it's not causing any true problems at the moment. Thanks!

**Comment by squaremo** [comment]
You can stop the checkpointing by including an environment entry for .. what is it, let me see ... `CHECKPOINT_DISABLE=true`.

We could have a flag to suppress other automatic (network-y) checks, like sniffing for AWS auth. This would clear up some log noise (and that would make it more obvious when it's not obeying the flag, incidentally). But I wouldn't put it as a priority, for now.

**Comment by jimangel** [comment]
Thanks @squaremo !

/close

**Comment by kwontae** [comment]
@squaremo hey! So I tried setting the CHECKPOINT_DISABLE=true as both env variable and arg in `flux-patch.yaml` but it causes the pod to go into crashloop... I'm running it with kustomize

**Comment by 2opremio** [comment]
@kwontae can you create an issue for this with more details (e.g. the crash backtrace)

**Comment by stefanprodan** [comment]
There is no such command arg that's why Flux crashes, you only need to set the env var.

**Comment by kwontae** [comment]
@stefanprodan I've added it to 
```
env:
  - name: CHECKPOINT_DISABLE
    value: "true"
```
but it results in Error as well

**Comment by kwontae** [comment]
Got it fixed. I included the env in `flux-patch.yaml`. I didn't realize kustomize overwrites the base layer of `deployment.yaml`
