### ISSUE TITLE
Rogue "helmOperator.namespace" value in chart (a typo?)

### ISSUE THREAD

**Issue by ivanfitenko** [weaveworks/flux#1723]
From readme, it can be concluded that deploying flux chart with '--set helmOperator.allowNamespace=my-namespace' would be sufficient to make flux helm operator to track helmreleases only in 'my-namespace'. However, this does not work this way right now, and '--allow-namespace=' will not be enabled for helm operator deployment. This is because the chart requires an additional option, "helmOperator.namespace" to be set. 
https://github.com/weaveworks/flux/blob/master/chart/flux/templates/helm-operator-deployment.yaml#L107-L109
```
        {{- if .Values.helmOperator.namespace }}
        - --allow-namespace={{ .Values.helmOperator.allowNamespace }}
        {{- end }}
```
This "helmOperator.namespace" value is not used anywhere else, so it seems to me that it is a typo and line 107 should have actually said 
```
        {{- if .Values.helmOperator.allowNamespace }}
```
If this is not a bug, however, then it would be good to have that "namespace" value explained somewhere in readme.

**Comment by stefanprodan** [comment]
It's a bug! Thanks for reporting this

**Comment by stefanprodan** [comment]
@ivanfitenko the fix has been published to our Helm repository as `https://weaveworks.github.io/flux/flux-0.6.2.tgz`

**Comment by ivanfitenko** [comment]
thank you. I deployed the new release and I can confirm that the problem is fixed now.
