### ISSUE TITLE
Check image name before making regrade

### ISSUE THREAD

**Issue by peterbourgon** [weaveworks/flux#173]
> **jml** the first time I ran [a release] I got the image name wrong, which I had to figure out by other means. I was surprised that flux didn't tell me, especially as it takes rather a lot longer to return than wcloud.

We should be able to guard against this somehow, perhaps by proactively reaching out to the relevant image repo and making sure the requested image is available before issuing a regrade?

**Comment by squaremo** [comment]
See also #232.

**Comment by paulbellamy** [comment]
Fixed by: https://github.com/weaveworks/flux/pull/369
