### ISSUE TITLE
Flux without Kubernetes?

### ISSUE THREAD

**Issue by bdaniel7** [weaveworks/flux#1739]
Does Flux work only with Docker containers (Compose, Swarm), without Kubernetes?

**Comment by 2opremio** [comment]
It doesn't (for now at least)

**Comment by ingshtrom** [comment]
Sorry for the necro, but why not keep this open as a feature request?

**Comment by 2opremio** [comment]
We could but it's really far away from what Flux does so I am not sure it makes sense.

**Comment by ingshtrom** [comment]
I see Flux as just a cluster synchronization tool for git -> cluster. Does it matter that the cluster is Kubernetes or Swarm? I'm just playing devil's advocate here. The team I'm on at Docker has written an internal tool to do just this (it also includes secret integration) for Kubernetes and Swarm. Eventually, I would like to get it open sourced, but if it makes more sense to integrate, I'd rather do that probably.

But just to be clear, sounds like secret integration (injecting secrets at runtime) and Swarm support are too far away from what Flux is meant to be?
