### ISSUE TITLE
Rearrange information in docs based on level of importance

### ISSUE THREAD

**Issue by dholbach** [weaveworks/flux#1750]
Feedback from parts of our docs seemed to be that the more interesting bits are either in the middle of a doc or at the bottom, which (even with a ToC) is a bit annoying.

One example was https://github.com/weaveworks/flux/blob/master/site/helm-integration.md#upgrading-images-in-a-helmrelease-using-flux

This issue will be about reviewing our docs and see we can't move relevant/interesting/important parts closer to the top.

**Comment by stefanprodan** [comment]
@dholbach maybe we should consider publishing the docs on a platform that supports sem ver. So we don't run into problems with merging docs in master that refer to an unreleased feature. Here is how cert-manager docs look like https://docs.cert-manager.io/en/latest/index.html you can change the version from the bottom left menu

**Comment by hiddeco** [comment]
> maybe we should consider publishing the docs on a platform that supports sem ver.

Agreed, this would also solve #1268

**Comment by dholbach** [comment]
Thanks Stefan and Hidde for the feedback and research. I'm not against what you're suggesting, but can we maybe move the discussion to a separate issue, or bring it to the next meeting?

This issue was meant to be just about reordering the actual bits of text in the individual articles.
