### ISSUE TITLE
Stale image

### ISSUE THREAD

**Issue by derrickburns** [weaveworks/flux#1758]
It appears that the helm operator continues to look for updates to images after then have been removed from all existing helm releases.

I get:

```ts=2019-02-23T01:49:53.028217228Z caller=warming.go:192 component=warmer canonical_name=index.docker.io/library/seagull auth={map[]} err="requesting tags: errors:\ndenied: requested access to the resource is denied\nunauthorized: authentication required\n"```

However, all references to index.docker.io/library/seagull have been removed from all releases.

**Comment by stefanprodan** [comment]
The image scanning is being performed by Flux, the above are Flux logs not helm-op. Do you still see this error in Flux logs? The cache should be cleared after some time.

**Comment by derrickburns** [comment]
Thanks for the clarification regarding responsibility. 

I will check to see if the cache was cleared.  How long do you expect before the sweep?

**Comment by 2opremio** [comment]
> How long do you expect before the sweep?

It will take [`max(time_to_process_backlog), 1min)`](https://github.com/weaveworks/flux/blob/fe2d2487ce2b5dbe7af8427bc19fe1cfbb456e41/registry/cache/warming.go#L121-L132), were `time_to_process_backlog` is the time it takes to go through all the repositories to sweep.

> However, all references to index.docker.io/library/seagull have been removed from all releases.

Note that flux checks all the [Kubernetes controllers](https://github.com/weaveworks/flux/blob/91ec3fd66782289407bc88ca15885102dc52d9f3/site/fluxctl.md#what-is-a-controller) existing [**in the cluster**](https://github.com/weaveworks/flux/blob/fe2d2487ce2b5dbe7af8427bc19fe1cfbb456e41/cluster/kubernetes/images.go#L103), not in your git repo.

@derrickburns my guess is that you have a controller in the cluster still using `index.docker.io/library/seagull`

@squaremo / @hiddeco why are we using the Cluster resources and not the Git repo manifest as the source of container image registries?

**Comment by stefanprodan** [comment]
@2opremio Flux has a readonly mode for Weave Cloud where we display all workloads running in your cluster.

**Comment by derrickburns** [comment]
Now that I understand flux better, I see that you are correct. There was probably an old helmrelease in the cluster. However, I had changed it in the repo.

Derrick

**Comment by squaremo** [comment]
@derrickburns fluxd doesn't garbage collect resources at present (though see the ever-ripening #1442), so perhaps what's happened is that the resource name changed, and there's an out of date HelmRelease floating around.

Would you be able to check if there's a HelmRelease anywhere that you don't expect to be there? Mainly so we can post a plausible explanation, before tying up this issue.

**Comment by derrickburns** [comment]
There was an old HelmRelease. Thx!

**Comment by squaremo** [comment]
Thanks for confirming that @derrickburns. Closing as we have an explanation and a remedy.
