### ISSUE TITLE
Ordering of installation.

### ISSUE THREAD

**Issue by derrickburns** [weaveworks/flux#1759]
So, it appears that I must install CRD definitions before their use.  This places an ordering constraint on helm installations.  However, I cannot control the order of helm installations in the Helm operator. 

For example, I am trying to use the Bitnami Sealed Secrets Controller.  I need to install it before I provide a SealedSecret CRD.  To do so, I cannot simply create a HelmRelease for the Controller (w/ CRDs).  Instead, I must install the Controller outside of the Operator.

Is this correct?  Is there a way to impose an ordering?

**Comment by stefanprodan** [comment]
The helm-op will retry the installation every 3 minutes. If you have a release with the Sealed Secrets Controller and another one that contains SealedSecrets, the 2nd one will fail at first but at the next run, the CRD is installed and it will succeed.

**Comment by derrickburns** [comment]
Thank you.

**Comment by hlascelles** [comment]
I had the same question. Should this be in the documentation proper? Also, is that 3 minutes configurable? In particular, can it be force retried from `fluxctl` (say a quick fix was known and performed to release a blocking item)?
