### ISSUE TITLE
Breaking change in Helm v2.13

### ISSUE THREAD

**Issue by stefanprodan** [weaveworks/flux#1774]
Helm 2.13 has a breaking change that effects Flux helm-op. We'll have to decide when to drop compatibility with Tiller < 2.13

Form the [release](https://github.com/helm/helm/releases/tag/v2.13.0) notes:
> In this release, we made a backwards-incompatible change to the gRPC API. To avoid backward compatibility breakers, we have been pinned to a very old version of gRPC for some time. Recent versions of gRPC fixed some significant networking fixes with TLS connection handling, but it required us to regenerate a few of the proto files, so some parts of the binary wire format may be broken in backwards-incompatible ways.
> 
> If you are working on a project that relies on the Helm client libraries, please update your dependencies before upgrading to Helm 2.13.

**Comment by bootc** [comment]
For clarity, doesn't this also mean that we can't upgrade to Helm / Tiller 2.13 until Flux's Helm Operator is upgraded to match?

**Comment by stefanprodan** [comment]
Yes

**Comment by stefanprodan** [comment]
@squaremo what's your opinion on this? Should we switch to v2.13 with the helm-op GA release?

**Comment by squaremo** [comment]
What the hey, introducing backward-incompatible changes in a minor version!? Well whatever the versioning mishaps, it's only been out for five days or something. Given that this would be burning the bridges, how much time do we want to give people to upgrade?

**Comment by stefanprodan** [comment]
A couple of weeks, maybe one month tops. I would include the client update in helm-op 1.0.0, otherwise we'll have to do a 2.0.0 release for that...

**Comment by stefanprodan** [comment]
We can prevent people from installing the current helm-op if they've upgraded to 2.13. In our Helm chart we could add this condition: `tillerVersion: "<2.13.0"`

**Comment by rockwe11** [comment]
Hey guys, what's your inclination from above? Are you going to upgrade to 2.13 any time soon?

**Comment by squaremo** [comment]
I have tried

 - the current helm-operator in a cluster running Tiller 2.13 (and TLS)
 - a helm-operator with Helm client package, and Helm binary bumped to 2.13, in a cluster with Tiller 2.9.1 (and TLS)

and both work OK. So I don't think there's an emergency here, though I do agree we ought to make the leap to a recent version of Helm before GA.

**Comment by hiddeco** [comment]
The fix itself has been merged into `master`.

@stefanprodan do you want to keep this open to address https://github.com/weaveworks/flux/issues/1774#issuecomment-469265423, or is this no longer a route you want to take as we have confirmed it is backwards compatible.

**Comment by stefanprodan** [comment]
I'll close it since the breaking change doesn't effects us.
