### ISSUE TITLE
Helm operator should either update deps for chart packages, _or_ skipDepUpdate should move

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#1782]
In https://github.com/weaveworks/flux/pull/1712, a field was introduced into the HelmRelease CRD to instruct the helm operator to skip dependency updates.

Since `helm package` won't complete unless the chart dependencies are present in `charts/`, the helm operator assumes[1] all charts from a Helm repo include their dependencies, and doesn't attempt to update them (anyway that would involve unpacking the chartball).

Either the assumption at [1] is wrong, and the helm operator should be unpacking and updating the dependencies for all charts; or, it's correct, in which case `skipDepUpdate` pertains only to charts from git and should be moved into that section in the CRD.

**Comment by hiddeco** [comment]
As Helm charts [define their own versions](https://github.com/helm/helm/blob/master/docs/charts.md#managing-dependencies-with-requirementsyaml) in their `requirements.yaml`, I would say our assumption is right and we should move it into the git section of the CRD.

I also think it would be wise to make this change before we release the GA.

**Comment by squaremo** [comment]
@stefanprodan Since you approved #1712, can you comment on whether this is a bona fide objection to it?

**Comment by stefanprodan** [comment]
I'm guessing one could package a chart by hand and not include the deps, but I don't think we should bother with this use case. I'm ok with moving the flag in the git section.
