### ISSUE TITLE
flux.weave.works/ignore: true get's redeployed

### ISSUE THREAD

**Issue by timothyjlaurent** [weaveworks/flux#1785]
I have 2 different flux deployments booth using the helm controller that are being redeployed after adding the `flux.weave.works/ignore: true` annotation.

So I'm trying to remove the deployment, I added the annotation and pushed to the repository. 

I then `helm delete --purge`'d the release. However the deployment keeps getting released. 

I then commented out the entire yaml file and pushed it `helm delete --purge` the release, but the deployment still is redeployed --- So it looks like there is no way to _ever_ stop releasing a release. 

looking into some more heavy handed way to get flux to forget these releases using fluxctl -- hopefully something works or I may have to look for a different CD solution.

**Comment by stefanprodan** [comment]
To delete a `HelmRelease` these are the steps:

- add the `flux.weave.works/ignore: "true"` annotation in git
- wait for flux to sync or run `fluxctl sync`
- delete the HelmRelease `kubectl delete hr/app`
- done!
 
The next release of Flux will delete the HelmRelease if you remove it from git, but for now try the above please.

**Comment by timothyjlaurent** [comment]
Ok I followed the above steps and here is what happened:

1. added `flux.weave.works/ignore: true` and pushed 
2. ran `fluxctl sync`
3. deleted the helm releases `helm delete --purge`
4. watched the `watch helm ls` show that the release was gone
5. watched the  `watch kubectl get all --all-namespaces` remove all the k8s objects
6. watched the releases show back up in `helm ls`
7. watched the k8s object  all show back up :(
8. repeated steps 2-7 2 times with the same result

**Comment by timothyjlaurent** [comment]
Thanks for the excellent support -- using `kubectl delete hr/app` was the key to getting this to work -- `helm delete --purge` just wasn't cutting it.
