### ISSUE TITLE
kubeyaml should not be a prerequisite for running the tests

### ISSUE THREAD

**Issue by dimitropoulos** [weaveworks/flux#1790]
currently when running tests, there are errors unless you have [`kubeyaml`](https://github.com/squaremo/kubeyaml) in your path:

```
$ go test github.com/weaveworks/flux/daemon
--- FAIL: TestDaemon_Release (0.21s)
        daemon_test.go:838: applying changes: exec: "kubeyaml": executable file not found in $PATH
--- FAIL: TestDaemon_PolicyUpdate (0.22s)
        daemon_test.go:838: exec: "kubeyaml": executable file not found in $PATH
--- FAIL: TestDaemon_SyncStatus (0.26s)
        daemon_test.go:838: applying changes: exec: "kubeyaml": executable file not found in $PATH
--- FAIL: TestDaemon_JobStatusWithNoCache (0.13s)
        daemon_test.go:838: exec: "kubeyaml": executable file not found in $PATH
--- FAIL: TestDaemon_Automated (10.17s)
        daemon_test.go:821: Waiting for image tag: "2"
--- FAIL: TestDaemon_Automated_semver (10.11s)
        daemon_test.go:821: Waiting for image tag: "3"
event="Sync: 9d04903, default:daemonset/init, default:deployment/helloworld, default:deployment/list-deploy, default:deployment/locked-service, default:deployment/multi-deploy, default:deployment/semver, default:deployment/test-service, default:service/list-service, default:service/multi-service" logupstream=true
event="Sync: cba0b77, default:deployment/helloworld" logupstream=true
FAIL
FAIL    github.com/weaveworks/flux/daemon       23.027s
```

It seems reasonable enough to me that this can/should be automated out.  Seems like we're close to that already anyway.  There's a `/bin` folder in the Flux repo that contains a dockerfile for running `kubeyaml`:
```dockerfile
#!/bin/sh
docker run --rm -i quay.io/squaremo/kubeyaml:0.5.1 "$@"
```

The code in question is in `kubeyaml.go`:

```
func execKubeyaml(in []byte, args []string) ([]byte, error) {
	cmd := exec.Command("kubeyaml", args...)
	...
	err := cmd.Run()
}
```

I don't have a solution off hand, but it seems reasonable that this is something you shouldn't need to install in your PATH before running tests.  I could happily be persuaded otherwise.  If this is intended, then I will update the documentation to list `kubeyaml` being in your path a requirement for the path.

---

For reference, here is what the `Dockerfile.flux` does:
```dockerfile
# Get the kubeyaml binary (files) and put them on the path
COPY --from=quay.io/squaremo/kubeyaml:0.5.1 /usr/lib/kubeyaml /usr/lib/kubeyaml/
ENV PATH=/bin:/usr/bin:/usr/local/bin:/usr/lib/kubeyaml
```

**Comment by dimitropoulos** [comment]
as an aside: there seem to be some refactors (#1120) lined up for `kubeyaml`'s place in the codebase.  Perhaps if there's reason to do anything more than update the developer docs to close this issue, this can be a part of that (larger) refactor.

**Comment by hiddeco** [comment]
If you run the whole testsuite (`make test`) your [path will be adjusted](https://github.com/weaveworks/flux/blob/master/Makefile#L45).

**Comment by squaremo** [comment]
> it seems reasonable that this is something you shouldn't need to install in your PATH before running tests.

`go test` is not especially accommodating in this situation.
