### ISSUE TITLE
Getting error function "nindent" not defined

### ISSUE THREAD

**Issue by hamid2013** [weaveworks/flux#1793]
Hello.

I am getting the below error:

`Error: parse error in "flux/templates/helm-operator-deployment.yaml": template: flux/templates/helm-operator-deployment.yaml:19: function "nindent" not defined`

The changes have been implemented on 14th feb: 9509b1ba272373bb6df06e630cb6265ababf8062

Can you please let me know what i need to do to make it work.

**Comment by cPu1** [comment]
What version of Helm is your cluster running? 
`nindent` is part of the Sprig library that Helm uses. From the changelog for Helm, `nindent` was made available in Helm `v2.7.0`, so your cluster must be running Helm `v2.7.0` or above in order for the Flux Helm chart to work.

To upgrade Helm, you'll need to use a newer version of Helm client and run `helm init --upgrade` to upgrade tiller (server-side component) in the cluster.

**Comment by 2opremio** [comment]
@hamid2013 was this resolved? Please reopen if not.
