### ISSUE TITLE
Blue/Green Deployments

### ISSUE THREAD

**Issue by syst0m** [weaveworks/flux#1802]
Is it possible to perform blue/green deployments with flux?
I was unable to find anything related in the documentation.
Do you need a service mesh, like Istio, to perform canary and blue/green with flux?
If I udnerstood correctly, currently you can only do k8s native recreate & rolling update deployments with flux?

**Comment by squaremo** [comment]
> Do you need a service mesh, like Istio, to perform canary and blue/green with flux?

It's possible to do these without using a service mesh, but not very satisfactory. I would have a look at [flagger](https://https://github.com/stefanprodan/flagger), which will orchestrate blue/green deployments and so on for you, and is designed to work with Flux.

> If I udnerstood correctly, currently you can only do k8s native recreate & rolling update deployments with flux?

In the sense that it only supports what your Kubernetes cluster supports, yes. But you can apply CRDs with Flux, and that gives you access to more sophisticated tooling (like flagger!)

**Comment by syst0m** [comment]
Ok, thanks for your feedback.
