### ISSUE TITLE
error: `:` used in label value is invalid

### ISSUE THREAD

**Issue by dimitropoulos** [weaveworks/flux#1805]
the commit just merged on master implements code that ends up putting a `:` in a kubernetes resource label.  this is invalid.

https://github.com/weaveworks/flux/commit/c9cda8abf093e276d9871368a861bcc12982f52b#diff-01a1bc681d547c2ba8d68501f424b99fR301

Here is an example of the error that happens when such a change is applied:
```
ts=2019-03-07T20:30:29.602546729Z caller=loop.go:208 component=sync-loop err="default:configmap/test: running kubectl: The ConfigMap \"test\" is invalid: metadata.labels: Invalid value: \"sha256:HIiQYQL2GNvdKPnbeUNdHpGfL0qMNdB0m1QBZtKVcps\": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')"
```

note:
> a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')

**Comment by 2opremio** [comment]
Fixed by #1806
