### ISSUE TITLE
Helm Chart: Allow use of alternative values file from remote chart

### ISSUE THREAD

**Issue by jrryjcksn** [weaveworks/flux#1809]
Some helm charts include multiple value file options (example: https://github.com/istio/istio/tree/master/install/kubernetes/helm/istio). It would be valuable to be able to select a specific values file to use rather than the default. If a user were to download the preferred file and add it to a secret, it could become stale.

**Comment by squaremo** [comment]
I don't think I understand what's going on with all those values files. How would you use them if you were just using the Helm command line tool?

**Comment by jrryjcksn** [comment]
Here's how I selected the `values-production.yaml` file for redis:

`helm install stable/redis --values https://raw.githubusercontent.com/helm/charts/master/stable/redis/values-production.yaml`

**Comment by kewlvishnu** [comment]
@squaremo another example:  ```helm install istio --name istio --values install/kubernetes/helm/istio/values-istio-demo.yaml --namespace istio-system```

**Comment by squaremo** [comment]
I'm all for making the Helm-operator more widely useful. I would ask this though: are you sure you want your deployed chart to depend on a resource that can change arbitrarily?

**Comment by jrryjcksn** [comment]
That's a fair question. The motivation here, though, is to use a "standard" package without having to worry about getting out-of-date if you pull your own copy in order to apply a different values file... I think there can be valid reasons to go either way.

**Comment by gigi-at-zymergen** [comment]
It would be even better if helm allowed packaging multiple values files in the packaged and versioned chart, and then you could install the chart and specify -f values-production.yaml and it would look for a values file named that packaged with the chart. This gives an easy way for the creators of charts to provide several different default configurations.
