### ISSUE TITLE
Allow not having to set values for Helm release

### ISSUE THREAD

**Issue by jpds** [weaveworks/flux#1812]
I sometimes just want to deploy a helm release without having to set any values outside of the defaults, however flux doesn't allow me to do this.

**Comment by squaremo** [comment]
As in, it requires a `values:` section in the HelmRelease manifest?

**Comment by jpds** [comment]
@squaremo  Yes.

**Comment by stefanprodan** [comment]
A workaround is to use `values: {}`

**Comment by squaremo** [comment]
I suppose we should alter the OpenAPI schema so `values` isn't required (and make sure the code doesn't balk if it's absent).
