### ISSUE TITLE
helm operator ignores deletion of helmRelease manifest

### ISSUE THREAD

**Issue by derrickburns** [weaveworks/flux#1853]
```
default/flux-helm-operator-64474d8dc9-pd4t4[flux-helm-operator]: ts=2019-03-21T19:28:33.437589762Z caller=release.go:186 component=release error="Chart release failed: qa1-tidepool: &status.statusError{Code:2, Message:\"customresourcedefinitions.apiextensions.k8s.io \\\"gateways.gateway.solo.io\\\" already exists\", Details:[]*any.Any(nil)}"
```

This is AFTER I deleted the HelmRelease  manifest using `kubectl` that referred to the CRDs.

**Comment by hiddeco** [comment]
Custom Resource Definitions installed using Helm with the `"helm.sh/hook": crd-install` annotation [are unmanaged](https://github.com/helm/helm/issues/4489#issuecomment-414135147) and will thus not be uninstalled by Helm (or the operator) during clean-up operations.

A workaround to prevent errors like you are seeing is to install the CRD and chart apart from each other. You do this by putting the CRD in plain git resource and disabling the installation of the CRD by the chart in your `HelmRelease`.

**Comment by hiddeco** [comment]
Closing this is not directly related to the Helm operator and an explanation (and workaround) have been provided.
