### ISSUE TITLE
Outdated fluxctl Homebrew formula - 1.8.2

### ISSUE THREAD

**Issue by dvelitchkov** [weaveworks/flux#1861]
The latest "stable" version of `fluxctl` deployed by Homewbrew` is 1.8.2 
It's still talking about "controllers" when the new nomenclature seems to be "workloads". 

Is there a reason it's @ 1.8.2 still? Do you guys maintain that at all or is it best-effort by the community-at-large?

**Comment by 2opremio** [comment]
> Do you guys maintain that at all or is it best-effort by the community-at-large?

It's a community effort

**Comment by 2opremio** [comment]
@dvelitchkov I am going to close this ticket if that's ok. The capacity of the flux maintainers  is limited and (even if w it would be great!) we cannot support every package manager.

However, we are happy to support you if you want to bump the formula and have some questions.
