### ISSUE TITLE
Flux with telepresence

### ISSUE THREAD

**Issue by alexanderbuhler** [weaveworks/flux#1874]
Hey guys, I started experimenting with telepresence recently. This "issue" is about the deployment swapping feature in particular.

When I instruct telepresence to proxy a locally running container to my cluster, it spins down the replicas of the initial deployment temporarily from n to 0 and creates another deployment with one instance of my proxied container. Everything works as intended so far. 

Just until flux runs another sync cycle, applying all configuration and restoring the n instances which were scaled down to 0 for telepresence development. Now the proxied local container competes/gets loadbalanced against the remote instances and makes actual development near impossible.

I don't have a clear solution in mind, but is there a way to tell flux to pause syncing for a while and therefore not touch the replica settings of a spun down deployment?

**Comment by squaremo** [comment]
You can annotate a resource with `flux.weave.works/ignore: "true"` and fluxd will not attempt to sync it. Either in the file, or in the cluster object.

**Comment by alexanderbuhler** [comment]
Thank you. Works. 👍
Didn't think it would work with just annotating the cluster object and not the file.

At least we have a solution for anybody coming across this issue in the future 😁
