### ISSUE TITLE
When we can use valuesfrom in HelmRelease

### ISSUE THREAD

**Issue by pmquang** [weaveworks/flux#1878]
I saw the new property of CRD HelmRelease support values from external source. But I can't use this feature.

HelmOperator : 0.7.1
Flux: 1.11.0

**Comment by hiddeco** [comment]
Resolved over Slack.

`HelmRelease` contained

```
valuesFrom:
- externalSourceRef:
  url: https://bitbucket.org/xxx/flux/raw/master/xxx/values.yaml
```

instead of 

```
valuesFrom:
- externalSourceRef:
    url: https://bitbucket.org/xxx/flux/raw/master/xxx/values.yaml
```
