### ISSUE TITLE
Can't apply cert-manager yaml

### ISSUE THREAD

**Issue by stillinbeta** [weaveworks/flux#1881]
I'm trying to set up cert-manager in my cluster. I'm not using helm, so I simply added [cert-manager.yaml](https://github.com/jetstack/cert-manager/blob/v0.7.0/deploy/manifests/cert-manager.yaml) to a directory. However, when I sync, I get an error message: 

`ts=2019-03-31T23:58:29.167727793Z caller=images.go:23 component=sync-loop error="getting unlocked automated resources: error looking up API resources for Issuer.certmanager.k8s.io/v1alpha1: not found"`

Applying the file with `kubectl -f` works as expected. 

```console
$ fluxctl list-controllers
CONTROLLER                    CONTAINER  IMAGE                           RELEASE  POLICY
default:deployment/flux       flux       quay.io/weaveworks/flux:1.11.0  ready    
default:deployment/memcached  memcached  memcached:1.4.25                ready    
$ fluxctl version
1.11.0
```

**Comment by hiddeco** [comment]
Sorry about that, the issue you are experiencing is tracked in #1825. I have two workarounds for you until it has been resolved (which hopefully will be soon, it is being worked on).

1. Simply downgrade Flux to `1.10.1`, the bug does not exist in this version.
2. Put the CRD and the manifests using the CRD in two separate commits. After Flux has applied the CRD the API lookup will succeed.

**Comment by hiddeco** [comment]
[Flux `1.11.1`](https://github.com/weaveworks/flux/releases/tag/1.11.1) was released yesterday with a patch for this issue. :sun_with_face:
