### ISSUE TITLE
Fluxd does not use configured branch for write check

### ISSUE THREAD

**Issue by hiddeco** [weaveworks/flux#1885]
When fluxd performs a checkout for a new repository it does a [write check](https://github.com/weaveworks/flux/blob/bd7a91e25f99dedaa70420ed4131ff394c066738/git/operations.go#L81) at a [certain step](https://github.com/weaveworks/flux/blob/267e0115d1a2a74956c94d37e844ffa531ce9f9c/git/repo.go#L266). This write check creates, pushes and removes a tag pointed at the default branch and not the one configured by the user with `--git-branch`.

I think it would be better if we would perform the write check against the configured branch. As we now (temporary) touch something we are not explicitly told to look at and it also has a chance of (unrelated) failure, for example, when the default branch contains no commits and Flux will be unable to get a `HEAD` revision (`caller=loop.go:90 component=sync-loop err="git repo not ready: tag for write check: fatal: Failed to resolve 'HEAD' as a valid ref."`).

**Comment by squaremo** [comment]
Makes sense to me.
