### ISSUE TITLE
Release can no longer release workload

### ISSUE THREAD

**Issue by stillinbeta** [weaveworks/flux#1891]
it looks like `fluxctl release` doesn't work for workloads anymore:

```console
$ fluxctl version
1.11.0
$ fluxctl release --workload=default:deployment/streaming --update-image=tootsuite/mastodon:v2.5.1
Error: unknown flag: --workload
Run 'fluxctl release --help' for usage.
```

If this is intentional, the [fluxctl page](https://github.com/weaveworks/flux/blob/master/site/fluxctl.md#releasing-a-workload) should probably be updated.

**Comment by hiddeco** [comment]
Please take a look at the [documentation for the latest release](https://github.com/weaveworks/flux/blob/1.11.1/site/fluxctl.md#releasing-a-controller) (it should be `--controller`).

The docs in `master` are ahead of the `fluxctl` version you are using (controller was recently renamed to workload but has not made it into a release yet).

**Comment by stillinbeta** [comment]
ahh, okay! thanks for the quick response and sorry for ot reading more closely!

**Comment by hiddeco** [comment]
No worries, this is a common mistake and we are working on creating a better doc experience.

**Comment by stillinbeta** [comment]
(and A+ on the name change, I was having trouble with `controller` because I thought it referred to the fluxd itself but workload clicked immediately!)

**Comment by 4c74356b41** [comment]
what kind of clown fiesta is this:
```
Flag --controller has been deprecated, changed to --workload, use that instead
```

why are you doing this?

**Comment by hiddeco** [comment]
> what kind of clown fiesta is this

A very neat deprecation notice with no further impact, as it is backwards compatible and will only shout at you.

> why are you doing this?

Because not all workloads you can automate with `fluxctl` are controller workloads, a `HelmRelease` for example isn't.

**Comment by 4c74356b41** [comment]
ugh. in what world does this make sense? it was `--workload`, you change it to `--controller` and then you change it back. You competing with Microsoft in renaming game?

**Comment by squaremo** [comment]
@4c74356b41 It was not `--workload` before it was `--controller`. So it hasn't been changed back.

**Comment by hiddeco** [comment]
> it was `--workload`, you change it to `--controller` and then you change it back. You competing with Microsoft in renaming game?

_A long time ago_, probably before you were even using the project, [the flag was `--service`](https://github.com/weaveworks/flux/blob/97e29f4541cd9c6433a6505088046fe57de8950f/cmd/fluxctl/release_cmd.go#L33). Then, _somewhere in 2017_, probably also before you were using the project, [it got changed to `--controller`](https://github.com/weaveworks/flux/commit/c7517ed0c7efad893ec107514be57115146791e8#diff-9e26089ce022703f43080e3cf4296be6). And finally, _a couple of months ago_, [it got changed to `--workload`](https://github.com/weaveworks/flux/commit/76c813b543b639e9ef271b76e3ebc8841a13f98a#diff-9e26089ce022703f43080e3cf4296be6). 

---

In addition, I would advice you to read our [Code of Conduct](https://github.com/weaveworks/flux/blob/master/CODE_OF_CONDUCT.md), which states

> Examples of unacceptable behavior by participants include:
> - ...
> - Trolling or insulting/derogatory comments

As I do not think that any further discussion will be fruitful, I am locking this conversation.
