### ISSUE TITLE
Garbage collection setting in the Helm chart

### ISSUE THREAD

**Issue by alexanderbuhler** [weaveworks/flux#1894]
Hey guys, could we get the garbage collection arg inside the helm chart? We'd like to use the Helm release of flux but want to try out the garbage collection. From the chart template I'm currently seeing no way of passing it to fluxd.

Thanks!

**Comment by stevenpall** [comment]
You can actually enable in the current chart like so:
```
additionalArgs:
  - --sync-garbage-collection
```

**Comment by alexanderbuhler** [comment]
Yep, was mistakenly looking at the helm template before and didn't see args there.

For anybody using just the cli it's:
```sh
helm upgrade -i flux --namespace=flux --reuse-values --set additionalArgs={--sync-garbage-collection} weaveworks/flux
```
