### ISSUE TITLE
error looking up API resources for HelmRelease.flux.weave.works/v1beta1

### ISSUE THREAD

**Issue by mulcahys** [weaveworks/flux#1898]
Now that #1896 is resolved I'm hitting another error after a sync of the flux-get-started.git repo from my private host (I had to follow https://github.com/weaveworks/flux/blob/master/site/standalone-setup.md#using-a-private-git-host to get that working but I think the clone is working ok).

I'm seeing the following error just after the close and no sign of the demo namespace or deployment/podinfo

```
ts=2019-04-03T16:54:50.865047078Z caller=loop.go:103 component=sync-loop event=refreshed url=git@github.example.com:xxx-xxx/flux-get-started.git branch=master HEAD=b87b0319407f3f05cdd44a9058599d183f011e20
ts=2019-04-03T16:54:50.938893382Z caller=loop.go:90 component=sync-loop err="loading resources from repo: error looking up API resources for HelmRelease.flux.weave.works/v1beta1: not found"
ts=2019-04-03T16:55:45.37419714Z caller=images.go:17 component=sync-loop msg="polling images"

```

**Comment by mulcahys** [comment]
I'm following https://github.com/weaveworks/flux/blob/master/site/get-started.md#get-started-with-flux without using Helm (is Helm actually required?)

**Comment by 2opremio** [comment]
I think that the problem is that the example repo contains a HelmRelease CRD which wasn't created as per the instructions.

Try doing:

```
kubectl apply -f deploy-helm
```

**Comment by mulcahys** [comment]
Thanks @2opremio , that seems to have fixed that error (although it does give an error on running)

```
$ kubectl apply -f deploy-helm
customresourcedefinition.apiextensions.k8s.io/helmreleases.flux.weave.works created
deployment.apps/flux-helm-operator created
Error from server (NotFound): error when creating "deploy-helm/weave-cloud-helm-operator-deployment.yaml": namespaces "weave" not found
```
It's not clear from https://github.com/weaveworks/flux/blob/master/site/get-started.md#get-started-with-flux that this also needs to be ran - did I miss a step?

**Comment by 2opremio** [comment]
It's probably just a problem with the guide.

**Comment by hiddeco** [comment]
The `deploy-helm/weave-cloud-helm-operator-deployment.yaml` was included in the `deploy-helm/` folder for [Weave Cloud](https://www.weave.works/product/cloud/) users. You can ignore the error (and the manifest) as an OSS user.

**Comment by mulcahys** [comment]
Thanks for the assistance @2opremio and @hiddeco
