### ISSUE TITLE
Weave cloud deploy page error with '---' at EOF

### ISSUE THREAD

**Issue by dwightbiddle-ef** [weaveworks/flux#1925]
It appears that when flux syncs a yaml that has a '---' at the end of the file, the application works correctly, and the yaml is applied, but afterwards the Weave Cloud interface for deployments has the following error: 
```parsing YAML doc from "{pathToYaml}": yaml: did not find expected node content'```

When I remove the '---' at the end of the file, this error goes away.

The only effect this has is that it prevents me from doing manual deployments, and we could add validation for this, BUT this seems like a Weave specific problem that should be resolved, since it is valid kubernetes syntax.

**Comment by 2opremio** [comment]
Yep, it seems that both `---` and `...` should be valid at the end of the document.

Out of curiosity, do you _need_ the `---` at the end of the file?

**Comment by dwightbiddle-ef** [comment]
No of course not and I have taken it out of the affected yaml, but it was quite time consuming to figure out that was the problem and I want to make sure others don’t go through the same. Also, I want to make sure these are things we can resolve relatively quickly in order to feel comfortable with Weave as a long term CD tool.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by 2opremio** [comment]
Yeah, we should obviously support it since it's valid Yaml. I just wanted to understand whether there was a specific need for it.

**Comment by aronne** [comment]
This has been a problem for our team as well. We have a repository that contains yaml definitions for tens of services and if even **one** of them has a trailing triple-dash (which is quite common if you are doing helm template XXX > output.yaml), flux chokes and stops automation of **all** workloads in the cluster.

Here's an example from the end of the file of one of our manifests that helm template generated which  triggers this error:

```
---
# Source: sample-webapp/templates/configmap.yaml


<EOF>
```

**Comment by 2opremio** [comment]
Can you provide full file causing the problem? (please redact whatever you see fit).

I made a fix but it seems that the test I created is bogus and I cannot reproduce the problem.

**Comment by 2opremio** [comment]
@aronne are you also using Weave Cloud?

**Comment by aronne** [comment]
@2opremio Here's a redacted sample yaml file:

[sample.yaml](https://gist.githubusercontent.com/aronne/364e7370857cf91a4f3d8942264b33a5/raw/96648cf9930a3afef029c4d9902307c9be422ad2/sample-flux-parse-problem.yaml)

We're using v1.12.0 of flux which is installed using the Helm Chart. We're not using Weave Cloud.

**Comment by 2opremio** [comment]
Thanks a lot. A simple parsing unit test for that file passes. 

It must be something more intricate. I will take a deeper look.

**Comment by 2opremio** [comment]
I have found the problem, it happens when flux edits the file to automatically release a newer image. The cause is a combination of:

1. [Kubeyaml](https://github.com/squaremo/kubeyaml) (which is what we use for updating the manifests) incorrectly adding `...` (Yaml's end-of-document marker) after every `---` without a document. Kubeyaml, should respect the original structure.
2. Flux choking on `...` when trying to re-parse the file.

I'll fix it in kubeyaml and add a few tests so that it doesn't happen again.

**Comment by dwightbiddle-ef** [comment]
Excellent! Thanks for jumping on this. What is normally the turnaround for release once you have a fix ready to go? And how would we go about patching through weave cloud... rerun the yaml generated in the “update cluster” section of the configuration page? Or does flux self-update?

Keep us posted,

- D

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by 2opremio** [comment]
> Excellent! Thanks for jumping on this. 

No problem

> What is normally the turnaround for release once you have a fix ready to go? 

It's ad-hoc check the details in CHANGELOG.md for specific historical details 

Are you blocked by this?



> And how would we go about patching through weave cloud... rerun the yaml generated in the “update cluster” section of the configuration page? Or does flux self-update?

It depends on how you installed flux. To the best of my knowledge, If you followed the instructions from Weave Cloud, an agent is installed which will automatically upgrade flux.

Flux itself doesn't self-update.

**Comment by dwightbiddle-ef** [comment]
Hi Alfonso,

We are not blocked, I am just more curious since we are new customers. And now that you mention the weave cloud auto-update, I remember that we do have that spun up.

Thanks for your responsiveness, and I look forward to hearing back when this is resolved so that we can confirm that the auto-update gets the change and this is no longer a problem for us.

Best,

- D

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by dwightbiddle-ef** [comment]
Confirmed this works in our environment, thanks for addressing this so promptly!
