### ISSUE TITLE
Ignore certain releases  in same git repo and branch when releasing in multiple clusters

### ISSUE THREAD

**Issue by koustubhg** [weaveworks/flux#1926]
I have 3 environments viz. `dev`, `stg` and `prd`. I want `dev` and `stg` to be running in the same cluster, however I want `prd` to be running in a different cluster.
I understand that this can be done by using one git branch for `dev` and `stg` and another git branch for `prd`. However, this would mean duplication of the `charts` code.

Is there a way I can ignore `prd` deployment in the `dev and staging` cluster and ignore `dev and staging` deployment in the `prd` cluster. I want to use just one `git` repo and branch for storing all the configuration related to all three environments.

I came across this https://github.com/weaveworks/flux/blob/master/site/faq.md#can-i-temporarily-make-flux-ignore-a-deployment, however is it possible to make this `ignore` conditional based on what cluster it is?

**Comment by lalisakkkk** [comment]
Do you think about how you are good good good good good

**Comment by hiddeco** [comment]
What about putting your charts in a seperate branch and using `ref: <chart branch>` in your `HelmRelease`?

**Comment by koustubhg** [comment]
@hiddeco 
ok, but that would mean I will need to have at least 3 branches right? one for storing `charts`, one for `dev/stg` and one for `prd`. Is there a way to keep it down to just one branch?

**Comment by hiddeco** [comment]
Flux supports a `--git-path`, you could create a folder structure like this

```
monolith
├── charts
│   └── foo
└── config
    ├── dev
    ├── prod
    └── stg
```

and set the `--git-path=<env folder>`.

**Comment by koustubh25** [comment]
@hiddeco 
Thanks, I came across this yesterday https://github.com/weaveworks/flux/blob/master/site/faq.md#i-have-a-dedicated-kubernetes-cluster-per-environment-and-i-want-to-use-the-same-git-repo-for-all-how-can-i-do-that
You can close this issue.

**Comment by hiddeco** [comment]
@koustubh25 great! In the future you may get a faster reply on questions like this in the [Weave Slack](https://slack.weave.works) `#flux` channel.
