### ISSUE TITLE
Registry cache warmer stops logging

### ISSUE THREAD

**Issue by brantb** [weaveworks/flux#1940]
We observed a scenario where the registry cache warmer stopped functioning and Flux would no longer automatically detect or apply updated tags.

We seem to be hitting Azure Container Registry's rate limit fairly hard, with a lot of rate limit errors being logged. However, at some point, the warmer component stopped logging entirely.

The relevant part of the log output is below:

```ts=2019-04-15T11:36:20.997722779Z caller=images.go:17 component=sync-loop msg="polling images" 
ts=2019-04-15T11:36:24.486593909Z caller=warming.go:268 component=warmer info="refreshing image" image=foobar.azurecr.io/image tag_count=516 to_update=152 of_which_refresh=152 of_which_missing=0 
ts=2019-04-15T11:36:25.113396872Z caller=warming.go:309 component=warmer canonical_name=foobar.azurecr.io/image auth= { map[] } warn="aborting image tag fetching due to rate limiting, will try again later" 
ts=2019-04-15T11:36:35.105444106Z caller=warming.go:313 component=warmer canonical_name=foobar.azurecr.io/image auth= { map[] } err="toomanyrequests: too many requests" ref=foobar.azurecr.io/image:tag 
[~50 similar lines snipped]
ts=2019-04-15T11:36:35.201179999Z caller=warming.go:364 component=warmer updated=foobar.azurecr.io/image successful=55 attempted=152 
ts=2019-04-15T11:36:35.867880443Z caller=warming.go:268 component=warmer info="refreshing image" image=foobar.azurecr.io/image tag_count=545 to_update=208 of_which_refresh=208 of_which_missing=0 
ts=2019-04-15T11:36:36.487968292Z caller=warming.go:309 component=warmer canonical_name=foobar.azurecr.io/image auth= { map[] } warn="aborting image tag fetching due to rate limiting, will try again later" 
[~30 similar lines snipped]
ts=2019-04-15T11:41:22.120128959Z caller=images.go:17 component=sync-loop msg="polling images" 
ts=2019-04-15T11:46:23.291988006Z caller=images.go:17 component=sync-loop msg="polling images" 
ts=2019-04-15T11:51:24.495635836Z caller=images.go:17 component=sync-loop msg="polling images" 
[Previous line repeated every --registry-poll-interval (5m) until flux was manually restarted]
ts=2019-04-15T16:38:32.956210183Z caller=loop.go:90 component=sync-loop err="git repo not ready: git repo has not been cloned yet" 
ts=2019-04-15T16:38:35.026483907Z caller=warming.go:268 component=warmer info="refreshing image" image=foobar.azurecr.io/image tag_count=41 to_update=41 of_which_refresh=0 of_which_missing=41 
ts=2019-04-15T16:38:45.376898488Z caller=warming.go:313 component=warmer canonical_name=foobar.azurecr.io/image auth= { map[] } err="toomanyrequests: too many requests" ref=foobar.azurecr.io/image:tag 
[... more rate limit spam ...]
```

A [discussion in #flux](https://weave-community.slack.com/archives/C4U5ATZ9S/p1555349267170900) revealed that the memcached cache is full due to the large number of tags being scanned, which might be contributing to the issue. (Possibly related: #1939)

**Comment by hiddeco** [comment]
I have a _theory_ that ACR might (automatically) null route you after repeatedly hitting their `HTTP 429` rate limit wall. If this is indeed the case, my suspicion is that a timeout occurs on the connection Flux attempts to make, in which case it falls into a black hole of not logging anything.

https://github.com/weaveworks/flux/blob/4feee5f4671a91151ddc0089c4c95769bd652426/registry/cache/warming.go#L301-L304

You restarting the pod probably meant Flux received a new outbound IP address with no null route attached to it.

**Comment by 2opremio** [comment]
> at some point, the warmer component stopped logging entirely

Nothing, not even "refreshing image" logs?

If that's the case I doubt it's the lack of timeout logs, because we only omit the "refreshing image" logs when we don't find images to update.

My hunch is that, somehow, `imagesToFetchFunc func() registry.ImageCreds` ends up silently returning an empty map.

**Comment by 2opremio** [comment]
> My hunch is that, somehow, `imagesToFetchFunc func() registry.ImageCreds` ends up silently returning an empty map.

Upon further reading, this seems highly unlikely

**Comment by 2opremio** [comment]
Maybe related? https://github.com/weaveworks/flux/issues/1808

**Comment by 2opremio** [comment]
@brantb have you seen this again recently?

**Comment by 2opremio** [comment]
I've just seen that the container image repository client we use:

1. Completely ignores the contexts being passed. For instance, [for the tag request](https://github.com/docker/distribution/blob/6d62eb1d4a3515399431b713fde3ce5a9b40e8d5/registry/client/repository.go#L187-L251), the parameters are not used at all.
2. It [sets an implicit timeout of zero in the client it uses](https://github.com/docker/distribution/blob/6d62eb1d4a3515399431b713fde3ce5a9b40e8d5/registry/client/repository.go#L140-L144)

So, I think that as soon as a request hangs, the warmer will get stuck. I believe that's what's happening both here and #1808 . I bet it only happens with ACR because other registry providers don't leave the connection open. It very well be a combination with rate limiting.

There are no new library updates (`master`still has this problem).

**Comment by 2opremio** [comment]
Not that we do anything with the context [other than set it to `Background()`](https://github.com/weaveworks/flux/blob/fefb216c1d2c415aa3adf00265c0a6ad0fecf7f5/registry/cache/warming.go#L86-L89)

**Comment by alexanderbuhler** [comment]
@2opremio I maybe have a similar issue but not due to rate limiting. At least I can't see anything related to that in the logs.

At some point warmer just disappears from logs. After that new images aren't refreshed/pulled.
Restarting the flux pod helps with this problem, until warmer will go dark at some point again.

Last lines of logs before warmer went dark. It was in the middle of the night...
```

  | Time | log
-- | -- | --
  | April 19th 2019, 01:02:16.660 | ts=2019-04-18T23:02:16.651435655Z caller=warming.go:192 component=warmer canonical_name=quay.io/weaveworks/helm-operator auth={map[]} err="requesting tags: Get https://quay.io/v2/weaveworks/helm-operator/tags/list: unknown: Namespace weaveworks has been disabled. Please contact a system administrator."

  | April 19th 2019, 01:01:46.172 | ts=2019-04-18T23:01:46.171809346Z caller=warming.go:364 component=warmer updated=quay.io/calico/node successful=1 attempted=1

  | April 19th 2019, 01:01:45.664 | ts=2019-04-18T23:01:45.663611449Z caller=warming.go:268 component=warmer info="refreshing image" image=quay.io/calico/node tag_count=2214 to_update=1 of_which_refresh=0 of_which_missing=1

  | April 19th 2019, 01:01:10.287 | ts=2019-04-18T23:01:10.286713882Z caller=warming.go:192 component=warmer canonical_name=quay.io/weaveworks/helm-operator auth={map[]} err="requesting tags: Get https://quay.io/v2/weaveworks/helm-operator/tags/list: unknown: Namespace weaveworks has been disabled. Please contact a system administrator."

  | April 19th 2019, 01:00:24.521 | ts=2019-04-18T23:00:24.518359858Z caller=warming.go:364 component=warmer updated=quay.io/calico/node successful=3 attempted=3

  | April 19th 2019, 01:00:24.010 | ts=2019-04-18T23:00:24.009899617Z caller=warming.go:268 component=warmer info="refreshing image" image=quay.io/calico/node tag_count=2213 to_update=3 of_which_refresh=0 of_which_missing=3

  | April 19th 2019, 00:59:30.520 | ts=2019-04-18T22:59:30.520191814Z caller=warming.go:192 component=warmer canonical_name=quay.io/weaveworks/helm-operator auth={map[]} err="requesting tags: Get https://quay.io/v2/weaveworks/helm-operator/tags/list: unknown: Namespace weaveworks has been disabled. Please contact a system administrator."

  | April 19th 2019, 00:59:14.927 | ts=2019-04-18T22:59:14.925749284Z caller=warming.go:192 component=warmer canonical_name=quay.io/weaveworks/helm-operator auth={map[]} err="requesting tags: Get https://quay.io/v2/weaveworks/helm-operator/tags/list: unknown: Namespace weaveworks has been disabled. Please contact a system administrator."

  | April 19th 2019, 00:57:01.282 | ts=2019-04-18T22:57:01.28240941Z caller=warming.go:192 component=warmer canonical_name=quay.io/weaveworks/helm-operator auth={map[]} err="requesting tags: Get https://quay.io/v2/weaveworks/helm-operator/tags/list: unknown: Namespace weaveworks has been disabled. Please contact a system administrator."


```

**Comment by alexanderbuhler** [comment]
Another update.
Yesterday he stopped logging after refreshing an image with rather many tags:

```
ts=2019-04-23T08:22:38.023090068Z caller=warming.go:268 component=warmer info="refreshing image" image=datawire/telepresence-k8s tag_count=575 to_update=575 of_which_refresh=0 of_which_missing=575
```

**Comment by 2opremio** [comment]
I think I may have fixed the problem in #1970 

@alexanderbuhler / @brantb Would you be able to confirm by running `docker.io/2opremio/flux:set-warmer-timeouts-496b1c91` ?

**Comment by alexanderbuhler** [comment]
@2opremio great work, thanks. I applied your image and will check back after some monitoring.

**Comment by 2opremio** [comment]
Perfect, thanks a lot!

**Comment by 2opremio** [comment]
Reopening until we get confirmation of #1970 fixing the problem

**Comment by alexanderbuhler** [comment]
@2opremio I already saw a new Flux release containing this fix but I'm confirming the warmer still works with our setup after >24h hours. Think we can close this. Thanks again!

**Comment by 2opremio** [comment]
GreatI! Just to be sure, it always took less than 24 hours for the problem to happen?

**Comment by alexanderbuhler** [comment]
@2opremio Not always, but mostly under 24 hours. Now after almost two days warmer's still working.

**Comment by 2opremio** [comment]
Great, closing. Let me know if it happens again.
