### ISSUE TITLE
Cope when syncing a helm-provided CRD and resources using the CRD

### ISSUE THREAD

**Issue by brantb** [weaveworks/flux#1941]
#1825 describes an issue where a commit cannot be synced if it contains both a CRD and a resource that uses that CRD. A fix was implemented in #1876 to look in the git repo for the manifest, however, this does not work if the CRD is installed via helm.

To reproduce:

* Have a git repository containing a `HelmRelease` for [rbac-manager](https://github.com/reactiveops/rbac-manager) and an `RBACDefinition` manifest
* Create a new Kubernetes cluster
* Install flux (v1.12.0) and flux-helm-operator

Expected result:

Flux applies the `HelmRelease`, which creates the `RBACDefinition` CRD, which allows Flux to apply the `RBACDefinition` manifest. In flux <= 1.10.1 this would take multiple sync passes, but the cluster would eventually reach the desired state.

Actual result:

After cloning the git repo, flux writes the following message to the log, and does not sync anything:

`s=2019-04-15T19:43:02.307951117Z caller=images.go:24 component=sync-loop error="getting unlocked automated resources: error looking up API resources for RBACDefinition.rbacmanager.reactiveops.io/v1beta1: not found"`

Since the CRD is [part of the rbac-manager helm chart](https://github.com/reactiveops/charts/blob/master/stable/rbac-manager/templates/customresourcedefinition.yaml) the code path added in #1876 doesn't seem to find it.

**Comment by 2opremio** [comment]
This one's tricky and calls for implementing the approach suggested by @squaremo in https://github.com/weaveworks/flux/issues/1825#issue-420940279

**Comment by 2opremio** [comment]
BTW, the workaround here is to first add the HelmRelease, wait for it to sync and then add the CRD instances. Sorry for the inconvenience.
