### ISSUE TITLE
Flux helm-operater image version at tag helm-0.8.0 is wrong

### ISSUE THREAD

**Issue by isen-ng** [weaveworks/flux#1944]
https://github.com/weaveworks/flux/blob/helm-0.8.0/chart/flux/values.yaml#L23

This should be 0.8.0 instead of 0.7.1.

This results in an error where `https://github.com/weaveworks/flux/blob/helm-0.8.0/chart/flux/templates/helm-operator-deployment.yaml` uses `--git-poll-interval={{ $gitPollInterval }}` but this arg is not available in 0.8.0 and thus flux fails to setup

**Comment by hiddeco** [comment]
The chart is released sepertly from the Helm operator, if you take the chart from `master` you will see it has the correct version and will work.

**Comment by isen-ng** [comment]
ah ha...
ok now I understand the tagging
