### ISSUE TITLE
Retry ssh-keyscan command

### ISSUE THREAD

**Issue by stefanprodan** [weaveworks/flux#1969]
The CircleCI tests are failing often with:
```
The command '/bin/sh -c ssh-keyscan github.com gitlab.com bitbucket.org ssh.dev.azure.com vs-ssh.visualstudio.com >> /etc/ssh/ssh_known_hosts &&     sh /home/flux/verify_known_hosts.sh /etc/ssh/ssh_known_hosts &&     rm /home/flux/verify_known_hosts.sh' returned a non-zero code: 1
```

We should wrap this command in a bash script are retry it a couple of times while waiting a couple of seconds between retries.

**Comment by dholbach** [comment]
Good thinking. This currently fails in about 70% of the cases for me and is quite annoying.
