### ISSUE TITLE
Workload autoupgraded before locking in annotations tutorial

### ISSUE THREAD

**Issue by cdenneen** [weaveworks/flux#1983]
Currently if you follow along with the https://github.com/weaveworks/flux/blob/master/site/annotations-tutorial.md example between the time you release 1.4.1 and you lock the deployment gets auto-upgraded to latest 1.4.x tag and therefore when you lock it locks on latest version. 

I would suggest therefore allowing the "lock" to be passed as a flag to release.

Something similar to:
```
fluxctl release --workload demo:deployment/podinfo -i stefanprodan/podinfo:1.4.1 --lock --lock-msg="1.4.2 does not work for us"
```

**Comment by cdenneen** [comment]
Other option would be to document step before `release` to `deautomate` to avoid automation upgrading the `release` before being able to `lock`

**Comment by 2opremio** [comment]
> Other option would be to document step before `release` to `deautomate` to avoid automation upgrading the `release` before being able to `lock`

I think that makes sense, I will update the guide
