### ISSUE TITLE
Upgrade helm chart fails

### ISSUE THREAD

**Issue by derrickburns** [weaveworks/flux#1984]
**Describe the bug**
Weave Helm Operator appears to be attempting an install when it should be attempting an upgrade.

**To Reproduce**
I have a Helm chart installed via a HelmRelease, referenced via a GitHub url. Works fine.

I updated the chart in GitHub to include an additional service/deployment.  I modified the `values.yaml` file.  

When I look at the logs, Weave Helm Operator appears to attempt to install the new chart over the existing one. I expected it to attempt to **upgrade** the chart.  Consequently, since the helm release name is the same, I get the 
```
a release named foo already exists.\\nRun: helm ls --all foo
```
error message.
**Expected behavior**
Upgrade the chart in place.

**Logs**
If applicable, please provide logs of `fluxd` or the helm-operator. In a standard stand-alone installation of Flux, you'd get this by running `kubectl logs -n default deploy/flux`.

**Additional context**
Add any other context about the problem here, e.g 
- Flux version: docker.io/weaveworks/flux:1.12.0
- Helm Operator version: docker.io/weaveworks/helm-operator:0.8.0
- Kubernetes version: v1.11.8-eks-7c34c0
- Git provider: GitHub
- Container registry provider: DockerHub

**Comment by hiddeco** [comment]
What is the status of the Helm release (`helm status <release>`)? My suspicion is that it failed and therefore Flux chooses to install rather than upgrade.

**Comment by derrickburns** [comment]
Ah. I see.

If I make a change to a helm chart that breaks the install, Weave Helm Operator does not revert the change.  So, the helm installation is left is a FAILED state.  

I think that is not the desirable behavior.

**Comment by hiddeco** [comment]
We do this because rollbacks for stateful deployments can be dangerous, an enhancement has been described in #1960 and will be implemented in the future.

**Comment by derrickburns** [comment]
That would be great. Thanks

**Comment by hiddeco** [comment]
Is it okay if I close this issue and we continue tracking it in the one I mentioned above?

**Comment by derrickburns** [comment]
Yes thx
