### ISSUE TITLE
Flux silently failing when a manifest ends in '---'

### ISSUE THREAD

**Issue by dwightbiddle-ef** [weaveworks/flux#2002]
Recently, I submitted issue #1925 because the '---' and the end of a yaml file broke the weave cloud deployment page. That issue was resolved, and I tested adding the '---' at the end of a file and the deployment page continued to work.

However, I left it that way, and a week later (middle of last week), I found that flux was not syncing any new changes _in that namespace_, and I saw the same error in the flux logs that I referenced in the issue above: '"{pathToYaml}": yaml: did not find expected node content'

When I removed the '---' at the end of the file again, the error in the flux agent logs went away, and all of the queued up changes to that namespace all came pouring in at once.

Though the fix for the issue mentioned above helped prevent a complete error in Weave Cloud UI, now it is silently failing, which is a more insidious problem, and harder to debug.

**Comment by 2opremio** [comment]
@dwightbiddle-ef what flux version are you running? Can you share the error log?

**Comment by dwightbiddle-ef** [comment]
We are on flux v1.10.1

I could add the --- back in and break everything, but if possible id rather not do that. Sorry I forgot to copy paste it out before fixing the issue.

Is that absolutely required to debug? Reproducing is quite simple, just add ‘---’ to the bottom of any yaml in a repo and flux will start choking.

Dwight Biddle
Technical Lead, Labs at EF Tours

/

EF Center Boston

Two Education Circle, Cambridge MA 02141
0ffice: +1.617.619.1372
Skype: dwight.biddle
www.ef.com<http://www.ef.com/>

**Comment by 2opremio** [comment]
> We are on flux v1.10.1

The fix for #1925  (#1931) was released with [Flux 1.12.1](https://github.com/weaveworks/flux/blob/master/CHANGELOG.md#1121-2019-04-25), so you are simply experiencing #1925

> That issue was resolved, and I tested adding the '---' at the end of a file and the deployment page continued to work.

Did you temporarily upgrade to 1.12.1 to test this? Otherwise, I don't see how it could have ever worked.

> I could add the --- back in and break everything, but if possible id rather not do that. Sorry I forgot to copy paste it out before fixing the issue.

There is no need, thanks. I was trying to figure out whether this was a different incarnation of #1925, but it's simply #1925 due to the version you are running.

> Though the fix for the issue mentioned above helped prevent a complete error in Weave Cloud UI, now it is silently failing, which is a more insidious problem, and harder to debug.

Uhm, I may not be understanding what you mean, but I don't see how the fix could have helped you.

What were you doing in the UI when you didn't get an error? What were you expecting to happen?

I don't work on Weave Cloud, but AFAICR, the Weave Cloud UI does display errors through events sent from Flux.

@squaremo Do you know if the Weave Cloud UI shows sync errors? Or is it a known issue

**Comment by dwightbiddle-ef** [comment]
Hmm interesting you are right about that. My testing did not include doing an upgrade, but the error we saw in the UI did stop happening (but that may have been a red herring as the agent obviously was still failing).

My understanding though, is that Weave Cloud will auto update. My weave cloud instance is in fact showing on the deploy page that the flux agent is behind in version (1.10.1 instead of 1.12.1), but it is read only since the agent was installed by running the kubectl command in the setup page. What is the best way to update? Is there a way to do auto-updates when you guys release new versions, or even sem-ver filtered auto-updates (i.e. 1.x)?

Thanks for your help,

Dwight Biddle
Technical Lead, Labs at EF Tours

/

EF Center Boston

Two Education Circle, Cambridge MA 02141
0ffice: +1.617.619.1372
Skype: dwight.biddle
www.ef.com<http://www.ef.com/>

**Comment by squaremo** [comment]
> My understanding though, is that Weave Cloud will auto update. My weave cloud instance is in fact showing on the deploy page that the flux agent is behind in version (1.10.1 instead of 1.12.1),

We have a "version gate" that limits which version is installed by Weave Cloud. It's currently at `^1.10`, because `1.11` changed how sync worked, and there were some things to iron out.

> Do you know if the Weave Cloud UI shows sync errors? Or is it a known issue

Er, some of them. It'll show when a particular workload is failing to be applied; but I don't think that it shows when a sync fails entirely. There is not great support for this in the API, which is partly to blame.

**Comment by dwightbiddle-ef** [comment]
Ok makes sense. When should we expect to get upgraded above 1.10?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by 2opremio** [comment]
It's up to you, we recommend upgrading to recent versions regularly if your
operation allows it. Read the CHANGELOG.md file for any
backwards-incompatible changes you should be aware of  when upgrading.

**Comment by squaremo** [comment]
> It's up to you

Not really; if you install via Weave Cloud, then the version is controlled by Weave Cloud.

**Comment by 2opremio** [comment]
True that, my bad, sorry. Thanks @squaremo !

**Comment by 2opremio** [comment]
@dwightbiddle-ef we expect to release 1.12.1 to the Weave Cloud agent sometime next week.

**Comment by 2opremio** [comment]
> > My understanding though, is that Weave Cloud will auto update. My weave cloud instance is in fact showing on the deploy page that the flux agent is behind in version (1.10.1 instead of 1.12.1),
> 
> We have a "version gate" that limits which version is installed by Weave Cloud. It's currently at `^1.10`, because `1.11` changed how sync worked, and there were some things to iron out.
> 
> Er, some of them. It'll show when a particular workload is failing to be applied; but I don't think that it shows when a sync fails entirely. There is not great support for this in the API, which is partly to blame.

I'll create a separate ticket for this.

@dwightbiddle-ef do you have any other questions or can I close this? (You can always reopen later on if you need it)

**Comment by dwightbiddle-ef** [comment]
Feel free to close - hopefully we will be notified when the flux version is updated?

**Comment by hiddeco** [comment]
@dwightbiddle-ef the Weave agent will automatically enrol it in your cluster, but I have set a reminder (read: post-it note below screen) to notify you once we have made the release.
