### ISSUE TITLE
Unable to deploy Prometheus-operator using flux

### ISSUE THREAD

**Issue by day1118** [weaveworks/flux#2013]
**Describe the bug**
Hi all
I am unable to deploy the Prometheus-operator from the stable charts using flux. This used to work correctly, however, I have seen some changes going on to do with how CRDs are handled and I think it is likely related. Based on the logs, it looks to me like the deployment fails due to missing CRDs (my understanding is this is expected, CRDs get applied in the first sync loop, and the rest deployed in the second), however, the CRDs then begin deleting and everything grinds to a halt. I'm not sure what is causing them to be deleted unless flux is trying to roll back the deployment? Note that I never see prometheus-operator listed as helm release when running 'helm ls -a'. Is this working for anyone else? My first unknown is whether the issue is specific to me / my cluster?

**To Reproduce**
Deploy the following helm release:
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/ignore: "false"
spec:
  releaseName: prometheus
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: prometheus-operator
    version: 5.5.1
  values: {}

For reference, my flux install command:
helm upgrade flux --install weaveworks/flux \
--set rbac.create=true \
--set helmOperator.create=true \
--set git.url=git@github.com:day1118/personal_k8_flux_test \
--set git.branch=prometheus2 \
--set git.timeout=120s \
--set helmOperator.git.timeout=120s \
--namespace flux \
--wait

**Expected behavior**
I expect the prometheus-operator chart to eventually fully install successfully.

**Logs**
*kubectl -n flux logs -f flux-helm-operator-6f5b84f4bb-mgnqc | grep prometheus*
ts=2019-05-07T01:32:00.737566587Z caller=operator.go:172 component=operator debug="PROCESSING item [\"monitoring/prometheus\"]"
ts=2019-05-07T01:32:00.737662426Z caller=operator.go:229 component=operator debug="Starting to sync cache key monitoring/prometheus"
ts=2019-05-07T01:32:17.853726759Z caller=release.go:149 component=release info="processing release prometheus (as prometheus)" action=CREATE options="{DryRun:false ReuseName:false}" timeout=300s
ts=2019-05-07T01:32:33.824605751Z caller=release.go:190 component=release error="Chart release failed: prometheus: &status.statusError{Code:2, Message:\"validation failed: [unable to recognize \\\"\\\": no matches for kind \\\"Prometheus\\\" in version \\\"monitoring.coreos.com/v1\\\", unable to recognize \\\"\\\": no matches for kind \\\"PrometheusRule\\\" in version \\\"monitoring.coreos.com/v1\\\", unable to recognize \\\"\\\": no matches for kind \\\"PrometheusRule\\\" in version \\\"monitoring.coreos.com/v1\\\", unable to recognize \\\"\\\": no matches for kind \\\"PrometheusRule\\\" in version \\\"monitoring.coreos.com/v1\\\", unable to recognize \\\"\\\": no matches for kind \\\"PrometheusRule\\\" in version \\\"monitoring.coreos.com/v1\\\", unable to recognize \\\"\\\": no matches for kind \\\"PrometheusRule\\\" in version \\\"monitoring.coreos.com/v1\\\", unable to recognize \\\"\\\": no matches for kind \\\"PrometheusRule\\\" in version \\\"monitoring.coreos.com/v1\\\", unable to recognize \\\"\\\": no matches for kind \\\"PrometheusRule\\\" in version \\\"monitoring.coreos.com/v1\\\", unable to recognize \\\"\\\": no matches for kind \\\"PrometheusRule\\\" in version \\\"monitoring.coreos.com/v1\\\", unable to recognize \\\"\\\": no matches for kind \\\"PrometheusRule\\\" in version \\\"monitoring.coreos.com/v1\\\", unable to recognize \\\"\\\": no matches for kind \\\"PrometheusRule\\\" in version \\\"monitoring.coreos.com/v1\\\", unable to recognize \\\"\\\": no matches for kind \\\"PrometheusRule\\\" in version \\\"monitoring.coreos.com/v1\\\", unable to recognize \\\"\\\": no matches for kind \\\"PrometheusRule\\\" in version \\\"monitoring.coreos.com/v1\\\", unable to recognize \\\"\\\": no matches for kind \\\"PrometheusRule\\\" in version \\\"monitoring.coreos.com/v1\\\", unable to recognize \\\"\\\": no matches for kind \\\"PrometheusRule\\\" in version \\\"monitoring.coreos.com/v1\\\", unable to recognize \\\"\\\": no matches for kind \\\"PrometheusRule\\\" in version \\\"monitoring.coreos.com/v1\\\", unable to recognize \\\"\\\": no matches for kind \\\"PrometheusRule\\\" in version \\\"monitoring.coreos.com/v1\\\", unable to recognize \\\"\\\": no matches for kind \\\"PrometheusRule\\\" in version \\\"monitoring.coreos.com/v1\\\", unable to recognize \\\"\\\": no matches for kind \\\"PrometheusRule\\\" in version \\\"monitoring.coreos.com/v1\\\", unable to recognize \\\"\\\": no matches for kind \\\"ServiceMonitor\\\" in version \\\"monitoring.coreos.com/v1\\\", unable to recognize \\\"\\\": no matches for kind \\\"ServiceMonitor\\\" in version \\\"monitoring.coreos.com/v1\\\", unable to recognize \\\"\\\": no matches for kind \\\"ServiceMonitor\\\" in version \\\"monitoring.coreos.com/v1\\\", unable to recognize \\\"\\\": no matches for kind \\\"ServiceMonitor\\\" in version \\\"monitoring.coreos.com/v1\\\", unable to recognize \\\"\\\": no matches for kind \\\"ServiceMonitor\\\" in version \\\"monitoring.coreos.com/v1\\\", unable to recognize \\\"\\\": no matches for kind \\\"ServiceMonitor\\\" in version \\\"monitoring.coreos.com/v1\\\", unable to recognize \\\"\\\": no matches for kind \\\"ServiceMonitor\\\" in version \\\"monitoring.coreos.com/v1\\\", unable to recognize \\\"\\\": no matches for kind \\\"ServiceMonitor\\\" in version \\\"monitoring.coreos.com/v1\\\", unable to recognize \\\"\\\": no matches for kind \\\"ServiceMonitor\\\" in version \\\"monitoring.coreos.com/v1\\\", unable to recognize \\\"\\\": no matches for kind \\\"ServiceMonitor\\\" in version \\\"monitoring.coreos.com/v1\\\", unable to recognize \\\"\\\": no matches for kind \\\"ServiceMonitor\\\" in version \\\"monitoring.coreos.com/v1\\\", unable to recognize \\\"\\\": no matches for kind \\\"ServiceMonitor\\\" in version \\\"monitoring.coreos.com/v1\\\"]\", Details:[]*any.Any(nil)}"
ts=2019-05-07T01:32:34.038194755Z caller=chartsync.go:373 component=chartsync warning="Failed to install chart" namespace=monitoring name=prometheus error="rpc error: code = Unknown desc = release: \"prometheus\" not found"
ts=2019-05-07T01:32:34.038374412Z caller=operator.go:214 component=operator info="Successfully synced 'monitoring/prometheus'"
I0507 01:32:34.039534       9 event.go:221] Event(v1.ObjectReference{Kind:"HelmRelease", Namespace:"monitoring", Name:"prometheus", UID:"e92010e3-7067-11e9-abad-005056bee076", APIVersion:"flux.weave.works/v1beta1", ResourceVersion:"102121", FieldPath:""}): type: 'Normal' reason: 'ChartSynced' Chart managed by HelmRelease processed successfully
ts=2019-05-07T01:32:53.455757283Z caller=release.go:149 component=release info="processing release prometheus (as prometheus)" action=CREATE options="{DryRun:false ReuseName:false}" timeout=300s
ts=2019-05-07T01:32:57.634524575Z caller=release.go:190 component=release error="Chart release failed: prometheus: &status.statusError{Code:2, Message:\"object is being deleted: customresourcedefinitions.apiextensions.k8s.io \\\"alertmanagers.monitoring.coreos.com\\\" already exists\", Details:[]*any.Any(nil)}"
ts=2019-05-07T01:32:58.473664897Z caller=chartsync.go:373 component=chartsync warning="Failed to install chart" namespace=monitoring name=prometheus error="rpc error: code = Unknown desc = release: \"prometheus\" not found"
ts=2019-05-07T01:35:53.48937013Z caller=release.go:149 component=release info="processing release prometheus (as prometheus)" action=CREATE options="{DryRun:false ReuseName:false}" timeout=300s
ts=2019-05-07T01:35:59.698655927Z caller=release.go:190 component=release error="Chart release failed: prometheus: &status.statusError{Code:2, Message:\"object is being deleted: customresourcedefinitions.apiextensions.k8s.io \\\"prometheuses.monitoring.coreos.com\\\" already exists\", Details:[]*any.Any(nil)}"
ts=2019-05-07T01:36:01.354793375Z caller=chartsync.go:373 component=chartsync warning="Failed to install chart" namespace=monitoring name=prometheus error="rpc error: code = Unknown desc = release: \"prometheus\" not found"
ts=2019-05-07T01:38:53.55274014Z caller=release.go:149 component=release info="processing release prometheus (as prometheus)" action=CREATE options="{DryRun:false ReuseName:false}" timeout=300s
ts=2019-05-07T01:38:56.577453841Z caller=release.go:190 component=release error="Chart release failed: prometheus: &status.statusError{Code:2, Message:\"object is being deleted: customresourcedefinitions.apiextensions.k8s.io \\\"alertmanagers.monitoring.coreos.com\\\" already exists\", Details:[]*any.Any(nil)}"
ts=2019-05-07T01:38:57.127629339Z caller=chartsync.go:373 component=chartsync warning="Failed to install chart" namespace=monitoring name=prometheus error="rpc error: code = Unknown desc = release: \"prometheus\" not found"

**Additional context**
I have tried using older flux versions (1.10.1) and have also been unsuccessful, so have removed all of my config and made it as generic as possible to see if anyone else can reproduce.
- Flux version: 1.12.1
- Helm Operator version: 0.8.0
- Kubernetes version: 1.13.2
- Git provider: Bitbucket & Github
- Container registry provider: docker.io/weaveworks

**Comment by stefanprodan** [comment]
Helm and CRDs don't play nice see https://github.com/helm/charts/tree/master/stable/prometheus-operator#work-arounds-for-known-issues

You need to extract the CRDs from the chart and put them in your git repo. Also set prometheusOperator.createCustomResource=false` in your HelmRelease.

**Comment by 2opremio** [comment]
@day1118 I am going to close the issue but please reopen if anything wasn't clear

**Comment by icy** [comment]
I'ma using Flux-1.17.0 on an EKS cluster (1.14.7), without Helm and I have the same issue:

```ts=2020-01-08T09:52:07.025017265Z caller=main.go:267 type="internal kubernetes error" kubernetes_caller=k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:270 err="pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to watch *v1beta1.CustomResourceDefinition: unknown (get customresourcedefinitions.apiextensions.k8s.io)"
ts=2020-01-08T09:52:08.094997447Z caller=main.go:267 type="internal kubernetes error" kubernetes_caller=k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:270 err="pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to watch *v1beta1.CustomResourceDefinition: unknown (get customresourcedefinitions.apiextensions.k8s.io)"
ts=2020-01-08T09:52:09.170984587Z caller=main.go:267 type="internal kubernetes error" kubernetes_caller=k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:270 err="pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to watch *v1beta1.CustomResourceDefinition: unknown (get customresourcedefinitions.apiextensions.k8s.io)"
```

**Comment by icy** [comment]
As I can't reopen this ticket, I create new one here https://github.com/fluxcd/flux/issues/2725 Thanks
