### ISSUE TITLE
Helm operator does not upgrade releases when a dependent chart version has changed.

### ISSUE THREAD

**Issue by agill17** [weaveworks/flux#2019]
**Describe the bug**
I have a HelmRelease CR deployed in my cluster thats pointing to an umbrella chart ( chart version: `0.0.1-test-version ) in a helm repository. Since this is an umbrella chart, it has requirements and dependencies. When one of the dependent chart version gets updated to a newer version, the helm operator does not see that as a change and as a result does not upgrade the release. 

** **However** ** if I delete my helmOperator pod and new one comes up, the new one sees the diff and triggers the upgrade right away. I was able to reproduce this 2 times back to back.

**To Reproduce**
Steps to reproduce the behaviour:
Running on kubernetes ( 1.12.5 ) in AWS using kops
1. Deploy a HelmRelease CR in a namespace
2. That HelmRelease CR must be configured to periodically check against a umbrella chart in a helm repository ( lets say your version of the umbrella chart is `0.0.1-test-version` )
3. Update one of the dependency version in that umbrella chart and package and push it back up to the helm repo *without changing the umbrella chart version* 
4. Watch logs of helm operator and you will see periodic checks happen in dry-run mode but a diff is not there to trigger an upgrade.
5. Finally, restart the helmOperator pod and watch logs of the new pod, you will see an upgrade trigger right away as it finds a diff between desired vs current state of the release.

**Expected behavior**
I expected my helm release to be updated without me having to restart helm operator pod.

**Logs**
** after helmOperator pod was restarted **
```
ts=2019-05-08T00:09:24.403614226Z caller=release.go:149 component=release info="processing release amrit (as 29775781-711b-11e9-a1ec-0e13ee82a392)" action=CREATE options="{DryRun:true ReuseName:false}" timeout=300s
ts=2019-05-08T00:09:24.759646814Z caller=chartsync.go:578 component=chartsync error="Release amrit: Chart has diverged due to manual Chart release" diff=...
```

**Additional context**
Add any other context about the problem here, e.g 
- Flux version: 1.12.1
- Helm Operator version: 0.8.0
- Kubernetes version: 1.12.5
- Git provider: github
- Container registry provider: nexus
- Helm chart registry: nexus

**Comment by hiddeco** [comment]
This is due to the fact that the Helm operator caches the tarballs it retrieves from a Helm repository, which is in my opinion not a wrong thing to do as the contents of a release should not change after it has been made.

Given the above, upgrading a dependency in your umbrella chart would mean that the umbrella chart itself also should have a new version/release.

If this is not an option for you, you can look into putting the umbrella chart in git as for git charts the operator works with the latest state in git and not a version.

**Comment by agill17** [comment]
@hiddeco ok so this is a normal behavior. However my flux operator is pointed to a repo that applies my helmReleases CR, which is the public key generated by flux. How do I configure HelmReleases to also look for umbrella chart changes in a separate git repository? ( since the public key is already in use by a different repository? I could not find docs on this, any pointers? )

**Comment by hiddeco** [comment]
@agill17 see the comment here: https://github.com/weaveworks/flux/blob/master/chart/flux/values.yaml#L59-L64
