### ISSUE TITLE
fluxctl requires running `kubectl proxy`

### ISSUE THREAD

**Issue by jml** [weaveworks/flux#203]
Previously, I deployed things to prod with:

``` console
$ cd ~/go/src/github.com/weaveworks/service-conf/k8s/prod
direnv: loading .envrc
direnv: export +BASE_URL +KUBECONFIG +SERVICE_TOKEN ~PATH
$ wcloud deploy <image>
```

Currently, I have to run:

``` console
$ cd ~/go/src/github.com/weaveworks/service-conf/k8s/prod
direnv: loading .envrc
direnv: export +BASE_URL +KUBECONFIG +SERVICE_TOKEN +FLUX_URL ~PATH
$ kubectl proxy &
$ fluxctl release --all --update-image=<image>
$ fg
^C
```

This is more commands & keystrokes than before, but without any extra benefit to me. 

I also constantly forget that I need to run a proxy. Security concerns discourage me from running a proxy to our prod cluster for longer than strictly necessary.

**Comment by squaremo** [comment]
You can now use Flux without the proxy, i.e., via authfe, and the binaries assume you are doing so by default. You just need to provide a service token.
