### ISSUE TITLE
Ad possibility to restart pod through fluxctl

### ISSUE THREAD

**Issue by mpashka** [weaveworks/flux#2036]
**Describe the feature**
I want possibility to initiate kubernetes deployment or daemonset restart through fluxctl.

**Expected behavior**
I want new command in fluxctl `restart` that will allow me to restart deployment or daemonset

**Workaround**
Now in order to restart I have to add some annotation into controller manifest, then commit file to git. If I want to do restart immediately I apply controller manifest to kubernetes manually. Sometimes I observed flux did update one more time during synchronizing with git. It's not convenient.

**Comment by rndstr** [comment]
Could you just do `kubectl delete pod -l name=flux` instead?

**Comment by mpashka** [comment]
I'm sorry. I initially wrote "initiate kubernetes deployment restart". But in flulx terms deployments and daemonsets are flux controllers. So my aim is to initiate graceful kubernetes deployment or daemonset restart.
`kubectl delete pod` is not a good option by many reasons. Even if deployment has single pod it can have `maxUnavailable: 0, maxSurge: 1` - in that case new pod must be created and started before removing old one.

**Comment by 2opremio** [comment]
Maybe I didn't fully understand the motivation for the feature request, but I don't think restarting workloads (at least per-se) falls into Flux's responsibilities.

Can you clarify why restarting a workload is related to what Flux does?

**Comment by mpashka** [comment]
Ok, sure

So we need to restart kubernetes deployment or daemonset. This is common thing and there are many reasons to do that. In our case common scenario is - we store configuration on some http resource, app loads configuration and in order to update config properties that are not hot reloadable we do app restart.

Now - how deployment or daemonset can be restarted in kubernetes. Gracefully, with respect to rollingUpdate policy. Currently kubernetes doesn't have native restart support. As far as I found one way to do that is to add some meaningless annotation - like "restart: _date_time_". So that can be done with pure kubernetes. It's possible to do that with flux as well - just add annotation into git file and that will initiate restart. Ok. But there are some caveats with that:
1) there is some lag between git commit and flux apply updates - so what if I want to apply changes immediately
2) there is no information about update process

So what I'm suggesting is to fix that two problems. One solution is to do that with flux - just add restart command that will do the thing. Another solution can be "apply git changes" flux command that applies changes from git immediately and reports in status progress.

**Comment by mpashka** [comment]
There is `fluxctl sync` command that can be used to synchronize the cluster with the git repository, now. So applying annotation to manifest file + applying `fluxctl sync` solves the issue
