### ISSUE TITLE
add security-context to memcached container

### ISSUE THREAD

**Issue by davidkarlsen** [weaveworks/flux#2041]
**Describe the feature**
The memcached container cannot be installed into a namespace with a strict pod-security-policy due to user it runs as.
The container will refuse to start:
```
  Warning  Failed     3s (x12 over 2m8s)  kubelet, alt-aot-r-kwo01  Error: container has runAsNonRoot and image has non-numeric user (memcache), cannot verify user is non-root
  Normal   Pulled     3s (x11 over 2m8s)  kubelet, alt-aot-r-kwo01  Container image "fsnexus.evry.com:8085/memcached:1.4.25" already present on machine
```

**What would the new user story look like?**
How would the new interaction with Flux look like? E.g.
0. Add a default security-context via values for the memcached container. Let it run as non-root user.

**Expected behavior**
Memcached should start without errors.

**Comment by davidkarlsen** [comment]
Doh - when I look at the template I see this is supported already. Let me come back with more info.

**Comment by stefanprodan** [comment]
You can set a security context for memcached at install time with `memcached.securityContext` see https://github.com/weaveworks/flux/blob/master/chart/flux/templates/memcached.yaml#L57
