### ISSUE TITLE
How to use a predetermined private SSH key to auth w/git repo?

### ISSUE THREAD

**Issue by NeverOddOrEven** [weaveworks/flux#2046]
**Use Case**

I want to specify the private key that Weave uses when authenticating with git. Since this key will be used to deploy short-lived development clusters, I want to re-use it rather than always adding new public keys to Git. 

However, when I specify the private key according to the documentation I am finding, suddenly fluxctl is unable to communicate with Kubernetes.

I could use some help making sense of the documentation, as it seems to me this private key is the same key Kubernetes uses to secure communication between `kubectl` and the cluster API -- not just for securing communication with Git. 

I would like to know if this is the case, and if so, maybe contribute some updates to the documentation. If it is not the same key, how do I configure my Weave agent to auth with Git, without breaking kubectl?

**Error** 

```bash
ts=2019-05-13T23:44:05.223868961Z caller=main.go:322 err="Get https://<url>:443/version?timeout=32s: dial tcp: i/o timeout"
```

**Recreating** 

I am following the [instructions in the FAQ](https://github.com/weaveworks/flux/blob/master/site/faq.md#how-do-i-use-my-own-deploy-key) to create the secret `flux-git-deploy`. I am installing it to the weave namespace, because that is where I will be installing Weave.
```bash

```
Then I am installing Weave Flux and Weave Flux Helm Operator

```bash
declare environment="dev.1"

kubectl --namespace weave \
    create secret generic flux-git-deploy --from-file=identity=/tmp/dev_key

helm upgrade --reset-values --recreate-pods \
    --install "weave" \
    --set rbac.create=true \
    --set image.repository=weaveworks/flux \
    --set image.tag=1.12.2 \
    --set helmOperator.create=true \
    --set helmOperator.repository=weaveworks/helm-operator \
    --set helmOperator.tag=0.9.1 \
    --set helmOperator.configureRepositories.enable=true \
    --set registry.acr.enabled=true \
    --set git.path="$environment" \
    --set git.label="$environment-sync" \
    --set git.url=ssh://git@<ssh host>/<gitops repository> \
    --namespace "weave" \
        "weaveworks/flux"
```

**Comment by 2opremio** [comment]
> as it seems to me this private key is the same key Kubernetes uses to secure communication between `kubectl` and the cluster API -- not just for securing communication with Git.

I can confirm they are separate.

1. To communicate with the API Server, [the default  service-account token is used](https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-api/#accessing-the-api-from-a-pod) (used by both `client-go` and implicitly by `kubectl`) unless you mount a custom kubeconfig file in `/home/root/.kube/config`.

2. To communicate with Git through ssh, the secret `flux-git-deploy` is used, as you have correctly mentioned.


> ```shell
> ts=2019-05-13T23:44:05.223868961Z caller=main.go:322 err="Get https://<url>:443/version?timeout=32s: dial tcp: i/o timeout"
> ```

Are you sure you are running version 1.12.2 ? This line doesn't match with the source code of 1.12.2 AFAICT

It's still a mystery to me why creating the Git secret would have an impact on the authentication with the API Server. 

Has Flux ever worked in your environment? 
How did you deploy Kubernetes? 
What does `kubectl get secrets --namespace weave` say? 
Does it include the default token? e.g. something like:

```
NAME                  TYPE                                  DATA   AGE
default-token-r4wvl   kubernetes.io/service-account-token   3      3d17h
```

> ```shell
> kubectl --namespace weave \
>     create secret generic flux-git-deploy --from-file=identity=/tmp/dev_key
> ```

This seems to be correct. How are you creating `/tmp/dev_key`? Something like `ssh-keygen -q -N "" -f /tmp/dev_key` ?

Here is an example of how to create the key and deploy flux with helm:
1. Create the key: https://github.com/weaveworks/flux/blob/1.12.2/test/e2e/e2e-git.sh#L11-L12
2. Deploy flux with helm: https://github.com/weaveworks/flux/blob/1.12.2/test/e2e/e2e-flux-chart.sh#L14-L30

> ```shell
> helm upgrade --reset-values --recreate-pods \
>     --install "weave" \
>     --set rbac.create=true \
>     --set image.repository=weaveworks/flux \
>     --set image.tag=1.12.2 \
>     --set helmOperator.create=true \
>     --set helmOperator.repository=weaveworks/helm-operator \
>     --set helmOperator.tag=0.9.1 \
>     --set helmOperator.configureRepositories.enable=true \
>     --set registry.acr.enabled=true \
>     --set git.path="$environment" \
>     --set git.label="$environment-sync" \
>     --set git.url=ssh://git@<ssh host>/<gitops repository> \
>     --namespace "weave" \
>         "weaveworks/flux"
> ```


As you may have already seen in the example above, you are missing the `--set git.secretName=flux-git-deploy` parameter (the chart suggests using name `helm-ssh` but that's up to you)

**Comment by NeverOddOrEven** [comment]
Thanks for the detailed response -- answers below.

> Are you sure you are running version 1.12.2 ? This line doesn't match with the source code of 1.12.2 AFAICT

It does appear to be the image tag version 1.12.2:

```bash
$ > kubectl -n weave describe pod weave-flux-58b7bcc5c8-65jlf
 Name:               weave-flux-58b7bcc5c8-65jlf
 Namespace:          weave
 ...
 Labels: app=flux
         pod-template-hash=58b7bcc5c8
         release=weave-flux
 ...
 Image: weaveworks/flux:1.12.2
 ```

> Has Flux ever worked in your environment?

Yes. When I add the public key of the ssh credentials generated by default, everything works fine. 

> How did you deploy Kubernetes?

It is an Azure Kubernetes instance, created via ARM template.

> How are you creating /tmp/dev_key? 

```bash
ssh-keygen -q -N "" -t rsa -b 4096 -f /tmp/dev_key

# not sure if this is the right namespace
kubectl create secret generic flux-git-deploy --from-file=identity=/tmp/dev_key

# or if this is the right namespace
kubectl create secret generic flux-git-deploy --from-file=identity=/tmp/dev_key -n weave
```

> What does kubectl get secrets --namespace weave say? 

```bash
Alex's MacBook> kubectl get secrets -n weave
NAME                     TYPE                                  DATA   AGE
default-token-jpp95      kubernetes.io/service-account-token   3      15h
flux-git-deploy          Opaque                                1      14h
flux-helm-repositories   Opaque                                1      15h
weave-flux-token-vwtw4   kubernetes.io/service-account-token   3      15h
```

> What does kubectl get secrets --namespace default say? 

```bash
Alex's MacBook> kubectl get secrets
NAME                                            TYPE                                  DATA   AGE
default-token-q7lwb                             kubernetes.io/service-account-token   3      20h
flux-git-deploy                                 Opaque                                1      15h
container-registry                              kubernetes.io/dockerconfigjson        1      15h
```

> Here is an example of how to create the key and deploy flux with helm:
>> Create the key: https://github.com/weaveworks/flux/blob/1.12.2/test/e2e/e2e-git.sh#L11-L12
>> Deploy flux with helm: https://github.com/weaveworks/flux/blob/1.12.2/test/e2e/e2e-flux-chart.sh#L14-L30

Currently, I only add the private key. Maybe I also need to include the private key, public key, and `known_hosts`. 

I will try this and follow-up with the results.

**Comment by NeverOddOrEven** [comment]
I seem to be suffering from DNS problems, possibly related to #1980? When I run `nslookup github.com`, I get an error. Which is really strange, because it works in a previously configured cluster. My `/etc/resolv.conf` is the same in both clusters, and both use the same `coredns` configmap. 

I tried added OpenDNS to my Core DNS resolvers, but that doesn't seem to work either. Thoughts?

**Comment by NeverOddOrEven** [comment]
The weird gets weirder... One moment it will resolve, then without any changes, it fails to resolve...

```bash
/home/flux # git clone https://github.com/weaveworks/flux.git
Cloning into 'flux'...
fatal: unable to access 'https://github.com/weaveworks/flux.git/': Could not resolve host: github.com
/home/flux # git clone https://github.com/weaveworks/flux.git
Cloning into 'flux'...
fatal: unable to access 'https://github.com/weaveworks/flux.git/': Could not resolve host: github.com
/home/flux # git clone https://github.com/weaveworks/flux.git
Cloning into 'flux'...
fatal: unable to access 'https://github.com/weaveworks/flux.git/': Could not resolve host: github.com
/home/flux # git clone https://github.com/weaveworks/flux.git
Cloning into 'flux'...
fatal: unable to access 'https://github.com/weaveworks/flux.git/': Could not resolve host: github.com
/home/flux # git clone https://github.com/weaveworks/flux.git
Cloning into 'flux'...
fatal: unable to access 'https://github.com/weaveworks/flux.git/': Could not resolve host: github.com
/home/flux # git clone https://github.com/weaveworks/flux.git
Cloning into 'flux'...
remote: Enumerating objects: 57, done.
remote: Counting objects: 100% (57/57), done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 21382 (delta 16), reused 29 (delta 10), pack-reused 21325
Receiving objects: 100% (21382/21382), 8.35 MiB | 13.98 MiB/s, done.
Resolving deltas: 100% (12908/12908), done.
/home/flux # cat /etc/resolv.conf 
nameserver 10.0.0.10
search weave.svc.cluster.local svc.cluster.local cluster.local xabccm33dkurhtpngmyz2souh.fx.internal.cloudapp.net
options ndots:5
```

**resolve.conf**
```bash
nameserver 10.0.0.10
search weave.svc.cluster.local svc.cluster.local cluster.local xabccm33dkurhtpngmyz2souh.fx.internal.cloudapp.net
options ndots:5
```

**Comment by 2opremio** [comment]
> ```shell
> # or if this is the right namespace
> kubectl create secret generic flux-git-deploy --from-file=identity=/tmp/dev_key -n weave
> ```

This is the right namespace since you seen to be deploying flux in the `weave` namespace.

The DNS  problem seems odd, could be a networking problem. Can you try using both an internal and an external DNS server, to rule out a problem in your internal resolver? 

That is `nslookup github.com` and e.g. `nslookup github.com 1.1.1.1` (using Cloudflare's DNS server)

Did you get to add the `--set git.secretName=flux-git-deploy` parameter when installing flux with helm? Did you get to make it work after changing that? (even if only once)

**Comment by NeverOddOrEven** [comment]
I haven't been able to recreate these DNS issues, so I think it was either pebkac or transient networking issues. I am successfully using the predefined ssh git credentials as well, so thanks for helping me to better understand those options @2opremio.
