### ISSUE TITLE
Service List UI in Weave Cloud

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/flux#206]
- [x] Brief @foot on how this should be

**Comment by squaremo** [comment]
Bumping to (presumably) next milestone.

**Comment by rade** [comment]
Can this be closed? We have gone through several iterations of the service list ui already, all without referencing this issue. Which suggests to me that this is done and any extra work should be tracked by fresh issues.

**Comment by foot** [comment]
Service list was implemented in https://github.com/weaveworks/service-ui/pull/60
