### ISSUE TITLE
Share Helm values using a local file

### ISSUE THREAD

**Issue by leoblanc** [weaveworks/flux#2072]
**Describe the feature**
Hi, this is a question and maybe a feature request. I mean, I'm not sure if this is already supported somehow.

I'm defining different environments (prod/dev/staging) for our custom applications. We are creating different HelmRelease files for each application+environment. Each Yaml file is very similar (same values) so I want to define them in a single file (stored on the same repo used by Flux). The goal of this feature is trying to avoid the duplication of these configurations and make maintenance simpler.

As I can see in [this documentation](https://github.com/weaveworks/flux/blob/master/site/helm-integration.md#supplying-values-to-the-chart) Flux already supports several features to do something similar but it seems like they don't cover our use case. 

These values are not stored in Kubernetes so we can't use valuesFrom + configMapKeyRef or secretKeyRef.

These values are not stored in the Helm Chart so we can't use valuesFrom + chartFileRef

The most similar option seems to be valuesFrom + externalSourceRef. This configuration accepts a URL. Can we use it to reference a file? I mean, by using something like this:

```
valuesFrom:
  - externalSourceRef:
      url: file://values/myapp.yaml
```
But I guess that this option needs an absolute path. In that case, I can't provide an absolute path because working directories are dynamically created by Flux (for example "/tmp/flux-working273968891"). So, I don't know if there is a way to reference a values file stored in the same Git repo used by Flux.

If this is not supported, could be really useful to have a new option like valuesFrom + localFileRef (or something like that) to reuse values from different HelmRelease files.

Thank you very much in advance!

**Comment by hiddeco** [comment]
What is the source of your Helm chart? Does it originate from a git source or a Helm repository? In case of the former you could try to use a `chartFileRef` with `../<depth>/values.yaml` (no guarantee this will work, have not tested it).

In case of the latter the git repository (containing your configuration) will not be available to the `HelmRelease` in any way as we maintain a checkout per `HelmRelease` that _uses a chart from a git source_.

Your best option would be to either incorporate it into the chart in some way, put the config somewhere on the (internal) web where it can be accessed (HTTP basic auth URLs should work), or wait for the kustomize feature to land so you can distribute the same `ConfigMap` over different namespaces and use the `configMapKeyRef` in every `HelmRelease`.

**Comment by leoblanc** [comment]
Thank you very much for your prompt response. This information is very useful, thanks.

I still think that could be great if we can store these shared values in the same Git repo used by Flux (instead of trying to reach the application's Helm Chart, a Kubernetes configmap or an external URL). I think that it's more "GitOps" since makes easier to see all our configurations in the same Git repo.

Anyway, I will explore the options mentioned by you, thank you very much!

**Comment by arturo-c** [comment]
@hiddeco @leoblanc it will work to reference a values file outside the helm chart location, I have tested it, but the problem is that flux doesn't detect changes to that file, so it will not attempt to update the helm release when you change that file outside.

**Comment by leoblanc** [comment]
@arturo-c Thanks for your info, I didn't know it. So, I guess that we need to set a new Helm Chart version (or Git tag) to force its update.

**Comment by arturo-c** [comment]
@leoblanc yup, that would be the way to force the update
