### ISSUE TITLE
Alternate formats for image created time

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#2075]
Some images (at least the library CentOS images) use a non-standard format for created date:

```
ts=2019-05-22T13:08:17.050122049Z caller=repocachemanager.go:226 component=warmer canonical_name=index.docker.io/library/centos auth={map[]} err="parsing time \"20180804\" as \"2006-01-02T15:04:05Z07:00\": cannot parse \"0804\" as \"-\"" ref=centos:latest
```

The spec they are following, https://label-schema.org/rc1/, says

> This label contains the Date/Time the image was built. The value SHOULD be formatted according to RFC 3339.

which is not exactly difficult to comply with, but there you are. As a matter of practicality, we could attempt alternate formats to see if we get a usable datetime.

**Comment by hiddeco** [comment]
I first thought we were at fault by not following the spec, but they are.

I am opposed to support something different than what the spec defines, as people should just follow the rules. Instead, I think we should silence the error, ignore the value, and fallback to the timestamp we get from the image registry.

**Comment by hiddeco** [comment]
I implemented what I described above in the PR linked to this issue (and also stated a couple of additional reasons to _not_ support more formats there). Feel free to re-open if you disagree.
