### ISSUE TITLE
Cut down number of image registry requests

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#208]
Ideally, we want "new image arrives; any service that uses it gets upgraded". What we do at present, asking each service to check for new images is the other way around, but provided the workers keep up with the jobs, it's a basically acceptable approximation of the ideal.

It does however do a lot more operations than necessary -- partly because it is polling, and partly because it does `poll x instance x service` operations. (This is somewhat mitigated if you expect _most_ images to be private to an instance; but, there will still be similar instances e.g., dev and prod, and in an instance, there will be reused images).

With each image fetch operation being potentially tens to hundreds of metadata requests, it adds up quickly: `poll x instance x service x image x tag`. Putting numbers to that: to support one hundred instances with an average of ten services (on the low side), each using two images and having fifty versions (Scope has > 50), that's `100 x 10 x 2 x 50 = 100,000` requests each poll.

One way to get closer to the ideal is to cache image information. Given appropriate security consideration (e.g., check first that the instance credentials can access the image repo), this cuts the best-case (no new information) requests down to `poll x instance x service x image` (the authentication request); i.e., `100 x 20 = 2,000` requests with the numbers from above, assuming no images are used in more than one place.

Doing all images for an instance at once cuts it down to `poll x instance x unique image`.

**Comment by squaremo** [comment]
(This is already a problem just with us using Flux ourselves)

**Comment by squaremo** [comment]
A few more notes:

 * if we want to support incoming hooks (e.g., from Docker Hub on image push) then we probably need a reverse index from images to services (or instances, at least). This would be tricky to maintain, though it can safely overestimate.

 * If we're very lucky Docker Hub and friends may give us caching headers or ETags when responding to `tags` requests, so we can at least tell if we need to fetch new metadata.
   * Failing that, we can use heuristics. Tags can be reassigned to different images, so it is not enough to map a tag to metadata once and for all; however, if a tag doesn't change for a while, it is less likely to be a "moving tag" so we can check it less often.

**Comment by paulbellamy** [comment]
For automated services, we could set up a webhook where possible (quay, and dockerhub, for non-public repos). exposing some api endpoint like `/api/flux/webhooks/index.docker.io/frosty-river-12`, which would get hit whenever a new image is built.

It is unfortunately not standardized for each registry. :(

**Comment by paulbellamy** [comment]
We also need to rate-limit registry requests, as we occasionally get:
```
registry-metadata-err="Get https://index.docker.io/v2/weaveworksdemos/front-end/manifests/39924531d700a3ee9c8539036a04acd3c3dc552b: malformed MIME header line: Too Many Requests (HAP429)."
```

**Comment by paulbellamy** [comment]
afaict there is no api for creating or viewing dockerhub webhooks.

**Comment by paulbellamy** [comment]
Another option is to do all registry requests from fluxd, which moves them to the user's infrastructure.

**Comment by philwinder** [comment]
Some more ideas:
- Add a hook (automatically) to CI to be notified when a new image _could_ have been pushed. Then we poll
- Add a hook to github (automatically) to be notified when we can poll for new images for a period of time.
- Add global rate limiting. I.e. monitor the numbers of global requests to hub.docker.. and rate limit on our front end.

**Comment by paulbellamy** [comment]
Discussed with @philwinder prioritization of stuff to try, roughly:

- [ ] ~~ webhooks ~~ (bust, not possible for dockerhub)
- [ ] Add a cache
- [ ] Investigate moving requests to fluxd
  - balance offloading processing to fluxd, with making it harder to upgrade.
- [ ] global rate limiting
- [ ] github/ci hooks

**Comment by rade** [comment]
Another option that got mentioned is to regularly spin up new IPs (via a new VMs?) for performing the requests, since the rate limiting appears to be keyed on source IP.

**Comment by rade** [comment]
Moving the requests to fluxd would also help with #351.

**Comment by paulbellamy** [comment]
Have added a cache and deployed through to prod. Was tricky to get deployed since we were being rate-limited, but appears to be working well: https://cloud.weave.works/admin/prometheus/graph?g0.range_input=30m&g0.stacked=1&g0.expr=sum(irate(flux_memcache_request_duration_seconds_bucket%5B1m%5D))+by+(method%2C+success)&g0.tab=0

**Comment by paulbellamy** [comment]
We should probably also have a global rate-limiting to ensure we don't get throttled by registries again.

**Comment by paulbellamy** [comment]
Have filed separate issue for global rate-limiting, and `Investigate moving requests to fluxd` will happen as part of https://github.com/weaveworks/flux/issues/351

**Comment by snwfdhmp** [comment]
Is there a fix for this ?
