### ISSUE TITLE
support for workload release 11.1 ?.

### ISSUE THREAD

**Issue by marcelonaso** [weaveworks/flux#2093]
Does anyone know until when there is support for workload release 11.1 ?.
Thank you
regards

**Comment by marcelonaso** [comment]
Does anyone know until when there is support for workload release 11.1 ?.
Thank you
regards

**Comment by 2opremio** [comment]
What do you mean by _support for workload_ ?

**Comment by marcelonaso** [comment]
necesito saber hasta cuando hay soporte para el release 11.1, tengo entendido que hasta octubre 2016.

**Comment by marcelonaso** [comment]
I need to know until there is support for release 11.1, I understand that until October 2016.

**Comment by 2opremio** [comment]
Flux doesn't have an 11.1 release

**Comment by marcelonaso** [comment]
Yo hablo de workload 11.1 , me estan preguntando hasta cuando hay soporte para ese release.

Marcelo Naso (Santiago - Chile)

**Comment by 2opremio** [comment]
No sé a qué te refieres con _workload 1.11_.. Me lo puedes aclarar?

**Comment by dholbach** [comment]
Maybe a different software that's called Flux?

**Comment by marcelonaso** [comment]
may be

**Comment by marcelonaso** [comment]
you know global variable?

**Comment by marcelonaso** [comment]
See this PGN, show version del workload.

![Workload_Help](https://user-images.githubusercontent.com/8159606/58430243-93762300-8076-11e9-9c31-b98b93699fed.PNG)

Regards

**Comment by 2opremio** [comment]
@marcelonaso I'm afraid this project is unrelated to that screenshot.. Closing

**Comment by marcelonaso** [comment]
OK
