### ISSUE TITLE
Missing image tag puts Flux in a weird state

### ISSUE THREAD

**Issue by michaelgeorgeattard** [weaveworks/flux#2098]
Given:
* A Helmrelease currently consumes image `123456789.dkr.ecr.eu-west-1.amazonaws.com/foo:1.0.1` which **no longer exists in the repository**
* A new image  `123456789.dkr.ecr.eu-west-1.amazonaws.com/foo:1.2.0`  is published
* Flux detects this new image, but does not upgrade as it cannot compare timestamps

```
ts=2019-05-28T07:26:46.716127145Z caller=images.go:107 component=sync-loop workload=test-fe:helmrelease/foo container=chart-image repo=123456789.dkr.ecr.eu-west-1.amazonaws.com/foo pattern=semver:^1.0 current=123456789.dkr.ecr.eu-west-1.amazonaws.com/foo:1.0.1 warning="image with zero created timestamp" current="123456789.dkr.ecr.eu-west-1.amazonaws.com/foo:1.0.1 (0001-01-01 00:00:00 +0000 UTC)" latest="123456789.dkr.ecr.eu-west-1.amazonaws.com/foo:1.2.0 (2019-05-28 07:15:57.401797549 +0000 UTC)" action="skip container"
```

A common use case which exposes this limitation is when Helmrelease is created before the actual image is published, and a random tag is used.

Flux should preferably just override the image tag when the previous one does not exist.

**Comment by 2opremio** [comment]
@michaelgeorgeattard how can know Flux whether it should actually replace the image if it cannot find the timestamp of the image?

I guess that we could obtain information from local images to fill the gap.

**Comment by 2opremio** [comment]
> A common use case which exposes this limitation is when Helmrelease is created before the actual image is published, and a random tag is used.

The image cache is refreshed periodically, so things will work once the image is published

**Comment by hiddeco** [comment]
Linking in #1831 as the strictness it was introduced there.

**Comment by 2opremio** [comment]
> I guess that we could try to obtain information from local images to fill the gap.

Uhm, that's not going to be easy, since flux and the image may live in different nodes

**Comment by hiddeco** [comment]
> Flux should preferably just override the image tag when the previous one does not exist.

The problem is that we do not know why a tag does not exists;

:heavy_check_mark: it got removed
:red_circle: the registry has a temporary problems with listing tags
:red_circle: our cache is not up to date
...etc

**Comment by michaelgeorgeattard** [comment]
I actually encountered this limitation by copy pasting another HelmRelease configuration, while leaving the old tag, which never existed for the new repository and will never exist. My hope was that Flux would detect a new tag being published and override the old (invalid, in-existing) tag.

**Comment by squaremo** [comment]
In this case, I think you will have to edit the manifest to have the correct tag, and commit that to git. We introduced a check on the timestamps to avoid situations in which fluxd made an update without knowing for sure that it was safe, and erroneously downgraded images. Side-stepping the check would reintroduce that risk.
