### ISSUE TITLE
Memcached fails to start

### ISSUE THREAD

**Issue by mani-rai** [weaveworks/flux#2106]
**Flux Version:** 1.12.3
**Environment:** minikube
**Used Command:** kubectl apply -f deploy

Log:
`     
WARNING: Setting item max size above 1MB is not recommended!
 Raising this limit increases the minimum memory requirements
 and will decrease your memory efficiency.
can't run as root without the -u switch`

**Comment by stefansedich** [comment]
@mani-rai I ran into this yesterday, and it looks related to this https://github.com/kubernetes/kubernetes/issues/78308

We could perhaps be explicit with the user in the chart to avoid this issue.

**Comment by hiddeco** [comment]
@stefansedich with #2107 merged, this has been 'resolved' (and can thus be closed)?

**Comment by stefansedich** [comment]
@hiddeco I think if @mani-rai is happy with it then it can be closed off.

**Comment by hiddeco** [comment]
Closing this as a fix has been made in both the chart and the plain manifest. @mani-rai if you are still experiencing issues, don't hesitate to reopen.
