### ISSUE TITLE
fluxctl does not authenticate properly to EKS using the new authenticator system

### ISSUE THREAD

**Issue by hlascelles** [weaveworks/flux#2118]
`fluxctl` does not authenticate properly to EKS using the new authenticator system

**To Reproduce**
Steps to reproduce the behaviour:
1. Use fluxctl 1.11.0
1. Update to use the latest aws cli: `pip install awscli --upgrade`
1. Make sure the authenticator is no longer on your PATH: `aws-iam-authenticator`
1. Run any command, eg `fluxctl sync`

**Expected behavior**
`fluxctl` should work as before.

**Logs**
```
» fluxctl sync                                                             
Unknown options: eks,get-token
Error: Could not create a dialer: Could not get pod name: Listing pods in kubernetes: Get https://xxxxxxxx.yl4.eu-west-1.eks.amazonaws.com/api/v1/namespaces/default/pods?labelSelector=app%3Dflux: getting credentials: exec: exit status 255
```

**Additional context**
The change was announced here: https://aws.amazon.com/about-aws/whats-new/2019/05/amazon-eks-simplifies-kubernetes-cluster-authentication/

When the new system is used to access a cluster, kubeconfig is rewritten to use a new authentication step which fluxctl appears to dislike.

I suspect this will require a change to the way fluxctl obtains credentials to access the cluster.

**Comment by jaksonwkr** [comment]
I got the same problem here

**Comment by 2opremio** [comment]
Can you try with a newer version of flux? Fluxctl `1.11` comes with pretty old Kubernetes libraries (they were updated in Fluxctl 1.12.1).

I presume `kubectl` works just fine with the same setup described in the issue, but can you confirm?

**Comment by 2opremio** [comment]
Lastly, if updating fluxctl doesn't help, can you share your kubeconfig file? Please redact the secrets before you do so.

**Comment by jaksonwkr** [comment]
Worked for me, I was using flux 1.12.0 then updated to 1.12.3 and worked fine, thanks.

**Comment by hlascelles** [comment]
Upgrading `fluxctl` to `1.13.1` has solved the issue for me.

**Comment by hlascelles** [comment]
Looks like that's the solution. I'll close this.
