### ISSUE TITLE
Slackbot to control flux deployments 

### ISSUE THREAD

**Issue by rimusz** [weaveworks/flux#212]
Slackbot would be handy to allow do manual deployments (using flux underneath) straight from slack channel.
Specially in the case when you have already promoted docker image from staging to prod.

**Comment by squaremo** [comment]
Yes. At the least, it would be handy to be able to ask, in Slack, for the status of services.

**Comment by sambooo** [comment]
The description is a bit vague, but I don't expect this to be something we'd support in Flux itself. Closing for now, counterarguments welcome.
