### ISSUE TITLE
Garbage collection flag question

### ISSUE THREAD

**Issue by marcincuber** [weaveworks/flux#2122]
Currently I use following flags in my config `- --sync-garbage-collection` together with `- --k8s-namespace-whitelist`. It happened that deployed namespace have been deleted.

Is there a way to configure flux so that it ignores specific resources and never deletes them? E.g. ignore deletion of namespaces and service accounts.

**Comment by 2opremio** [comment]
You add a `flux.weave.works/ignore: true` annotation to each resource you want Flux to ignore.

There is no way to tell flux to generically ignore all the resources of certain Kind though (e.g. tell Flux to ignore all namespace resources, for instance).

**Comment by 2opremio** [comment]
Closing this, please reopen if the answer wasn't clear.
