### ISSUE TITLE
Add helm diff functionality to fluxctl

### ISSUE THREAD

**Issue by michaelgeorgeattard** [weaveworks/flux#2133]
I propose adding helm diff functionality to `fluxctl` to:

* Locally test out `HelmRelease` changes before committing to origin
* Show diffs in `Flux` `HelmRelease` repository pull requests before merging

Currently this functionality can be hacked by copying `values` portion of `HelmRelease` to a separate file and running `helm diff` plugin accordingly.

**Comment by hiddeco** [comment]
Duplicate of #1864
