### ISSUE TITLE
A broken helm chart can cause flux-helm-operator to freeze

### ISSUE THREAD

**Issue by derrickburns** [weaveworks/flux#2141]
**Describe the bug**
A broken helm chart can cause flux-helm-operator to freeze

**To Reproduce**
I had a helm template that had a parse error:

```
yaml.scanner.ScannerError: mapping values are not allowed here
  in "<stdin>", line 1153, column 29
```

I tried to load it as a HelmRelease.  Instead of rejecting it, the `flux-helm-operator` froze:

**Expected behavior**
Report the release as failed.  Better yet, show the error output.
**Logs**
Last log entry:
```
ts=2019-06-09T23:57:38.52438155Z caller=release.go:167 component=release info="processing release develop-tidepool ││  (as af915a64-87b1-11e9-a9fd-0a3217e4fc30)" action=CREATE options="{DryRun:true ReuseName:false}" timeout=300s 
```
**Additional context**
Add any other context about the problem here, e.g 
- Flux version: 1.12.3
- Helm Operator version: 0.9.1
- Kubernetes version: 1.12.6
- Git provider: GitHub
- Container registry provider: Docker

**Comment by hiddeco** [comment]
Do you still have a copy of the template that caused the parse error so I can replicate the exact error?

**Comment by derrickburns** [comment]
no

**Comment by squaremo** [comment]
I constructed a chart that has an invalid template (https://github.com/squaremo/flux-example/blob/master/charts/garbage/templates/deployment.yaml#L27), and a HelmRelease to deploy it (https://github.com/squaremo/flux-example/blob/master/config/garbage-hr.yaml) to my minikube. The helm operator rolled right over it -- failing the release and reporting that, but not stopping there.

I suspect that @hiddeco's code changes in e.g., #2103 among others, have removed some problems with the operator getting stuck. I'm going to close this as "works for me", but @derrickburns if you see it again, and can furnish the problematic chart or template, please do re-open it.
