### ISSUE TITLE
Error: unknown flag: --log-format

### ISSUE THREAD

**Issue by brandon-bethke-neudesic** [weaveworks/flux#2145]
The flux and helm operator pod fails with the following error:
`Error: unknown flag: --log-format`

We pulled the latest flux and installed using the helm chart.
chart version: flux-0.9.5
app version: 1.12.3
flux image: docker.io/weaveworks/flux:1.12.3
operator image: docker.io/weaveworks/helm-operator:0.9.1

Thankfully, we were able to workaround this problem by removing `logFormat: fmt` from the values file.

**Comment by 2opremio** [comment]
If you were expecting to use this https://github.com/weaveworks/flux/pull/2138/files it hasn't been released yet.
