### ISSUE TITLE
Installation Order

### ISSUE THREAD

**Issue by muhlba91** [weaveworks/flux#2157]
I know the operator retries failed releases or files to be applied, e.g. if a CRD is not yet available.

Now I have some deployments not managed by Helm charts and want to deploy applications simply via multiple YAML files, e.g. one contains the Role, one the RoleBinding and one the Deployment object.

If the role bindings are not created before the deployment, the entire deployment could fail without the operator knowing about it. As an example would be PSPs that allow a certain capability on top of a cluster wide PSP or any permissions to the kubernetes API where the application will simply retry it.
In fact, is there any way to achieve an ordering of deployment objects, e.g. via filenames or annotations to be able to have those roles and bindings created before the deployment object?

**Comment by squaremo** [comment]
Are you asking about fluxd or about the helm operator?

**Comment by hiddeco** [comment]
Flux currently already takes this into account, see: https://github.com/weaveworks/flux/blob/b7e335ec206b55d0680195194ec90ea5bb082e9f/cluster/kubernetes/sync.go#L433-L452

**Comment by muhlba91** [comment]
@hiddeco thank you, this was my missing piece. I couldn't find any information in the documentation. :)

**Comment by kwontae** [comment]
Does it also have `rankOfKind` for Istio installations as well?

**Comment by gregorygtseng** [comment]
> Does it also have `rankOfKind` for Istio installations as well?

Doesn't seem like it because I created a namespace with the `istio-injection` label, and had to delete my pods for it to take effect.
