### ISSUE TITLE
Messaging system to intermediate between daemons and service

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#216]
In #199 daemons connect to a single fluxsvc instance with a websocket. Operations needing to ask the platform for something use a Connecter to get a handle to the RPC mechanism; that RPC mechanism is simply to serialise the request to the websocket (as a JSON-RPC), and decode the response.

Once there is more than one instance of fluxsvc this will not be adequate. Requests from one instance must be conveyed to wherever the desired daemon is connected (which is still via websockets).

One fairly obvious way to do it is with a messaging system to route the requests and responses. This does not have to be reliable, since we expect RPCs to fail from time to time anyway. RPCs get put into the system with the daemon (instance) name along with a "reply to", and relayed by the fluxsvc to which that daemon is connected, along with the "reply to". The responses include the "reply to", and relayed by the fluxsvc to the messaging system with the "reply to" as the destination.

(Another way is to simply have a directory to look up the address the fluxsvc to which the daemon is connected, and have that daemon relay requests along with a return address.)

**Comment by paulbellamy** [comment]
Next up, is to deploy nats and switch over, right? Anything else outstanding?

**Comment by paulbellamy** [comment]
Before deploying, please check https://github.com/weaveworks/flux/pull/314 hasn't broken this.

**Comment by paulbellamy** [comment]
Blocked from going to prod on: https://github.com/weaveworks/flux/issues/420

**Comment by rade** [comment]
I know we've discussed what's left to do here, but I keep forgetting.... so could somebody please list that here?

**Comment by paulbellamy** [comment]
We've changed the rate limits in fluxd, but need to have people deploy that, otherwise switching this  on will make it timeout for them.

**Comment by paulbellamy** [comment]
Discussed f2f: Releasing this means we need to tell everyone (all 5 of them) to upgrade their fluxd. That's easy, but let's wait for a bigger release to minimize disruption. Moved into :octocat: sync-loop milestone to be deployed when we do that release.

**Comment by squaremo** [comment]
Imma just close this -- we're using NATS for the (>=v6 API) service.
