### ISSUE TITLE
helm-operator unable to connect to tiller

### ISSUE THREAD

**Issue by roaddemon** [weaveworks/flux#2165]
I tried uninstalling and reinstalling flux because I was seeing some issues, but the new deployment isn't working since the helm operator can't connect to tiller.  When I look at the pod's logs, I see this error being repeated every 30 seconds or so:

ts=2019-06-18T11:55:06.764693961Z caller=helm.go:84 component=helm warning="unable to connect to Tiller" err="error getting tiller version: context deadline exceeded" host=tiller-deploy.kube-system:44134 options="{Host: Port: Namespace:kube-system TLSVerify:false TLSEnable:false TLSKey:/etc/fluxd/helm/tls.key TLSCert:/etc/fluxd/helm/tls.crt TLSCACert: TLSHostname:}"

To Replicate Issue:
I've deleted and reinstalled both helm and flux many times, using the flux installation instructions here:
https://github.com/weaveworks/flux/blob/master/site/helm-get-started.md

```
helm delete flux --purge
#this delete doesn't remove the CRDs so I skip the CRD creation step here.  I've also tried deleting and recreating but it doesn't have any affect.

helm upgrade -i flux \
--set helmOperator.create=true \
--set helmOperator.createCRD=false \
--set git.url=git@github.com:myuser/flux-get-started \
--namespace flux \
weaveworks/flux

kubectl -n flux logs deployment/flux 
#lots of errors here
```

**Comment by stefanprodan** [comment]
Hi @roaddemon 

Is Tiller accessible inside your cluster on this address `tiller-deploy.kube-system:44134`?

**Comment by roaddemon** [comment]
No, it's not accessible from inside the cluster.  Thanks.  I'll close this since it's a helm issue.

Working cluster:
```
$ kubectl run -i --tty busybox --image=busybox --restart=Never -- sh
If you don't see a command prompt, try pressing enter.
/ # telnet tiller-deploy.kube-system 44134
Connected to tiller-deploy.kube-system
```

Not working cluster:
```
$ kubectl run -i --tty busybox --image=busybox --restart=Never -- sh
If you don't see a command prompt, try pressing enter.
/ # telnet tiller-deploy.kube-system 44134
telnet: bad address 'tiller-deploy.kube-system'

```
