### ISSUE TITLE
Working clones occasionally balk at fetching sync tag

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#2169]
A user that has fluxd 1.12.3 connected to weave cloud occasionally sees an error message in the UI, represented in the log like this:

```
ts=2019-05-29T06:51:26.34694615Z caller=logging.go:42 component=upstream method=ListServices error="git fetch --tags /tmp/flux-gitclone212733495 [refs/notes/flux-flux:refs/notes/flux]: From /tmp/flux-gitclone212733495\n * [new ref]         refs/notes/flux -> refs/notes/flux\n ! [rejected]        flux-sync -> flux-sync (would clobber existing tag)\n"
```

(NB I have anonymised the name of the ref)
I think the chain of events is something along the lines of:

 1. The UI calls the API ListServices
 2. fluxd clones its repo mirror into a temporary directory, at HEAD, so it can examine the files
 3. as part of the clone, it fetches the sync tag from the mirror to the temp dir
 4. for whatever reason, between the clone and the subsequent fetch, the tag has changed

**Comment by errordeveloper** [comment]
I came across this earlier, as we've had an issue with eksctl release script. As of git [2.20.0](https://github.com/git/git/blob/master/Documentation/RelNotes/2.20.0.txt#L67-L71), one has to run `git fetch --tags --force`, if they'd trust the remote tags.
