### ISSUE TITLE
Output lines are chomping newlines on long lines

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/flux#219]
When the next line prints the wrapped text from the previous output line gets deleted (along with the newline).

**Comment by philwinder** [comment]
@paulbellamy I haven't seen this, and I can't find any commands that "wrap" in the way that you are describing. Do you mean wrap due to shell terminal size? Since that's handled by the terminal. If so, it might be an issue with your shell.

If not, can you suggest a command that shows what you mean, or maybe an example?

**Comment by paulbellamy** [comment]
If I remember right, it's like doing a release for an image which is longer than your terminal width.

**Comment by philwinder** [comment]
Understood. It's the "Status" line in the release, where the Status is some sort of stdout rewriter: https://github.com/weaveworks/flux/blob/master/cmd/fluxctl/check_release_cmd.go#L77

Simplest option is not to use the rewriting. Just print it sequentially. But I'll look if there is a fix.

**Comment by philwinder** [comment]
Is a bug with the uilive library: https://github.com/gosuri/uilive/issues/3

**Comment by philwinder** [comment]
Solutions are:
a) Remove live update.
b) Try another library, e.g. https://github.com/buger/goterm
c) Attempt to fix with this PR https://github.com/gosuri/uilive/pull/4/files. But the repo hasn't been touched in a year.

Just removing it is the best option IMO. I'm not convinced that it's totally necessary.

**Comment by philwinder** [comment]
I'm going to try and replace with https://github.com/buger/goterm

**Comment by errordeveloper** [comment]
I believe this issue is about pre-1.0 CLI functionality, closing.
