### ISSUE TITLE
Report on daemon status via service connection

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#220]
It's be helpful to show, in the web user interface at least, whether there's a daemon connected for an instance, and if so, whether it's running happily.

**Comment by squaremo** [comment]
See also #229, which is pretty closely related and could probably be done at the same time.

**Comment by philwinder** [comment]
Pretty sure that this is complete. The UI shows connected icons.

**Comment by paulbellamy** [comment]
Closing as fixed.
