### ISSUE TITLE
Make generating a deploy key easier

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#225]
At the minute we ask a user to supply a key pair, give the secret key to us, and add the public key to their github repo.

We can make this simpler, though:
 - there's no reason for the private key to leave our service, so we could generate it in the server and only send back the public key (and include a means of rotating the keys).
 - Since we're given the repo address, we can construct the appropriate page URL for adding the deploy key, and supply that
 - (In web UI, we might be able to add the deploy key for them)

**Comment by philwinder** [comment]
## Backend notes

- The backend fluxsvc 
    - generates keys, 
    - stores the private key in postgres for the user and 
    - Integrates with the Github API to add the public deploy key
- The user's Github OAuth token resides in the users service.
- Need an API to create/update a users key.

### This requires
- Github integration (and a click- through from the UI to allow access)
- Link to repository to be deployed to

### User features
- User doesn't have to touch any GH-related keys
- User is able to recreate their key at any point

### Advanced features
- Automated rolling of keys

**Comment by paulbellamy** [comment]
s/user/instance/g

**Comment by philwinder** [comment]
Requires work on backend users service. Awaiting design review. Can continue with items on the flux side.

**Comment by squaremo** [comment]
> Can continue with items on the flux side.

In particular, being able to

    `fluxctl set-config --generate-key`

(or analogous) to generate a deploy key and provide the public half of it would be a major advance.

**Comment by philwinder** [comment]
Backend flux plan:

Responsible for generating and inserting a deploy key into the repository of choice.

[ ] - Add API to accept token and other required parameters
[ ] - Reuse current key generation code to generate key
[ ] - Work with GH API to insert deploy key into repo

*Expectations*
The caller will provide the GH token and other required parameters (e.g. repo address)

**Comment by philwinder** [comment]
Fixed in https://github.com/weaveworks/service/issues/1102
and #431
