### ISSUE TITLE
Flux not taking into account /etc/hosts

### ISSUE THREAD

**Issue by BenHall** [weaveworks/flux#226]
The IP of our Docker Registry is listed in the /etc/hosts file. This doesn't seem to be taken into account with flux.

Attempt to access fails:
```
fluxctl list-images --service=sock-shop/front-end                             
Error: executing HTTP request: reading HTTP response: 500 Internal Server Error (getting images for services: fetching image metadata for registry.test.training.katacoda.com:4567/root/front-end: Get https://registry.test.training.katacoda.com:4567/v2/root/front-end/tags/list: dial tcp 46.101.43.49:4567: i/o timeout)       
```

Add /etc/hosts entry:
```
POD=$(docker ps | grep fluxd| tr -s ' ' | cut -d ' ' -f 1)
docker exec -it $POD ash -c 'echo "172.17.0.22 registry.test.training.katacoda.com gitlab" >> /etc/hosts'
docker exec -it $POD ping -c1 registry.test.training.katacoda.com
```

But sadly this doesn't look to be taken into account:
```
fluxctl list-images --service=sock-shop/front-end                             
Error: executing HTTP request: reading HTTP response: 500 Internal Server Error (getting images for services: fetching image metadata for registry.test.training.katacoda.com:4567/root/front-end: Get https://registry.test.training.katacoda.com:4567/v2/root/front-end/tags/list: dial tcp 46.101.43.49:4567: i/o timeout)       
```

I tried to upgrade to Alpine 3.4 but that didn't resolve the problem. Any ideas or suggestions on a workaround?

**Comment by squaremo** [comment]
`POD=$(docker ps | grep fluxd| tr -s ' ' | cut -d ' ' -f 1)`

I think you want fluxsvc here, unless I've an inaccurate idea of how you're setting things up.

**Comment by errordeveloper** [comment]
> `docker exec -it $POD ash -c 'echo "172.17.0.22 registry.test.training.katacoda.com gitlab" >> /etc/hosts'`

Ok, but not sure if it won't get overwritten right away... could you check if it's still there after a while?

**Comment by errordeveloper** [comment]
In anyway, seems like adding a proxy for the registry that will on kube would be a better option. I don't see a way of creating a Kubernetes service and pointing it at an external endpoint, so you'd probably need to run an nginx or haproxy, or whatever of such sort...

**Comment by squaremo** [comment]
> unless I've an inaccurate idea of how you're setting things up

I think I probably do have an inaccurate idea. If you're running everything in one pod, it's as you say, and the problem does seem to be with musl -- or as it's known here, **bleeep** musl.

**Comment by BenHall** [comment]
It's musl. I changed the base image to Ubuntu and it worked as expected.

**Comment by philwinder** [comment]
> I changed the base image to Ubuntu and it worked as expected.
Closing due to this indication that it's working for you. Let us know if you have any more issues.
