### ISSUE TITLE
fluxtcl returning a 404 on commands

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/flux#230]
I've run the following: 

~~~
kubectl apply -f https://gist.githubusercontent.com/errordeveloper/0e92c0223ac40a9df68df8e402ca873c/raw/2eaf7a567d75a41faf7a6712aded3d6fa6ad13ff/flux.yaml
~~~
 
setup my keys, etc. and configured travis and quay.io and forked the demo repos. 

then, Install: 

~~~
curl -o /usr/local/bin/fluxctl -sSL https://github.com/weaveworks/flux/releases/download/master-6cc08e4/fluxctl-linux-amd64
   57  chmod +x /usr/local/bin/fluxctl
~~~

 but when I attempt to run  the following (or any flux command for that matter):

~~~
fluxctl set-config --file=flux.conf
~~~

~~~~
Error: executing HTTP request: reading HTTP response: 404 Not Found ({"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"endpoints \"fluxy\" not found","reason":"NotFound","details":{"name":"fluxy","kind":"endpoints"},"code":404})
~~~~

**Comment by abuehrle** [comment]
This has been fixed and is invalid.

**Comment by abuehrle** [comment]
I retested this using:  'https://cloud.weave.works/k8s/flux.yaml'

and I get the same errors.

**Comment by rade** [comment]
do other fluxctl commands work, e.g. `fluxctl history` and `fluxctl list-services`?

**Comment by abuehrle** [comment]
Same error on all of them. 

I will add you to my cloud instance so you can see the websocket issue.

**Comment by rade** [comment]
Works fine for me using the same executable and an running against your instance.
```
$ sha256sum ./fluxctl 
d00cfdd0318b82b7441d714208fd2d078fa60260f7965b6f7073b3f556d08962  ./fluxctl
$ ./fluxctl -t <token> get-config
git:
  URL: ""
  path: ""
  branch: ""
  key: ""
slack:
  hookURL: ""
  username: ""
registry:
  auths: {}
```

**Comment by rade** [comment]
Having looked into this, chances are you followed the instructions at https://github.com/weaveworks/flux/blob/master/deploy/README.md, in particular the "use the Kubernetes API proxy" bit. These instructions are out of date, so it's probably best to wait until they have been updated.

**Comment by squaremo** [comment]
> chances are you followed the instructions at https://github.com/weaveworks/flux/blob/master/deploy/README.md, in particular the "use the Kubernetes API proxy" bit.

Yep that's my guess too. To use cloud flux,

 1. Unexport `FLUX_URL` (or export it as empty), and export `FLUX_SERVICE_TOKEN`, or provide the token as an argument to `fluxctl`.
 2. Make sure the daemon is given _only_ a token, and no `--fluxsvc-address` argument, so it defaults to cloud.weave.works.

The instructions are cleared up (I hope) in #235.

**Comment by abuehrle** [comment]
thanks @squaremo I will give it a try today and update our new guide as well.

**Comment by abuehrle** [comment]
Still can't seem to make this work:  ```--url string     base URL of the flux service; you can also set the environment variable FLUX_URL (default "https://cloud.weave.works/api/flux")```

I am setting this to on the master node in my cluster: 

`export FLUX_URL=http://localhost:8080/api/v1/proxy/namespaces/default/services/flux`

**Comment by abuehrle** [comment]
Ok,  a number of things went wrong here:  a frustratingly Incorrect port in the YAML file was one. Exporting the URL with localhost doesn't seem to work either.  Got this to work by using @squaremo's instructions and also exporting the variable with the weave cloud token seemed to do the trick.  

Closing this, but do have some usability suggestions for you.

**Comment by squaremo** [comment]
> do have some usability suggestions for you.

Splendid, yes please.
