### ISSUE TITLE
Status monitoring

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/flux#244]
It would be useful to have a way to confirm flux is running properly. I would propose:

* A Status command, contacting the backend and showing everything is OK.
* Prometheus metrics (and grafana graphs).

**Comment by squaremo** [comment]
> A Status command, contacting the backend and showing everything is OK.

We are plumbing this into the service for the purpose of web UI, but it could equally be used for both ad-hoc checks from the command line, and monitoring.

> Prometheus metrics (and grafana graphs).

We do expose some prometheus metrics; we have not hooked them into any of our own charts yet.

**Comment by paulbellamy** [comment]
Would be nice to have grafana charts of Database request qps and latencies, as well as fluxd request qps and latencies.

**Comment by paulbellamy** [comment]
Have created: https://github.com/weaveworks/flux/pull/324 for database request qps. and I suppose we'll get fluxd request qps/latencies from the nats bus stuff.

**Comment by paulbellamy** [comment]
All except the `status` command are done, which is in: https://github.com/weaveworks/flux/pull/323
