### ISSUE TITLE
Automator logs no-ops

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#251]
The automator does its job by speculatively enqueuing a job to upgrade each automated service, each tick (= each minute, I think). However, most of the time, there is nothing to do -- but because each release job writes to the history (and to logs), it fills the history (and logs) with worthless messages.

**Comment by paulbellamy** [comment]
When automating more stuff this becomes worse!

**Comment by squaremo** [comment]
There's a couple of options here:

 1. Tell the releaser to not record anything if there were no changes to make
 2. Explicitly check, in the automator, what needs to be updated and if anything, schedule exactly that

The first has the advantage that it might be useful for other purposes (e.g., as an option for CLI releases). In fact, maybe we could just not record no-ops at all ...

**Comment by paulbellamy** [comment]
> maybe we could just not record no-ops at all ...
👍

**Comment by paulbellamy** [comment]
Automator now only schedules release jobs when there is something to do.
