### ISSUE TITLE
Release Jobs are not recoverable

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#256]
In some circumstances a release job will never be marked as complete. We do report back if we *see* a failure, so a person can retry; however, we do not see all failures, and possibly worse, we do not see all successes.

Here are some of the things that can go wrong during a release, and the outcome.

*1. Error at any point up to pushing a commit to the config repo*

The failure is reported back to the user (or to the logs and history, if an automated release). No lasting effects.

*2. The service is restarted during a regrade*

The goroutine waiting on the regrade result is running in the service; when the service pod is terminated, the result of the regrade is lost. The user, or the client, may retry `CheckRelease`, but it will never be updated. No history or notification is recorded.

*3. The daemon terminates or loses the connection during the regrade*

In this case we don't know the result of the regrade. An error is reported back to the user, who can e.g., restart the daemon, etc., then review the state of the system to reconstruct what happened. The release is recorded as failed, though it may actually have succeeded.

------

The first is basically business as usual.

To mitigate 2) and to some extent 3), we can make the regrade operation non-blocking -- calling Regrade kicks a regrade off (i.e., calls only `kubectl apply`) and returns only any immediate problems (e.g., malformed yamel). The history and notifications are recorded at this point.

Subsequent invocations of `CheckRelease` look at the "rollout state" of the service by asking the daemon, rather than simply reporting on what's in the release job record, since there is no process actively updating it. (The staleness criteria for release jobs would need to be changed.)

We'd also need to try and make the release workers shut down gracefully, i.e., not leave incomplete records, although this will never be perfect of course.

The main problem with 3) is that successes can look like failures. With the mitigation above, the window for this to happen is smaller, but it can still happen. Possibly we can report this to the user in such a way as to make it clear that the outcome is unknown, and please check later.

**Comment by squaremo** [comment]
Note transplanted from #261: the worker can become a worker pool, managing its own goroutines. This would help tidy up main.go.

**Comment by paulbellamy** [comment]
This (combined with: https://github.com/weaveworks/flux/pull/311) would fix long-running deploys (e.g. cortex)

**Comment by squaremo** [comment]
Another problematic scenario: if a job panics, it will not be completed, and our rate limiting will mean no further jobs for that instance will be attempted.

**Comment by philwinder** [comment]
Need to take another look at this after the move to git-sync. We will probably have similar issues, but they might be different.

Also, this issue is too vague to take any action. Needs some refining.

**Comment by squaremo** [comment]
Yes, this is no longer an issue in the same way, now that jobs are done in the daemon. In general, the successful outcome of any job is that commits were pushed. If it simply fails to get to that point, the failure is reported to the user (if they are still watching); there is no partial success. If a job panics, the daemon will restart, and any pending jobs will be forgotten and be treated as failures.
