### ISSUE TITLE
Supply a message when releasing

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#274]
For later readability, it'd be good to be able to supply a message when releasing, e.g.,

```sh
$ fluxctl release --no-update --service=fluxy/fluxsvc -m "Update env changes from git"
```

**Comment by philwinder** [comment]
Similar to #501

**Comment by philwinder** [comment]
Code for adding a user/message to a release was added in #495

**Comment by philwinder** [comment]
And stores the user/message data to the history at: https://github.com/weaveworks/flux/blob/master/release/releaser.go#L217

**Comment by paulbellamy** [comment]
@philwinder so is this closed then?

**Comment by philwinder** [comment]
@paulbellamy See PR referenced above. Requires review.
