### ISSUE TITLE
Tune the job queue GC to be a bit more aggressive

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/flux#279]
We *might* need to do this? Since #265, there are more jobs going through. And it is only set to GC jobs after they've been around (& completed) for 1 hour. They are left around for a little bit for debugging (which I'm questioning the practicality of).

We should consider tightening this up, or adding a criteria of "run a GC if there are > X finished jobs".

**Comment by paulbellamy** [comment]
Note: this isn't currently causing any issues, just a tidiness thing.

**Comment by squaremo** [comment]
> They are left around for a little bit for debugging

Also so that people can abandon long-running jobs and come back to see what happened later -- for this reason, if anything one hour is a little short!

**Comment by sambooo** [comment]
No longer relevant.
