### ISSUE TITLE
typo in docs

### ISSUE THREAD

**Issue by rade** [weaveworks/flux#28]
reported by a user...

The [docs](http://weaveworks.github.io/flux/web) say
```
docker run -d -e ETCD_ADDRESS -e PROMETHEUS_ADDRESS -p 7070:7070 \
    name=fluxweb weaveworks/flux-web
```
`name` should be `—name`.

**Comment by squaremo** [comment]
Fixed in master already, and in gh-pages in 50670d60614794fec5a74e978e6cc4cc94218d7a
