### ISSUE TITLE
Upgrading fluxctl is painful

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/flux#282]
I've heard this from several members of the weave team.

Because you have to pull in the dependencies to build fluxctl, which includes k8s.

We could potentially:
1. [use kubernetes go-client](https://github.com/weaveworks/flux/issues/277)
2. Pre-build and cross-compile binaries into github releases (or elsewhere). We could have circle build them, and push when on master.
3. Split fluxctl into a separate (smaller) repo.

**Comment by rade** [comment]
I thought we already did publish binaries for releases.

**Comment by paulbellamy** [comment]
This is less about releases, and more about `latest`, for internal users.

**Comment by rade** [comment]
Ah ok. Github releases are probably not the best place for that. Unless we have some sort of "current snapshot" release that we update/re-create continuously.

**Comment by squaremo** [comment]
We can have CircleCI put the most recent binaries somewhere.

Most of the time it's not necessary to have the absolute latest, even for internal use; downloading from github is fine, until the API version changes. Which we should avoid doing too much.

**Comment by squaremo** [comment]
fluxctl binaries are uploaded to github releases now. As mentioned, you don't in general have to have the absolute latest.
