### ISSUE TITLE
There are multiple sources of truth about desired state of cluster

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/flux#283]
It would be nice if there were only a single place to consult to tell a log of what happened to the cluster.

Places/ways we could store it:
- in kubernetes
  - is the ultimate source of truth about what state the cluster *is* in
  - has limited history capability
  - goes away if the cluster is rebuilt/upgraded (not reusable)
  - difficult to shoe-horn the data we might want in
  - would integrate manual user config changes
- in git
  - is the ultimate source of truth about what state the cluster *should be* in
  - may not reflect what state the cluster *is* in
  - could use labels in the k8s manifest to attach policies to services
  - could use git log history (which we already do) to record changes
  - would integrate manual user config changes
  - persists beyond the actual k8s cluster, and is reusable.
- in flux's db
  - easy to implement
  - how it is now
  - has to be correllated with the git repo
  - persists beyond the actual k8s cluster, and is reusable

Of those options, I think I prefer the "in git" option.

WDYT?

**Comment by squaremo** [comment]
I like the idea of policies being put in the resources themselves. It also means

 * other things that understand k8s can see those policies
 * we don't have to worry about having config for things that don't exist

**Comment by squaremo** [comment]
> in git
> 
>     is the ultimate source of truth about what state the cluster should be in
>     may not reflect what state the cluster is in

Broadly, I think we'd apply changes to git and then to k8s (as we do for upgrades), but look in k8s when querying for the state (as we do for upgrades).

**Comment by paulbellamy** [comment]
In practice, this means we are looking up the services from the kubernetes cluster, so any services which are not running (say they're new and haven't been deployed yet) won't show up in list-services, and cannot be deployed with flux.

**Comment by philwinder** [comment]
In a slightly unrelated note, I just hit upon this issue after forgetting that I need to `create` the deployments/services first, before using flux.

To address this, we could have an `initialise` or `diff` command to get the cluster into the same state as git. (also see #364 for a diff like command but for a different reason)

But like Paul says, the better long-term solution would be to obtain all state from git and just make sure it's in sync.

**Comment by squaremo** [comment]
We now treat the git repo as the source of truth, and things that aren't in the cluster but are in the git repo will soon be created by the sync mechanism.
