### ISSUE TITLE
fluxctl automate should only return true if it could find the service

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/flux#287]
Actual Behaviour:
```
$ fluxctl automate -s something-that-doesn't-exist
$ echo $?
0
```

Expected Behaviour:
```
$ fluxctl automate -s something-that-doesn't-exist
Some message about service not existing
$ echo $?
1
```

**Comment by squaremo** [comment]
'Twas implemented such that it didn't have to look at either kubernetes or git. But I agree, it is a bit silly, and demonstrably causes problems (including for us: failure logs every automation run).

**Comment by sambooo** [comment]
Not an issue with Flux 1.*
