### ISSUE TITLE
Reconnect timeouts are quite long

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/flux#289]
We retry connecting every 5s (in fluxd and fluxsvc), but each attempt can take waaaay too long, which means, that if we restart authfe/fluxd/etc, the reconnection attempt can take longer than we would like.

**Comment by squaremo** [comment]
> but each attempt can take waaaay too long, which means, that if we restart authfe/fluxd/etc

The too-long reconnects are gateway timeouts, I believe. We can tune those down in the proxies, and we can cancel attempts from fluxd after a timeout.

**Comment by paulbellamy** [comment]
> We can tune those down in the proxies
aye, but I can see a user having some other proxy in the way potentially, so would be nice to timeout attempts in fluxd/ctl

**Comment by paulbellamy** [comment]
Fixed by: https://github.com/weaveworks/flux/pull/379
