### ISSUE TITLE
fluxctl release --no-update fails when no deployment

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/flux#294]
If you `kc delete -f my-deployment.yaml`, then try to `fluxctl release --no-update` it, it fails with:
```
failed: getting pod controller: no matching replication controllers or deployments
```

**Comment by squaremo** [comment]
There's no such deployment in the running service, so it can't release it. It's consistent, though I do wonder if it's the most useful way of doing things.

**Comment by paulbellamy** [comment]
The reason this came up, is it means kubefix can't fix diffs where the pods aren't running.

**Comment by squaremo** [comment]
Right I see, so there's a difference between the models, which we'll need to figure out.

**Comment by sambooo** [comment]
The `fluxctl release --no-update` command no longer exists.
