### ISSUE TITLE
Instrument job queue

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#299]
- rate of completion
 - queue depth
 - running time per job type
 - uncollected garbage (count; age)

Probably other things.

**Comment by philwinder** [comment]
@squaremo I think these are already covered in: https://github.com/weaveworks/flux/blob/master/jobs/metrics.go
Close?

**Comment by squaremo** [comment]
Mmm yes those are good. Does it also have queue depth? (I think I've seen that in the dashboard, just not in that file). If so please close away!

**Comment by philwinder** [comment]
You can calculate queue depth from the number of "available" statuses.
