### ISSUE TITLE
Reasons for "no change to service" not logged or reported

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#302]
If kubeservice fails to find the deployment file to change for a service, it still tries to commit a change, fails at that, and ultimately fails the release. But the reason is not very obvious, because it reports "Regrade due to "Release latest images to <service>": failed: no definition found; skipping regrade", and does not record the reason for the failure in the fluxsvc log.

**Comment by squaremo** [comment]
In the PR #421, the repo is checked before anything else. If a service doesn't appear there, but it was requested specifically (rather than with --all), it's skipped. If `--all` is used, the services included are those defined (according to kubeservice) in the repo.

**Comment by paulbellamy** [comment]
Fixed in #421
