### ISSUE TITLE
Flux should skip (or join-in-progress) when the same release is already happening

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/flux#305]
e.g. flux automator schedules a release, which commits to git. Kubefix then runs, detects a diff, and schedules a release job. But the same release is already in progress. This means we get 2 slack notifications.

Edit: or, kubefix should run internally to fluxsvc

**Comment by squaremo** [comment]
Funnelling everything through git-sync will naturally serialise things (though we should be careful not to introduce similar problems elsewhere).
