### ISSUE TITLE
tell users how to get fluxctl

### ISSUE THREAD

**Issue by rade** [weaveworks/flux#312]
We are not telling users a) that they need fluxctl, and b) how to get hold of it.

[The first thing](https://github.com/weaveworks/flux#installing) we tell users is that
> For the minute you will have to build or use the container images weaveworks/flux{d,svc}.

Since the user won't even know at that point that there is such a thing as fluxctl, they will likely assume they have to build container images. Which is unnecessary, and furthermore we don't actually tell users how to do that (unless they are ["Developing"](https://github.com/weaveworks/flux#developing)).

We then say
> The directory [`/deploy`](https://github.com/weaveworks/flux/tree/master/deploy) has example Kubernetes configuration and instructions for using it.

The `/deploy` README says
> There's two ways to deploy Flux: you can use the hosted service at Weave Cloud, or you can run the service yourself. Using Weave Cloud is described in [`cloud/`](https://github.com/weaveworks/flux/blob/master/deploy/cloud/README.md);

So we hop along to `/cloud`, which says
> Flux comes in two parts: the service, which serves the API for the command-line client to use, and the daemon, which carries out some tasks on behalf of the service.

No mention of `fluxctl`. Yet `fluxctl` is used in the instructions that follow.

**Comment by rade** [comment]
I suggest we amend [the top-level Installing section](https://github.com/weaveworks/flux#installing) as follows:

> Flux comes in three parts: a command-line client, a service, which serves the API for the command-line client to use, and a daemon, which carries out some tasks on behalf of the service.
>
> You can download the command-line client, `fluxctl`, from [published releases](https://github.com/weaveworks/flux/releases).
>
> The service and daemon are delivered as `weaveworks/flux{d,svc}` container images that you need to [deploy to your Kubernetes cluster](https://github.com/weaveworks/flux/tree/master/deploy).

And the [cloud](https://github.com/weaveworks/flux/blob/master/deploy/cloud/README.md) and [standalone](https://github.com/weaveworks/flux/tree/master/deploy/standalone) instructions need amending to get rid of or amend the "two parts" language.

I also suggest moving both these README into https://github.com/weaveworks/flux/tree/master/deploy/README.md, so the user doesn't have to backtrack.

**Comment by rade** [comment]
This is somewhat related to #248, though IMO it is ok to point users at the current, ad-hoc, releases in the meantime.

**Comment by paulbellamy** [comment]
@pidster says, "We should put instructions on how to get this, in the web UI too"

**Comment by pidster** [comment]
Possibly is in there already, might be made clearer.

**Comment by philwinder** [comment]
Fixed in #411
