### ISSUE TITLE
failing automated services spam slack

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/flux#319]
```
[11:22]  
foo/bar: Regrade due to "Release latest images to foo/bar": failed: no definition found; skipping regrade

[11:23]  
foo/bar: Regrade due to "Release latest images to foo/bar": failed: no definition found; skipping regrade

[11:24]  
foo/bar: Regrade due to "Release latest images to foo/bar": failed: no definition found; skipping regrade

... etc ...
```

**Comment by squaremo** [comment]
I think failing automated releases should probably have a back-off (and eventual abandonment). It's way to easy to automate something that just doesn't exist!

**Comment by paulbellamy** [comment]
It also might be worth doing an immediate release when automating a service, and if that fails, refuse to automate.

**Comment by paulbellamy** [comment]
Proposed solution is two-fold:

1) do an immediate release when automating, and if that fails, refuse to automate it.
2) keep an index somewhere (memcached? pg?) of which automated services are currently failing, and the last time they failed. Use that to do an exponential backoff on those services, up to trying once/day.

**Comment by paulbellamy** [comment]
There's a somewhat separate issue of "if you've automated some services, but misconfigured your repo, you'll never get alerted of that"

**Comment by sambooo** [comment]
No longer an issue because Flux itself doesn't send Slack notifications any longer.
