### ISSUE TITLE
Add edge balancer to swarm tutorial

### ISSUE THREAD

**Issue by amouat** [weaveworks/flux#32]
The swarm tutorial launches curl in a container to connect to the service end-point. It would be nice if you took this one step further and added the edge balancer, so that users could connect from the host:

    docker run -p 8080:80 -d -e ETCD_ADDRESS -e SERVICE=httpd weaveworks/flux-edgebal

You could also update the image from httpd to weaveworks/hello-world and connect via the browser as per the normal tutorial. This would have the advantage of showing that all nodes are load-balanced. There is a slight complication with which VM is exposed though.

Personally, I wasn't overly concerned with the monitoring or UI stuff, I just needed a quick & easy solution to load-balancing a group of images on swarm. The tutorial was great after my coffee kicked and I managed to follow it correctly, but it felt like it was missing the final steps. Alternatively, I guess you could just point users to the normal tutorial at the end.

**Comment by squaremo** [comment]
Hi @amouat, thanks for the suggestion. I've added material on using `flux-edgebal` into the swarm guide; it's waiting for a new release so I can swap the screenshots for those of the new version.

(I just use the swarm leader as the "public IP")

**Comment by amouat** [comment]
Cool.

Another pedantic point - the "Guides" link on the flux homepage (https://www.weave.works/products/weave-flux/) leads to a generic Weave Guides page which doesn't mention flux. I think it would be better to just have a single "Documentation and Guides" link as the documentation page has prominent links to your tutorials.

Adrian.

**Comment by mjlodge** [comment]
Thanks -- we need to put Flux guides on the main site, alongside the other guides we have for Net and Scope.

**Comment by dpw** [comment]
The updates swarm guide was pushed out with the 0.2 release.

The problem with the "guides" link has been reported to the relevant people.
