### ISSUE TITLE
Handle changing tags

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/flux#320]
It seems like users quite frequently change tags, which is how they expect automation to work.

For example: having a `0.0.1-SNAPSHOT` tag (or `latest`), and just changing that on dockerhub to point to the new thing.

**Comment by peterbourgon** [comment]
For the record, this is a big no-no, and expressly verboten by folks like Kelsey. The right thing to do here is education, not acquiescence.

**Comment by squaremo** [comment]
I agree with Peter on this one, if it's a terrible practice (and it's easy to see that it is) we ought to educate, rather than encourage.

**Comment by paulbellamy** [comment]
> and it's easy to see that it is
Not convinced of that, but fine. That's all a reasonable argument.
