### ISSUE TITLE
Workflow is unclear

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/flux#321]
Might be solved with docs.

* Unclear *why* users should store manifests in git (vs just k8s gui)
* Unclear exactly *what* `fluxctl release` does without running it (does it update manifests in git?)
* ~~What should repo structure look like? Do I need each k8s "thing" in it's own file? Where should those files go?~~ #313
* ~~Given flux-example repo, do we have to have the Dockerfiles in the same repo as the manifests?~~ #313

**Comment by rade** [comment]
> * What should repo structure look like? Do I need each k8s "thing" in it's own file? Where should those files go?
> * Given flux-example repo, do we have to have the Dockerfiles in the same repo as the manifests?

I already filed #313 for these.

**Comment by paulbellamy** [comment]
Also evidenced by: https://github.com/weaveworks/flux/issues/370

**Comment by paulbellamy** [comment]
Also, limitations would be good to document.

**Comment by philwinder** [comment]
Fixed in #411
