### ISSUE TITLE
Support Deis Workflow for docker image deployments 

### ISSUE THREAD

**Issue by rimusz** [weaveworks/flux#328]
Would be nice that flux had support for Deis Workflow app deployment using `deis` cli or API.

**Comment by rimusz** [comment]
It could be done allowing flux to run custom commands instead triggering
k8s deployment release e.g. ` deis pull rimusz/test_image:v0.0.1 -a my_app"

**Comment by sambooo** [comment]
Workflow is no longer maintained.
