### ISSUE TITLE
Long-running rolling-updates block other releases

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/flux#329]
Because #311 means we only run one-release at a time per instance, any long-running deploys (e.g. cortex takes > 30 minutes) cause other releases to become bottlenecked.

I expect https://github.com/weaveworks/flux/issues/256 would fix it, but they are still serialized in the platform (or not?)

**Comment by paulbellamy** [comment]
This also blocks the job queue, so automated services stop working.

**Comment by paulbellamy** [comment]
Note: I've deautomated the cortex stuff in dev for now, because of this. Should re-automate it when this is fixed.

**Comment by squaremo** [comment]
Jobs now modify files and push a commit, which takes about the same amount of time whatever you're doing.

Synchronising from git tends to take about the amount of time on each occasion, as well, and crucially it uses `kubectl apply` which won't block on a rollout completing.
