### ISSUE TITLE
kubeservice fails on .yml files

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/flux#330]
yamls can have either `.yml`, or `.yaml`, extensions, but kubeservice fails on `.yml`.

**Comment by paulbellamy** [comment]
@nustiueudinastea just hit this.

**Comment by errordeveloper** [comment]
You mean `kubectl` just ignores them silently?

**Comment by paulbellamy** [comment]
it says they "are not yaml files", so yes it ignores them.
