### ISSUE TITLE
Add an alert on number of queued jobs

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/flux#334]
# TODO

- [x] Add a metrics on the number of available jobs, active jobs, scheduled jobs, orphaned jobs, and finished jobs (waiting for GC)
- [ ] Add the alert in monitoring repo

**Comment by philwinder** [comment]
Tried to add this as a prom metric, but it doesn't quite work since the metric would only be updated when someone/thing hits one of the job endpoints.

Instead, I/we propose that we create a separate service that is able to query the database whenever a prom scrape is requested.

**Comment by philwinder** [comment]
State transitions: scheduled -> available -> active -> abandoned/finished

- scheduled means scheduled_at is in the future
- available means scheduled_at is in the past, and claimed_at is null
- active means `claimed_at is not null and finished_at is null and heartbeat_at is less than 30m old (or something)`
- abandoned is like active but heartbeat_at is old
- finished is `finished_at is not null`

by 30m I mean, some multiple of whatever the heartbeat frequency is

**Comment by philwinder** [comment]
@paulbellamy Just waiting for this to propagate through to Prod. Then you'll need to create the alert that you want in prod. Example prom query in dev:
http://frontend.dev.weave.works/admin/prometheus/graph?g0.range_input=1h&g0.expr=flux_jobs_states&g0.tab=1

**Comment by paulbellamy** [comment]
@philwinder. Looks awesome! alerts are defined in `service-conf/jobs/monitoring/flux.rules` please add some reasonable ones there.
Maybe three alerts?
  - "if failed is > X"
  - "if available > X"
  - "if abandoned > X"

wdyt?

**Comment by philwinder** [comment]
@paulbellamy That's cool. Could you check what the "normal" ranges are for those metrics in prod? I don't have access. On dev, failed is around 10, (issue?) abandoned is about 1-2, available about 1.
