### ISSUE TITLE
Automate terminology is unclear

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/flux#339]
We need a better explanation of what this does for users.

There is (I think) an expectation that any and all changes (including config) to a service will be auto-applied when automated. Tracking latest images seemed less expected?

needs some investigation and talking with users.

**Comment by paulbellamy** [comment]
User feedback on locked and automated here: https://github.com/weaveworks/flux/issues/370
And, thoughts on what should be allowed for automated services here: https://github.com/weaveworks/flux/issues/356

**Comment by sambooo** [comment]
I don't think this is a problem any more since Flux's role as a tool is more clearly defined now. All changes to a manifest in the user's git repo will be automatically applied ('synced') to their cluster.
