### ISSUE TITLE
Create setup and configuration dialog

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/flux#344]
Setting up and confuring flux would be simpler in a gui:

- ability to paste in ssh keys 
- editing yaml files without vi
- ability to add 3rd party environment variables
- weave cloud token detected automatically
- fluxd and fluxctl launched without cli (optionally)

**Comment by lukemarsden** [comment]
@pidster PTAL

**Comment by pidster** [comment]
Thanks! We've been talking about this, we are definitely going to work on improvements in the GUI for setup of Flux.

**Comment by paulbellamy** [comment]
@abuehrle Could you please clarify the workflow you want here?

**Comment by abuehrle** [comment]
I will sketch something out and run it by some people here.

**Comment by pidster** [comment]
@abuehrle There's a doc in drive for discussion about this.

**Comment by philwinder** [comment]
@foot Can you specify what more you need from flux to achieve what you want to do with the UI? 

Right now, all you can do to set the slack/registry settings is to do a `get-config` from the API, alter the yaml file yourself, then `set-config` back.

If you're happy doing that, then great, no more work required.

However if you think it would be better to have an API to get/set specific settings, then let me know. Or something else if that's not right.

Thanks.

**Comment by philwinder** [comment]
Note: If we do go ahead with this, add it to the CLI too.

**Comment by foot** [comment]
@philwinder #441 talks about it a little more. The gist is that get-config doesn't return full values: 
- registry.auths: "***"
- git key: just gives the hash / snipped.

I will add some more details to that issue.

**Comment by squaremo** [comment]
Closing this in favour of issues elsewhere (weaveworks/service-ui, for example) or forthcoming, specific requests.
