### ISSUE TITLE
Build relies on GNU-specific `find -printf`

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#35]
It's a minor wart. Workaround for MacOSX, if you have homebrew and don't mind replacing `find`, `locate` and `xargs` with the GNU versions:

    brew install --with-default-names findutils

**Comment by peterbourgon** [comment]
Thanks, also hit this issue & would not like to replace findutils.

**Comment by dpw** [comment]
Fixed in 3d090b23f6c659af574075f12f4e8209a3279280
