### ISSUE TITLE
Can't use private registries

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/flux#351]
People hosting registries behind the firewall doesn't work with current flux architecture.

Options:
1) tell people are to make it public, and add credentials
2) proxy registry requests through fluxd
  - Would maybe "fix" registry throttling as well
  - Makes doing webhooks harder, potentially? maybe not...

Note:
Estimated ~26% of orgs use self-hosted image registries.

**Comment by pidster** [comment]
Webhooks will probably work, as they're outbound - unless the orgs firewall policies are particularly strict.

**Comment by paulbellamy** [comment]
But the user would have to expose flux (or the webhook receiver) on the internet, and configure flux with an endpoint to point the servers on.

**Comment by pidster** [comment]
Webhooks a Cloud only feature then?

**Comment by paulbellamy** [comment]
Probably, but then automating a bunch of stuff will never work if you selfhost, as you'll just get ratelimited.

**Comment by pidster** [comment]
We can't solve all of the problems if you're using Docker Hub and self-hosting, but Weave Cloud does a better job because we can support webhooks. Sounds reasonable enough to me.

**Comment by awh** [comment]
This is fixed now.
