### ISSUE TITLE
Example jenkins integration

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/flux#352]
To show people how flux and jenkins should work together.

A lot of people use jenkins, and their first question is, "how do I integrate flux with my existing ci pipeline?" Maybe it is as simple as saying "have jenkins push your images to X"...

**Comment by sambooo** [comment]
I don't think this is necessary at this point. The guide would consist almost entirely of showing people how to make Jenkins build an image. Open to disagreement though 😄
