### ISSUE TITLE
Consider fluxctl api change for `get-*` and `list-*` parameters

### ISSUE THREAD

**Issue by philwinder** [weaveworks/flux#362]
I'm not sure what the perfect answer is, but there is room for improvement.

E.g. I don't like the fact that we have a list verb in front of images/services. I think get is enough.

And you have separate get-config and set-config commands. Couldn't they be `fluxctl get config` and `fluxctl set config` like `kubectl`?

And if we're doing that, then can't we just have `fluxctl get services` and `fluxctl get images`?

The `get/set` paradigm provided by `kubectl` seems to have worked and people are probably used to it now. I think it's more flexible for future api extensions too.

**Comment by paulbellamy** [comment]
For context and previous discussion see: https://github.com/weaveworks/flux/issues/146

**Comment by philwinder** [comment]
Doesn't seem to be any traction on this so consider booting.

**Comment by squaremo** [comment]
I reckon a "UX review" is in order; let's boot this specific issue on the understanding that the CLI should get an overhaul at some point.
