### ISSUE TITLE
Kubefix is surprisingly race-y with flux itself

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/flux#364]
Often races with releases themselves.

Solution is to integrate the kubediff & fixing diffs into flux itself, as a serialized job. But, how to do the diff over the `platform.Platform` interface is difficult to do in a non-k8s-specific way.

In general it would be good to fix the issue and define what flux should do if a user manually edits stuff in the definitions repo.

It seems we could do the diff by:
a) Doing a`platform.Platform.AllServices() []platform.Service` which returns a list of everything currently running, then doing the diff on fluxsvc.
b) Having a `platform.Platform.Apply(definitions []Definition) []Update` which sends all the relevant definitions (or whole git repo?) to the fluxd, and it diffs/fixes stuff, and returns a list of what it did.
c) Have something similar to the kubernetes events API, which fluxsvc could subscribe to, and get "pushed" notifications from the platform when things change. This would be the most responsive.

With a small amount of thought, I favour B (which seems simpler) or C (which seems more responsive). Though A would be a fine stopgap to C.

**Comment by paulbellamy** [comment]
Also, it is unclear what the terminology and UI for switching this on should be. Either in config, or could be conflated with "automating" a service.

**Comment by paulbellamy** [comment]
I've now removed kubefix from dev, as it was causing more issues than it was fixing.

Based on various conversations people expect automated services to automatically get configs applied too, not just images. We should prioritize fixing this.

It might just be possible for `a` to just have fluxsvc ask about automated services, not all of them.

**Comment by sambooo** [comment]
Not relevant to this repo. No idea if the general problem still exists for anyone.
