### ISSUE TITLE
/var/run/docker.sock: connect: permission denied

### ISSUE THREAD

**Issue by asiqq23** [weaveworks/flux#37]
Running command:

docker run --name=fluxd -d -e ETCD_ADDRESS \
       --net=host --cap-add=NET_ADMIN \
       -v /var/run/docker.sock:/var/run/docker.sock \
       weaveworks/fluxd --host-ip $HOST_IP

starts container with fluxd, but don't permits fluxd to do connection routing.

I saw in logs that
time="2016-04-06T21:54:44Z" level=error error="Get http://unix.sock/version: dial unix /var/run/docker.sock: connect: permission denied"

For me worked if i added --privileged=true flag to give special permissions. Maybe there is another solution?

**Comment by dpw** [comment]
Thanks for reporting this.  What Linux distro are you running, and what version of docker?

**Comment by asiqq23** [comment]
Docker version 1.9.1, build 78ee77d/1.9.1
CentOS Linux release 7.2.1511 (Core)

And I am root

**Comment by dpw** [comment]
> CentOS Linux release 7.2.1511 (Core)

Ah yes.  It's an selinux issue.   So either you'll have to use the `--privileged` workaround, or use https://github.com/dpw/selinux-dockersock

We'll update the docs to mention this.
