### ISSUE TITLE
Automate and Locked confusion

### ISSUE THREAD

**Issue by BenHall** [weaveworks/flux#370]
![screenshot 2017-01-12 16 22 42](https://cloud.githubusercontent.com/assets/82614/21898045/651bda46-d8e3-11e6-80a1-97ac2c165373.png)

Given the above screenshot, I'm not sure how I can have the images as automated to be released, but it also locked. When I unlock, should it automatically deploy the latest image? Or wait until the next image is released?

**Comment by squaremo** [comment]
Good points, thanks Ben.

Automated and Locked both have distinct meanings but the meaning of the each permutation is not obvious. If a service is locked, the automation state is irrelevant. This suggests that it's really three states: Locked, Automated, and Not automated; however, we do want to support the workflow of locking a service temporarily, then returning it to its former state of automation.

I think we can certainly be clearer about what is or isn't going to happen -- i.e., make the UI show the _consequence_ of the settings.

> When I unlock, should it automatically deploy the latest image?

It'll look at whether it's up to date, decide it's not, and deploy the latest image.

**Comment by sambooo** [comment]
This is (was?) a Weave Cloud issue, not a Flux issue.
