### ISSUE TITLE
Wasn't flux something different not too long ago?

### ISSUE THREAD

**Issue by faddat** [weaveworks/flux#373]
Hi, experiencing some mild confusion at the moment.  IIRC, flux *was* a fancy routing thing for docker containers.  

Now, seems that it is a container deployment tool for kube?  Am I understanding the transition correctly?

And then-- this raises a question of opinion, and I surely value them in this case......

For the long run, do you recommend Swarm or Kube?  Why and for which deployment types?  Should I take the changes in flux to mean that weave.works is transitioning to a mostly-kube shop?

Oh, and this ins't an issue so much as a comment:

**Positively love the "builds with standard plain-jane "go build."**  A+ for that feature!

**Comment by pidster** [comment]
> Hi, experiencing some mild confusion at the moment. IIRC, flux was a fancy routing thing for docker containers. Now, seems that it is a container deployment tool for kube? Am I understanding the transition correctly?

Yes, that's correct. We've moved along a bit and now focus on deployment ops in Flux.

> And then-- this raises a question of opinion, and I surely value them in this case...... For the long run, do you recommend Swarm or Kube? Why and for which deployment types? 

No recommendation.

> Should I take the changes in flux to mean that weave.works is transitioning to a mostly-kube shop?

No, we've just prioritised Kubernetes integrations as those benefit our own use, in Weave Cloud.

**Comment by faddat** [comment]
Interesting!

Thanks!
