### ISSUE TITLE
Provide more info in `/api/history` for deep linking and richer UI interactions

### ISSUE THREAD

**Issue by foot** [weaveworks/flux#374]
To allow more elegant implementation of https://github.com/weaveworks/service-ui/issues/117 (vs. regex parsing text).

History entry wishlist: (are these possible?)
- `serviceId` (to link to a service page)
- `imageId` (to link to image / issue re-release)
- `imageSource` (to link to quay.io UI)
- `releaseId` (possible?, to show more info about a release)
- `status` (success|fail) for some nice green/red coloring.

**Comment by paulbellamy** [comment]
I'd suggest something like this for a release event, (forgive the go syntax):
```Go
type Event struct {
	ID string `json:"id"`

	// usually "Release" for now, but could be other things later
	Type string `json:"type"`

	// instance affected by this event
	InstanceID string `json:"instanceID"`

	// What time the event was started.
	StartedAt time.Time `json:"startedAt"`

	// If the event had a duration, how long did it last?
	EndedAt time.Time `json:"endedAt"`

	// success|fail, or maybe `debug|info|warn|error`, like log-levels?
	Status string `json:"status"`

	// Maybe a pre-formatted info string for errors, and ?other-stuff? ?
	// or, maybe this is unnecessary given the metadata below...
	Message  string `json:"message,omitempty"`

	// EventType-specific metadata here. for example, for a release:
	Metadata map[string]interface{}{

		// Maybe this is just the same as the event id? maybe not?
		ReleaseID  string 

		// Might be a bunch of services affected by a single release
		ServiceIDs []string 

		// likewise for images, can include repository/etc in each image
		ImageIDs   []image

		// could also include stuff like "triggering user" in here.
	}
}
```

You could see how other events could fit into this, such as "Service Automated", "Service Locked", "New Image Discovered", etc...

**Comment by squaremo** [comment]
> You could see how other events could fit into this, such as "Service Automated", "Service Locked",

I don't have interpretations of startedAt, endedAt for these events (although I'm not sure the events belong in the log anyway ..)

**Comment by paulbellamy** [comment]
For automated/locked events startedAt/EndedAt would likely be the same.
