### ISSUE TITLE
Limit concurrent connections to memcached

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/flux#384]
Occasionally we use a lot of transient connections to memcached at once, which causes some requests to `connect timeout`.

Could use get_multi for fetching them from memcached in batches, to go faster, and use less connections.

But, in fact it seems like most of the transient connections being opened is from set being called a lot in parallel.

**Comment by paulbellamy** [comment]
Maybe it would be more efficient to store tag history in blocks. Have a `tags a-d` block, a `tags e-h` block, etc, then just look up the appropriate block of tags. When fetching.

Either way, this probably involves changing the registry interface to support fetching multiple tags at once.

**Comment by philwinder** [comment]
Can we boot this when we move the docker list to fluxd?

**Comment by paulbellamy** [comment]
There'll still be a cache, which will probably memcached, just in the users' cluster.

**Comment by squaremo** [comment]
I think this will be mitigated in #851, which now does a single read for `registry.GetResository()`.
Other than that, we limit the number of concurrent writes implicitly by only having a certain number of fetches going (in warming.go).
