### ISSUE TITLE
Build a flux dashboard for grafana (for us)

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/flux#385]
Should include:
* incoming http requests qps & latency
* connected fluxd instances and duration
* queued and processing jobs (stacked graph? broken down by job method)
  * alert if queued available jobs is > something
* job durations, and success rates
* registry qps, duration, success rate, and cache hit ratio
  * alert if non-cached hits is > something for a while
* fluxy/memcached memory usage
  * alert if it gets too close to max, or is approaching max too quickly

**Comment by paulbellamy** [comment]
Some of the alerts will be done as part of: https://github.com/weaveworks/flux/issues/334

**Comment by philwinder** [comment]
Current dashboard here: https://cloud.weave.works/admin/grafana/dashboard/file/flux-services.json
Boot?

**Comment by paulbellamy** [comment]
Closed by https://github.com/weaveworks/monitoring/pull/109

**Comment by mazzy89** [comment]
Is it possible to have public that Grafana Flux dashboard?
 
I have not found anything around.

**Comment by nabadger** [comment]
A public one would be awesome :)

**Comment by manicole** [comment]
[This dashboard](https://grafana.com/grafana/dashboards/10475) is a good start, and adding [these](https://github.com/fluxcd/flux/blob/master/docs/references/monitoring.md) makes it even better !

**Comment by 2opremio** [comment]
This issue is closed. Let's move the discussion to  #2792
