### ISSUE TITLE
Make readme easier to understand

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/flux#386]
It would help a lot if user could discover Flux much easier, e.g. using Google or Github search.

Below is what I think would help a lot:

- Use keywords continuous+delivery+kubernetes+tool
- Add a simple description of how it brings together code/CI/registry/cluster (may include a diagram), and stress that it's not very trivial  to do properly yourself
- Add `fluxctl` usage examples right below the description, with configuration steps below it or in separate doc
- link to ["Try in your browser now"](https://www.weave.works/guides/cloud-testdrive-part-2-deploy-continuous-delivery/)
- Weave Cloud UI screenshot

**Comment by errordeveloper** [comment]
Let's consider one item at a time.

> - Use keywords continuous+delivery+kubernetes+tool

Right now the description sates the following 
> _"A tool for turning container images into running Kubernetes services"_

How about changing this to something like:
> _"Weave Flux is a production-grade tool that helps you to implement continuous delivery for Kubernetes in a simple and flexible fashion"_

Or shorter:
> _"Weave Flux is a tool that helps you to do continuous delivery for Kubernetes, simple and flexible"_

Down below we currently have:
> _"Flux is a tool for deploying container images to Kubernetes clusters."_

I think we could use the longer from above version here, may be extend it a little bit...

**Comment by paulbellamy** [comment]
Some specific docs feedback here: https://docs.google.com/document/d/1kPXn8rCvb6svN-rpNmpqaKBWSdAovKElS2oWTGLYx5Y/edit?ts=588b6f16

**Comment by errordeveloper** [comment]
I've added topic to the repo, now it shows up here:
https://github.com/search?utf8=%E2%9C%93&q=topic%3Aci-cd+topic%3Akubernetes&type=Repositories&ref=searchresults

**Comment by errordeveloper** [comment]
Are we happy with the tagline: "Weave Flux is a tool that helps you to do continuous delivery for Kubernetes, simple and flexible"?

**Comment by rade** [comment]
No
