### ISSUE TITLE
create & populate git repo from k8s, for bootstrapping

### ISSUE THREAD

**Issue by rade** [weaveworks/flux#387]
At a guess, a fair number of potential users with existing k8s deployments aren't going to have their configurations in a git repo suitable for flux consumption. Flux could give them a hand by creating and populating a repo based on the current state of their k8s.

**Comment by paulbellamy** [comment]
Or, at worst a skeleton repo for people starting out.

**Comment by awh** [comment]
Can this be closed now we have `fluxctl save`?

**Comment by squaremo** [comment]
Yes, I think `fluxctl save` fulfils this need.
