### ISSUE TITLE
Global rate-limit on registry requests

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/flux#389]
So we don't get rate-limited/blacklisted again.

Separated out of: https://github.com/weaveworks/flux/issues/208

**Comment by philwinder** [comment]
Boot, moving to fluxd?

**Comment by squaremo** [comment]
> Boot, moving to fluxd?

I think this will remain a problem with fluxd; all it will take is a few concurrent list-images requests (e.g., by more than one person having the UI open). Perhaps less of a chance of getting blacklisted entirely.

**Comment by squaremo** [comment]
This was addressed in #633.
