### ISSUE TITLE
Easier kubernetes config

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/flux#40]
It'd be nice to auto-config kubernetes. For example, if you're running fluxd locally we could look up the current kubectl config. If you're running it in a cluster, we could look up the in-cluster config. Then you could just do `fluxd --kubernetes` and away you go.

**Comment by squaremo** [comment]
We now just use client.NewInCluster() or its close equivalent, which means you don't have to supply all the arguments any more.
