### ISSUE TITLE
There will be changes to permissions of the default service account in 1.6

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/flux#400]
See https://github.com/weaveworks/scope/issues/2149 for details.

**Comment by paulbellamy** [comment]
@errordeveloper any details on the intended changes anywhere?

**Comment by errordeveloper** [comment]
The toplevel meta-issue is https://github.com/kubernetes/features/issues/2,
but I'm not able to dig out anything more specific right now...

**Comment by errordeveloper** [comment]
From talking to @luxas, I figure we will need to create some RBAC API object from the launch generator. There is code in `kubeadm` with some examples of such kinds of object. I suppose from Flux's perspective, we would want to ensure that user at least sees a descriptive error message, when flux cannot access the API as it currently expects.

**Comment by errordeveloper** [comment]
Also, there also a problem that RBAC goes from Alpha to Beta, namely RBAC for rules for v1.5 won't have the same `apiVersion` then the once for v1.6.

**Comment by liggitt** [comment]
both alpha and beta APIs exist in 1.6, and a role created with v1alpha1 will also be accessible from the v1beta1 API

**Comment by errordeveloper** [comment]
@liggitt thanks very much!

**Comment by errordeveloper** [comment]
I need a list of permissions that Scope requires, like [what we have for Net](https://github.com/weaveworks/weave/blob/8862d4f76e8ccc208d35b05b25f95f465edb7fc6/prog/weave-kube/weave-daemonset-k8s-1.6.yaml), any chance someone could look into it?

**Comment by squaremo** [comment]
Presently, we need:

 * list, get Namespaces
 * list, get Services
 * list, get, apply Deployments
 * list, get, create, delete ReplicationControllers

I have guessed some actions / objects; we'll need to test them out of course.

**Comment by errordeveloper** [comment]
> list, get, apply Deployments

I think `apply` translates to `create` and `update`

**Comment by errordeveloper** [comment]
This should had be closed a while ago, however it'd be good to refine permissions we ask for – https://github.com/weaveworks/flux/issues/850.
