### ISSUE TITLE
Error returned by some fluxctl commands is not printed

### ISSUE THREAD

**Issue by philwinder** [weaveworks/flux#409]
The error returned by commands using the `newUsageError` method in https://github.com/weaveworks/flux/blob/master/cmd/fluxctl/error.go#L11, for example here: https://github.com/weaveworks/flux/blob/master/cmd/fluxctl/automate_cmd.go#L36

I'm assuming that it should be printed?

Doesn't actually print the error. E.g.:

```
$ fluxctl automate

Usage:
  fluxctl automate [flags]

Examples:
  fluxctl automate --service=helloworld

Flags:
  -h, --help             help for automate
  -s, --service string   Service to automate

Global Flags:
  -t, --token string   Weave Cloud service token; you can also set the environment variable FLUX_SERVICE_TOKEN
  -u, --url string     base URL of the flux service; you can also set the environment variable FLUX_URL (default "https://cloud.weave.works/api/flux")
```

**Comment by squaremo** [comment]
Yeah this is a regression -- oops.

**Comment by squaremo** [comment]
When I run `fluxctl automate` I get

```
$ fluxctl automate
Error:  -s, --service is required
Run 'fluxctl automate --help' for usage.
```

which seems better (it does print the error out) but also worse (it doesn't print the usage).

**Comment by paulbellamy** [comment]
This was fixed *en passant* by https://github.com/weaveworks/flux/pull/435 (particularly f8fe434), where I noticed the same issue. I thought that printing the usage as well cluttered the output, making the actual error harder to see. I figured that the `Run 'fluxctl automate --help' for usage` was enough. Can we close this? or do you disagree?

**Comment by squaremo** [comment]
> I figured that the Run 'fluxctl automate --help' for usage was enough. Can we close this? or do you disagree?

Yeah good point, a clear and specific error message, plus how to get more information, is fine.
