### ISSUE TITLE
Flux fails to deploy image

### ISSUE THREAD

**Issue by nustiueudinastea** [weaveworks/flux#413]
When using Flux to upgrade an image that is hosted on Docker HUB, I get the following output:

```
Release job submitted, ID 6338c14c-864a-87a2-6eb7-e9ac0ba6103f
Status: Failed: updating pod controller for index.docker.io/weaveworksdemos/cart:master-129ef150: Could not find image name

1) Queued.
2) Calculating release actions.
3) Release latest images to sock-shop/cart
4) Clone the config repo.
5) Clone OK.
6) Update 1 images(s) in the resource definition file for sock-shop/cart: cart (weaveworksdemos/cart:0.4.0 -> index.docker.io/weaveworksdemos/cart:master-129ef150).
7) updating pod controller for index.docker.io/weaveworksdemos/cart:master-129ef150: Could not find image name
8) Failed: updating pod controller for index.docker.io/weaveworksdemos/cart:master-129ef150: Could not find image name
```

It seems that the image that Flux is trying to retrieve is "index.docker.io/weaveworksdemos/cart", instead of "weaveworksdemos/cart"

**Comment by nustiueudinastea** [comment]
Related to https://github.com/microservices-demo/microservices-demo/issues/586

**Comment by paulbellamy** [comment]
command ran is: `fluxctl release --service=sock-shop/catalogue --update-all-images`

**Comment by nustiueudinastea** [comment]
The k8s manifest for the deployment: https://github.com/microservices-demo/flux-staging-deploy/blob/master/deploy/kubernetes/manifests/cart-dep.yaml
