### ISSUE TITLE
Bus subscriber blocks on Apply

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#420]
The NATS bus which conveys RPCs to where they need to go, includes a loop that deals with relaying requests and responses. The idea of having a loop was simply to be able to use a single (wildcard) subscription, and thus avoid complicated {set,clean}up.

However, because the loop deals with one request at a time, it can block subsequent requests indefinitely. For almost everything, this is not a problem, since most RPC calls should be quick. But `Apply` (new definitions) can take an arbitrary duration to complete.

This problem likely shows up as RPCs (e.g., ping) timing out while a release is in progress.

**Comment by paulbellamy** [comment]
nice find!

**Comment by awh** [comment]
I believe it was also possible to trigger this by clicking around in the UI quickly, resulting in a backlog of requests to list services.
