### ISSUE TITLE
Weave Cloud interface issue

### ISSUE THREAD

**Issue by nustiueudinastea** [weaveworks/flux#424]
In the Weave Cloud dashboard, in the Deploy section, services have a version value of "undefined/undefined/undefined:undefined". 

<img width="734" alt="screen shot 2017-02-03 at 17 29 47" src="https://cloud.githubusercontent.com/assets/588327/22642630/3d20cc92-ec64-11e6-9105-774d8aaa80fe.png">

**Comment by paulbellamy** [comment]
This was just fixed this morning with: https://github.com/weaveworks/service-ui/pull/183/commits/2ace3253382438643bf7aa7d88fd3edad23f8bdb
