### ISSUE TITLE
releasing via the ui hangs

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/flux#426]
e.g. trying to release a different image of `prose` on weave.cloud, begins the release, but then hangs. It looks like the response format may have changed, without the UI keeping up?

**Comment by paulbellamy** [comment]
Ah, serviceSpec vs serviceSpecs, looks like.

**Comment by foot** [comment]
Ah! The servicespecs was fixed a few days ago... https://github.com/weaveworks/service-ui/commit/c0c0d74ea2bb6f0f196ed653e651c76290b2964d

Can you still repro? After refreshing? Maybe our cache busting ain't perfect..

**Comment by foot** [comment]
I missed a ServiceSpec! My bad.
