### ISSUE TITLE
Separate Release records and Jobs

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#438]
The `Job` table holds ephemeral records of different kinds of job to be run, and currently includes (in release jobs) information about releases.

We want the records of releases to be more persistent, though; and, to be able to store information about the result of a release, for instance, which is not represented in the jobs table.

The Job table needs all of the things necessary for selecting, dispatching, and (potentially) recovering jobs:

```
Job
  ID -- PK
  Instance -- multitenancy

  Queue  -- )
  Method -- ) dispatch
  Params -- )

  ScheduledAt -- queuing (delayed jobs)
  Priority -- queueing
  Key -- queueing (deduplication)

  Claimed --   ) healthcheck / recovery
  Heartbeat -- ) 

  Finished -- ) GC and reporting
  Error --    )
```

The Release table records everything about a release:
```
Release
  ID -- PK
  Instance -- multitenancy
  Spec -- ReleaseSpec
  Log -- possibly incomplete log
  Result -- possibly incomplete result
  StartedAt --  ) for audit
  FinishedAt -- )
```

There is a chicken and egg problem: does the job just update the release, or does the job create the release? (Alternatively put, if I want to check the status of a release, where do I check?)

I am inclined to make it the job of the .. er, job .. to create the release. So, if you're checking its progress, you

 1. look for the release record and look for the job record;
 2. if a release record and no job record, it has been completed
 3. if a job record and no release record, it has not been started yet
 4. if both, it's in progress
 5. if neither, there's no such release

**Comment by paulbellamy** [comment]
Job should just update the release, and Job.Params should just point to the release ID.
So, to schedule a new release, you would create the release, then put the job to actually do the work, with the release id as it's only param.

Then, you always look at the `releases` table to find a release, whether it is started or not.

**Comment by squaremo** [comment]
Yeah, that's the other way around. That alternative has its own trickinesses:

 - if the job doesn't run for whatever reason, you end up with orphaned, never-to-be-completed release records. I guess these can be excluded in queries, and GCed if never started.
 - we won't be able to rely on deduplication (of jobs) to avoid repeating work

Neither of these are insurmountable of course.

**Comment by paulbellamy** [comment]
> if the job doesn't run for whatever reason, you end up with orphaned, never-to-be-completed release records. I guess these can be excluded in queries, and GCed if never started.
It's also an accurate record of what happened.

> we won't be able to rely on deduplication (of jobs) to avoid repeating work
true.. that does favour the other way.

My preference for always creating a release is primarily that it makes querying code much simpler, and makes the job params simpler, while having a link from jobs to the release they processed. To do recovery of jobs, you'd have to update the job with the release ID it created also (not a big deal).

**Comment by squaremo** [comment]
> To do recovery of jobs, you'd have to update the job with the release ID it created also (not a big deal).

Hmm yeah, the params of a job should really be immutable (new params should be a new job). This makes me think I have gone down the wrong path.

**Comment by squaremo** [comment]
OK I change my mind .. requesting a release creates the release record, then a job to run the release.

This gives rise to a secondary problem: how do you report on what's happening with a release? We can see whether it has started, and whether it has completed, from the Release record. But the client expects to be able to tell if the job itself is underway, stalled or whatever, so we'll have to do something tricky.

**Comment by sambooo** [comment]
Flux no longer has any database concerns.
