### ISSUE TITLE
`/api/ping` returning 500s when fluxd not connected to instance.

### ISSUE THREAD

**Issue by foot** [weaveworks/flux#440]
We're expected 404s! See

https://github.com/weaveworks/service-ui/issues/256.

We'll change the ui so any error code === no connection too.

**Comment by paulbellamy** [comment]
404 is a bit of a weird status code as well, because the route exists, it just isn't connected...

**Comment by foot** [comment]
True!

But if we wanna change this away from 404 too i would +1, 404 look like errors to the browser.

200 `{ connected: false }`, or some other obscure http code that has something to do w/ some backend thing not being connected in the <400 range. 👍
