### ISSUE TITLE
Support partial configuration / configuration from browser.

### ISSUE THREAD

**Issue by foot** [weaveworks/flux#441]
`/api/flux/v4/config` returns helpful little stubs for `registry.auths` and `git.key`.

In the browser we wanna let the user update certain fields e.g. git branch without having to re-enter auth/key creds if present.

Sooo! Some kind of partial update mechanism would be really neat.

Perhaps using `PATCH` instead of `POST` or by ignoring missing keys by default anyway. In this case we'd use `registry: auths: null` to explicitly clear them perhaps.

**Comment by paulbellamy** [comment]
Could do a similar config update mechanism to git, with a path.

e.g. `fluxctl set-config foo.bar=baz`

**Comment by foot** [comment]
We want to be able to:
- Update just one field, like git.url without updating git.key.
- Add a new auth entry without modifying the existing ones.
- Remove an auth entry without modifying others.

It would be cool to be able to do a partial config update of multiple fields in a single atomic request just-in-case, but then we'd have to come up w/ some adding/removing/modifying protocol I think. Paul's suggestion of path style updates is simpler and good enough, though we'd maybe have to do 3-4 requests sometimes.

`GET /api/config?path=git.URL`
`PUT /api/config?path=git.URL` body: `git@github.com/derp`
`DELETE  /api/config?path=registry.auths.https://index.docker.io/v1/`

?

**Comment by philwinder** [comment]
@foot: I'll do this today. API looks good. Need to do some investigation, but shouldn't be too difficult.

**Comment by foot** [comment]
Cool! 

To simplify path parsing (e.g. `registry.auths.https://index.docker.io/v1/` is tricky) we could make it more JSONy:
`GET /api/config?path=["registry","auths","https://index.docker.io/v1/"]` (but encode that path value into a %20 etc mess)

Also (I'm not completely sure about this), to keep the whole API more jsony and extensible it might be nice to wrap things in a layer of JSON object: 

`GET /api/config?path=["git","URL"]` -> `{"value":"git://github.com/derp"}`
`PUT /api/config?path=["git","URL"]` body: `{"value":"git://github.com/derp"}`

**Comment by philwinder** [comment]
The array mapping feels a bit clunky. What don't you like about: 
`/api/config?path=registry.auths.https://index.docker.io/v1/`
You'd still have to URL encode the `[]` version.

If you're worried about the complexities in the url parameter, then maybe just put it in the JSON?
```
{
  "key": "registry.auths.https://index.docker.io/v1/"
  "value":"git://github.com/derp"
}
```
The real issue here is the use of a value in the key.

**Comment by foot** [comment]
In the URL is fine. It just depends on how generic we wanna make the path stuff I guess. If we make it a bit clever so that is can understand that anything coming after `auths` is a key then we're gold. Otherwise as `.` is the delimiter the path could generically be interpreted as:

```
{
  "registry": { 
    "auths": { 
      "https://index": {
        "docker": {
          "io/v1/": <value>
        }
     }
  }
}
```

This is avoided if we break the path up more explicitly in a json array.

**Comment by philwinder** [comment]
Ah of course. Thank you for spelling it out. Hmm. Ugly.

What about being verbose about this? This format would be the easiest for me to parse too, as it represents the structure of the configuration object.
```
{
  "registry": { 
    "auths": { 
      "https://index.docker.io/v1/": <value>
  }
}
```

**Comment by foot** [comment]
Yep, that works fine! Kind of like a patch, neat.

For `GET`ing it might be a bit clumsy? I'm not sure how'd you'd express that..

**Comment by philwinder** [comment]
Yes, same for deleting... Still not quite right.
How about good ol' REST?
```
GET /api/config/registry/auths/https\:\/\/index\.docker\.io\/v1\/
PATCH GET /api/config/registry/auths/https\:\/\/index\.docker\.io\/v1\/
<value>
DELETE GET /api/config/registry/auths/https\:\/\/index\.docker\.io\/v1\/
```
You still have the ugliness, but at least its semantically correct.

**Comment by foot** [comment]
Yep that works fine for us.

I'm not sure what the "correct", encoding scheme is for values in the path part of the URL.
GET `/api/config/registry/auths/https%3A%2F%2Findex.docker.io%2Fv1%2F` maybe? using `encodeURIComponent("https://index.docker.io/v1/")`

Only doing a patch could work. e.g.

```
{
  "registry": { 
    "auths": { 
      "https://index.docker.io/v1/": null
  }
}
```

would remove that auth? I think this would work for all the cases though.

**Comment by philwinder** [comment]
Can I ask whether you need a GET method?

I think that's the crux. Since if you need the GET, it's just as easy to implement the delete. If you don't need the GET then I don't need any code to parse/interpret path.

**Comment by foot** [comment]
The GET as it currently exists is fine for us. 

So just implementing a PATCH endpoint sounds like it will do the trick.

**Comment by philwinder** [comment]
@foot Sorry to bother again, but I've found that the PATCH won't work. Because when you send a partial JSON body, Go parses than and interprets missing fields as an empty string. 

Hence, there is no way to tell whether you intentionally wanted to delete the value in the field, or the field is just missing a value.

I've had a further idea which would result in no API changes. You say you're ok with the get. And the initial problem was the key and auth's bit.

Maybe the simplest thing is to fix that problem. I could add some code to the current set to say that if the <any of the hidden fields> are not set, then keep the old values in the new set-config.

**Comment by philwinder** [comment]
@paul Can you provide an example on how you would like to use the CLI to update the setting: `registry.auths.https://index.docker.io/v1/`? The periods in the address will be interpreted as keys.

**Comment by foot** [comment]
Oh you can't easily have a generic JSON structure in go? :(

Option 2 is fine though, any of the path options we explored would work!

**Comment by squaremo** [comment]
> `DELETE /api/config?path=registry.auths.https://index.docker.io/v1/`

Delete works fine for getting rid of credentials; but the analogous Set isn't really appropriate, or needs special treatment at least. Docker registry credentials are stored in the way docker stores them in ~/.docker/config.json, which is idiosyncratic (glom them together and base64 encode, or something). You can't just set a username and password*.

*Unless we change how it's treated in the backend.

**Comment by foot** [comment]
We can glom and base64 encode in the browser when adding a new set of credentials no worries.

We'd go for adding and deleting creds in the UI i think. No modifying.

**Comment by foot** [comment]
So the UI will change a little, to add creds we'll introduce a dialog asking for the username/pass. Then show a list of available creds w/ little delete buttons next to them perhaps.

**Comment by squaremo** [comment]
> We can glom and base64 encode in the browser

No doubt. But for the command line, we're asking someone to do that themselves. (or that the client treats those paths specially, I suppose).
