### ISSUE TITLE
Flakey NATS tests

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#445]
E.g., in this build https://circleci.com/gh/weaveworks/flux/1046

Quite irritating, since it means clicking rebuild all the time.

**Comment by squaremo** [comment]
Fixed by #446 (tom some extent ..)

**Comment by squaremo** [comment]
Also https://circleci.com/gh/weaveworks/flux/1074, though (I believe) we see this variety much less often

**Comment by philwinder** [comment]
Continuing to occur: e.g. https://circleci.com/gh/weaveworks/flux/1344

**Comment by sambooo** [comment]
There is no longer any NATS in this repo.
