### ISSUE TITLE
Ignore kubernetes addons

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/flux#459]
See: https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/README.md

> Each add-on must specify the following label: `kubernetes.io/cluster-service: true`.

We should just ignore them because they can't be changed via the api, only by modifying files on the server.

**Comment by squaremo** [comment]
https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/addon-manager/README.md

Looks like any of the labels `kubernetes.io/cluster-service=true`, `addonmanager.kubernetes.io/mode=EnsureExists`, or `addonmanager.kubernetes.io/mode=Reconcile` indicates an add-on. (The first of these is apparently the "old way").
