### ISSUE TITLE
bootstrap/save functionality

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/flux#460]
Will need fluxd changes to AllServices, so that it returns enough information to generate a manifest.

Undecided is whether this should commit straight into git, or should save them locally, then let the user commit and push them.

If we are doing it locally, we should detect and warn the user if it isn't in a git repo..

**Comment by paulbellamy** [comment]
Discussion pointed out that kubectl might just be used to generate the manifests.

**Comment by squaremo** [comment]
I would start with outputting them locally (as a minimal useful thing).

We would have to strip out a lot of the detail that otherwise comes with manifests when you ask kubectl for them.

**Comment by paulbellamy** [comment]
Also, we don't need to do git repo detection at all.

**Comment by paulbellamy** [comment]
Discussion in the rfc doc indicates that `fluxctl save` is a good name for this.
