### ISSUE TITLE
Expand synchronisation loop to include more than just deployments

### ISSUE THREAD

**Issue by philwinder** [weaveworks/flux#461]
Needs more clarification.

Kubernetes manifests can change in a number of ways. We currently support some, but not all:
- (supported) An image is updated
- (supported) The manifest is altered (e.g. change arguments)
- A manifest is deleted
- A manifest is added

Hence, we need to expand the sync loop to:
- [ ] Delete resources when manifests are deleted
- [ ] Add resources when manifests are added

Also, we currently only consider deployments in our reconciliation loop. We now need to also consider all other types of k8s resource. Is there a generic way in which we can do this? E.g. 
- [ ] config maps
- [ ] services
- [ ] secrets

This will involve Flux "services". There was a time where we used the term service to abstract the idea of a service for use with other orchestrators. However, this is no longer a long-term goal (we're only suportting k8s for now) and the naming of flux services conflicts with the definition of a K8s service.

Hence, consider the alteration or removal of the service abstraction as a part of this work.

**Comment by paulbellamy** [comment]
Depends on https://github.com/weaveworks/flux/issues/463

**Comment by squaremo** [comment]
See #465 on whether fluxd will handle things other than deployments and replication controllers. (To save a click: no it won't, but it's only a small part of this larger effort to adapt it).

**Comment by squaremo** [comment]
#489 added a protocol to the v5 endpoint for deleting or applying resources, and reimplemented Apply in terms of it.

**Comment by squaremo** [comment]
The sync loop will `kubectl apply` _all_ resources it finds, effectively implementing this so far as `kubectl` allows.

One exemption is deletions: this is implemented, but not "switched on", because it was too scary to do so in our own use of Flux. With some further finessing (e.g., having grace periods for deletion) that would be less of an issue.
