### ISSUE TITLE
React to Changes in Git

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/flux#463]
- Entails notifications of git changes
- Via hooks only
  - (Nice-to-have) provide an image (based on git-sync) for any repos which don't support hooks. users would run that themselves. Assumption is that, if they are using a custom git server they will not be keen on a hosted CD solution, so they will be self-hosting flux anyway.
- Option to delete/not delete

`fluxctl on|off`, and warn before deleting stuff where appropriate. Default may be to not delete, and only delete if the user passes --delete?

Kubernetes manifests can change in a number of ways. We currently support some, but not all:
- (supported) An image is updated
- (supported) The manifest is altered (e.g. change arguments)
- A manifest is deleted
- A manifest is added

Hence, we need to expand the sync loop to:
- [ ] Delete resources when manifests are deleted
- [ ] Add resources when manifests are added

**Comment by paulbellamy** [comment]
We may want to look at using the existing python kubediff script. Either calling out to a modified version of it, or porting it to go (look at https://github.com/google/grumpy)

**Comment by squaremo** [comment]
I would start by ignoring apparent deletions, rather than being able to switch deletions on and off, for the purpose of breaking things into smaller chunks.

**Comment by paulbellamy** [comment]
Yes. Also, per discussion with @lukemarsden, hooks have to be best effort, as katacoda (and probably others) use self-hosted gitlab repos.

**Comment by squaremo** [comment]
> hook installation has to be best effort, as katacoda (and probably others) use self-hosted gitlab repos.

As in, installing a hook is an integration with GitHub and will have to be done manually if you're not using GitHub? :+1:

**Comment by paulbellamy** [comment]
and/or fallback to polling for new commits if it isn't github.

**Comment by squaremo** [comment]
> and/or fallback to polling for new commits if it isn't github.

Am I wrong about being able to put hooks in vanilla git repos?

**Comment by paulbellamy** [comment]
No, I think you can, just not have cloud do it automatically.

**Comment by paulbellamy** [comment]
Oh, I was misunderstanding the above, I thought you meant webhooks, you meant just have a git hook script that calls `curl`. There is no `post-push` hook, the closest is a server-side `post-receive` hook, or a `pre-push` (which is called before anything is transferred so would need to have some delay).

I had assumed you would implement that by having a job which periodically fetches and does a `curl` if it has changed.

**Comment by squaremo** [comment]
Some day soon we will reinstate the hooks (which will be a service-only feature, at least to start). In the meantime, syncing with git is done and dusted.
