### ISSUE TITLE
Check whether fluxd handles more than deployments

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/flux#465]
It should also handle configmaps, secrets, services, etc...

**Comment by squaremo** [comment]
The code looks at whether the supplied definition (a bunch of bytes) parses as a Deployment or ReplicationController, so it can decide how to roll it out. Anything else will provoke an error.

It also looks up the "pod controllers" (deployments or replication controllers) in each relevant namespace, and will refuse to apply a definition that doesn't correspond.

This code would be fairly easy to open up to other kinds of resource; the far greater job would be changing everything else (user interface, and so on) to other kinds of resource.

**Comment by squaremo** [comment]
Checked.
