### ISSUE TITLE
Implement delete in fluxd

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/flux#468]
So fluxsvc can tell it to delete manifests, not just kubectl apply

**Comment by paulbellamy** [comment]
Maybe doesn't need to take a manifest, just type namespace and name.

**Comment by paulbellamy** [comment]
Let's do it in a batch with apply + delete as a single new rpc method.

**Comment by paulbellamy** [comment]
We should detect if fluxd supports this method, or something, and fail gracefully.

**Comment by squaremo** [comment]
Fixed in the PR #489 .
