### ISSUE TITLE
FIle to say which services to ignore

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#469]
`.fluxignore` (in the repo) lists patterns for services (resources?) that `fluxctl`, syncing and automation should ignore.

**Comment by squaremo** [comment]
How do the things in here get expressed?

While we are still concerned with "services" in flux, it is easy -- line items are services. However:

 * we plan to include other kinds of resource, like config maps
 * if it's going in a file in the repo, it seems least surprising (and easiest to maintain) if it refers to the files in that repo.

Perhaps we really want two features:

 1. Protect a running service (or more generally, resource) from deletion, if it's not defined in the repo.
 2. Ignore specified files that are in the repo, but aren't supposed to be made into resources in the cluster.

`Lock`ing a service already protects it from automation and fluxctl release; it could also protect it from sync. The question is whether that information is better in the repo, or in the service. It can't be attached to file, since it will not always refer to something that has a file. On the other hand, we don't want to accumulate garbage in the instance's config, where garbage is records of locked things that don't exist any more.

**Comment by squaremo** [comment]
Upgrading this to `size/medium`, based on my uncertainty of how it should work. If someone can write down a concise specification, we can downgrade it again ...

**Comment by philwinder** [comment]
Discussed on call.

Use cases:
1. Manually started on the cluster, don't want it to get deleted because it's not in the repository.
1.a. Temporarily testing a new image.
1.b. Running a container to access a DB.
2. Manifest in the repo that you don't want to be k8s.

Both use cases can be solved by parsing a k8s annotation in the manifest.
```yaml
metadata:
  annotations:
    "flux.weave.works/ignore": "true"
```
(Open to suggestions on the annotation name. Standard annotations keys seem to be a URL. And the value is a string type.)

Then the diff tool would need to parse and check whether the manifest in the cluster or the repository has an ignore flag. If either of them have an ignore flag, then the resource is skipped.

**Comment by squaremo** [comment]
> If either of them have an ignore flag, then the resource is skipped.

I'm not sure about this, so I made a table.

```
cluster \ repo | ignored       | not ignored   | absent
---------------+---------------+---------------+------------
 ignored       | nothing       | [1]           | nothing
 --------------+---------------+---------------+------------
 not ignored   | [2]           | update        | delete
 --------------+---------------+---------------+------------
 absent        | nothing       | create        | [3]
 --------------+---------------+---------------+------------
```

[1] The file does not have the annotation; the cluster resource does. How would this happen? Maybe if you created the resource from the file, then applied the annotation to it. In which case you probably want to leave it alone. But: you may have removed the annotation from the file to remove that protection, so it should be applied. Hm.

[2] The resource does not have the annotation; the file does. Again, the annotation was added to the file, or removed from the resource, after the fact. Taking [1] as a model, the difference can be ignored, or the resource can be updated to match the file.

[3] How did you even get here.

**Comment by philwinder** [comment]
Yes good points. That's why I thought the logic "if either have an ignore, nothing will happen to that resource" is the simplest thing to do.

**Comment by squaremo** [comment]
It's definitely the simplest thing to do; and, there are remedies if if is not what you want, although you have to reach outside flux to use them.

Let's bimble through some examples ..

Say I have a deployment that I want to take out of sync for a while, so I can mess around with it manually. I most likely want the failsafe to be that if the cluster is recreated, the deployment goes back in sync -- i.e,. I want to leave the file in the repo as-is. Therefore: leave resources marked as ignore alone, even if not so marked in the repo.

Other way around:

I have a manifest in the repo which corresponds to a running resource, but I have decided to take it out of sync permanently, so I add the annotation to the manifest file (but not to the cluster resource). If I now remove it from the cluster, it will not be created again. If I recreate the cluster from the files, it will be run in the cluster but then be ignored.

What should happen if I remove it from the repo though? The file is gone; the cluster resource does not have the annotation; so it will get deleted on the next sync. I honestly can't decide if this is more or less surprising than leaving it alone!

**Comment by philwinder** [comment]
Yes, that is what will happen. And given the logic, is expected.

Regarding the bottom question: deletion. That is more part of the deletion logic than it is the ignore logic. If the deletion policy states that if a file doesn't exist in the repo, it will be deleted from the cluster, then that is what will happen.

So that is not really a worry for the ignore logic.

**Comment by squaremo** [comment]
> And given the logic, is expected.

My aim was not to figure out what was expected given the logic we are ourselves proposing. It was to figure out what a person using it, not party to this discussion, might reasonably expect.

> Regarding the bottom question: deletion. That is more part of the deletion logic than it is the ignore logic. If the deletion policy states that if a file doesn't exist in the repo, it will be deleted from the cluster, then that is what will happen.
> 
> So that is not really a worry for the ignore logic.

It certainly is a worry for the ignore logic if someone might reasonably expect to use the ignore logic to protect something from deletion, but find that it is deleted regardless. That's arguably the case: I am told that adding the ignore annotation to a resource will stop it being synced; so I add the annotation to the file, then later remove the file, expecting that since I said it was ignored, nothing will happen. But it's deleted.

**Comment by philwinder** [comment]
:+1:
> expecting that since I said it was ignored, nothing will happen. But it's deleted.
If they added the annotation to the _running_ manifest, then it would not be deleted.

I.e. add the annotation to anything that you want flux to ignore.

**Comment by squaremo** [comment]
> If they added the annotation to the running manifest, then it would not be deleted.
> I.e. add the annotation to anything that you want flux to ignore.

Now the user has to have a model in their head about where to add the annotation to get the right result, rather than a simple rule. You may say "add the annotation to what you want to ignore" is a simple rule -- but this ignores the fact that if you add it to the file, and it didn't exist in the resource, it will be propagated, whereas this _won't_ happen in other circumstances. See what I mean?

Maybe it's possible to explain it in a different simple rule.

**Comment by squaremo** [comment]
> but this ignores the fact that if you add it to the file, and it didn't exist in the resource, it will be propagated,

Actually is that even correct? If you add it to the file, it'll get ignored, so not synced, and the resource will stay the same.

**Comment by philwinder** [comment]
There's probably other ways to do it, but probably not a simpler way. Because whether we like it or not, there are two sources of truth. Purely because the user can do things manually on git or on the cluster.

But yes, if you add the annotation to the file in git and there is nothing on the cluster, the result will be still nothing on the cluster. Because you've told flux to ignore that file.

And by ignore that file, I think in reality that would mean, ignore that "object id". However it is parsed.

**Comment by squaremo** [comment]
Imaginary documentation (does this cover it?):

### Ignoring resources

Sometimes you want flux to ignore a resource for the purpose of sync. For example,

 * You want to create an ephemeral deployment that won't be deleted if there's no manifest in the repo; or,
 * You want to temporarily suspend changes to a particular resource while you troubleshoot a problem; or,
 * You want to commit a manifest that you don't want to be created in the cluster.

To ignore a resource or manifest, give it the annotation `flux.weave.works/ignore=true`. If you do this to a resource (e.g., with `kubectl annotate ...`), it won't be affected if the corresponding manifest is different or absent. If it's applied to a manifest in the repo, the corresponding resource won't be updated or created.

**Comment by philwinder** [comment]
Yes, almost perfect. The I reword the last part with a rule, then some examples.

Once annotated, flux will not alter any repository or cluster resource with that `namespace/name` id.

For example, If you annotate a resource in the cluster, flux will completely ignore that resource, even if you make changes in the repository. If you annotate a file in the repository, the corresponding cluster resource won't be updated, created or deleted.

**Comment by squaremo** [comment]
This was implemented as part of "git sync" and made more visible in #618.
