### ISSUE TITLE
Use caching k8s client in fluxd

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#471]
Using the REST client, we run into throttling quite easily, as our queries generally scale with the number of objects (namespaces, as it happens). Usually this ends up meaning concurrent queries begin to time out.

If we were to use the mechanisms in the k8s to listen to changes and "reflect" those into a locally cached model, concurrent queries would not add to the k8s query rate, and would not be throttled.

A possible downside is that the cached model can be out of date. It may be useful to stamp query results with the version of the model, if we can, to see if this is a problem in practice.

**Comment by sambooo** [comment]
I think #46 covers this.
