### ISSUE TITLE
Allow users to specify async services

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/flux#476]
(In addition to flux by default). For example, we could add authfe, which would stop the EOF error when releasing it.

**Comment by squaremo** [comment]
I think every service should be async, in the sense that we only `apply` the new config before returning. We should then check with the platform whether the rollout has finished, if we need to synchronise on that.

**Comment by squaremo** [comment]
> if we need to synchronise on that.

Do we need to synchronise on that? I really wonder. It's possible that an application fails, but in general, we won't know (and kubectl wouldn't know either). We _may_ be able to report the rollout or health status of a service in the response to ListServices commands, but I'd expect people to have monitoring to tell them at least the latter.

**Comment by squaremo** [comment]
Implementing Sync, and reimplementing Apply in terms of Sync (as in #489), means every apply action is asynchronous.
