### ISSUE TITLE
Automatic fluxd upgrades

### ISSUE THREAD

**Issue by awh** [weaveworks/flux#477]
There are a variety of circumstances in which it would be useful for us to be able to cause remotely deployed fluxd instances to upgrade themselves:

* Roll out critical bug fixes
* Enable new platform functionality
* Enable us to deprecate old APIs

Ideally this will have the usual 'best-practice' features for remote software updates e.g. ability to conduct phased roll-outs and transactional application that tests that the updated fluxd is working before removing the old one.

**Comment by squaremo** [comment]
Some things to figure out:

 * If fluxd is represented by a file in the repo, do we need to update that? (yes)
 * How do we know which file?
 * If fluxd is _not_ represented by a file in the repo, what do we do

**Comment by sambooo** [comment]
This is no longer a Flux concern. The desired behaviour is implemented in the Weave Cloud launcher.
