### ISSUE TITLE
Include cause of a release in release info

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#481]
It is helpful to know why a particular was run -- was it automation, and if so, what triggered it? Was it a person, if so who?

**Comment by squaremo** [comment]
The information is included in the release record in #495.

**Comment by philwinder** [comment]
I think the information is available in the event. It contains the release type, the user and a message. It's just a matter of improving how these are presented. E.g. #480
Recommend closing and reopening with specific issues to present how and what information should be presented in the history and the slack integration.

**Comment by squaremo** [comment]
Including it in the event and notifications is adequate.
