### ISSUE TITLE
Cannot distinguish information kubeservice output from errors

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#490]
We use a script `kubeservice` to find the services that a deployment (or replication controller) supplies pods to. What `kubeservice` _does_ is find the services given a particular deployment (or rc) file; what we _want_ is to find all the services, and for each, the deployment (or rc) files. This entails scanning the files n^2 times; but never mind, that's not why we're here.

The problem at hand is that kubeservice operates this way:
 1. try to load the file specified; if it's not a deployment or replication controller, exit with an error.
 2. for every other file in the directory, try to load it; if you can't output an error and continue. If the file is a service, add it to the list of candidates.
 3. for each candidate service, see if it matches the given deployment or rc and output it if so.

This is fine for the intended use, since the result will be either success: zero or more service names output; or failure, the given file was bad.

But in our use, kubeservice is invoked for every file, and we cannot distinguish between failing because a file isn't yaml (in which case, move on to the next) and failing because there's a "real" problem.

This came up because a user had an invalid yaml file in their repo, and flux would balk at it on every run, and report 0 services found.

**Comment by philwinder** [comment]
If we port kubeservice to use `client-go`, then this would be an easy fix. Probably a good time to do this?

**Comment by philwinder** [comment]
Is being ported to go as part of git-sync. So this should be fixed then.

**Comment by squaremo** [comment]
This problem was obviated during the git-sync renaissance, when we rewrote the resource parsing in Go.
