### ISSUE TITLE
No way to annotate deployment decisions

### ISSUE THREAD

**Issue by jml** [weaveworks/flux#501]
I just disabled automated rollout of consul to our servers for Very Good Reasons. There is nowhere in the flux UI to state these reasons, and thus no way to discourage my teammates from re-enabling automated deployments. (And why wouldn't they? Auto deployments are a Good Thing.)

This has the potential to cause an outage for my end users.

**Comment by squaremo** [comment]
In terms of how this gets used, it sounds like you'd want something along these lines:

    fluxctl deautomate --service=consul --message='Deautomated until we can sort out such and such'

or the equivalent in web UI; then, when someone looks at the service in the UI, it'll show that message (and where there's not the space, give an indication that there is such a message).

What other aspects to this are there -- I guess we'd want to record the message in the (de)automate event, so it shows up in history. Would locking the service at the same time be appropriate (i.e., requiring someone to unlock it before it could be changed even manually)?

**Comment by jml** [comment]
Am not 100% sure what locking is about.

**Comment by squaremo** [comment]
> Am not 100% sure what locking is about.

"Nothing can be updated until this is unlocked, whether automated or not"

**Comment by jml** [comment]
Thanks. In that case, I definitely think it should be possible to provide a reason for locking that's visible in the UI. Providing *that* functionality might cover this case, assuming it were discoverable enough.

**Comment by jml** [comment]
I think allowing a message on the lock would be an improvement. Saying _who_ set the lock and when they did it would also be very useful.

**Comment by squaremo** [comment]
One can provide a message (and user, which defaults to the git user + email) for mutating operations now. The message is recorded as the git summary, and the user is recorded as the commit author if `--git-use-author` is set on the daemon.

In addition, when you lock a service, it sets a policy on the resource, recording the message. The significance of it being a policy is that it shows up as an annotation, and in the output of the list-controllers API, so can be displayed in UI.

**Comment by squaremo** [comment]
https://github.com/weaveworks/service-ui/issues/1022 deals with showing these in the web UI.
