### ISSUE TITLE
History API response too big for integrations

### ISSUE THREAD

**Issue by davkal** [weaveworks/flux#503]
At Kubecon, loading the history on socks shop took forever, repsonse sizes of >1MB.
For most timelines, the `[{Stamp, Message},...]` is enough.

**Comment by paulbellamy** [comment]
Or, could trim to some time-span/number of messages, and paginate.

**Comment by davkal** [comment]
> Or, could trim to some time-span/number of messages, and paginate.

The Cortex UI use case is to show the flux history under the timeline chart.

There are some technical limitations:

- the graph can only be rendered once (updates look bad), which means the history should be available already and should not be queried at the same time
- loading the history took >30sec, limited by bandwidth

For that reason I think a "simple" history would be great idea. The date-based pagination would be a cherry on top.

**Comment by davkal** [comment]
`simple=1` has no effect. Should be `simple=true`.
