### ISSUE TITLE
in-cluster docker builder agent

### ISSUE THREAD

**Issue by rimusz** [weaveworks/flux#505]
would be great to have an optional docker builder agent running in-cluster which could be used to build docker images and push to docker registry, that would eliminate to have any other CI/CD system which could do that.

**Comment by rimusz** [comment]
cc @errordeveloper @lukemarsden

**Comment by paulbellamy** [comment]
Sounds cool. Might be out of scope for flux, though?

**Comment by rimusz** [comment]
I do not think it is out of scope for flux, could be an optional, having flux why I do I need some CI/CD system to use with? I would love one nice package what does everything.
And when it is optional it will fill rest of setups too. 
I love to build docker images in my Kubernetes cluster, keep it close heh, that brings speed to push to my GCR/ECR registry then.

**Comment by sambooo** [comment]
The desired behaviour is out of scope for Flux. Users should use an existing image builder and push images, after which point Flux will deploy them.
