### ISSUE TITLE
Flux generate does not 400 when no token provided

### ISSUE THREAD

**Issue by BenHall** [weaveworks/flux#520]
If I don't provide a service token, I expect the yaml generator to fail.

Current behaviour when using Flux 
```
$ curl https://cloud.weave.works/k8s/flux.yaml?service-token=
> yaml blob returned and deployed but can't be used linked to Weave Cloud
```

Expected behaviour based on Cortex
```
$ curl -L https://cloud.weave.works/k8s.yaml?t=
code: BadRequestError
message: '(t|service-token): invalid service token provided'
```

**Comment by squaremo** [comment]
Thanks @BenHall. I've reported it as an issue in the internal system we use to generate those yamels. Closing here, but I'll try to remember to report back when it's sorted.

**Comment by errordeveloper** [comment]
Copying my comment from the internal issue:

> That's sort of desired, without the token you will get standalone version. This is the same for flux and scope, but there is no standalone cortex, hence there it's different.

> I'm open to alternative, e.g. an explicit standalone parameter.
