### ISSUE TITLE
have a story for integration testing using flux

### ISSUE THREAD

**Issue by lukemarsden** [weaveworks/flux#522]
luke [1:22 PM] 
how is flux supposed to work with integration tests? i.e. if the user wants to test a complete system before deploying, perhaps the user will try to get the CI system to spin up a complete system to test it before deploying it to prod, and in that case, is the CI system supposed to use flux? (edited)

[1:22]  
(i got asked this question after a talk i gave, and it’s been bothering me, because i didn’t have a good answer)

michael [1:22 PM] 
We are not trying to address that scenario.

[1:23]  
Maybe one could come up with some way flux is helpful.

luke [1:23 PM] 
@michael right, but users will want to run integration tests

philwinder [1:24 PM] 
Old flux: no, you might as well just `kubectl create -f` and be done.
New flux: possibly. Procedure would be to point flux at a specific (new) branch and allow the git-sync loop do it’s stuff, then do tests.

michael [1:24 PM] 
Users want to do all sorts of things.

luke [1:25 PM] 
@philwinder mmm in that case flux really is just doing `kubectl create -f` for you

[1:25]  
I can get behind the answer being “run kubectl yourself in your CI to spin up an integration testing namespace” or suchlike

philwinder [1:25 PM] 
Errm. That’s all it does anyway. :troll:

luke [1:25 PM] 
haha!

[1:25]  
it does the changing-the-files thing too

michael [1:26 PM] 
How do you _think_ it should help people run integration tests? (edited)

philwinder [1:27 PM] 
I guess what might be nice is: `flux sync --revision=F8AC41`. Forcing the cluster to a specific revision. (edited)

[1:27]  
Then once verified that it’s up to date and stable, run your tests. (edited)

luke [1:27 PM] 
i suppose a feature whereby you could tell flux “deploy what’s in prod to a new, ephemeral, test-local namespace, except with what _would_ be deployed if i did this release”, then run my integration/smoke tests, then tear down the namespace could be useful for this scenario

michael [1:27 PM] 
If you can come up with a canonical way people run their integration tests in kubernetes, you could start from there to figure out how flux might help with that.

philwinder [1:28 PM] 
:point_up: Yes, this would be the first challenge. What scope are we talking about here? New containers? New clusters? New/altered manifests? (edited)

luke [1:28 PM] 
aye

[1:28]  
could be an interesting area to explore for future feature work, anyway

michael [1:29 PM] 
Sure, put it on the list.

**Comment by sambooo** [comment]
Closing as out of scope for Flux. The way to achieve what I think is being asked for here is to clone the repo Flux is pointed at, then run `kubectl apply -f path/to/yamls`.
