### ISSUE TITLE
`422 Nats timeout` when an instance does not have Flux configured

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/flux#530]
Discovered as part of the service-ui on-boarding improvements. When an instance does not have Flux configured, requests to the `/api/flux/v3/services?namespace=` route return 422s.

We are trying to use the presence of services to validate whether or not the user has Flux configured. If a user does not have Flux configured, we want to take them to a configuration page.

Since the timeout takes ~5 seconds, navigation appears very slow. I am currently working around this by validating whether or not the git repo credentials are present, which is not ideal since the user can have services present without a git repo configured.

Reproduce:
1. Create an instance
2. Navigate to /flux/dawn-lake-16/services

Expected:
Return an empty array to indicate no services are present.

Actual:
Calls to /services time out with `nats timeout`

**Comment by paulbellamy** [comment]
You probably want the `/api/flux/v4/ping` endpoint, which checks if the daemon is connected. Should return 404 NotFound, if the daemon is not connected, and No Content if it *is* connected.

If it is slow and timeout-ey (I suspect it will be), please post here, as it shouldn't be.

**Comment by jpellizzari** [comment]
@paulbellamy `/api/flux/v4/ping` is doing the same thing, but with a 500 instead of a 4XX. I still get a `nats: timeout` response body

**Comment by squaremo** [comment]
Unfortunately that is the nature of networks: you cannot tell whether something is never going to respond, or just taking its time to respond.

We *could* store connection state in consul, say, a bit like Scope does. But we would still have the problem that it would be out of date (the connection can go away without us noticing; messages can be delayed arbitrarily; etc.).

If you just want to record whether a daemon has *ever* connected (and therefore has been given correct configuration), that's relatively easy. We can distinguish between this and the case of "has connected, but apparently not so at the minute" in any way that's convenient.

**Comment by paulbellamy** [comment]
afaik, there is a heartbeat on the connection, so we could loosen the check to just "is there a tcp socket open to this daemon?"

**Comment by jpellizzari** [comment]
To add more context, the question we are trying to answer on the front-end is "Should we take the user to the intro/setup flow, or should we take them to their instance?".

> We can distinguish in the API between this and the case of "has connected, but apparently not so at the minute" in any way that's convenient.

I think this is a good approach. Could we add a key to the `/config` response body that will indicate that we have seen a daemon connect for this instance?

**Comment by squaremo** [comment]
#658 introduced a fast path for determining if the daemon is connected (the code has since migrated out of this repo).
