### ISSUE TITLE
Timeouts on calls that reach out to docker hub

### ISSUE THREAD

**Issue by philwinder** [weaveworks/flux#533]
Using docker containers that have a large number of tags causes the `get images/tags/manifests` calls to time out. E.g.
```
fluxctl list-images
Error: 500 Internal Server Error getting images for services: fetching image metadata for quay.io/weaveworks/fluxd: Get https://quay.io/v2/weaveworks/fluxd/manifests/master-f94fd3e: context deadline exceeded
```
This occurs after 10s, which indicates that it is due to a default timeout somewhere.

It could be in Weave Cloud's authentication layer, or it could be in Flux.

**Comment by philwinder** [comment]
# To recreate locally
1. Fire up the minikube
2. Build/run flux as normal
3. Apply the manifests from the `docker-timeout` branch on https://github.com/philwinder/flux-example
```
kubectl apply -f https://raw.githubusercontent.com/philwinder/flux-example/docker-timeout/helloworld-deploy.yaml
kubectl apply -f https://raw.githubusercontent.com/philwinder/flux-example/docker-timeout/helloworld-svc.yaml
```
4. Run the list images command on `helloworld` (no need to setup the config, we're just getting images):
```
fluxctl list-images --service=default/helloworld
```
You will receive some error depending on which point the timeout was cancelled. It could be tags, it could be manifests. Some examples:
```
== Error ==

Internal error: getting images for services: fetching image metadata for node: Get https://index.docker.io/v2/library/node/manifests/4.0.0-slim: net/http: request canceled

We don't have a specific help message for the error above.
```
```
== Error ==

Internal error: getting images for services: fetching image metadata for node: Get https://index.docker.io/v2/library/node/manifests/5.10.0-wheezy: net/http: request canceled

We don't have a specific help message for the error above.
```

**Comment by philwinder** [comment]
After increasing [timeout](https://github.com/weaveworks/flux/blob/master/registry/registry.go#L14) to 300s:
```
fluxctl list-images --service=default/helloworld
SERVICE             CONTAINER   IMAGE                         CREATED
default/helloworld  helloworld  index.docker.io/library/node
                                |   7-wheezy                  12 Apr 17 17:31 UTC
                                |   7.9-wheezy                12 Apr 17 17:31 UTC
                                |   7.9.0-wheezy              12 Apr 17 17:31 UTC
                                |   wheezy                    12 Apr 17 17:31 UTC
                                |   7-slim                    12 Apr 17 17:31 UTC
                                |   7.9-slim                  12 Apr 17 17:31 UTC
                                |   7.9.0-slim                12 Apr 17 17:31 UTC
                                |   slim                      12 Apr 17 17:31 UTC
                                |   7-onbuild                 12 Apr 17 17:30 UTC
                                |   7.9-onbuild               12 Apr 17 17:30 UTC
                                :
                                '-> 4-alpine                  07 Apr 17 17:42 UTC
```
This request took approximately 40s.
Note that subsequent requests take approximately 30s, which is interesting considering it's supposed to be using the cache.

**Comment by philwinder** [comment]
Notes: Potential todos:
- Does authfe also need a fix?
- The error messages are poor. Investigate parsing the errors from the docker library and result in a "we timed out" message
- Integration test to test that we can retrieve node tags/manifests.

**Comment by awh** [comment]
This is manifesting under git-sync in the form of automation delays, which persist until successive (failed) attempts have warmed up the cache.

Design doc to address: https://docs.google.com/document/d/1z3CqJaj8oiatIdNnxW2qbSg4WBf9lSHElUjyg9KVGP4/edit

CC @rade

**Comment by philwinder** [comment]
Fixed (from the user's perspective) by the new caching mechanism introduced in #633. However, the timeouts do still occur, we only allow 10s per image. After this all remaining requests for manifests are timed-out. This is by design, however. It allows other images time to get their data. It will be retried on the next cache refresh.

Also see #688, which is about suppressing the http fetch i/o timeout messages.
