### ISSUE TITLE
fluxsvc 500: Server does not allow access to get namespaces

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/flux#546]
Possible k8s 1.6 related?
```
ts=2017-04-21T09:07:55Z caller=server.go:468 instanceID=2504 method=AllServices error="getting namespaces: the server does not allow access to the requested resource (get namespaces)"
ts=2017-04-21T09:07:55Z caller=server.go:490 method=ListServices url="/v3/services?namespace=" took=98.605243ms status_code=500 error="getting services from platform: getting namespaces: the server does not allow access to the requested resource (get namespaces)"
```

**Comment by paulbellamy** [comment]
This will be that their fluxd is misconfigured. Could be due to a k8s 1.6 upgrade. Would be nice to have a way to display service-level errors to the user, so we could prompt them to fix it.

**Comment by paulbellamy** [comment]
See: https://github.com/weaveworks/service-ui/issues/460

**Comment by tomwilkie** [comment]
This seems to be the cause of the recent alerts; is it appropriate for flux to 500 in this case?

**Comment by squaremo** [comment]
> is it appropriate for flux to 500 in this case?

No, it is just a catch-all that has never been corrected. We have started using HTTP 422 for application level errors -- that is, when the request is reasonable, the server didn't encounter anything unexpected, but it couldn't be completed.

**Comment by paulbellamy** [comment]
Fixed by https://github.com/weaveworks/flux/pull/549
