### ISSUE TITLE
User cannot find out how fluxd is currently configured

### ISSUE THREAD

**Issue by foot** [weaveworks/flux#569]
In the new gitsync model the ui will generate kubectl commands for the user to run to start/configure fluxd.

The user probably would like to be able to find out which git repository fluxd is currently configured to use. Ways for the user to do this in order of ease:
 1. Show the git url in the flux/setting page
 2. Provide the kubectl command the user can run to find out which git repo flux is using:
    - `kubectl get pod --name-matches=fluxd --json|grep cmd`

**Comment by foot** [comment]
Arguments against 1):
  - The git url might be a sensitive and include user/pass: `git://user:pass@myrepo`
    - If they have kubectl access they should be allowed to see the user/pass
    - If they have access to cloud.weave.works/instance they shouldn't necessarily be able to see user/pass? It is not nice to share this stuff I suppose.
    - We could sanitize password.

**Comment by squaremo** [comment]
> It is not nice to share this stuff I suppose.

Exactly; in general we don't want to leak things that might include credentials. As a sidenote, `fluxctl save` is a bit problematic this way as well (so we may want to impose restrictions on its use, e.g., by making people have to explicitly enable it).

**Comment by squaremo** [comment]
I am coming around to the idea of supplying some of this in a `Status` method. We can parse URLs to sanitise them, or indeed, just provide "safe" details. And I'm sure it'll be handy to be able to sanity check the daemon's set up with `fluxctl status`, for the same reason it was before.
