### ISSUE TITLE
Incorrect fluxctl response on release error (git-sync)

### ISSUE THREAD

**Issue by philwinder** [weaveworks/flux#577]
**Git-sync branch only**

Issue with lack of an error message from a release.

To recreate, have an invalud git deploy key, but a valid repo, then release:
```
$ fluxctl -u http://192.168.99.100:30303 release --service=default/helloworld --update-image=quay.io/weaveworks/helloworld:master-a000002
Requesting release ...
Nothing to do
```
Message “nothing to do”, but actually an error:

 ```
ts=2017-05-23T11:36:10Z caller=loop.go:155 component=sync-loop err="pushing tag to origin: fatal: Could not read from remote repository."
```

**Comment by squaremo** [comment]
This also happens if you supply an image that isn't used in the service (it should give a result with "skipped"). But first things first.
