### ISSUE TITLE
Rewrite releaser for clarity

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#599]
The code in releaser.go which builds a record of what to do with each image/container is very difficult to follow, and therefore difficult to modify. It could do with a rewrite to clear things up (after writing a test to guard against regressions!).

**Comment by squaremo** [comment]
Sam, can this be closed, or is there more to be done do you think?

**Comment by sambooo** [comment]
There'll always be refactoring to do, this isn't a special case anymore :)
