### ISSUE TITLE
Kubernetes manifests in the repo

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/flux#600]
@rimusz has asked me if manifests in `deploy/standalone` are up-to-date, so I've checked and noticed that it points and [specific image tag and which has not been updated in](https://github.com/weaveworks/flux/blob/8790c1dcf5027397684e237b276cf99b2e59dd1a/deploy/standalone/flux-deployment.yaml#L30). I am also not sure why memcache manifest is included there.

If we think that there should be manifests in the repo, we can keep them up to date by periodically syncing with launch generator, otherwise perhaps we should point folks at instructions that rely on launch generator.

I'd be happy to pick this up sometime, if we agree.

**Comment by squaremo** [comment]
It's a tricky one. On the one had we want to have an example deployment. On the other, it will always be out of date since it will mention a particular version. But -- the name "standalone" is a clue -- we should not really rely on a weave cloud service to provide the manifest.

**Comment by squaremo** [comment]
>  I am also not sure why memcache manifest is included there.

The daemon uses memcache for image registry requests; otherwise, it will make hundreds or thousands of requests every time it polls.

**Comment by sambooo** [comment]
The manifests in the `deploy/` directory are now updated with every Flux release.
