### ISSUE TITLE
Private Docker Registry sub-subdomain url resolution failing

### ISSUE THREAD

**Issue by Keidrych** [weaveworks/flux#606]
Hi all,

When trying to connect to a private docker repository that isn't quay.io anything with just a single '.' separator will resolve such as
something.co

Any domain that has more than one '.' will fail to resolve and becomes appended to the default url instead.
something.somewhere.co will fail always.

`
Internal error: getting images for services: fetching image metadata for something.somewhere.co/kube-test: Get https://index.docker.io/v2/something.somewhere.co/kube-test/tags/list: http: non-successful response (status=401 body="{\"errors\":[{\"code\":\"UNAUTHORIZED\",\"message\":\"authentication required\",\"detail\":[{\"Type\":\"repository\",\"Class\":\"\",\"Name\":\"something.somewhere.co/kube-test\",\"Action\":\"pull\"}]}]}\n")
`

This also means that images hosted on AWS or Azure container registries will also fail to be accessible as they use the xxx.xxxx.xxx format for domain name.

Adding https:// in front of the authentication url in the config file also causes this behaviour to occur.

**Comment by squaremo** [comment]
Thanks for this report, @Keidrych.

Just to check I understand the situation: you have a private image registry hosted at `something.somewhere.co`, which contains an image called `kube-test`. You refer to that image in files as `something.somewhere.co/kube-test`, and flux interprets that to be an image repo hosted at Dockerhub (index.docker.io), and fails authentication trying to look it up. Is that accurate?

**Comment by Keidrych** [comment]
Ahh, sorry reply got stuck in my outbox... 

Yes that's 100% correct. 

Flux believes that `something.somewhere.co/kube-test` is actually `https://index.docker.io/v2/something.somewhere.co/kube-test`

It doesn't even try to authenticate against `something.somewhere.co`

**Comment by squaremo** [comment]
OK, thanks @Keidrych. This may be a problem with how we parse image names -- well it certainly is, but it may or may not be our fault, depending on how the image name format is specified (or whether it is specified ..). Either way, we'll need to come up with a way to figure out when we have a DockerHub image, and when we have a private repo image.

**Comment by philwinder** [comment]
The issue here isn't the doman name. The issue is that the example you provided is not using the format `domain/owner/name:tag` as expected by the registry parser. You've missed out the owner, so it's interpreting your domain as the owner.

The quick fix would be to use the standard docker hub style naming convention. However, I agree that this isn't ideal. I will add this as a test case, then add some extra parsing to try and see if there is a domain in the name (basically, whenever there is a `.`, it must be a domain).

**Comment by philwinder** [comment]
Actually, I think that this would also result in problematic names. By default in docker, if you don't specify an owner, it applies the owner `library`. Is this what you are expecting when you type `something.somewhere.co/kube-test`, do you mean for that to resolve to `something.somewhere.co/library/kube-test` @Keidrych?

**Comment by Keidrych** [comment]
@philwinder that totally makes sense and your right in this instance we're using a Docker repository (Nexus) that doesn't use 'owner' and /library doesn't resolve internally. Will raise this with the guys internally to use something sensible such as 'Portus' moving forward.
