### ISSUE TITLE
Show ignored / no-config in list-services

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#610]
list-services (and any API/UI that derives from it) ought to show which things

 * are both running and configured
 * are running but not configured

and given a flag,
 * are running or configured but ignored

**Comment by sambooo** [comment]
What does "configured" mean here?

**Comment by squaremo** [comment]
> What does "configured" mean here?

In the git repo. #962 effectively resolves this, because it marks services (controllers, now) as read-only if they are in the cluster but not in the repo (and a couple of other reasons).
