### ISSUE TITLE
Tag filtering UI

### ISSUE THREAD

**Issue by sambooo** [weaveworks/flux#636]
This will enable users to only release images for which the tag matches a given pattern, rather than always releasing the latest tag.

TODO:

- [ ] Merge core functionality in #589
- [ ] CLI for updating/removing tag globs
- [ ] Web UI for end users

**Comment by rade** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Flux: enable automated releases for versions other than "latest"](https://trello.com/c/v8XGjgIL/56-flux-enable-automated-releases-for-versions-other-than-latest)
