### ISSUE TITLE
sample flux-deployment.yaml shouldn't refer to :latest

### ISSUE THREAD

**Issue by lukemarsden** [weaveworks/flux#644]
https://github.com/weaveworks/flux/blob/master/deploy/flux-deployment.yaml#L21 refers to `:latest`, which is sad because it doesn't exist.

**Comment by squaremo** [comment]
There does not seem to be any entirely satisfactory solution to this. But using `:latest` is certainly wrong, since it doesn't, and oughtn't, exist.

In #650 I amended the image name to refer to the version current at the time, and left a note saying how to find the most recent.
