### ISSUE TITLE
Leverage pod template imagePullSecrets

### ISSUE THREAD

**Issue by awh** [weaveworks/flux#652]
Any pod templates that refer to images hosted in private registries _must_ have `imagePullSecrets` specified, or Kubernetes wouldn't be able to pull them. Flux should be able to read these secrets itself, and therefore does not have to be independently configured with a registry secret.

**Comment by awh** [comment]
This seems to be relatively straightforward when built on top of #633 - we would extend the `servicesToRepositories` function to extract credentials from k8s alongside the image IDs, and have the warmer pass them down into the registry client. The `Cluster` interface will need to be changed to support getting the secrets. I would estimate this is only a few days effort @rade.

**Comment by awh** [comment]
In GKE environments it's possible for fluxd to gain access to the underlying instance's service account that authenticates it to GCR using a combination of https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances#applications and https://cloud.google.com/container-registry/docs/advanced-authentication#using_an_access_token

**Comment by rade** [comment]
To clarify, we need a special approach for GKE+GCR because GKE has some magic sauce that allows it to pull images from GCR; it's not using `imagePullSecrets`. Correct?

**Comment by awh** [comment]
Yes - Kubernetes has native support for GCR when running on GCE as documented here https://kubernetes.io/docs/concepts/containers/images/#using-google-container-registry - no `imagePullSecrets` required.

**Comment by philwinder** [comment]
GCR integration was implemented in #663
