### ISSUE TITLE
Add alternative registry cache implementation: disk

### ISSUE THREAD

**Issue by philwinder** [weaveworks/flux#660]
Memcache is nice, because it persists after the death of the fluxd container. But it does represent some extra baggage.

Add another registry cache implementation that doesn't have any dependencies (e.g. on disk).

**Comment by sambooo** [comment]
The registry cache doesn't even really need to persist across Flux restarts any more since the daemon will continue to operate with incomplete information. Closing as it is unlikely we will need this.
