### ISSUE TITLE
Flux syncs when no change to k8s happens

### ISSUE THREAD

**Issue by aaron7** [weaveworks/flux#665]
Flux attempts to sync with a change to a README.md file for example.

We also receive the notification `Sync: 15d3dda, <no changes>`

**Comment by philwinder** [comment]
Good catch! We should probably only react to certain changes.

**Comment by squaremo** [comment]
Alternatives:
 1. only consider revisions for sync'ing if they changed files in the configured subdirectory
 2. sync on every revision (and move the tag forward) and post an event, but don't send a notification if there were no changes in the configured subdirectory

Options:
 3. mark sync events if they didn't appear to change any manifests, and don't send a notification if 
 4. use `--first-parent` so we don't report on commits from merged branches

**Comment by sambooo** [comment]
Slack notifications are a Weave Cloud concern, not handled in this repo any more. This issue is also fixed in Weave Cloud.
