### ISSUE TITLE
Sync notifications fire on irrelevant changes to repo

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#682]
E.g., we get a sync notification from our dev environment when something is deployed to prod, because they use the same repo.

**Comment by philwinder** [comment]
related to #665

**Comment by squaremo** [comment]
> E.g., we get a sync notification from our dev environment when something is deployed to prod, because they use the same repo.

To elaborate: the sync mechanism is essentially

 1. pull from the upstream repo
 2. apply each manifest in the subdirectory
 3. move the "sync tag" to HEAD and push that tag back upstream

After step 2, a notification is sent to the service saying "I have sync'ed up to this commit". It includes the (parsed) output of `git log --oneline` -- i.e., commit hashes and summaries.

If more than one daemon is using the same repo and branch, their commits will be interleaved; and, the output of `git log --oneline` will include commits from both daemons, some of which won't be relevant.

**Comment by squaremo** [comment]
Fixed in #725, which restricts the commits considered to those affecting the git path.
