### ISSUE TITLE
Flakeyness when nats fails/restarted/something

### ISSUE THREAD

**Issue by philwinder** [weaveworks/flux#686]
We've had at least three reports of timeout and/or connection errors with nats ~~and memcache~~. E.g. `nats: timeout`.

My current theory is that `kube-dns` is failing and for whatever reason, the dns cache inside the fluxsvc container doesn't get purged. But I'm not sure.

**Comment by leth** [comment]
It would be good to see some alerts covering areas where brokenness can cause outages

**Comment by philwinder** [comment]
Well, after a thourough thrashing of memcache and/or kube-dns, I can't get memcache to fail for longer than the time it takes to reestabilish a connection.

So I'm happy to scratch memcache off the flakey list...

**Comment by sambooo** [comment]
There is no NATS in this repo any longer.
