### ISSUE TITLE
Discovery of balancer stat endpoints

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#7]
The balancer exposes stats for prometheus to pick up; but prometheus needs to be told about the host, to know where to pick them up. It would be a convenience if we helped this along.

One idea from @peterbourgon is for each amber balancer to register itself in etcd, and have prometheus look for endpoints there (or rather, to have the contraption described in http://prometheus.io/blog/2015/08/17/service-discovery-with-etcd/).

**Comment by dpw** [comment]
Done
