### ISSUE TITLE
automatic update of init containers

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/flux#702]
Init containers are not part of [`PodSpec`](http://godoc.org/k8s.io/api/core/v1#PodSpec), we should consider supporting them.
Istio makes an extensive use of this feature.

**Comment by errordeveloper** [comment]
> Istio makes an extensive use of this feature.

Istio uses initializers now, so this may be less relevant, but this is a general feature we probably might like to support in the future anyway.

**Comment by stefanprodan** [comment]
I've recently bump into this. For example a init container is used to run migrations and another one to copy the application code (php) into a shared volume for nginx to pic it up.

**Comment by stefanprodan** [comment]
Needs https://github.com/squaremo/kubeyaml/issues/1

**Comment by bricef** [comment]
Note how the YAML processing is done by https://github.com/squaremo/kubeyaml/, and there is an appropriate issue opened there already: https://github.com/squaremo/kubeyaml/issues/1

**Comment by rade** [comment]
This got resolved by #1258.
