### ISSUE TITLE
Confusing display of image age

### ISSUE THREAD

**Issue by bboreham** [weaveworks/flux#746]
Quay says the image was last modified 12 minutes ago; Flux says 26 minutes ago.

![image](https://user-images.githubusercontent.com/8125524/30537566-0e3bd594-9c62-11e7-8607-b1bfb12873d9.png)

![image](https://user-images.githubusercontent.com/8125524/30537593-2d8c9c26-9c62-11e7-94e7-562ee2402e77.png)

I suspect one is the time the image was stamped and the other is the time it was uploaded, since those events are some time apart in the build of this particular image.

**Comment by squaremo** [comment]
We don't in general have access to the time the image was uploaded.
