### ISSUE TITLE
Flux reports everything when no Notification settings are checked. 

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/flux#750]
Issue raised in community Slack:
https://weave-community.slack.com/files/U77DGG7QT/F78JG8W2K/screen_shot_2017-09-22_at_11.46.55_am.png

https://files.slack.com/files-pri/T2NDH1D9D-F78JG8W2K/screen_shot_2017-09-22_at_11.46.55_am.png

> I had expected fluxbot to report nothing with these settings. Instead, it reports everything?

**Comment by squaremo** [comment]
FTR, the screenshot is "all notifications switched off":
![screen shot 2017-09-22 at 11 46 55 am](https://user-images.githubusercontent.com/62033/30803467-a49a3d4e-a1e1-11e7-84f6-791c57a0b74c.png)

**Comment by squaremo** [comment]
I set up a fresh local instance and the service and daemon, and I see that

 1. supplying the hook URL, not touching the checkboxes, and saving results in getting "release" and "automated release" notifications
 2. checking just "automated releases" and saving means I get only notifications for automated releases
 3. unchecking all of them again, and saving, means I get "release" and "automated release" notifications again

The checkbox values are stored in the config DB. For backwards compatibility, I made the service distinguish between no values given (the user has never selected a checkbox) and an empty value (the user selected no checkboxes). Or I thought I did. It's possible the unmarshaling is defeating this distinction by making no value and the empty value indistinguishable.

**Comment by squaremo** [comment]
> It's possible the unmarshaling is defeating this distinction by making no value and the empty value indistinguishable.

Yes; Go's `omitEmpty` annotation treats both `nil` and an empty slice as empty. If you send an empty array in JSON, it'll unmarshal the field as nil.
