### ISSUE TITLE
git-style usernames get escaped in Slack notifications

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#751]
![image](https://user-images.githubusercontent.com/62033/30805649-375a94a0-a1ea-11e7-9eca-2b3cf785372b.png)

**Comment by sambooo** [comment]
Replacing <> with () seems like our best bet. [We can't escape those characters](https://api.slack.com/docs/messages/builder?msg=%7B%22text%22%3A%22foo%20%26lt%3Bbar%26gt%3B%22%2C%22attachments%22%3A%5B%7B%22text%22%3A%22foo%20%26lt%3Bbar%26gt%3B%22%2C%22author_name%22%3A%22foo%20%26lt%3Bbar%26gt%3B%22%7D%5D%7D) in the author field.

I'll make a PR.

**Comment by squaremo** [comment]
But [it appears to work if you don't escape them](https://api.slack.com/docs/messages/builder?msg=%7B%22text%22%3A%22foo%20%26lt%3Bbar%26gt%3B%22%2C%22attachments%22%3A%5B%7B%22text%22%3A%22foo%20%26lt%3Bbar%26gt%3B%22%2C%22author_name%22%3A%22foo%20%3Cbar%3E%22%7D%5D%7D) -- am I missing something?

**Comment by sambooo** [comment]
Oh hmm. I assumed (by looking at the code) that it's what we were already doing and it wasn't working. That'll teach me to assume :D

**Comment by squaremo** [comment]
> I assumed (by looking at the code) that it's what we were already doing and it wasn't working.

TBH I don't know where we URL-encode them, maybe it's on the way in to the template, maybe earlier.

**Comment by sambooo** [comment]
I'll put on my figuring-stuff-out hat.

**Comment by squaremo** [comment]
It looks like it doesn't matter how you encode `author_name`, it is always escaped on the way out.

Alternatives, at this point:

*Use different brackets*

Looks a bit funny perhaps, but it's only display so who cares.

*Use just the name (or email)*

If supplied e.g., `Michael Bridgen <michael@weave.works>", just show "Michael Bridgen". If the name bit is missing, show the email address.

Cons: misses information out. In the case of names synthesised from c.w.w usernames, may end up as not very informative.
