### ISSUE TITLE
 Include errors in sync events 

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#756]
When we run the sync, we log but otherwise ignore error results from `kubectl apply`. The excuse is that in many cases it will be to do with the ordering -- creating a resource before its namespace has been created, for example. But this misses some important cases that we do want to know about, like having an invalid manifest.

I suggest we include these "genuine" errors in the sync event sent upstream, so they can be included in notifications. (If we can be clever about not including ordering problems, either by filtering them out, or #602, so much the better).

**Comment by tamarakaufler** [comment]
At the moment my thoughts are that namespaces should be created first, and all errors logged.

**Comment by squaremo** [comment]
I had another idea: we could annotate resources with the last sync error (if the resource exists), and show those in UI/CLI.

**Comment by tamarakaufler** [comment]
I like it

**Comment by squaremo** [comment]
> we could annotate resources with the last sync error

The trouble is not all resources appear in the CLI/UI. So we'd need a special means of displaying these; maybe as part of a special sync status view.

**Comment by rade** [comment]
Does #970 resolve this?

**Comment by squaremo** [comment]
> Does #970 resolve this?

Yup. Shall make a comment there.
