### ISSUE TITLE
Multi-doc yamls with 'empty' sections cause a mysterious error

### ISSUE THREAD

**Issue by awh** [weaveworks/flux#761]
A yaml like this:

```
# Define flux namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: flux
```
will result in a mysterious but otherwise benign error on each sync:

```
err=" default/: running kubectl: error: no objects passed to apply"
```

due to the fact that we split multidoc yamls ourselves and pipe each chunk into a separate `kubectl  apply -f -`invocation. The above example contains two documents, one of which comprises a lone comment; this could be mitigated by discarding obviously 'empty' documents.

**Comment by tamarakaufler** [comment]
Fixed.
