### ISSUE TITLE
Support image names containing slashes

### ISSUE THREAD

**Issue by awh** [weaveworks/flux#767]
GCR allows you to organise your images in a directory structure, so it's possible to have names such as `gcr.io/dx-general/sock-shop/frontend` (browse an example [here](https://console.cloud.google.com/gcr/images/dx-general/GLOBAL/sock-shop)) which flux does not currently support. The [Docker docs](http://docs.docker.com/engine/reference/commandline/tag/) have the following to say - the convention of `<host>/<organisation>/<repository>` used by the Docker hub is not prescribed:

```
An image name is made up of slash-separated name components, optionally
prefixed by a registry hostname.
```

**Comment by errordeveloper** [comment]
@sambooo ping when you have something I can test!

**Comment by sambooo** [comment]
@errordeveloper #767 will fix this, but now gcr image pulling is blocked by #778.

**Comment by errordeveloper** [comment]
I have commented on #778, hope that helps in some way to get us moving
along.

**Comment by sambooo** [comment]
I just realised I linked #767, I meant to link #779 

My bad!
