### ISSUE TITLE
support namespace:kind/name syntax in fluxctl

### ISSUE THREAD

**Issue by rade** [weaveworks/flux#776]
fluxctl should support the same `namespace:kind/name` syntax as is used in the UI, so that's easier for users to switch between and c&p between CLI and UI.

**Comment by squaremo** [comment]
>  so that's easier for users to switch between and c&p between CLI and UI.

I have never felt the need to do that.

A better reason is that it makes it possible to select (with `--controller`) and exclude (`--exclude`) services from different namespaces.

**Comment by rade** [comment]
I found the difference in format quite jarring.

Arguably that also applies to the display format, e.g. output of `fluxctl list-services`.
