### ISSUE TITLE
Change the format of Slack release messages

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/flux#781]
I had some thoughts on how to improve our slack messages while implementing slack-style attachments in the browser.

Currently, messages about releases a difficult to parse, especially now that the controller type is included in the message:
![screen shot 2017-10-06 at 3 26 09 pm](https://user-images.githubusercontent.com/2802257/31300816-b489d670-aaaa-11e7-96e6-f565b4d2e080.png)

I think splitting each controller entry into an attachment would be easier to understand:
![screen shot 2017-10-06 at 4 12 36 pm](https://user-images.githubusercontent.com/2802257/31301756-36c6e97e-aab1-11e7-8cad-4878aa87a744.png)

This provides the opportunity to include more interesting content, such as links to the release itself, individual services, and container images.

One drawback is the 20 attachment limit from Slack. We would need to handle cases where more than 20 services get updated.

[Link to the Slack Message formatter](https://api.slack.com/docs/messages/builder?msg=%7B%22text%22%3A%22Automated%20Release%3A%20%3Chttps%3A%2F%2Fcloud.weave.works%2Ffluxv2%2Fproud-wind-05%2Freleases%2F3d6066eb-df32-4454-6ec3-1aac67ee63af%7C3d6066eb-df32-4454-6ec3-1aac67ee63af%3E%22%2C%22attachments%22%3A%5B%7B%22title%22%3A%22%3Chttps%3A%2F%2Fcloud.weave.works%2Ffluxv2%2Fproud-wind-05%2Fservices%2Fnotification%253Adeployment%252Feventmanager%7Cnotification%3Adeployment%2Fconfigmanager%3E%22%2C%22text%22%3A%22A%20new%20container%20image%20was%20released%20to%20your%20service%22%2C%22color%22%3A%22%2336a64f%22%2C%22fields%22%3A%5B%7B%22title%22%3A%22Previous%20Image%22%2C%22value%22%3A%22%3Cquay.io%2Fweaveworks%2Fnotification-sender%3Amaster-ee6a451%7Cmaster-ee6a451%3E%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22New%20Image%22%2C%22value%22%3A%22%3Cquay.io%2Fweaveworks%2Fnotification-sender%3Amaster-5a7b625%7Cmaster-5a7b625%3E%22%2C%22short%22%3Atrue%7D%5D%7D%2C%7B%22title%22%3A%22%3Chttps%3A%2F%2Fcloud.weave.works%2Ffluxv2%2Fproud-wind-05%2Fservices%2Fnotification%253Adeployment%252Feventmanager%7Cnotification%3Adeployment%2Feventmanager%3E%22%2C%22text%22%3A%22A%20new%20container%20image%20was%20released%20to%20your%20service%22%2C%22color%22%3A%22%2336a64f%22%2C%22fields%22%3A%5B%7B%22title%22%3A%22Previous%20Image%22%2C%22value%22%3A%22%3Cquay.io%2Fweaveworks%2Fnotification-eventmanager%3Amaster-ee6a451%7Cmaster-ee6a451%3E%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22New%20Image%22%2C%22value%22%3A%22%3Cquay.io%2Fweaveworks%2Fnotification-eventmanager%3Amaster-5a7b625%7Cmaster-5a7b625%3E%22%2C%22short%22%3Atrue%7D%5D%7D%5D%7D)

This json renders the message you see in the screenshot:
```json
{
    "text" : "Automated Release: <https://cloud.weave.works/fluxv2/proud-wind-05/releases/3d6066eb-df32-4454-6ec3-1aac67ee63af|3d6066eb-df32-4454-6ec3-1aac67ee63af>",
    "attachments": [
        {
            "title": "<https://cloud.weave.works/fluxv2/proud-wind-05/services/notification%3Adeployment%2Feventmanager|notification:deployment/configmanager>",
            "text": "A new container image was released to your service",
            "color": "#36a64f",
            "fields": [
              {
                 "title": "Previous Image",
                 "value": "<quay.io/weaveworks/notification-sender:master-ee6a451|master-ee6a451>",
                 "short": true
               },
               {
                  "title": "New Image",
                  "value": "<quay.io/weaveworks/notification-sender:master-5a7b625|master-5a7b625>",
                  "short": true
                }
            ]
        },
        {
            "title": "<https://cloud.weave.works/fluxv2/proud-wind-05/services/notification%3Adeployment%2Feventmanager|notification:deployment/eventmanager>",
            "text": "A new container image was released to your service",
            "color": "#36a64f",
            "fields": [
              {
                 "title": "Previous Image",
                 "value": "<quay.io/weaveworks/notification-eventmanager:master-ee6a451|master-ee6a451>",
                 "short": true
               },
               {
                  "title": "New Image",
                  "value": "<quay.io/weaveworks/notification-eventmanager:master-5a7b625|master-5a7b625>",
                  "short": true
                }
            ]
        }
    ]
}

```

**Comment by jpellizzari** [comment]
@awh @foot @squaremo LMK what you think. I would be willing to work on this if we agree its a good improvement. This would have have a nice side effect of making events render nice in the browser.

**Comment by foot** [comment]
Slick!

Clicking release id through to the releases page for more details would be neat. (#782 related?).

**Comment by squaremo** [comment]
@jpellizzari This is a much clearer display of the release information. I'm happy for you to adapt the notifications.

Do all the individual entries have to be in a different attachment? If we can do tables (like old image, new image above) perhaps we can just list all the updates out in one attachment -- or, since there's the possibility of failures, in two attachments -- and summarise at the top.

The screenshot above doesn't mention the image that got released (something like `quay.io/weaveworks/notification-sender`), or the container using that image. In many cases the container doesn't matter, mind you.

**Comment by sambooo** [comment]
This isn't a Flux feature. I would recommend migrating this issue into the service repo.

**Comment by jpellizzari** [comment]
This issue was moved to weaveworks/service#1928

**Comment by jpellizzari** [comment]
It was a Flux feature when the issue was created. Moved now.
