### ISSUE TITLE
Request info about an old release via http api.

### ISSUE THREAD

**Issue by foot** [weaveworks/flux#782]
E.g. to support `/flux/:orgId/releases/:releaseId` links in the slack messages.

`/jobs?id=x` eventually expires. (I think...?).

The release details are available in the history but are tricky to get at.

`/api/history?event.release.id=abcdcafe` would be cool. But I can't think of other use cases for a general querier off the top of my head right now so perhaps `?releaseId` would be fine!

**Comment by sambooo** [comment]
Not a Flux issue. Please recreate this in our service repo if it is still desired.
