### ISSUE TITLE
Implement image manifest request with HTTP rather than client

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#790]
Follow on from #780: it is not ideal to try to fetch one schema of manifest, check for a particular error and fail, then fetch the other. And more of a problem, this still doesn't account for signed manifests.

Since the manifest schema version is decided by content negotiation (hooray for sane use of HTTP!), it'd be much better to just issue an HTTP request with an `Accept` header, and deal with whatever `Content-Type` we get back. This would also go towards helping #741 (we'd at least be able to discard images that aren't for linux/amd64, rather than failing to update the repo).

**Comment by squaremo** [comment]
This may precipitate a rewrite of the registry code to not use the client -- the only really tricky bit of what the client does is authentication, otherwise we are mostly working around its limitations, with #780 and the various `RoundTripper` implementations.

**Comment by awh** [comment]
Useful links:

* https://docs.docker.com/v1.6/reference/api/registry_api/
* https://docs.docker.com/registry/spec/api/
* https://docs.docker.com/registry/spec/manifest-v2-1/
* https://docs.docker.com/registry/spec/manifest-v2-2/
* https://cloud.google.com/container-registry/docs/concepts/image-formats
* https://docs.docker.com/registry/spec/auth/jwt/#using-the-signed-token
