### ISSUE TITLE
provide some interesting info about cluster before git is configured

### ISSUE THREAD

**Issue by rade** [weaveworks/flux#800]
In Weave Cloud, we display some interesting info about the user's cluster when an agent connects. "N metrics found", "N probes connected". What info could we obtain from fluxd _prior to git being configured_? Something like the number of services that could potentially be controlled by flux, perhaps?

**Comment by sambooo** [comment]
No longer a Flux concern now that it will answer queries without a repo configured. Recreate this in the service-ui repo if it still needed.
