### ISSUE TITLE
Cannot combine flux automate and tag filtering

### ISSUE THREAD

**Issue by bsambrone** [weaveworks/flux#819]
I'm trying to automate deployment to my dev namespaces and I only want to push the latest image that has either a prerelease tag, or the *-beta-* glob. I've tried either approach (I only need one) as a tag filter in the UI, and as soon as I click the automate button in Weave Flux the little truck icon appears then goes away. 

I checked what Weave is writing to my monorepo with all my yaml files and I see:
```
  annotations:
    flux.weave.works/tag.inventory-cdk-api: glob:*-beta-*
```
or
```
  annotations:
    flux.weave.works/automated: "true"
```

... but not both.

Is there a way to accomplish what I'm trying to do? I did see issue [260](https://github.com/weaveworks/flux/issues/260) which seems to indicate this is possible, but I didn't see any documentation around it.

Another oddity I noticed (and might be related) is that when I hit the automate button, the latest image is not pushed. I'm using GCR and my latest image has multiple tags of 0-1-beta, 0-beta, beta, 0.1.0-beta-07178, and prelease. Each of these individual tags on a single image appear in the Weave Flux UI as a separate image, although they are all really the same one.

**Comment by squaremo** [comment]
> as soon as I click the automate button in Weave Flux the little truck icon appears then goes away [...]

The idea is certainly that you can have a resource automated (flux will update images in it) and filter the tags it will consider for updates. It sounds like there's a bug preventing you from making both annotations stick -- I will try to reproduce this locally.

> when I hit the automate button, the latest image is not pushed. I'm using GCR and my latest image has multiple tags of 0-1-beta, 0-beta, beta, 0.1.0-beta-07178

At the minute we treat images as (almost) opaque strings. We can find out when an image was pushed, but this doesn't always correspond to when the tag was "created" -- and of course, more than one tag can refer to the same image layer. So, in the case that you push an image with several tags, you may have to be careful how you filter for the ones you want. (And we will have to consider how we can deal with it better.)

**Comment by bsambrone** [comment]
Good to know! I haven't tried manually editing my yaml to include both annotations yet, but I can give that a whirl if you think that would be helpful for troubleshooting.

For the tag stuff, I can filter pretty reliably to the one I want so I'm not too concerned about that one. Glad to know that it's expected behavior :)

**Comment by squaremo** [comment]
>  I haven't tried manually editing my yaml to include both annotations yet, but I can give that a whirl if you think that would be helpful for troubleshooting.

Yeahp, adding the annotations to the files and committing should have the right effect, and be reflected in the UI. In other words it should be enough to get the effect you want.

On tags, it's not totally obvious how to treat tags that refer to the same image layer -- I think we _can_ tell when it's the case, so I guess we could show it in the UI and in the fluxctl output. We could also suppress the display of images that have been filtered out.

**Comment by bsambrone** [comment]
I added both annotations to my deployment yaml file, and it looks to be working as expected now!

Once thing I noticed previously is that I had my deployment, service, and ingress all combined into one yaml file. Only my ingress had annotations attached to it. When Weave Flux did it's thing, it blew away ALL my annotations in my ingress and replaced it with the flux annotation. I'm guessing that Flux is looking for the first annotations area it finds and replaces all the contents, which is bad news bears if there are other ones present. I solved my problem my breaking out my service and ingress into separate yaml files, but thought you should be aware of this behavior.

**Comment by squaremo** [comment]
> Once thing I noticed previously is that I had my deployment, service, and ingress all combined into one yaml file. Only my ingress had annotations attached to it. When Weave Flux did it's thing, it blew away ALL my annotations in my ingress and replaced it with the flux annotation

Ahhhhhhhh OK yes -- that's a bug for sure, related to the "put anything to be automated in its own file" limitation. I should at least document that consequence.

**Comment by squaremo** [comment]
Extra documentation in https://github.com/weaveworks/flux/pull/820

**Comment by sambooo** [comment]
I assume this is no longer an issue. Please reply here if that is not the case, Bill.
