### ISSUE TITLE
glob matching not working as expected

### ISSUE THREAD

**Issue by bsambrone** [weaveworks/flux#823]
So this is sort or related to [822](https://github.com/weaveworks/flux/issues/822) in that with multiple tags I'm trying to zero in on one tag to be my latest that should get pushed. 

I'm using a tag filter of &ast;-beta-&ast; and the tags that are showing up are (in this order):
0-1-beta
0-beta
0.1.0-beta-07178

These all refer to the same image in GCR. I tested this glob online and it correctly matches to only 0.1.0-beta-07178, but the UI doesn't seem to be. Flux is correctly deploying 0.1.0-betas-07178.

The main problem is that 0.1.0-beta-07178 is the currently deployed tag, but Weave Flux thinks that 0-1-beta is the latest (at least as surfaced by the UI) and it continually tries to deploy this thing every 5 minutes. Being the same image nothing actually happens which is good from my end, but it's a bear to look at in the UI for a history perspective.

**Comment by awh** [comment]
Hi @bsambrone could you let us know which version of flux you're using, and a copy of the `flux.weave.works/` annotations from the deployment yaml manifest in question?

**Comment by bsambrone** [comment]
Sure thing, the annotation I saw is:

```
annotations:
    flux.weave.works/tag.inventory-cdk-api: glob:*-beta-*
```

I installed Flux using the what the UI provided for me to copy/paste, so I assume it's the latest? I took a look at the yaml for weave-agent-flux and I see a version of ```quay.io/weaveworks/flux:1.0.2```

**Comment by awh** [comment]
Thanks @bsambrone. It's normal for the UI to list _all tags_ that are available, newest first, even if you have a filter set - the filter just restricts the set of tags that will trigger an automated release. What are you seeing happening every five minutes? Can you share a sample of the history?

**Comment by bsambrone** [comment]
Turns out the deployment loop wasn't an issue with flux, but that I had the same hostname for 2 different namespaces. We've already torched the original kube project and have a fresh one now so unfortunately I don't have the history anymore.

**Comment by squaremo** [comment]
@bsambrone D'oh! Ah well accidents happen. Especially with computers.

Do you mind elaborating a bit on what was causing the problem -- what things had the same hostname? Maybe it's something we can at least detect. Thanks!

**Comment by squaremo** [comment]
@bsambrone Did this get resolved with the fresh kubernetes cluster? (can we close it?)

**Comment by dmccaffery** [comment]
@squaremo we stopped using vanity tags all together as a workaround at the time. I’ll investigate this again to see if it’s still an issue. The preference would be that flux would treat all labels referencing the same image layer as the same “version”; perhaps as a delimited list rather than separate versions.

**Comment by squaremo** [comment]
Yeah, how we interpret tags vs image IDs, and using digests and so on, really needs a good thinking through, for this and other reasons (see #909 etc.)

**Comment by squaremo** [comment]
Actually, closing this one as I think the specific problem went away. Dealing with multiple tag for an image etc., is covered in #822;  handling digests in #sha256
