### ISSUE TITLE
Support giving a client certificate in fluxctl

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#833]
If you are running Flux standalone and want to expose the API, to secure the channel you really need to use SSL (via a LoadBalancer service or an Ingress, most likely); and to authenticate it, absent other means, you need to be able to supply a client certificate.

**Comment by squaremo** [comment]
If we do this, we could also give instructions for putting an ingress in front of the flux API. It's possible with newer minikubes, even: https://medium.com/@Oskarr3/setting-up-ingress-on-minikube-6ae825e98f82

**Comment by sambooo** [comment]
We now recommend using `kubectl port-forward` to talk directly to a Flux daemon running in a kubernetes cluster.

**Comment by squaremo** [comment]
> We now recommend using kubectl port-forward to talk directly to a Flux daemon running in a kubernetes cluster.

We do, but it's not a cover-all solution. You may want your team members, or apps, to have access to the flux API without giving access to the Kubernetes API.
On the other hand I'm fine with leaving this closed until someone specifically has this use case.

**Comment by sambooo** [comment]
It'd be handy if some company had already written a daemon proxy implementation wouldn't it? 😁
