### ISSUE TITLE
Repeated calls to job status after getting 500

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#844]
In Weave Cloud we've seen logs indicating that something is repeatedly calling job status and getting a 500 "unknown job". #843 makes the daemon return a 404 instead of a 500, but there's still the underlying problem.

Possible reasons for the daemon not having a record of a job:
 * the job failed or didn't result in a commit, and the daemon crashed or was otherwise restarted shortly afterwards (such jobs are recorded _only_ in the job status cache, in memory)

Possible reasons something kept asking for the job:
 * the daemon crashed or otherwise restarted just after returning a "not complete" status, so the caller asked again after the restart
 * a bug in the job status refetching which means it doesn't give up after getting a failure status

**Comment by sambooo** [comment]
Not a Flux issue as far as I can tell.
