### ISSUE TITLE
flux doesn't seem to forget deleted tags

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/flux#849]
Not sure what's happening, but I've just tried to clean-up some of the tags Socks Shop, but even after I kill agent and memcached pods, I still find the tags in the UI.

Here are some screenshots to illustrate this, but we probably need to investigate what's going on. The two tags I've deleted are `fast` and `slow`, both still show up in the UI...

[![screenshot 2017-11-20 15 08 29](https://user-images.githubusercontent.com/251467/33025136-ff9ef64a-ce04-11e7-8252-684e750a7080.png)](https://hub.docker.com/r/weaveworksdemos/catalogue/tags/)

![screenshot 2017-11-20 15 14 02](https://user-images.githubusercontent.com/251467/33025299-7a8dd59c-ce05-11e7-990e-571b0e4552a8.png)

I've checked the [Docker Hub API](https://hub.docker.com/v2/repositories/weaveworksdemos/catalogue/tags/), and the `fast` and `slow` tags aren't there.

**Comment by errordeveloper** [comment]
Now that I think of it, perhaps this is to do with images cached in the cluster?

**Comment by errordeveloper** [comment]
Still would be good to investigate, and another good reason to consider using SHA1 IDs (see #498).

**Comment by squaremo** [comment]
That sure is odd, we just go on what the registry tells us! I don't know why it would be omitting tags in DockerHub but including them in its API responses.

**Comment by squaremo** [comment]
Do you still consider this a bug @errordeveloper ?

**Comment by squaremo** [comment]
Closing as out-of-date; if we see this again, we can make a new issue.
