### ISSUE TITLE
DockerHub tags include windows images, but manifests are missing

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#853]
Following the docker registry API, when retrieving image metadata from an image registry, we first ask for all the tags, then for each tag, ask for the manifest addressed by that tag.

For some images (e.g., `nats`), the tags include images built for windows (e.g., nats:1.0.4-nanoserver), but the manifests implied are not available and we get 404. But in general, we don't know that this is because it refers to a windows image -- the tag is just a string.

It turns out that for (at least) some library images, a `manifestlist` is used. You need to _explicitly_ ask for it using an `Accept` header, as for schema v2. The resulting document gives a list of manifests, surprise, of which you can choose which you want.

We'll have to figure out how to deal with this extra indirection.

**Comment by squaremo** [comment]
NB we handle `manifestlist`s as of #851; however, if there's no linux/amd64 image, it's counted as a failure, and the whole image list abandoned. So it's not yet ideal.

**Comment by rade** [comment]
Isn't this a _dup_ of #741 now?

**Comment by squaremo** [comment]
> Isn't this a dup of #741 now?

Yes, the remaining bit of this is the thing we need to fix for #741 to be closed.
