### ISSUE TITLE
Include more repository status details in the /status response.

### ISSUE THREAD

**Issue by foot** [weaveworks/flux#864]
Currently we have `configured: true|false`.

It would be really cool to be able to show that we've detected a repository at the URL you've provided, but cannot read/write it with the keys we have.

We could then give the user more hints about what they should be doing next in the configuration process.

`found: true|false` could work?

- `found: false, configured: false`: check your repo addr
- `found: true, configured: false`: check your permissions
- `configured: true`: happy days!

WDYT?

**Comment by foot** [comment]
Interpretation of `:error` should change from RED to YELLOW perhaps too.

We use it for "cloning repo..." and other stuff.

**Comment by squaremo** [comment]
A bit of implementation detail ... the /status API in the service uses two RPCs to the daemon:
 - `GitRepoConfig`, which reports the {URL, branch, path} triple and the public key (potentially generating the latter); then, provided that succeeds,
 - `SyncStatus`, which is taken as an indication of whether the git repo has been cloned and thereby everything is cool -- if that _doesn't_ return an error, `configured` is set to `true`.

We can include more information in the first call, like whether the git repo in question has been cloned, and is writable (given #865).

**Comment by foot** [comment]
In conclusion!: We can't really differentiate between "does it exist" and "do we have access". Read vs. Write in the error message is a nice addition from #865 though.

**Comment by foot** [comment]
Would still be useful to report whether we can write to the repo and if we've been able to clone it!

**Comment by squaremo** [comment]
@foot I think we do report more on the specific repo status now, can you check when you have a sec, and close if it's satisfactory...

**Comment by foot** [comment]
Yep, the newer API responses here let us see write/cloned. 👌
