### ISSUE TITLE
Authentication error when running fluxctl post 'standalone' install

### ISSUE THREAD

**Issue by u-phoria** [weaveworks/flux#871]
Giving Flux a try for the first time, attracted by its core principles.

Have installed fluxctl and the flux daemon [standalone](url). Have followed the service account / RBAC route, as running a 1.7.7 cluster.

Daemon seems happy, as it's created a deployment + pods from a given git repo. Awesome!

However accessing the api (using the ```kubectl port-forward``` route) gives the authentication error, suggesting that a token is required:

```
== Error ==
The request failed authentication
This most likely means you have a missing or incorrect token. Please
make sure you supply a service token, either by setting the
environment variable FLUX_SERVICE_TOKEN, or using the argument --token
with fluxctl.
```

Is a Weave Cloud account / token mandatory for standalone use also? Or is this some other token?

**Comment by squaremo** [comment]
> Is a Weave Cloud account / token mandatory for standalone use also? Or is this some other token?

Nope -- I think this is indicating that the instructions for using a port-forward are inaccurate or misleading. Do you mind posting a transcript of what you did, from the port-forward command onward?

**Comment by u-phoria** [comment]
Ah got it - all it was, was fluxctl wasn't seeing the FLUX_URL env variable. I'd just copied the lines from the standalone install page without giving them much thought.

Simply ```export```ing FLUX_URL did the trick.

The clue helped, thanks.

**Comment by squaremo** [comment]
Do you reckon a config file, a bit like the Kubernetes one say, would help?

**Comment by u-phoria** [comment]
Personally, I prefer seeing the explicit steps as given in the docs for this kind of short, environment-specific thing.

Only thing worth adding is the export for FLUX_URL, so fluxctl sees it in its env.
