### ISSUE TITLE
Fully qualified image names being written to yamls

### ISSUE THREAD

**Issue by sambooo** [weaveworks/flux#877]
When [doing a prod deploy](https://github.com/weaveworks/service-conf/commit/8309f22236d4bc9acda9460c47b9382b3a8e0324), image names were rewritten unintentionally.

`weaveworks/foo:bar` -> `index.docker.io/weaveworks/foo:bar`

I suspect #851 caused this.

**Comment by sambooo** [comment]
Should be fixed in #876.

**Comment by squaremo** [comment]
Fixed in #876 and #880 .
