### ISSUE TITLE
Support gcr hostnames other than gcr.io

### ISSUE THREAD

**Issue by mithrandi** [weaveworks/flux#878]
GCR has regional hostnames (eg. `eu.gcr.io`) for a number of regions, but only `gcr.io` is hardcoded in https://github.com/weaveworks/flux/blob/5245a0cf9e9d2c8f760726fd0a4ceb3c9d6f186f/registry/credentials.go#L93

**Comment by squaremo** [comment]
Good call, @mithrandi.

Implementation notes:  the set of gcr.io hostnames is in https://cloud.google.com/container-registry/docs/pushing-and-pulling. We may want to just use `host == "gcr.io" || strings.HasSuffix(host, ".gcr.io")` though -- maybe they'll expand the set of hostnames.
