### ISSUE TITLE
Flux doesn't like some of my manifests

### ISSUE THREAD

**Issue by mithrandi** [weaveworks/flux#883]
I see this logged by Flux:
```
ts=2017-12-22T15:15:57.130121631Z caller=loop.go:164 component=sync-loop err="default:clusterrolebinding/prometheus: yaml: line 1: mapping values are not allowed in this context; default:prometheus/prometheus: yaml: line 2: mapping values
are not allowed in this context; default:service/prometheus-global: yaml: line 2: mapping values are not allowed in this context; default:serviceaccount/prometheus: yaml: line 1: mapping values are not allowed in this context; default:servicemonitor/prometheus-global: running kubectl: error: unable to decode \"STDIN\": Object 'Kind' is missing in '{\".rules\":\"groups:\\n- name: isaacranks.rules\\n  rules:\\n  - record: service_version:isaacranks_ballot_generation_seconds_count:irate\\n    expr: sum(irate(isaacranks_ballot_generation_seconds_cou\\n\"}'"
```

The resource definitions it complains about seem to be these:
https://github.com/mithrandi/my-kube/blob/5daf8f0755ff66f54ef4a63c8b59afea2e6904d5/manifests/prometheus/monitoring.yaml

I think possibly the other errors are caused by the last error which seems to be caused by the ConfigMap, but I'm not sure exactly where to begin debugging.

**Comment by squaremo** [comment]
This line is suspicious: https://github.com/mithrandi/my-kube/blob/5daf8f0755ff66f54ef4a63c8b59afea2e6904d5/manifests/prometheus/monitoring.yaml#L34

(Granted Flux's parser thinks that's line 1. Go home, Flux, ...)

**Comment by squaremo** [comment]
Or it's not? I assumed it was complaining that the dash there introduced an array item when it was expecting just fields, but let me look that up ...

**Comment by squaremo** [comment]
I'm wrong: https://kubernetes.io/docs/admin/authorization/rbac/#rolebinding-and-clusterrolebinding shows an example.

**Comment by squaremo** [comment]
Possible workaround: separate the configmap into its own file, if you can.

**Comment by mithrandi** [comment]
Workaround seems to have worked:
https://github.com/mithrandi/my-kube/commit/f2ae9ed11b56c91de4887ffa6cba177ad8ae33c6
```
ts=2017-12-22T15:43:03.872257819Z caller=daemon.go:458 component=daemon event="Sync: f2ae9ed, default:clusterrole/prometheus, default:clusterrolebinding/prometheus, default:configmap/prometheus-rules, default:prometheus/prometheus, default:service/prometheus-global, default:serviceaccount/prometheus, default:servicemonitor/prometheus-global" logupstream=false
ts=2017-12-22T15:43:07.743230229Z caller=loop.go:376 component=sync-loop tag=flux-sync old=5daf8f0755ff66f54ef4a63c8b59afea2e6904d5 new=f2ae9ed11b56c91de4887ffa6cba177ad8ae33c6
```

**Comment by squaremo** [comment]
![image](https://user-images.githubusercontent.com/62033/34304076-0cfdfec8-e730-11e7-9bf7-c2fbdf05547b.png)
