### ISSUE TITLE
'Connection refused' error with standalone Flux installation

### ISSUE THREAD

**Issue by RochesterinNYC** [weaveworks/flux#888]
I deployed Flux in the standalone manner (using https://github.com/weaveworks/flux/blob/master/site/standalone/installing.md) to a k8s cluster via editing the `deployment.yaml` and kube applying all the other resources in the https://github.com/weaveworks/flux/tree/master/deploy directory.

I use port forwarding to connect my localhost to the flux deployment like so:

```
$ flux_pod=$(kubectl -n system-ns get pod -l name=flux -o name | awk -F / '{ print $2; }')
$ flux_port=$(kubectl -n system-ns get svc flux --template '{{ index .spec.ports 0 "nodePort" }}')
$ kubectl -n system-ns port-forward "$flux_pod" 10080:$flux_port
```

However, when I try to use port forwarding to issue `fluxctl` commands against the running `flux` deployment, I get the following error:
```
$ export FLUX_URL="http://localhost:10080/api/flux"
$ fluxctl list-controllers --all-namespaces
Error: Get http://localhost:10080/api/flux/v6/services?namespace=: EOF
Run 'fluxctl list-controllers --help' for usage.
```

And the following error shows up in the blocking port-forwarding command above:

```
$ kubectl  -n system-ns port-forward "$flux_pod" 10080:$flux_port

Forwarding from 127.0.0.1:10080 -> 30033
Handling connection for 10080
E1228 13:08:06.142623   97096 portforward.go:331] an error occurred forwarding 10080 -> 30033: error forwarding port 30033 to pod 68af6b53a1b4d35bc0d3a1034fad8a0fed9a7480cde09b210ce0c97b24299f57, uid : exit status 1: 2017/12/28 18:08:06 socat[1636] E connect(5, AF=2 127.0.0.1:30033, 16): Connection refused
```

**Comment by squaremo** [comment]
I think I see what's happening -- `kubectl port-forward` forwards traffic to the given port of a pod, and you are supplying it the port that the _service_ is mapped to. If you want to use a port forward, I think you just want

```
kubectl  -n system-ns port-forward "$flux_pod" 10080:3030
```

since `3030` is the port the pod listens on. If that works, you can get rid of the service, which is merely another (less secure) way of arranging access to the pod.

**Comment by RochesterinNYC** [comment]
Using `kubectl  -n system-ns port-forward "$flux_pod" 10080:3030` worked. Thanks! Marking this as resolved.

**Comment by squaremo** [comment]
Brill, thank you for reporting back!
