### ISSUE TITLE
Improve logging in order to help diagnosing issues

### ISSUE THREAD

**Issue by marccarre** [weaveworks/flux#895]
**Problem**:
The following log statement does not say enough to be able to debug the actual issue.
```
ts=2018-01-10T21:16:55.42468337Z caller=warming.go:154 component=warmer err="requesting tags: errors:\ndenied: requested access to the resource is denied\nunauthorized: authentication required\n"
```

**Solution**:
Log details like:

- what image was Flux requesting tags for,
- from which repository,
- with which credentials,
- etc.

**Where the issue occurred**:
- Slack: https://weave-community.slack.com/archives/C4U5ATZ9S/p1515685389000781
- Full logs: https://weave-community.slack.com/files/U8S9JQP2S/F8QQX4MAL/logs-from-agent-in-weave-flux-agent-c65ccd47b-v99lh.txt

**Comment by rade** [comment]
I believe the error does bubble up and gets logged with a little bit more context:
```
ts=2018-01-10T21:10:06.053691237Z caller=images.go:89 component=daemon err="fetching image metadata for index.docker.io/contractlandstaff/helium-authentication-web: errors:\ndenied: requested access to the resource is denied\nunauthorized: authentication required\n"
```
Still doesn't tell you anything about the credentials used though.
