### ISSUE TITLE
How handle different environments (dev/prod)?

### ISSUE THREAD

**Issue by leoblanc** [weaveworks/flux#908]
Hi, I'm totally new at Flux and I have a question please. I'm reading about Flux and it looks great. However, it's still not clear to me how Flux handles different environments (like development and production). 

I mean, I like the [automated update of images feature](https://github.com/weaveworks/flux/blob/master/site/using.md#turning-on-automation). According to what I read, that update occurs automatically when a [new version of the image is detected](https://github.com/weaveworks/flux/blob/master/site/how-it-works.md#monitoring-for-new-images) on its Docker repo. 

However, on the same Docker repo you will have both "production-quality" images (built from "master" branch) and "development-quality" images (built from development/topic branches). Supposing that I have a production Kubernetes cluster and a development Kubernetes cluster (to run and test development versions), how can I instruct to Flux to update the "right" images on each case? I mean, to prevent that the Flux service running on the production cluster blindly update the latest version of the Docker image (which most of times will be a development image). 

Or maybe the automated update feature is not suitable for this kind of use case?

Thanks in advance for your feedback!

Cheers,
Leo

**Comment by sambooo** [comment]
Hey Leo,

Flux's tag filter policies may be what you're looking for. See the output of `fluxctl policy --help`:

```
Manage policies for a controller.

Tag filter patterns must be specified as 'container=pattern', such as 'foo=1.*'
where an asterisk means 'match anything'.
Surrounding these with single-quotes are recommended to avoid shell expansion.

If both --tag-all and --tag are specified, --tag-all will apply to all
containers which aren't explicitly named.

Usage:
  fluxctl policy [flags]

Examples:
  fluxctl policy --controller=deployment/foo --automate
  fluxctl policy --controller=deployment/foo --lock
  fluxctl policy --controller=deployment/foo --tag='bar=1.*' --tag='baz=2.*'
  fluxctl policy --controller=deployment/foo --tag-all='master-*' --tag='bar=1.*'
```

If you have controller `deployment/foo` and you want to automatically release the latest tag that looks like `dev-*`, the command to run would be `fluxctl policy --controller=deployment/foo --tag-all='dev-*'`.

**Comment by leoblanc** [comment]
@sambooo Hi Sam, thank you very much! Yes, this is exactly what I was looking for, thanks!

**Comment by jasonyihk** [comment]
Hi leo,  we using different config repo for dev & prod, with two flux installation in different cluster to do the sync.

**Comment by leoblanc** [comment]
@jasonyihk Great, thanks for your info
