### ISSUE TITLE
Deal with multi-document yaml files

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#91]
The Sock shop uses k8s definition files with multiple resources in them. Fluxy messes this up by replacing wrong bits of things.

Solution sketch: break files up by `---`, and treat each piece separately, then reassemble at the end.

**Comment by paulbellamy** [comment]
A user just hit this, with their service and deployment in the same file, btw.

**Comment by SamMorrowDrums** [comment]
I'd say a lot of users hit this. I hit this from the moment I tried using flux, because initially I'd set up up deployments and services in the same files for convenience.

**Comment by squaremo** [comment]
Fixed by #976.
