### ISSUE TITLE
Push Github Deploy Key errors 422, deletes deploy key on the repo

### ISSUE THREAD

**Issue by crw** [weaveworks/flux#920]
Background:

- User has two instances (one gke, one aws/kops). 
- Pushes GH deploy key on gke; works fine. 
- Switches instance to aws. Deploys agents. 
- Uses SAME github repo, path, branch. 
- Pushes GH deploy key, hits this error:
<img width="607" alt="screen shot 2018-01-25 at 2 22 19 pm" src="https://user-images.githubusercontent.com/57712/35418231-ff1b1f18-01e5-11e8-8a78-c205aa97f58e.png">

- GKE deploy key deleted!

You can switch back to the GKE instance and push the deploy key fine; anytime you try to push the deploy key from the AWS instance, it throws that error and deletes the other key. Repeatedly trying to push the deploy key results in the same error. 

FWIW, it is possible the user used the same weave agent kubectl apply on both clusters (so, same service token) but that is not confirmed. 

Two things:

1. Can we show an error when a user specifies the same repo, path, and branch across two instances?
1. Is it possible to not delete the other instance's deploy key in this scenario?

**Comment by squaremo** [comment]
Ideally the key should be named for the instance -- but this is really a matter for the service -- all flux is doing is providing the public key when asked.

**Comment by squaremo** [comment]
> Can we show an error when a user specifies the same repo, path, and branch across two instances?

We can, and it might help troubleshoot _some_ varieties of problem -- but it's not necessarily mistaken to have this arrangement. You might want to keep two or more clusters up-to-date with respect to config you're changing by other means, for example.

> Is it possible to not delete the other instance's deploy key in this scenario?

I've opened weaveworks/service#1705 to cover avoiding clashes.

**Comment by crw** [comment]
> We can, and it might help troubleshoot some varieties of problem -- but it's not necessarily mistaken to have this arrangement. You might want to keep two or more clusters up-to-date with respect to config you're changing by other means, for example.

Couldn't this potentially cause race conditions? Regardless, it is good to hear this is a supported scenario.

**Comment by squaremo** [comment]
> Couldn't this potentially cause race conditions?

Modulo bugs, changes are effectively serialised through the git repo. Your change succeeded === it was pushed to the upstream git.

**Comment by crw** [comment]
There is no scenario where two devs deploy different image tags in each instance at the same time creating a ping-pong deployment between the two instances?

**Comment by squaremo** [comment]
> There is no scenario where two devs deploy different image tags in each instance at the same time creating a ping-pong deployment between the two instances?

No; one of the `git push` invocations will fail since it can't be a fast-forward.

**Comment by squaremo** [comment]
Although you don't have to go far before you encounter other problems. The release _automation_ could ping-pong if you've set different filters on the images (e.g., one deploys `master-*` and one deploys `dev-*`). So it's not a situation we want people to end up in by accident.
