### ISSUE TITLE
github push hook causes kubectl to be run constantly

### ISSUE THREAD

**Issue by rade** [weaveworks/flux#930]
Extracted from #926...

In the weaveworks sock shop cluster I observed fluxd running kubectl every few seconds. See https://github.com/weaveworks/flux/issues/926#issuecomment-362556183

@squaremo discovered that there was a github hook configured, and removing that stopped this behaviour.

What's puzzling here is that the underlying repo receives just ~1 commit a day, so the hook should not be triggered frequently.

One theory here is that flux is doing some git tagging when sync'ing, and that in turn is triggering the hook, which in turn would trigger more sync'ing.

**Comment by squaremo** [comment]
> One theory here is that flux is doing some git tagging when sync'ing, and that in turn is triggering the hook, which in turn would trigger more sync'ing.

Maybe, but the daemon doesn't attempt to push a new tag unless the head commit has changed, and I'd expect it to log that it was doing so. Maybe there's some corner case for this particular repo; one could try installing the hook for a fresh `flux-example` to see if it happens there too.

**Comment by squaremo** [comment]
Also: this really belongs as a bug against the service, not here.
