### ISSUE TITLE
Figure out cause of timeouts for full list-images, and adjust

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#933]
We want to make more use of the all resources list-images API, but in our dev environment for instance, it tends to time out.

Possible remedies:

 - if there's too much data, introduce a summary mode or the like so that we send only (say) the current image, the latest (filtered) image, and the distance between them.
 - if there's too much calculation, um ... figure out how if we can do less calculation.

**Comment by foot** [comment]
Related #913

**Comment by squaremo** [comment]
Ops! Closing as duplicate of #913.
