### ISSUE TITLE
Add --deploy-path argument to flux container to limit paths considered for deployment

### ISSUE THREAD

**Issue by cptbigglesworth** [weaveworks/flux#935]
At present the flux container image only allows users specify --git-url and --git-branch which limits options for environment separation. Whereas branching suits some customers, we've had issues with it in the past and prefer to store multiple environments in a single git repo. We need a way to limit flux to the correct directory path for the env we wish it to deploy.

An option such as --deploy-path or --resource-path or --deployables-path which specifies a relative directory within the git repo would allow : 
a) environments for multiple clusters to be stored in a single git repo and referenced by a deployer in each cluster. In this case the repo would contain directories such as : 

clusterA/... containing k8s resources only for clusterA
clusterB/... containing k8s resources only for clusterB

and deployerA would use --resource-path=clusterA etc.

b) preparation files to be stored in the git repo alongside the resource files : 

In many cases, users render the final deployable resource files for an environment from preparation files (e.g. rendering templates + values) ... ideally flux would only examine --resource-path so these files would not be considered. The same applies for any client-side validation tooling etc. to be colocated in the repo.

WDYT ?

**Comment by squaremo** [comment]
From your description, I think you can use `--git-path` to restrict the path flux considers for syncing and updating. We use the scheme you describe ourselves at weaveworks -- we have `dev/` and `prod/` directories in a single repo, on master.

Here's a list of the supported arguments, for reference: https://github.com/weaveworks/flux/blob/master/site/daemon.md

**Comment by squaremo** [comment]
Hi @cptbigglesworth, did you give `--git-path` a go?

**Comment by squaremo** [comment]
Closing to take off the radar -- if the suggestion of using `--git-path` is no good, please reopen.
