### ISSUE TITLE
fluxctl list-controllers returns empty result

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#968]
I've just noticed it /en passant/. May be either recent fluxctl or recent fluxd.

**Comment by alexanderbuhler** [comment]
It's still empty with fluxctl 1.13.1 and flux 1.13.1. Wasn't this supposed to be a core feature? 🙆‍♂

**Comment by hiddeco** [comment]
@alexanderbuhler my local development build of `master` works as expected, so this may be workload and/or setup related.

```
~/projects/flux
❯ fluxctl list-workloads
WORKLOAD                      CONTAINER  IMAGE               RELEASE  POLICY
default:deployment/flux       flux       fluxcd/flux:latest  ready    
default:deployment/memcached  memcached  memcached:1.5.15    ready    

~/projects/flux
❯ fluxctl list-workloads -a
WORKLOAD                          CONTAINER   IMAGE                          RELEASE  POLICY
default:deployment/flux           flux        fluxcd/flux:latest             ready    
default:deployment/memcached      memcached   memcached:1.5.15               ready    
kube-system:daemonset/kube-proxy  kube-proxy  k8s.gcr.io/kube-proxy:v1.14.3  ready    
kube-system:deployment/coredns    coredns     k8s.gcr.io/coredns:1.3.1       ready    
```

**Comment by alexanderbuhler** [comment]
Eh, my bad guys. Didn't figure you need -a for all namespaces 🙄

**Comment by hiddeco** [comment]
> Works fine!

Given this, and the fact that the issue is more than a year old and we have had no complaints in the past months. I will mark this issue as magically solved in a release after this issue was created.
