### ISSUE TITLE
Consider using one git mirroring implementation

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#984]
The helm operator has a similar, essential requirement to the flux daemon, that of mirroring a git repo. Because the `git` package was very coupled to how the daemon worked, at the time, they use entirely separate packages. Now the `git` package has been rewritten, it's plausible that it could be adapted for use in both the helm operator and the daemon.

**Comment by ncabatoff** [comment]
It probably makes more sense to do #957 instead given the other simplifications it allows.

**Comment by squaremo** [comment]
Fixed in #1240.
