### ISSUE TITLE
Flux fails to connect to an on-premise instance of Bitbucket

### ISSUE THREAD

**Issue by bricef** [weaveworks/flux#989]
When trying to connect to an on-premise instance of Bitbucket, Flux fails with

```
The git repository has not been successfully cloned.
```
![screen shot 2018-03-07 at 20 36 59](https://user-images.githubusercontent.com/250051/37117033-e546e874-2247-11e8-9774-512898be9750.png)

This may be due to bitbucket key configuration as per [the Atlassian documentation](https://confluence.atlassian.com/bitbucketserver/ssh-access-keys-for-system-use-776639781.html)

For people using weave cloud, we could:

- Create a custom WeaveCloud user in BitBucket, for them
- Give it an SSH key
- Ask users to add this custom WeaveCloud BitBucket user to their repo.

**Comment by bricef** [comment]
In addition, the affected instance's `Read/Write access for this deploy key has been enabled` button does not seem to have any effects.

**Comment by squaremo** [comment]
> In addition, the affected instance's Read/Write access for this deploy key has been enabled button does not seem to have any effects.

This one is for the user to confirm that they've installed the key and can move to the next step, since we can't see that happen otherwise. It _should_ simply enable the next step; if not, that's certainly a bug.

**Comment by squaremo** [comment]
I believe this is an instance of #724 -- let's wait to see if it can be resolved in the same way.

**Comment by squaremo** [comment]
@bricef Any idea what happened to this one?

**Comment by bricef** [comment]
@squaremo We hit this issue with other clients since. I have been meaning to go through the remedial instructions on a real cluster and write them up properly for a little while.

**Comment by squaremo** [comment]
Yep, anyone using a git provider or server other than {github.com, gitlab.com, bitbucket.com} will run into this. #1142 will make it easier.

**Comment by squaremo** [comment]
The mechanism in flux for dealing with self-hosted repos is pretty well documented now.
