### ISSUE TITLE
Deal with images for another arch/OS

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#999]
Some image repositories have images available for architectures other than amd64/Linux. We explicitly omit these from results, but our fetching logic means that we'll go looking for exactly the same image metadata next time around.

There are two problems:
 - Not getting metadata for certain tags means we can't have a result at all. We need to be able to assemble a result from _just_ the relevant tags.
 - We persist in attempting to fetch the results again and again. Similarly to #910, it would be good to store something saying "just ignore this tag from now on", so that we don't keep trying to fetch it.

Possibly we could fix both of these things by storing the result whatever it is, and filtering out the wrong arch/OS when assembling the result.

**Comment by rade** [comment]
Is this a dup of #741?

**Comment by squaremo** [comment]
Hmm yeah I had forgotten that one. Though #851 fixed many of the issues around fetching image metadata, including being able to handle fat manifests (like the example there has), we still have the symptom that we can't give an ListImages response for e.g., NATS. I'll put my suggestion from above in the issue instead.

**Comment by squaremo** [comment]
Closing as duplicate of #741.
